### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [eclipse/omr#10]
I would like to point out that identifiers like "[`__ccsid_t`](https://github.com/eclipse/omr/blob/64edf053d9d1cfe1594f9cf5bc2925f8b1beedba/util/a2e/atoe.c#L118)" and "[`m__exitlock`](https://github.com/eclipse/omr/blob/64edf053d9d1cfe1594f9cf5bc2925f8b1beedba/fvtest/threadtest/CThread.hpp#L55)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by charliegracie** [comment]
1. The code is declaring a variable of type __ccsid_t which is defined in a system header I believe.  This code should not be changed unless I am missing something.
2. The m__exitlock and m__terminated members could be modified to only have a single "_".

**Comment by igouss** [comment]
Those are Z/OS specific, and can't be changed.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by charliegracie** [comment]
If we go back to my comment the 1st example can not be changed as this a type defined in a system header that the code needs to use.  There are actually two member names in the file from your second example that could be changed.  Would you like to contribute a change set modifying those?

**Comment by elfring** [comment]
1. How portable is the identifier "`__ccsid_t`"?
2. Are you quicker (than me) to [delete misplaced underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by charliegracie** [comment]
1. That is not portable but it is in code specifically for zOS.
2. I do not believe that this is a necessary change as a compiler would almost certainly never use those names as reserved names.

I am going to close the Issue but if you would like to make the change feel free to re-open the Issue and create the Pull Request.  Thanks
