### ISSUE TITLE
Bogus check in port library

### ISSUE THREAD

**Issue by dnakamura** [eclipse/omr#1029]
port/win32/omrintrospect.c:244  has the following code:
`if (result != -1 || (HANDLE) GetLastError() != INVALID_HANDLE_VALUE) {`
I'm not really sure what the logic is here. `GetLastError()` will return an int type, while `INVALID_HANDLE_VALUE` is obviously a handle value. There is a cast (presumably to silence compiler warnings), but I am unclear on the intent of this code. Further `GetLastError()` returns an unsigned int, while `INVALID_HANDLE_VALUE` evaluates to -1

**Comment by dnakamura** [comment]
Currently the code is equivalent to `if (result != -1 ) {` However the logical change would be `if (result != -1 || GetLastError() != ERROR_INVALID_HANDLE) {`. However I'm hesitant to change working code

**Comment by mstoodle** [comment]
@dnakamura can getLastError() ever return (unsigned int)-1 ?

**Comment by dnakamura** [comment]
In theory its possible in a future release. Although presently Microsoft has no defined error codes that go that high
