### ISSUE TITLE
Issues in omr/port/unix/omrintrospect.c

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/omr#106]
* The body of close_wrapper() doesn't match the comments describing its intended behavior.
* The uses of setup_native_thread() don't use its return value properly.
* omrintrospect_threads_nextDo() sends an excessive number of signals while waiting for the next thread to signal that it has captured its call stack. The comments refer to a Linux scheduler bug that has long-since been fixed: there is no longer a need for this (badly behaving) workaround.

**Comment by charliegracie** [comment]
I believe this issue was resolved via #109

**Comment by keithc-ca** [comment]
The previous workaround is still necessary for Linux kernel releases 2.x, but not for the reasons described by the original comment in the code. Instead, signals are either being lost or some threads are chosen to receive more than one. Either way, not all other threads have reached the signal handler before the controller starts waiting for client threads to trace their stacks. Sending additional signals (and yielding) while the controller is waiting for a client thread to trace its stack deals with both kinds of problems.
