### ISSUE TITLE
Lack of universal return in TR_X86OpCode::OpCode_t::ImmediateSize() causes prolific warnings.

### ISSUE THREAD

**Issue by lmaisons** [eclipse/omr#1068]
Compiling with clang causes a litany of instances of this warning:

/home/lmaisons/tr.open/omr/compiler/x/codegen/X86Ops.hpp:362:10: warning: control may reach end of non-void function [-Wreturn-type]

The function in question is `inline uint8_t ImmediateSize() const`

I wasn't sure what a sane default would be or I would have created a PR myself.

**Comment by mgaudet** [comment]
`TR_ASSERT_FATAL`?

**Comment by lmaisons** [comment]
I forgot about that, that's probably adequate to not worry so much about making sure the returned value won't be misinterpreted as something useful.

**Comment by mgaudet** [comment]
Now that I honk about it tho, it may not successfully stop the warning.

**Comment by mstoodle** [comment]
I fixed this problem with a code change in #1129 .
