### ISSUE TITLE
Verbose bits not set in subproject

### ISSUE THREAD

**Issue by ncough** [eclipse/omr#1085]
Subprojects that rely on `setVerboseBitsInJitPrivateConfig()` will no longer correctly set verbose bits after #1007.

This is due to changes to `setVerboseBits()` as it no longer consider its base argument, rather it uses _feBase directly. However, `setVerboseBitsInJitPrivateConfig()` uses this argument to point at the `TR_JitPrivateConfig`, which contains the verbose bits. The immediate fix seems to be to revert to using the base argument, rather than _feBase, but I am not certain if this clashes with the greater intentions of the PR.

@mpirvu Will other changes related to #1055 account for this, or should this be fixed?

**Comment by mpirvu** [comment]
I understand the issue. The code needs some refactoring and I'll work on it.

**Comment by mpirvu** [comment]
Nick, could you please review my fix for this issue? Thanks
