### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [eclipse/omr#11]
I find that include guards like "[`omr_h`](https://github.com/eclipse/omr/blob/b3c44edf20ca4ea9362b9325754d1eed85a34394/include_core/omr.h#L19)" and "[`pool_api_h`](https://github.com/eclipse/omr/blob/b3c44edf20ca4ea9362b9325754d1eed85a34394/include_core/pool_api.h#L19)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by charliegracie** [comment]
We are open to hearing all ideas as we hope a larger development community can help improve the code base. How would you change the include guards so they provide more protection.?

**Comment by elfring** [comment]
How do you think about to make [include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by charliegracie** [comment]
Appending a UUID seems overly complicated as it would require a tool to generate the guards so that they are in fact unique.

**Comment by elfring** [comment]
There are some development tools available to achieve a safer name pattern also for include guards.
Would you like to reduce the probability for name clashes a bit more?

**Comment by charliegracie** [comment]
I do not see the value in making such a sweeping change to add a UUID.  If they are issues in the future we can revisit this but I think a better solution may be to pre-pend the omr namespace.
