### ISSUE TITLE
GRA support for Vector registers on x86

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/omr#1126]
To further expand on autoSIMD support on x, GRA support will be added for vector registers on x. This change will indicate to GRA that TR_VRF registers exist and that GRA can be performed on them. This is done by indicating which range of registers can hold TR_VRF registers. Also various functions that deal with registers will need to be updated to recognize TR_VRF registers. In most cases, these functions will perform a similar action to how TR_FPR registers are handled but slightly modified for the TR_VRF register case.

**Comment by 0xdaryl** [comment]
@IBMJimmyk , can this issue be closed now or is there outstanding work to be done?
