### ISSUE TITLE
Discuss: use c++ namespaces

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#114]
Proposal: Use a combination of namespaces and classes to scope our code. Eliminate uses of prefixes where it makes sense. Wrap all OMR code in the `omr` namespace.

Some example transformations:
- `omrport_*` -> `omr::port::*`
- `OMR_VM` -> `omr::VM`
- `MM_CollectorLanguageInterface` -> `omr::mm::CollectorLanguageInterface`
- `omr_thread_attach` -> `omr::attachThread` or `omr::Thread::attach`

Blocking Issues:
- Existing DDR implementation does not support namespaces (needs confirmation)

**Comment by mgaudet** [comment]
+1, with the caveat that Testarossa is already using the `OMR` namespace, so we'd have to find a consistent sizing, so we may potentially have to change around this, unless we can come to a consistent story that suits both projects.

**Comment by mstoodle** [comment]
I think Matthew just means that the choice of "OMR" would help simplify the contribution of the large, existing JIT compiler component (currently being refactored from the Testarossa JIT compiler used in IBM J9) that IBM is working hard to contribute to the Eclipse OMR project mid year. While it's possible to change the namespace, "OMR" seems like a reasonable choice and a large body of code (that isn't part of the project yet but will be soon) already uses it.

I am also a +1 to introduce an OMR namespace.

**Comment by rwy0717** [comment]
A few more ideas:

For macros use `OMR_*`
- `MMINLINE` ->`OMR_MM_INLINE`
- `OMRPORT_ACCESS_FROM_PORT` -> `OMR_PORT_ACCESS_FROM_PORT`

For C APIs, use `omr_*`
- `omrtty_print` -> `omr_tty_print`
- `OMR_Runtime` -> `omr_Runtime`

**Comment by rwy0717** [comment]
Another idea, use the `omr::impl` namespace to place implementation details that need to be inlined. I've also seen `namespace detail` used.
