### ISSUE TITLE
No template instantiation for CodeGenerator::loadAndStoreMayOverlap that leads to "undefined symbol" at runtime

### ISSUE THREAD

**Issue by last5bits** [eclipse/omr#1183]
The following template method violates the C++ standard ([StackOverflow](https://stackoverflow.com/questions/26745973/potential-evaluation-of-inline-function-bodies-and-instatiation-of-template-memb)):

`omr/compiler/z/codegen/OMRCodeGenerator.hpp`

`template <class TR_AliasSetInterface> bool loadAndStoreMayOverlap(TR::Node *store, size_t storeSize, TR::Node *load, size_t loadSize, TR_AliasSetInterface &storeAliases);`

since the template method is implemented in the .cpp file rather than the header file.

This leads to an `undefined symbol` error during runtime. The code works on GCC 4.4.7; however, GCC 4.8.5 seems to inline the template straight into the other overload candidate without emitting the template instantiation (hence, `undefined symbol`).

**Comment by last5bits** [comment]
There are two potential solutions:
1) Move the template definition into the header
2) Explicitly instantiate the template

Solution 1) is preferable since it won't require manually instantiating the template function after adding new calls (with different template arguments).

I will push the corresponding fix shortly.

**Comment by mstoodle** [comment]
Hi @last5bits , would you please change the text in this issue to refer to a problem in OMR without directly referencing the project you're working on that consumes OMR?
