### ISSUE TITLE
JBCodeCacheManager should not define "pyfe()"

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#1191]
The original JitBuilder compiler project grew from an older CPython compiler project that has not (yet?) been open sourced. One holdover from that evolution is the presence of the "pyfe()" call in jitbuilder/runtime/JBCodeCacheManager.hpp . This function should be removed.

There is only one use of pyfe() which is in JBCodeCacheManager.cpp, and it should be easily adjusted to instead rely on fe().

**Comment by 0xdaryl** [comment]
I'm presently working on removing the FE dependence in CodeCacheManager.  This function will vanish as part of that work.
