### ISSUE TITLE
Add omrsysinfo support for Windows Server 2016

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#120]
Extend omrsysinfo_get_OS_type to handle Windows Server 2016
Change both the IsWindowsXXXOrGreater() and GetVersionEx() algorithms.

**Comment by rwy0717** [comment]
I feel like the commit and issue information should be swapped here :p

**Comment by charliegracie** [comment]
I agree.  @pdbain-ibm Can you fix up the text of the issue and your commit message.  The Issue should describe a problem and the commit message should describe the solution.  See the CONTRIBUTING.md for more details on the commit message format. Thanks

**Comment by charliegracie** [comment]
Resolved by #121
