### ISSUE TITLE
Provision compactOnIdle independent from gcOnIdle

### ISSUE THREAD

**Issue by Param-S** [eclipse/omr#1213]
As per the current implementation, if systemGarbageCollect is called with GC code "J9MMCONSTANT_EXPLICIT_GC_IDLE_GC", compaction is always combined with "releasing free pages".  In scenarios where runtime wants to perform only compaction to make manage heap free from fragmentation as preparation for the next active cycle.  Separating out compactOnIdle from gcOnIdle make the runtime to set & invoke these two independent.

**Comment by Param-S** [comment]
PR submitted for this issue: https://github.com/eclipse/omr/pull/1214

**Comment by charliegracie** [comment]
Closing as #1214 has been merged.  If I have incorrectly closed this issue please re-open it.
