### ISSUE TITLE
Bad initialization of GCExtensions

### ISSUE THREAD

**Issue by youngar** [eclipse/omr#1220]
To construct `GCExtensionsBase`, we use `memset`, then placement `new`. Placement `new` is considered to fully initialize all memory of the object. This causes the compiler to treat the `memset` as a *dead store*. Some compilers will completely omit the `memset`, and may cause some fields of `GCExtensionsBase` to be indeterminately initialized. The solution is to fully initialize `GCExtensionsBase` in it’s constructor, and stop calling `memset`.

```C++
MM_GCExtensionsBase*
MM_GCExtensionsBase::newInstance(MM_EnvironmentBase* env)
{
	OMRPORT_ACCESS_FROM_ENVIRONMENT(env);
	MM_GCExtensionsBase* extensions;

	/* Avoid using MM_Forge to allocate memory for the extension, since MM_Forge itself has not been created! */
	extensions = static_cast<MM_GCExtensionsBase*>(omrmem_allocate_memory(sizeof(MM_GCExtensionsBase), OMRMEM_CATEGORY_MM));
	if (extensions) {
		/* Initialize all the fields to zero */
		memset((void*)extensions, 0, sizeof(MM_GCExtensionsBase));

		new (extensions) MM_GCExtensionsBase();
		if (!extensions->initialize(env)) {
			extensions->kill(env);
			return NULL;
		}
	}
	return extensions;
}
```

Memset was confirmed to be omitted on my computer using **gcc (GCC) 6.3.1 20170306**

You can read more about this [here](https://stackoverflow.com/a/41902202)

**Comment by rwy0717** [comment]
Just for fun, [here](https://godbolt.org/g/91mquw) is a godbolt demonstrating a disappearing `memset`.

**Comment by charliegracie** [comment]
What about memsets called from with-in the constructor?  I assume those do not get removed
