### ISSUE TITLE
Verbose GC heap-resize tag not appearing for EXPLICIT_GC_IDLE_GC

### ISSUE THREAD

**Issue by Param-S** [eclipse/omr#1233]
heap-resize verbose tag not seen on instances where EXPLICIT_GC_IDLE_GC is last GC activity.
Example:

| EXPLICIT_GC_IDLE_GC -follows-> Scavenge/Global | verbose GC tag appears |
|:-:|:-:|
| EXPLICIT_GC_IDLE_GC -follows-> no GC activity or JVM shutdown | verbose GC tag doesn't appear |

**Comment by Param-S** [comment]
PR submitted : https://github.com/eclipse/omr/pull/1234

**Comment by charliegracie** [comment]
Closing as I believe this had been resolved via #1234.  Please re-open if I have closed this incorrectly.
