### ISSUE TITLE
Update the guidelines for commits and issues

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#124]
I think we need to take another look at our commit standard for OMR. Proposing the following guidelines: 

The first line should be:
- Imperative, saying what the patch does.
- Very short, preferable < 80 characters. I know this is hard.
- Not describing the issue it fixes, save that for the body. Describe what the change itself is.

The second line is always blank.

Put as much information in the commit body as possible. Describe the change as well as relevant  features, designs, issues, everything. Don't be afraid to write a lot. The commit should be as self contained as possible.

keep text bodies hard wrapped at 80 where reasonable.

If there is an associated issue, reference it with `Issue: #XXX` in the footer of the commit. If the commit fixes a bug, reference it with `Fixes: #XXX` (this will close the issue when the commit is accepted).
Important issue information must be placed in the relevant commit.

You can reference issues, commits, and pull requests in the body for discussion.

Issues are for new feature requests, problem reports, discussion, things like that. If everything can be described in a single commit, do it. Big documentation details that can't be expressed in commits should be checked in. Comment your code, or put something in /doc.

Put any other metadata in the footer. Keys can be repeated. One value per key.
```
Svt: 123456
Found-in: java70
Reviewed-by: Watson <watson@cloud.ibm.com>
```

Try to keep the repository self contained.

This is a good commit from the linux kernel
```
net_sched: close another race condition in tcf_mirred_release()

We saw the following extra refcount release on veth device:

  kernel: [7957821.463992] unregister_netdevice: waiting for mesos50284 to become free. Usage count = -1

Since we heavily use mirred action to redirect packets to veth, I think
this is caused by the following race condition:

CPU0:
tcf_mirred_release(): (in RCU callback)
	struct net_device *dev = rcu_dereference_protected(m->tcfm_dev, 1);

CPU1:
mirred_device_event():
        spin_lock_bh(&mirred_list_lock);
        list_for_each_entry(m, &mirred_list, tcfm_list) {
                if (rcu_access_pointer(m->tcfm_dev) == dev) {
                        dev_put(dev);
                        /* Note : no rcu grace period necessary, as
                         * net_device are already rcu protected.
                         */
                        RCU_INIT_POINTER(m->tcfm_dev, NULL);
                }
        }
        spin_unlock_bh(&mirred_list_lock);

CPU0:
tcf_mirred_release():
        spin_lock_bh(&mirred_list_lock);
        list_del(&m->tcfm_list);
        spin_unlock_bh(&mirred_list_lock);
        if (dev)               // <======== Stil refers to the old m->tcfm_dev
                dev_put(dev);  // <======== dev_put() is called on it again

The action init code path is good because it is impossible to modify
an action that is being removed.

So, fix this by moving everything under the spinlock.

Fixes: 2ee22a9 ("net_sched: act_mirred: remove spinlock in fast path")
Fixes: 6bd00b8 ("act_mirred: fix a race condition on mirred_list")
Cc: Jamal Hadi Salim <jhs@mojatatu.com>
Signed-off-by: Cong Wang <xiyou.wangcong@gmail.com>
Acked-by: Jamal Hadi Salim <jhs@mojatatu.com>
Signed-off-by: David S. Miller <davem@davemloft.net>
```

**Comment by rwy0717** [comment]
Some links on good git commit style that we could be following:
* http://chris.beams.io/posts/git-commit/
* https://git-scm.com/book/ch5-2.html#Commit-Guidelines
* http://who-t.blogspot.com/2009/12/on-commit-messages.html

**Comment by rwy0717** [comment]
Some other ideas can be pulled from here https://www.kernel.org/doc/Documentation/SubmittingPatches

**Comment by rwy0717** [comment]
Some other advice, pulled verbatim from the node contributor guidelines, but very common:

1. The first line should be 50 characters or less and contain a short description of the change prefixed with the name of the changed subsystem (e.g. "net: add localAddress and localPort to Socket").
2. Keep the second line blank.
3. Wrap all other lines at 72 columns.

https://github.com/nodejs/node/blob/master/CONTRIBUTING.md

**Comment by mstoodle** [comment]
I will agree that our history is looking pretty jumbled and not very easy to follow. Many of these recommendations seem like they would help clean up our history which would be a very Good Thing.

**Comment by charliegracie** [comment]
I like a lot of your ideas @rwy0717.  I think it would be great if all commit messages were as thorough as the ones you showed above.

**Comment by mstoodle** [comment]
As it turns out, git log --grep is able to pull the issue number out of a commit message without it having to be in the title, so I think @rwy0717's suggestions are completely compatible with Angela's "hard requirements" listed in Issue #46.

Robert, would you like to take a crack at updating the contributing guidelines to include your recommendations?

**Comment by mgaudet** [comment]
Another tool worth looking at in this context is [GitCop](https://gitcop.com) that may be able to help us enforce whatever guidelines we have here.

**Comment by charliegracie** [comment]
@rwy0717 have you had a chance to look into updating the contributing guidelines?

**Comment by rwy0717** [comment]
I have a draft around. I'll open a pull request so everyone can take a look at it.

**Comment by rwy0717** [comment]
How do we feel about tagging pull requests, commits, and issues with components? The common way is to write `component: message` on the first line of a commit. I see it as primarily useful for reviewers facing a large number of pull requests.  For now I think we should leave this out of our guidelines, seeing as we don't currently face too much traffic, and it takes up precious first line space. I see it as something we may want in the future.

Any one else have opinions?

**Comment by mstoodle** [comment]
Personally, I agree with your take: at some point it will probably be useful but maybe not warranted quite yet. 

That being said, Charlie has been handling virtually all of the review traffic lately, so I'm happy to defer to him if he has a different opinion.

**Comment by rwy0717** [comment]
The contributing is still missing a few things:
1. When and how to use issues.
2. Advice for j9 users on referencing java issues.

**Comment by dorrab** [comment]
Can we have a label to identify long standing issues or issues that we are not planning on fixing and closing quickly? I am thinking about issue #165 opened for the documentation. As we reference the issue in the website, I believe we will keep it open for a little while (at least until all pages are created/populated)

**Comment by DanHeidinga** [comment]
> The footer cannot have any blank lines. 
What's the rationale for this requirement?  Does it matter if there is a blank line between the Issue: # and the signed off line?

**Comment by rwy0717** [comment]
Yes, a lot of tools will consider the line above the blank line to be in the body of the message. Take a look here [1]. You might trip up the eclipse validation.

[1] https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit

**Comment by DanHeidinga** [comment]
So the real requirement is that the signed-off line must be in the footer of the message and can't be followed by any blank lines.  Probably worth adding some of the reasoning into the guidelines so it looks less arbitrary.

**Comment by rwy0717** [comment]
I've elaborated on the format of the footer, and added a reminder specifically for the signed off line. What do you think?

**Comment by DanHeidinga** [comment]
+1 - Looks good to me.
