### ISSUE TITLE
JitBuilder uses incorrect x86-64 register to allocate small stack frames in function prologues

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#1243]
When allocating a stack frame that is 8-bytes or less on x86-64, the function prologue generated by JitBuilder uses a `push` of a dummy register. In the epilogue, it pops the same register to de-allocate the frame.

However, the dummy register currently used (on x86-64) is `rbx`, which is a preserved register. This is a problem because when the register is popped in the epilogue, it overwrites the value of the register with whatever was left on the stack.

**Comment by mstoodle** [comment]
Yeah, that was a dumb mistake I made with one of the commits in #1146 (bad Mark!). Not sure what I was thinking (well, clearly I wasn't thinking).

We should use a volatile register like r11 for this purpose rather than rbx.
