### ISSUE TITLE
Using blocking IO for VerboseGC causes unnecessary long pauses during GC

### ISSUE THREAD

**Issue by youngar** [eclipse/omr#125]
VerboseGC uses hook events triggered during a garbage collection to print GC stats,  which are helpful for debugging any GC related issues.  Currently we use blocking synchronous IO to write this information to a filedescriptor.  This use of blocking synchronous IO during VerboseGC occasionally takes much longer than normal, sometimes stalling for seconds.  Since exclusive access is held during this event, it causes the GC pause times to inflate while waiting for the logs to be written.

**Comment by charliegracie** [comment]
I believe this is completely resolved by #131 is that correct?

**Comment by charliegracie** [comment]
Closing as I believe this is resolved by #131 please re-open if I am wrong
