### ISSUE TITLE
Potentially unwanted variable shadowing in LocalOpts.cpp

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#1308]
When compiling LocalOpts.cpp with GCC the following warning is produced due to nested loop variable shadowing:

```
../omr/compiler/optimizer/LocalOpts.cpp: In member function ‘int32_t TR_HoistBlocks::process(TR::TreeTop*, TR::TreeTop*)’:
../git/omr/compiler/optimizer/LocalOpts.cpp:1627: warning: name lookup of ‘nextEdge’ changed
../git/omr/compiler/optimizer/LocalOpts.cpp:1550: warning:   matches this ‘nextEdge’ under ISO standard rules
../git/omr/compiler/optimizer/LocalOpts.cpp:1605: warning:   matches this ‘nextEdge’ under old rules
```

We should verify what logic is wanted here and rename the most nested loop variable appropriately.

**Comment by Leonardo2718** [comment]
@PeXXeR looks like you might right! @fjeremic can you confirm?

**Comment by fjeremic** [comment]
> @PeXXeR looks like you might right! @fjeremic can you confirm?

Confirmed.
