### ISSUE TITLE
Fix dead code in TR_HoistBlocks

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#1321]
The implementation of `TR_HoistBlocks::process()` in `compiler/optimizer/LocalOpts.cpp` contains the following block, inside a loop:

```c++
if (isLoopHdr)
   {
   // Disable partial peeling of loops by hoisting.
   // Gives rise to strage loop layout with part/all of the iteration
   // peeled outside.  No convincing reason to keep hoisting out of
   // loops enabled.
   //
   nextEdge = next;
   continue;


   // Check if the hoisted loop header won't have a block in
   // middle of the loop as a successor; this situation could
   // create improper regions, reducing effectiveness of opts that
   // follow.
   //
   int32_t successorsInMidLoop = 0;
   for (auto nextEdge = block->getSuccessors().begin(); nextEdge != block->getSuccessors().end(); ++nextEdge)
      {
      TR::Block *succBlock = toBlock((*nextEdge)->getTo());
      TR_Structure *succBlockStructure = succBlock->getStructureOf();
      while (succBlockStructure)
         {
         if (succBlockStructure == containingLoop)
            break;

         succBlockStructure = succBlockStructure->getParent();
         }

      if (succBlockStructure)
         {
         successorsInMidLoop++;
         if (successorsInMidLoop > 1)
            break;
         }
      }

   if (successorsInMidLoop > 1)
      {
      nextEdge = next;
      continue;
      }
   }
```

A peculiarity of this code is that the very first `continue` statement causes everything after it in the `if` block to be skipped. 

Due to my lack of familiarity with the code, I'm unsure whether the correct fix is to eliminate the dead code or to move it out of the if block.

**Comment by mstoodle** [comment]
Looks to me like someone discovered a problem and, rather than completely remove the suspect code, disabled it (at least they left a comment :) ).

My vote would be to remove the code that's downstream of the continue, but leave the comment explaining why we don't do hoisting out of loops via this particular optimization.

@andrewcraik @vijaysun-omr agree or no?

**Comment by vijaysun-omr** [comment]
I am fine removing the dead code.

**Comment by 0xdaryl** [comment]
The disposition here is to remove the dead code following the `continue` statement in the `if` block.
