### ISSUE TITLE
rememberSet insufficiently guarded

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1359]
In `gc/base/standard/EnvironmentStandard.cpp` there is a [naked reference to `rememberSet`](https://github.com/eclipse/omr/blob/master/gc/base/standard/EnvironmentStandard.cpp#L54)

[The definition of this member](https://github.com/eclipse/omr/blob/master/gc/base/GCExtensionsBase.hpp#L244) is guarded by `OMR_GC_MODRON_SCAVENGER`, and so a build will fail unless scavenger is enabled.

**Comment by 0xdaryl** [comment]
@mgaudet @rwy0717 : can this be closed now?
