### ISSUE TITLE
Remove 'no virt' comments from code generators

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1398]
This is a follow-on action from issue #1072.

When the code generator was converted to an extensible class a number of marker comments were left in the header files that provided some metadata about the functions.  These are no longer relevant, useful, or correct in some cases.  Simply delete them.

grep the code generator source files for 'no virt' and eliminate the comments.  For example,
```
p/codegen/OMRCodeGenerator.hpp:   bool shouldValueBeInACommonedNode(int64_t); // no virt, cast
x/codegen/OMRCodeGenerator.hpp:   bool internalPointerSupportImplemented() {return false;} // no virt
z/codegen/OMRCodeGenerator.hpp:   bool supportsNamedVirtualRegisters(); // no virt, default
```

**Comment by vidyasubramanyam** [comment]
I think there are around 144 "no virt" comments in code generator of which 140 comments are in ./compiler/codegen/OMRCodeGenerator.hpp . Should all be removed.
