### ISSUE TITLE
Remove unused `TR::idoz` opcode and evaluator

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1400]
This opcode is left over from a previous compiler implementation is no longer used.  Delete the opcode, the evaluator, and remove it from all tables in which it appears.

**Comment by 0xdaryl** [comment]
@GesusK, please investigate this.

**Comment by agarwalrounak** [comment]
I am working on this issue.

**Comment by 0xdaryl** [comment]
It appears this opcode has already been removed from the codebase.  Closing.
