### ISSUE TITLE
Remove unused `TR::bztestnset` opcode and evaluator

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1401]
This opcode is left over from a previous compiler implementation is no longer used. Delete the opcode, the evaluator, and remove it from all tables in which it appears.

**Comment by 0xdaryl** [comment]
@GesusK, please investigate this.

**Comment by GesusK** [comment]
@0xdaryl When I'm working on this issue, I found there are some lines in `compiler/x/i386/codegen/TreeEvaluatorTable.hpp`:
```
    TR::TreeEvaluator::icmpsetEvaluator,                 // TR::icmpset (zPDT)
    TR::TreeEvaluator::lcmpsetEvaluator,                // TR::lcmpset (zPDT)
    TR::TreeEvaluator::atomicorEvaluator,                // TR::ibatomicor (zPDT)
    TR::TreeEvaluator::atomicorEvaluator,                // TR::isatomicor (zPDT)
    TR::TreeEvaluator::atomicorEvaluator,                // TR::iiatomicor (zPDT)```

But in `compiler/x/amd64/codegen/TreeEvaluatorTable.hpp`, or other files, the same TR IL's are not marked as related to zPDT.
So are they specified only for zPDT? If so, should we remove them?

**Comment by 0xdaryl** [comment]
yes, those can be removed as well.  I can't find them generated in any downstream project.  Be sure you also clean up any TreeEvaluator evaluators as well.

**Comment by agarwalrounak** [comment]
I am working on this issue.

**Comment by 0xdaryl** [comment]
I have come to learn that there is a private downstream project consuming this opcode, and hence I am no longer recommending it be removed.
