### ISSUE TITLE
Rewrite z/OS version of omrsysinfo_get_physical_memory

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#142]
On z/OS, omrsysinfo_get_physical_memory() uses the CVTRLSTG field which returns the 
amount of physical memory at IPL. 
This value may not be correct at the time due to reconfigurable memory. 
The correct field is RCEPOOL.

**Comment by charliegracie** [comment]
I believe this should be closed via #143.  Please re-open if I am incorrect
