### ISSUE TITLE
Test: ThreadAbortTest.Running hangs occasionally on linux_x86-64_cmprssptrs

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#1438]
Output:

```
./omrthreadtest
Note: Google Test filter = -*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended
[==========] Running 77 tests from 10 test cases.
[----------] Global test environment set-up.
[----------] 1 test from ThreadAbortDeathTest
[ RUN      ] ThreadAbortDeathTest.Nullpointer
[WARNING] ../../third_party/gtest-1.7.0/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.
[       OK ] ThreadAbortDeathTest.Nullpointer (147 ms)
[----------] 1 test from ThreadAbortDeathTest (147 ms total)
[----------] 3 tests from ThreadAbortTest
[ RUN      ] ThreadAbortTest.Running
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

This is using the old autoconf build system.

**Comment by charliegracie** [comment]
Has this happened recently?  @youngar, @mstoodle, @vijaysun-omr, @0xdaryl have any of you had to restart jobs due to this issue for PR builds recently?  I personally have not witnessed it since I made improvements to the time taken to run the FV tests.  If it has not happened I suggest that we leave this open for another week and if it has not happened by then we can close this issue.  Does that make sense @rwy0717?

**Comment by 0xdaryl** [comment]
I personally haven't encountered this failure for a few weeks, though I don't know if anything was done to explicitly fix this issue (perhaps its just masked now).  It was quite prevalent at one point.  I agree with closing it for now, but re-opening and figuring out an investigation plan if it recurs.

**Comment by rwy0717** [comment]
I haven't seen this issue in a while either. Closing this issue makes sense.
