### ISSUE TITLE
Work Packet Overflow warning is missed in GC verbose log

### ISSUE THREAD

**Issue by LinHu2016** [eclipse/omr#144]
for both standard overflow and concurrent overflow case, warning message for work packet overflow is missed in gc verbose log.

**Comment by charliegracie** [comment]
@LinHu2016 is this something you would like to work on?

**Comment by LinHu2016** [comment]
@charliegracie , Hi Charlie, this issue has been fixed in June 2016 in pull request#146, https://github.com/eclipse/omr/pull/146
