### ISSUE TITLE
Proposal to shorten Tril commoned node identifiers

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1508]
In an attempt to make Tril slightly less verbose when dealing with commoned nodes, instead of declaring `@common id="foo"` can we simply shorten it to `@id="foo"` ?

To my eye, it is still easy to distinguish commoned and uncommoned node identifiers.  It also looks more readable when there are a lot of commoned nodes in play (though, arguably, Tril isn't really supposed to favour human readability).

Any thoughts?

@Leonardo2718

**Comment by Leonardo2718** [comment]
I'm okay with the shorter syntax, though I would prefer `@id "foo"` (without the `=`) as this avoids having to changing the parser :sweat_smile: .

Any objections to supporting both forms (at least until Tril gets proper versioning)?

**Comment by mgaudet** [comment]
Can you emit a deprecation warning if you use `@common`? Just, if you support both without... soon both will be there forever...

**Comment by 0xdaryl** [comment]
No objections to supporting two syntaxes provided there is justification.

As we discussed in person, I'm OK with the alternate `@id` syntax and the reasoning for it (the reasoning being that an `id` cannot appear as the first term in an s-expression in the current grammar).  I'm willing to trade off the slight inconsistency with id usage for the decrease in verbosity.
