### ISSUE TITLE
LOA resizing adjustements

### ISSUE THREAD

**Issue by amicic** [eclipse/omr#152]
There are two unrelated items:
- occasionally we may end up doing LOA resizing, while it's really unnecessary, simply due to math rounding errors. Eventually, when reporting it (in verbose GC) we would observe conflicting information in resize type  and resize reason and assert. Whole this logic is messy (type and reason are only loosely related in the code, while there should be tighter connection), but for now, we at least need to ensure that we do not do this unnecessary resize.
- default LOA min is 0% of Tenure. In several real life scenario, enforcing a small LOA min size (like 1%) was rather helpful. On the other side, this small sacrifice will be unnoticeable for majority of workloads (although it might still be regression for contrived testcases, that are aware of heap size). New default LOA min is to be set to 1%.

**Comment by charliegracie** [comment]
Closing as I believe this was resolved under #153.  If I am incorrect please re-open

**Comment by amicic** [comment]
This issue actually has wider scope. But hope to resolve it soon.
