### ISSUE TITLE
Un-necessary objects in JitBuilder builds?

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1537]
Building JitBuilder on OS/X the archiver warns about objects it believes to be empty. 

* `compiler/x/codegen/Trampoline.cpp` 
* `compiler/codegen/OMRRegisterDependency.cpp` 

Cursory inspection suggests these warnings are correct and we can even probably delete these files, but that needs validation.

**Comment by 0xdaryl** [comment]
Done.
