### ISSUE TITLE
Xcode Build of omrutil with CMake fails

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1542]
<img width="263" alt="screen shot 2017-08-20 at 8 30 04 pm" src="https://user-images.githubusercontent.com/2906003/29499763-64a6854c-85e6-11e7-96ec-a47195bb25bb.png">

(Almost everything else seems to succeed though!)

**Comment by dnakamura** [comment]
Weird. This almost feels like an issue with CMake itself, as all the path tracking stuff is handled automatically

**Comment by mgaudet** [comment]
It appears it passes now :) 

```
mkdir build; cd build; cmake -GXcode -C../cmake/caches/Travis.cmake .. 
```

I then used the GUI to compile, though, I suspect that `xcodebuild` might do the trick here.
