### ISSUE TITLE
Enable up to 64 GB heaps for ZOS Compressed References platform

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/omr#157]
Add up to 64 GB heaps support for zOS Compressed References platform

zOS has a special support for Virtual Memory allocation for Compressed References - an allocation below 32GB bar. Recently this functionality has been extended to support allocations below 64GB bar. 
This item enables usage of new extended feature so heaps up to 64GB can be used in Compressed References for zOS.

**Comment by charliegracie** [comment]
Can you provide a few more details about the proposed solution?  Thanks

**Comment by charliegracie** [comment]
Implemented via pull request #160
