### ISSUE TITLE
Fix function name typo in UseDefInfo

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1582]
Fix typo in `setVolatileSybolsIndexAndRecurse` function name in UseDefInfo.cpp/hpp and repair all references.

Should be `setVolatileSymbolsIndexAndRecurse`.

**Comment by mgaudet** [comment]
```
setVolatileSybolsIndexAndRecurse
setVolatileSymbolsIndexAndRecurse
```

Note the missing `m` (I had to do the above alignment to see the issue :P )

**Comment by peey** [comment]
This issue should be closed. There are no more occurrences of the wrong name `setVolatileSybolsIndexAndRecurse` in the code
