### ISSUE TITLE
Updating our license to EPLv2

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#1596]
With this project's largest stakeholder becoming an open source project (Eclipse OpenJ9), a licensing compatibility issue has arisen that affects Eclipse OMR. I would like to resolve this via a committer vote, but we also need to collect some data from our contributors.

What's the issue?

The Eclipse OpenJ9 Java Virtual Machine project both consumes Eclipse OMR project and must have a compatible license story to work within the context of OpenJDK. The current state is:

- Eclipse OMR has dual Apache License 2.0 and Eclipse Public License 1.0

- OpenJDK has GNU General Public License, version 2 with the GNU Classpath Exception [1] and GNU General Public License, version 2 with the OpenJDK Assembly Exception [2].

OpenJ9 is stuck in the middle :) . What they have opted to do is a more complicated license to support two primary activities: 1) moving code back and forth between OMR and OpenJ9, and 2) being used alongside the precise flavour of GPLv2 license (with the noted exceptions) used OpenJDK.

To be more specific, Eclipse OpenJ9 is going with this license:
```
This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which accompanies this distribution and is available at http://eclipse.org/legal/epl-2.0 or the Apache License, Version 2.0 which accompanies this distribution and is available at https://www.apache.org/licenses/LICENSE-2.0.

This Source Code is also Distributed under one or more Secondary Licenses, as those terms are defined by the Eclipse Public License, v. 2.0: GNU General Public License, version 2 with the GNU Classpath Exception [1] and GNU General Public License, version 2 with the OpenJDK Assembly Exception [2].
```

For that license to work for the two activities mentioned, Eclipse OMR would have to have this same license. I propose that Eclipse OMR should adopt the license above. We lose nothing that I can see, and will continue to work with our largest stakeholder, the Eclipse OpenJ9 project.

I would like the committers to vote on this proposal with Agree (+1), Disagree (-1), or Abstain (0). I will hold the voting open for one week, but if the vote has been decided (i.e. enough +1's or -1's have been submitted that the remaining committer votes cannot change the result), then I will call the vote complete. There are additional tasks to perform if the vote succeeds (to ensure all contributors will provide their contributions under the new license).

**@charliegracie @alin00 @0xdaryl @youngar @jduimovich @vijaysun-omr please vote before 11:59:59 EST on Thursday, September 7. Any committer who does not explicitly vote will be counted as an Abstain (0). The sum of all votes must be > 0 for the proposal to pass.**

[1] https://www.gnu.org/software/classpath/license.html 
[2] http://openjdk.java.net/legal/assembly-exception.html

**Comment by mgaudet** [comment]
What happens if we cannot get in contact with all contributors?

**Comment by mstoodle** [comment]
Let's worry about that if it happens.

**Comment by 0xdaryl** [comment]
+1

**Comment by mstoodle** [comment]
+1

**Comment by jduimovich** [comment]
+1

**Comment by charliegracie** [comment]
+1

**Comment by youngar** [comment]
+1

**Comment by mstoodle** [comment]
Ok, that was fast :) . So far we have a +5 vote with only two committers not yet having voted. I'm going to call the proposal "passed" so that we can start the official process to change the license.

I will still encourage the remaining committers @alin00 and @vijaysun-omr to put their vote "on the record". I won't close this issue until the voting period officially ends.

**Comment by vijaysun-omr** [comment]
+1

**Comment by mstoodle** [comment]
Sorry, I was late closing off this vote. The final tally is +6 with no negative votes and we have already initiated the process to change our license and file headers accordingly.

Thanks everyone!

**Comment by 0xdaryl** [comment]
FYI, the Eclipse license reported here https://projects.eclipse.org/projects/technology.omr needs to be updated to EPLv2 as well.  I looked around but there doesn't appear to be a way for me to change it.  Likely something at the project level needs to change.

**Comment by mstoodle** [comment]
I think we have to open a bug for that at eclipse. Thanks for the reminder!

**Comment by DanHeidinga** [comment]
@mstoodle Can this be closed now that the relicensing is complete?

**Comment by mstoodle** [comment]
Hi @DanHeidinga. I was leaving it open as a place to record and track any remaining bits that needed to be changed. Our projects page is still not updated, so I was keeping this around. That's the only remaining piece I am aware of.

Of course, I didn't put anything into this issue to record what I had done in the last 10 days :( . I contacted the Eclipse Foundation and they were looking into the right process to use to make this change.

**Comment by DanHeidinga** [comment]
Given this work is complete, @charliegracie or @mstoodle can this be closed?

**Comment by mstoodle** [comment]
Nonetheless, it's a good reminder to circle back to Eclipse on it. Thanks, @DanHeidinga :)

**Comment by mstoodle** [comment]
Ok, the reminder eventually worked *sigh* . I opened a bug here to get the license changed on the project page: https://bugs.eclipse.org/bugs/show_bug.cgi?id=528511

**Comment by 0xdaryl** [comment]
The license on the [project page](https://projects.eclipse.org/projects/technology.omr) has been updated (yay!).  However, it's missing one of the secondary licenses:

`LicenseRef-GPL-2.0 WITH Assembly-exception`

I think another bug report from @mstoodle or @charliegracie to rectify is in order.

**Comment by mstoodle** [comment]
Thanks @0xdaryl ! I updated the bug (since it is still open) to point out the omission.

**Comment by 0xdaryl** [comment]
This was fixed today.  There are no outstanding issues.  Closing this.
