### ISSUE TITLE
Remove deprecated CS2 DirectedGraph

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1603]
CS2 classes are deprecated and are incrementally being eliminated.

Prove that DirectedGraph and its support classes are no longer used and delete them (`cs2/dgraph.h`).

**Comment by wbh123456** [comment]
@0xdaryl The `cs2/dgraph.h` file no longer exists. Thus this issue can be closed.

**Comment by Leonardo2718** [comment]
@wbh123456 is correct. This issue was resolved in #1737. Closing.
