### ISSUE TITLE
Request contributor approval to relicense all contributions

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#1606]
With the committer vote in #1596 having passed (well, technically, it hasn't closed yet but enough committers have +1'd that the result cannot change), we need to collect approvals from all contributors to relicense their contributions under the new license.  For reference, here is the new license information:

To be more specific, the Eclipse OMR project has decided to change its license to the following:
```
This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which accompanies this distribution and is available at http://eclipse.org/legal/epl-2.0 or the Apache License, Version 2.0 which accompanies this distribution and is available at https://www.apache.org/licenses/LICENSE-2.0.

This Source Code is also Distributed under one or more Secondary Licenses, as those terms are defined by the Eclipse Public License, v. 2.0: GNU General Public License, version 2 with the GNU Classpath Exception [1] and GNU General Public License, version 2 with the OpenJDK Assembly Exception [2].

[1] https://www.gnu.org/software/classpath/license.html 
[2] http://openjdk.java.net/legal/assembly-exception.html
```

This license updates our existing Eclipse Public License from v1 to the latest v2, and adds a secondary license compatibility statement so that our project code can be combined with the GPLv2 license described above. This change only expands the scenarios where the Eclipse OMR code can be used, which consequently requires contributors to permit broader licensing terms on their contributions. This broader licensing requirement is why we need this approval request from all existing contributors to the project.

To simplify the approval process, any contributor who was an IBM employee at the time of their contribution can be covered by a single executive-level IBM approver. After discussion with the Eclipse Foundation, @jduimovich can provide this approval for all IBM contributions (including his own :) ).

Not all contributions have come from IBM employees, however, so there are still a few people who we must explicitly ask to give their approval to re-license all their contributions, specifically @amitin @erik-brangs @gurinderu @Krovatkin .
 
Would everyone @ mentioned directly in this issue please respond with a +1 to confirm that you agree to relicense your contributions (all IBM contributions in @jduimovich's case) according to the license outlined above (I suppose -1 is also a possible response)?

If there are any non-IBM contributors that are not identified in this list, please mention it here (and give your +1/-1).

**Comment by amitin** [comment]
+1

**Comment by jduimovich** [comment]
+1

**Comment by Krovatkin** [comment]
+1

**Comment by erik-brangs** [comment]
+1

**Comment by gurinderu** [comment]
+1

**Comment by mstoodle** [comment]
Thanks to everyone for responding. Unfortunately, I missed one of our external contributors: @Varun-garg with his GSoC work!

@Varun-garg, would you also please respond to this request?

**Comment by Varun-garg** [comment]
It's alright @mstoodle, I am in.

+1

**Comment by mstoodle** [comment]
Ok, that's everyone! Thank you all for responding and confirming your agreement to relicense your (organization's) Eclipse OMR contributions under the terms described in the introduction to this issue.

**Comment by mstoodle** [comment]
I have confirmation from the Eclipse Foundation that we can proceed with updating our copyright headers and license files. There's a change to the required text, which fortunately isn't substantial enough to require a revote.

The text we need to use is here:
```
    Copyright (c) {date} {owners} 

    This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which accompanies this distribution and is available at http://eclipse.org/legal/epl-2.0 or the Apache License, Version 2.0 which accompanies this distribution and is available at https://www.apache.org/licenses/LICENSE-2.0. 

    This Source Code may also be made available under the following Secondary Licenses when the conditions for such availability set forth in the Eclipse Public License, v. 2.0 are satisfied: GNU General Public License, version 2 with the GNU Classpath Exception [1] and GNU General Public License, version 2 with the OpenJDK Assembly Exception [2]. 

    [1] https://www.gnu.org/software/classpath/license.html  
    [2] http://openjdk.java.net/legal/assembly-exception.html 

    SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
```
The PRs linked to this issue will need to be updated before any can be merged.

**Comment by mstoodle** [comment]
This issue has been resolved for quite some time now. Closing.
