### ISSUE TITLE
Create a simple logger for fvtest

### ISSUE THREAD

**Issue by renfeiw** [eclipse/omr#163]
The main purpose of the logger is to provide different layers of logging level:
LEVEL_VERBOSE   -   detailed message for debug purpose.
LEVEL_INFO          -   default level.
LEVEL_WARN       -    warning message.
LEVEL_ERROR       -   error/failure message.
LEVEL_OFF            -    no message from logger.

Use function log(LogLevel ll, const char *format, ...) to write test message to stdout. If no log level is provided, the level defaults to LEVEL_INFO.

To control the finest log level to output, use command line option "-logLevel=". The accepted values are "verbose, info, warn, error, off" corresponding to the logging levels shown above. If no "-logLevel" is passed, the finest level is LEVEL_INFO.

We plan to change gctest to use logger first and set it as an example for the rest of the fvtests.

**Comment by charliegracie** [comment]
closed via #169
