### ISSUE TITLE
Externalize slot object for GC_ObjectScanner

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/omr#1638]
GC_ObjectScanner (omr/gc/base/ObjectScanner.hpp) contains a GC_SlotObject _slotObject member that it uses to communicate found reference slots to calling code in getNextSlot(). This arrangement prohibits calling code from using a subclass of GC_SlotObject that may contain additional object metadata, eg object size, that is important to its task. Also, it opens up the possibility of leaving the caller with a dangling GC_SlotObject pointer after the GC_ObjectScanner instance has been destroyed. 

A GC_SlotObject * _slotObjectPtr member (private) should be added to GC_ObjectScanner, and a new constructor. In the existing constructor, _slotObjectPtr should be set to the address of the existing _slotObject member, to maintain compatibility with existing code that uses GC_ObjectScanner. The new constructor should present all of the parameters of the existing construct plus a GC_SlotObject * valued parameter that can receive a pointer to a GC_SlotObject or subclass instance of the caller's choosing. In the new constructor, _slotObjectPtr must be set to the parameter's value.

The implementation of `GC_ObjectScanner::getNextSlot()` should then be refactored to use exclusively _slotObjectPtr, and any other direct references to _slotObject.x must be replaced with  _slotObjectPtr->x.

Object scanning is interruptible, so GC_ObjectScanner must present a new public method `setSlotObject(GC_SlotObject *x)` to set _slotObjectPtr = x, To be called when restoring interrupted scanning state. 

Additionally, all subclasses of GC_SlotObject must add a new constructor that receives a GC_SlotObject parameter and passes it down the inheritance chain to the new GC_ObjectScanner constructor. 

Finally, a comment must be added to the existing GC_ObjectScanner and subclass constructors to indicate that they are DEPRECATED and will be removed at some point in the future, with instructions to use the new constructor.

**Comment by smlambert** [comment]
@amicic - do you feel this an interesting exercise for some one?

**Comment by amicic** [comment]
On a quick pass, I'm not sure I understood the point. I'll pass on@rwy0717 and @dmitripivkine (who are anyway more familiar with it) to comment.

**Comment by dmitripivkine** [comment]
I believe it is not

**Comment by rwy0717** [comment]
I'm closing this issue, because I don't think it's a change we will want to make.
