### ISSUE TITLE
Selecting a thread notify policy

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#167]
Adding a framework to choose a thread notify policy at startup using a
potential command line option.

This framework applies only to POSIX complaint platforms. Two thread
notify policies are available on POSIX complaint operating systems:
signal and broadcast.

Signal thread notify policy wakes up a single thread that is waiting
on the condition. In contrast, broadcast thread notify policy wakes
up all the threads that are waiting on a condition.

On Windows, only one thread notify policy (SetEvent) is available. So,
this framework doesn't support Windows platform.

In OMR, waiting threads are notified from the following functions:
1) omrthread_resume
2) threadInterrupt
3) interrupt_blocked_thread
4) threadNotify
5) threadInterruptWake
6) omrthread_unpark
7) unblock_spinlock_threads

Previously, broadcast thread notify policy was used by default in all
of the above functions.

In OMR, each thread has a unique condition variable associated with it.
So, only one thread wakes up whether we use the signal or broadcast
thread notify policy.

But, we occasionally wake up more than one thread by repeatedly calling
the thread notify policy. All the woken threads may contend for the same
mutex. The cost of contention varies depending upon the notify policy
which is employed to wake up the threads. The cost of contention has an
impact on the performance.

This framework would allow selection of a thread notify policy at
startup using a potential command line option. Thus, an application's
performance can be improved if a thread notify policy with lower cost of
contention is employed at runtime.

Implementation details:

i) Compile flag, OMR_NOTIFY_POLICY_CONTROL, has been added. The code
changes for this framework can be included and excluded by enabling and
disabling the flag respectively.

ii) A new field has been added to struct J9ThreadLibrary for storing the
thread notify policy that is selected at startup. This field is named
notifyPolicy.

iii) J9ThreadLibrary->notifyPolicy stores 0 if thread notify policy is set
to signal. It stores 1 if thread notify policy is set to broadcast. Two macros
have been added: J9THREAD_LIB_NOTIFY_POLICY_SIGNAL (0) and
J9THREAD_LIB_NOTIFY_POLICY_BROADCAST (1).

iv) By default, J9ThreadLibrary->notifyPolicy is initialized to
J9THREAD_LIB_NOTIFY_POLICY_SIGNAL at startup unless
omrthread_global("notifyPolicy") is set.

v) A new macro named NOTIFY_WRAPPER is also added. This macro selects the
appropriate thread notify policy based upon the value stored in
J9ThreadLibrary->notifyPolicy.

**Comment by charliegracie** [comment]
Can you please provide more details?  An issue should describe a problem you are seeing, describing a feature you think should be added or for asking a question.

Thanks

**Comment by charliegracie** [comment]
Implemented via #168
