### ISSUE TITLE
Use do/while pattern in trace macros

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1692]
in `compiler/ras/LogTracer.hpp` there's a pair of macros: 

```cpp
#define heuristicTrace(r, ...) \
   if (true) { \
      if ((r)->heuristicLevel()) { (r)->alwaysTraceM(__VA_ARGS__); } \
   } else \
      (void)0


#define debugTrace(r, ...) \
      if (true) { \
         if ((r)->debugLevel())\
            {\
            (r)->alwaysTraceM(__VA_ARGS__);\
            }\
      } else \
         (void)0
```

Both have an awkward trailing else that triggers warnings on newer compilers: 

```
../compiler/optimizer/Inliner.cpp:5440:10: warning: add explicit braces to avoid dangling else [-Wdangling-else]
         heuristicTrace(tracer(),"Requesting another pass of MethodHandle invoke inlining due to %s\n", tracer()->traceSignature(calleeSymbol));
         ^
../compiler/ras/LogTracer.hpp:33:6: note: expanded from macro 'heuristicTrace'
   } else \
```

It seems like it should be pretty trivial to correct... but the pattern is so curious I feel like I'm missing something. Hence me opening an issue.

**Comment by 0xdaryl** [comment]
What springs to mind is that someone wrote this such that calls to `heuristicTrace()` and `debugTrace()` look like statements that introduce a scope and require a trailing `;`.

I believe the more conventional way to do this is in a C macro is:
```
#define MYMACRO(x,y,z) \
   do { \
       ooey gooey macro filling \
   } while (0)
```

Unless I'm wrong...

**Comment by mgaudet** [comment]
Huh. That seems pretty reasonable. I think the resolution of this one should be convert to the `do { } while(0)` format: This probably can be tagged as beginner and help-wanted.

**Comment by 0xdaryl** [comment]
Done.
