### ISSUE TITLE
OSX builds with recent clang: error: shifting a negative signed value is undefined

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#171]
On my macbook pro with the following clang version:
$ cc --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

The following recommended commands result in compile errors:
$ git clone https://github.com/eclipse/omr
$ cd omr/
$ make -f run_configure.mk SPEC=osx_x86-64 GLUE=./example/glue
$ make
...
./unix/omrfile.c:1151:58: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
                setPortableError(portLibrary, fileFStatErrorMsgPrefix, OMRPORT_ERROR_FILE_FSTAT_ERROR, myerror);
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include_core/omrporterror.h:114:43: note: expanded from macro 'OMRPORT_ERROR_FILE_FSTAT_ERROR'
#define OMRPORT_ERROR_FILE_FSTAT_ERROR (-2<<16)
                                        ~~^
./unix/omrfile.c:1160:60: error: shifting a negative signed value is undefined [-Werror,-Wshift-negative-value]
                setPortableError(portLibrary, fileFStatFSErrorMsgPrefix, OMRPORT_ERROR_FILE_FSTATFS_ERROR, myerror);
                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include_core/omrporterror.h:115:45: note: expanded from macro 'OMRPORT_ERROR_FILE_FSTATFS_ERROR'
#define OMRPORT_ERROR_FILE_FSTATFS_ERROR (-3<<16)
                                          ~~^
2 errors generated.

**Comment by mstoodle** [comment]
Should be should be (mistyped the OMRGLUE as GLUE):

 $ make -f run_configure.mk SPEC=osx_x86-64 OMRGLUE=./example/glue

**Comment by mstoodle** [comment]
Proposed fix is to change e.g. (-2<<16) to (-2*65536)

**Comment by charliegracie** [comment]
Fixed via #172
