### ISSUE TITLE
Refactor assertions handling

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1720]
When compiling with clang, you'll see 

```
[13/262] Building CXX object jitbuilder/CMakeFiles/jitbuilder.dir/__/compiler/infra/Assert.cpp.o
../compiler/infra/Assert.cpp:171:7: warning: function declared 'noreturn' should not return [-Winvalid-noreturn]
      }
     
```

This is because the OMR_NORETURN annotation is applied to the fatal assertion, however, the function it calls is not also annotated with OMR_NORETURN, because it's implementation is shared with non-fatal assertions.

Correcting this is best done by refactoring the contents of Assert.cpp to keep the fatal and non-fatal portions better isolated such that the annotations are correct. The annotation is intended to make static analysis of the codebase more accurate. 

(This is part of #1640)

**Comment by 0xdaryl** [comment]
Fixed in #3597.
