### ISSUE TITLE
Document compilation exception semantics

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1726]
The compiler technology uses C++ exceptions to indicate abnormal circumstances while a method is being compiled.  Many of them are fatal for the method being compiled, but some are not.

While many appear to be self-explanatory by their name alone, each exception should be documented and describe to runtime implementors the circumstances in which they should be thrown and the implications of handling them.

Documentation on how a runtime implementor can add their own compilation exception and how a downstream project can add one is helpful too.

From `runtime/CodeCacheExceptions.hpp`:
* CodeCacheError
* RecoverableCodeCacheError

From `compile/CompilationException.hpp`:
* CompilationException
* ILGenFailure
* RecoverableILGenException
* ExcessiveComplexity
* MaxCallerIndexExceeded
* CompilationInterrupted
* UnimplementedOpCode
* InsufficientlyAggressiveCompilation
* GCRPatchFailure

**Comment by dsouzai** [comment]
Since I added these exception types, I will document them. Should it be a comment in the *.hpp files or should it be in a .md file in the doc directory?

**Comment by 0xdaryl** [comment]
Thanks @dsouzai !  I would prefer comments in the code to avoid staleness.

**Comment by dsouzai** [comment]
I think this issue can be closed.
