### ISSUE TITLE
omrthreadnuma.c initialization code is slow

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#173]
On machines with many CPUs and memories initializeNumaNodeData() does large numbers of
filesystem accesses to determine the CPU affinities.
It reads each entry in /sys/devices/system/node/node\<n\>, checks if it starts with "cpu%lu" and updates the node data accordingly. 
However, there is typically a file called "cpulist" which contains the CPUs associated with the node.  Rewrite the initialization code to look for this file first.

**Comment by charliegracie** [comment]
Resolved by #179
