### ISSUE TITLE
Provide one line description for the OMR project

### ISSUE THREAD

**Issue by DanHeidinga** [eclipse/omr#178]
Looking at pages like the [Eclipse github org](https://github.com/eclipse), the OMR project is missing a description.  It currently displays as:

> omr
OMR project
Updated 12 minutes ago

A better description will make it easier to find and help users to know what it is.

I suggest text to the effect of:

> Eclipse OMR: high performance, cross-platform language runtime components

This can be updated by (a project lead?) on the https://github.com/eclipse/omr page directly under the `<> Code` tab.  It should show a '-- Edit' for those able to modify it.

/CC @mstoodle

**Comment by mstoodle** [comment]
Thanks, Dan. I was looking at that just an hour or so ago too; sadly, it does not show up with an edit button for me.

I suspect the Eclipse webmaster owns it because we're under the eclipse foundation. Will find out.

**Comment by mstoodle** [comment]
Asked webmaster to fix it and verified there is now text in our project front page and it shows up when you ask about the OMR project.

**Comment by DanHeidinga** [comment]
Thanks Mark!
