### ISSUE TITLE
Signed Integer Overflow in TR_RandomSeedSignatureHash

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1794]
Minor issue :) 

https://github.com/eclipse/omr/blob/8595d1c3b98b623cf696f9e1cb8a8ae1c94e0925/compiler/compile/OMRCompilation.cpp#L338-L347

```
../compiler/compile/OMRCompilation.cpp:342:19: runtime error: signed integer overflow: 33 * 1856584571 cannot be represented in type 'int'
```

Discovered by running Tril's compiler tests with `-fsanitized=undefined`

**Comment by mstoodle** [comment]
Would this also fail if hash was uint32_t ?

**Comment by mgaudet** [comment]
Unsigned overflow is defined behaviour: So yes, it would pass by changing that type.
