### ISSUE TITLE
Queries regarding Valgrind integration

### ISSUE THREAD

**Issue by Varun-garg** [eclipse/omr#1799]
While most of the work is already done (#1311 and #1759) , there are some queries to give it a smooth finishing touch.

1. **Using configure option `OMR_VALGRIND_MEMCHECK` (currently) or use valgrind request `RUNNING_ON_VALGRIND`** : This allows us to skip an extra step for developers and users - recompile OMR for valgrind. However, this may increase a few branch conditions and will require valgrind installed or at least its headers while compiling OMR.

2. **Using STL container set:** Though all tests run fine, but @youngar couldn't compile it with internal java build because we aren't linking with Standard C++ library. Either we use a alternative or we can try static linking STL. 

3. **Redzones:** These are small empty regions between objects that are supposed to be marked non accessible. These help in detecting if data inside object is leaking to just next object. Note: valgrind already throws errors if objects overlap during their allocation using API which is different from this (Eg: `Mempool chunk 7 / 4633 overlaps with its successor`) 
In `AllocationInitialization.hpp`,  this can be done by

```
int originalSize = objectModel->adjustSizeInBytes( _allocateDescription.getBytesRequested());
_allocateDescription.setBytesRequested(redzoneSize + originalSize);
-> get heapBytes
-> mark area b/w heapBytes and heapBytes + redzoneSize as nonaccessable
-> heapBytes += redzoneSize
_allocateDescription.setBytesRequested(originalSize);
continue
```
Similar changes will be done in scavenger.

4. **Different ways of freeing valgrind objects:** This has been explained here: https://github.com/eclipse/omr/blob/master/doc/Valgrind%20Memcheck%20API.md#different-ways-of-freeing-objects-in-valgrind. Currently we are keeping a record of allocated objects (in the stl set) while running valgrind. I am not sure about this, but there may be a memory leak in GC (internally only) that can damage / destroy this set affecting valgrind functionality. 

5. **`MM_HeapLinkedFreeHeader` and detecting size of valgrind objects:** Currently everywhere whenever a HeapLinkedFreeHeader is read / written, it is first marked as defined and then later as noaccess. Is this alright? or should it be treated as a object.  While freeing objects, object size isn't needed, but for asserting if they are accessible just being freed (#1759) we need to know their size, following is our current approach, I want to know if it can be improved. And if we mark HeapLinkedFreeHeader as an object, how can it fit in following code.

```
int objSize;
if(MM_ForwardedHeader((omrobjectptr_t) *it).isForwardedPointer())
    objSize = sizeof(MM_ForwardedHeader);
else
    objSize = (int) ((GC_ObjectModel)extensions->objectModel).getConsumedSizeInBytesWithHeader((omrobjectptr_t) *it);
```

**Comment by Varun-garg** [comment]
Sorry to bump this issue, but if there is anything wrong, unclear or this is not needed please let me know. Because of these queries the work in #1759 has been stuck for a while.

**Comment by mgaudet** [comment]
(cc @youngar )
