### ISSUE TITLE
Build Artifacts on OS X Showing up as Untracked Files

### ISSUE THREAD

**Issue by rservant** [eclipse/omr#18]
After building and testing the OMR project with the default glue, there are a large number of untracked files that should likely be added to .gitignore.

Steps to reproduce:
< clone repo to local disk > 
> make -f run_configure.mk SPEC=osx OMRGLUE=./example/glue
> make
> make test
> git status 

git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	VerboseGC_59109_1457627456535.xml.001
	VerboseGC_59109_1457627456535.xml.002
	VerboseGC_59109_1457627456535.xml.003
	VerboseGC_59109_1457627456758.xml
	VerboseGC_59512_1457627886676.xml.001
	VerboseGC_59512_1457627886676.xml.002
	VerboseGC_59512_1457627886676.xml.003
	VerboseGC_59512_1457627886843.xml
	VerboseGC_64521_1457628095035.xml.001
	VerboseGC_64521_1457628095035.xml.002
	VerboseGC_64521_1457628095035.xml.003
	VerboseGC_64521_1457628095225.xml
	config.guess
	config.sub
	libbindthreadagent.dylib.dbg
	libcpuLoadAgent.dylib.dbg
	libinvalidAgentMissingOnLoad.dylib.dbg
	libinvalidAgentMissingOnUnload.dylib.dbg
	libinvalidAgentReturnError.dylib.dbg
	libmemorycategoriesagent.dylib.dbg
	libomrsig.dylib.dbg
	libsampleSubscriber.dylib.dbg
	libsltestlib.dylib.dbg
	libsubscriberAgent.dylib.dbg
	libsubscriberAgentWithJ9thread.dylib.dbg
	libtraceNotStartedAgent.dylib.dbg
	libtraceOptionAgent.dylib.dbg
	libtraceagent.dylib.dbg
	mmapTest1.tst
	mmapTest10.tst
	mmapTest11.tst
	mmapTest13.tst
	mmapTest2.tst
	mmapTest3.tst
	mmapTest4.tst
	mmapTest5.tst
	mmapTest6.tst
	mmapTest7.tst
	mmapTest8.tst
	mmapTest9.tst
	omrfile_test20_child_1_got_lock
	omrfile_test20_child_2_done
	omrfile_test20_file
	omrfile_test22_child_1_got_lock
	omrfile_test22_child_2_done
	omrfile_test22_child_2_trying_for_lock
	omrfile_test22_file
	omrfile_test24_child_1_got_lock
	omrfile_test24_child_2_done
	omrfile_test24_child_2_trying_for_lock
	omrfile_test24_file
	omrfile_test25_child_1_got_lock
	omrfile_test25_child_2_done
	omrfile_test25_child_2_trying_for_lock
	omrfile_test25_file
	omrmmap_test5_child_1_checked_file
	omrmmap_test5_child_1_mapped_file
	omrmmap_test5_child_2_changed_file
	traceLogTest.trc

**Comment by mstoodle** [comment]
Yeah, I noticed those too. Thanks for beating me to raising the issue...I believe they're leftover stuff from running the tests that should either be cleaned up (especially for passing tests) or put in a more out of the way location (and also ignored as you say).

**Comment by alin00** [comment]
config.sub and config.guess are intentionally not gitignored, since we're just waiting for approval to import those into scm.

*.dylib.dbg should have been added to .gitignore.

Yes, everything else is fvtest output.

**Comment by renfeiw** [comment]
I am working on this issue, and will add the following part to the .gitignore file:
	# Test Output
	VerboseGC_*.xml*
	*.dylib.dbg
	mmapTest*.tst
	tfileTest*.tst
	omrfile_test*
	omrmmap_test*
	traceLogTest.trc

As for cleaning up test output when test passes, the solution can be writing clean up in omrtest.mk or in the tear down part of test case.

**Comment by mstoodle** [comment]
When I ran make test on my macbook with your fix, I see the following 4 files (which, granted, weren't in Ron's original list):
subscriberAgentTrace1.out
subscriberAgentTrace2.out
subscriberAgentWithJ9threadTrace1.out
subscriberAgentWithJ9threadTrace2.out

Can those also be removed on successful run?

**Comment by renfeiw** [comment]
Sure I am working on it.
