### ISSUE TITLE
ThreadExtendedTest.TestThreadCpuTime times out on Travis-CI

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#181]
This test will periodically overrun the ten minute timeout with no output on Travis CI.

```
[ RUN      ] ThreadExtendedTest.TestThreadCpuTime
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

https://travis-ci.org/eclipse/omr/jobs/151842717

**Comment by mgaudet** [comment]
Is this still true? I just followed that link and noticed that it seems to have passed now... automatically restarted? 

Though, having said that, the test did take 9 minutes even on that run, which seems... long.

**Comment by mgaudet** [comment]
Definitely still happening: Pull Request #286 log:  https://s3.amazonaws.com/archive.travis-ci.org/jobs/163497414/log.txt

**Comment by mgaudet** [comment]
Is the problem here that the test is designed to run for 10 minutes? Or just a side effect of the load on the build machines it takes 10 minutes? Can we reduce input by some factor to get similar coverage?

**Comment by rwy0717** [comment]
I believe the test is designed to run for a fixed amount of cpu time.

@charliegracie Are we OK to disable this test until the run time is shortened? GTest will print a big warning until it's reenabled.
