### ISSUE TITLE
Support building OMR with sanitizers

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1829]
Some compiler systems (gcc and clang) support the notion of Runtime Sanitizers. These are builds that are instrumented to flag bugs at runtime. Sanitizers are nice because they typically have a very low false positive rate, and as such, when an issue is flagged, it typically can be relied on. 

Sanitizers include 

- [AddressSanitizer (ASan) ](https://github.com/google/sanitizers/wiki/AddressSanitizer )which flags memory errors
- [UndefinedBehaviorSanitizer (UBSan)](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) which flags undefined behaviour usage
- [ThreadSanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html) flags threading errors such as data races. 

Others also exist.

I've hacked the CMakeLists.txt for OMR to add undefined behaviour sanitizing, and have flagged a couple of issues already: 

- [ ] #1793 
- [ ] #1794 
- [ ] #1797 

It would be useful to have a reliable way to enable this for OMR projects.

**Comment by mstoodle** [comment]
Once supported, maybe something we could run periodically, rather than as a regular thing, just to avoid more pressure on our meagre build farm resources. I would prefer to get the cmake work done and settled before we expand too much though.

**Comment by mgaudet** [comment]
Closed by #2008
