### ISSUE TITLE
Compilation fails for forward declaration of class defined in other namespace

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/omr#1832]
``` 
/**
 * Backwards compatible alias.
 */
typedef OMR::GC::Forge MM_Forge;
```

^^^ this is not always a backwards compatible alias. This produces an error as below:

```
In file included from ./EvacuatorController.hpp:67,
                 from standard/Scavenger.hpp:37,
                 from Configuration.hpp:37,
                 from Configuration.cpp:31:
./Evacuator.hpp:44: error: using typedef-name 'MM_Forge' after 'class'
Forge.hpp:147: error: 'MM_Forge' has a previous declaration here
```

Offending line in EvacuatorController.hpp was:

```
class MM_Forge;
```

With gcc (GCC) 4.4.6 20120305 on rhel6x64compvm10. I worked around this by deleting the forward declaration -- it was then picked up from an included header file.

**Comment by mgaudet** [comment]
Namespaced forward declarations need to be done like this: 

```
namespace OMR { namespace GC { namespace Forge { class MM_Forge; } } } 
```

In older compilers :)

**Comment by rwy0717** [comment]
Right, we can't forward declare `MM_Forge` anymore. Sorry I missed that one!

**Comment by ktbriggs** [comment]
Point is this sort of error should never be reported, or it should be obvious from reading omr/README.md what the solution is (upgrade compiler). Problem is that we don't (haven't yet) published in omr/README.md what level of C/C++ standard is required of compiler, and maybe what versions of compiler per paltform are minimally required to build OMR.

Maybe a better title for this issue would be "Minimal C/C++ standard level and per platform compiler versions need to be published in omr/README.md", but that would be too long. 

We also need to publish recipes for building omr with or without tests for different configurations in omr:

release-clean (full build)
release-incremental (incremental build, please, please)
debug-clean (full build, with no optimizations and debug symbols included)
debug-incremental (incremental build, no optimizations, debug symbols, continued pleading)

**Comment by rwy0717** [comment]
No, it's not actually an issue with compiler versions. Now that `MM_Forge` is a typedef, it cannot be declared as a class. MM_Forge is a temporary measure, expect it to go away. The solution is to include the forge header, or use the new name: `OMR::GC::Forge`.

(When I wrote "backwards compatible", I meant "compatibility with older versions of OMR")

**Comment by charliegracie** [comment]
@ktbriggs is this resolved?
