### ISSUE TITLE
Avoid passing both CodeGenerator and Compilation objects in an API

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1855]
For a particular compile, there is only one Compilation and CodeGenerator object created.  Both are cross-referencing, so it is redundant to pass them both into an API as it clutters the API.

The work here is to sweep through the compiler technology, identify APIs where both parameters are passed, choose only one to pass, and modify the API and its uses.  The decision of which to use I think should be driven by the context.  For example, if the API exists or is exclusively used as part of the code generation process then pass the CodeGenerator object.

Examples of APIs affected (not an exhaustive list):

```
compiler/codegen/OMRCodeGenerator.hpp:   void incRefCountForOpaquePseudoRegister(TR::Node * node, TR::CodeGenerator * cg, TR::Compilation * comp)
compiler/z/codegen/OMRCodeGenerator.hpp:   TR_S390Peephole(TR::Compilation* comp, TR::CodeGenerator *cg);
```

Be aware that there may be downstream projects that depend on these APIs so staging this work to allow those projects to transition seamlessly might be in order (I realize this is a vague, perhaps unhelpful, statement).

**Comment by wbh123456** [comment]
Searched every function calls that pass `TR::CodeGenerator * cg` as a parameter. The following list are all the functions that pass `TR::Node * node`  and `TR::CodeGenerator * cg` at the same time:

- `void incRefCountForOpaquePseudoRegister`
- `TR_S390Peephole`
- `TR_S390PreRAPeephole`
- `TR_S390PostRAPeephole`

**Comment by wbh123456** [comment]
Both  parameters `cg` and `comp` can be removed from the function `void incRefCountForOpaquePseudoRegister` . Going to  simplify this function in 6 PR:

1.  Overload the function with less parameters in OMR
2.  Overload the function with less parameters in OpenJ9
3.  Fix the function calls in OpenJ9 (Should call the new function created above is instead)
4.  Fix the function calls in OMR
5.  Delete the old function in OpenJ9
6.  Delete the old function in OMR

Note: the order of step 3 and 4 does not matter
