### ISSUE TITLE
Remove dead ENABLE_STRUCTS code

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#1856]
This ENABLE_STRUCTS code was part of a now removed experiment, and can in turn be removed 

https://github.com/eclipse/omr/blob/470bcf78c72a72a2d71fef6f314ad28f3f338e13/compiler/optimizer/OMRSimplifierHandlers.cpp#L5588-L5593

**Comment by 0xdaryl** [comment]
Just to be clear, this includes the `#ifdef` and all code in between.

**Comment by 0xdaryl** [comment]
Done.
