### ISSUE TITLE
Move supportsNativeLongOperations to OMRCPUEnv

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1864]
Move the CodeGenerator query `supportsNativeLongOperations` to env/OMRCPUEnv.cpp.

I suggest the API in OMRCPUEnv class look like this:
```
bool supportsNativeLongOperations(TR::Compilation *comp)
   {
   return (self()->is64Bit() || self()->use64BitRegsOn32Bit(comp));
   }
```
The latter part of the query depends on #1860.  But its best to double check the implementation against the current implementation when this issue is worked on.

CPU architectures can extend this class and provide an overriding method that specializes the function for that architecture.

Fix up all uses of the original function.

Uses of this migrated function would therefore look like:
```
TR::Compiler->target.cpu.supportsNativeLongOperations(comp)
```

**Comment by PeXXeR** [comment]
As per discussion with @0xdaryl -
The API `supportsNativeLongOperations()` is not required.
Its uses can directly be replaced with the definition of the api.
So, there isn't any need of moving to env/OMRCPUEnv.cpp for this particular case.
