### ISSUE TITLE
Move createOrFindClonedNode to OpenJ9

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1867]
The OMR::CodeGenerator function `createOrFindClonedNode` is not used in OMR.  Relocate it to the OpenJ9 project and delete it from OMR.

More generally, this function manipulates a `_uncommmonedNodes` hash table (beware the subtle typo in the name).  After this function moves, this data structure is no longer referenced in OMR and it should be moved into OpenJ9 as well.

**Comment by wbh123456** [comment]
This issue has already been solved in #2068.
