### ISSUE TITLE
Move getMonClass/addMonClass to OpenJ9

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1869]
The OMR::CodeGenerator functions `getMonClass` and `addMonClass` are not used in OMR but have OpenJ9 relevance.  Relocate this functions to the OpenJ9 CodeGenerator class and delete from OMR.

The functions also manipulate an array `_monitorMapping` that is not used elsewhere.  It should be relocated as well.

**Comment by alvee-unb** [comment]
I have done the requested changes and would appreciate the review. Thank you.
