### ISSUE TITLE
Move isRotateAndMask to Power-specific Node class

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1876]
The common `OMR::CodeGenerator` has a function `isRotateAndMask` that is asked on behalf of a `TR::Node`.  This is a Power architecture question and pattern match only, and really should be a asked on the `TR::Node` itself.

Hence, relocate this function to the `OMR::Node` class and provide the Power-specific override in a `p/il/OMRNode.[ch]pp` class.

**Comment by 0xdaryl** [comment]
The description of this issue has changed in case anyone was actively considering it.

**Comment by shivammittal99** [comment]
Should I create the OMRNode.cpp and OMRNode.hpp in p/il/ . And is there any other function to be added to them except isRotateAndMask

**Comment by andrewcraik** [comment]
I am not a fan of codegen specific IL / nodes - the current compiler is complex enough without having to wonder what kind of node you have. The IL is common currency of the optimizer and the codegens and avoiding fragmentation is key to keeping things shareable and understandable. The query is not a property of a single node but is asking a question about a pattern of nodes and for that reason I don't think it should be on node. If we don't want it in the code generator or we want to try and corral pattern  matchers then I would suggest we have a matcher utility class and put it in there. That class should not be Power specific - this concept can apply on other codegens and could apply in the optimizer.
