### ISSUE TITLE
Detect truncated paths

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#189]
GetModuleFileNameW retrieves the fully qualified path for the file that
contains the specified module.

DWORD WINAPI GetModuleFileName(
   \_In\_opt\_ HMODULE hModule,
   \_Out\_    LPTSTR  lpFilename,
   \_In\_     DWORD   nSize
);

If the length of the path exceeds the size that the nSize parameter
specifies, GetModuleFileNameW will succeed and the path is truncated to
nSize characters including the terminating null character.

Checks are needed to properly detect truncated paths.

**Comment by charliegracie** [comment]
Can you please provide more details about the issue?

**Comment by babsingh** [comment]
@charliegracie Added more details, and removed the extra space.

**Comment by youngar** [comment]
Closed via #190
