### ISSUE TITLE
Remove deprecated _compressedRefs CodeGenerator field

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#1896]
The `OMR::CodeGenerator` defines a field `_compressedRefs` that is not used in OMR and has relevance only to OpenJ9.  It should be relocated to `J9::CodeGenerator`.

It doesn't actually appear to do anything useful in OpenJ9, so deleting it outright might be the best option.  However, that is beyond the scope of this OMR issue.

**Comment by charliegracie** [comment]
The idea of compressed references is actually an idea that should be fully supported by OMR and is by all components other than the compiler. I believe this should stay in OMR

**Comment by 0xdaryl** [comment]
This issue isn't about removing compressed refs support from OMR.  It's about removing a field called `_compressedRefs` from the CodeGenerator object pointing to a list of `TR::Nodes`.  This list is only initialized in OMR, and only cleared and pushed to in OpenJ9.  It seems to be leftover remnant of "something" in the past and can be deleted.  Sorry if that wasn't clear.

Rather than sink to OpenJ9, I propose this issue track deleting this field altogether.  Start by deleting the two references to the field in OpenJ9, and then come back to OMR and remove the field and its initialization outright.
