### ISSUE TITLE
There is no OMR IL Opcode for loading unsigned shorts (suload).

### ISSUE THREAD

**Issue by rbanerjee** [eclipse/omr#1902]
`buload`, `luload` and `iuload` all exist but there's no equivalent Opcode for `TR::Int16`. 

See: https://github.com/eclipse/omr/blob/master/compiler/il/ILOpCodeProperties.hpp

Seems rather inconsistent. Curious whether this was a design decision or as @mgaudet  suggests below just an oversight and needs to be implemented eventually?
 
While we are on the topic, what's the reasoning behind `unsigned loads`. As in how do they differ from their signed counterparts?

**Comment by mgaudet** [comment]
I suspect there's an oversight in the missing if `suload`, but @andrewcraik and @vijaysun-omr ... what's the deal with unsigned loads?

**Comment by charliegracie** [comment]
Can the title and description have more details added.  For anyone without significant OMR compiler experience this Issue does not provide many details.

**Comment by rbanerjee** [comment]
Ooop! Sorry about that. Updated the description and title to provide more context.

**Comment by andrewcraik** [comment]
The unsigned loads are all deprecated and should be removed - there is no difference between a signed and an unsigned load. These are vestigial from an older implementation of unsigned ness. The unsigned short version is cload (char load) so the set is complete, but not obvious and not desirable.

**Comment by mgaudet** [comment]
Sweet. @rbanerjee can you open a followup item to remove the unsigned loads (thanks @andrewcraik -- I totally couldn't explain why they would exist!)

**Comment by rbanerjee** [comment]
@andrewcraik  thanks. @mgaudet  done.

Closing this one.
