### ISSUE TITLE
Remove unsigned loads from IL Opcodes

### ISSUE THREAD

**Issue by rbanerjee** [eclipse/omr#1913]
As per the discussion in Issue #1902, the unsigned loads should be removed. 

These are all now deprecated and also there is no functional difference between a signed load and it's unsigned counterpart.

To be more specific this is the list of `unsigned load` Opcodes that are currently part  of  the IL and need to be removed

- [ ] buload 
- [ ] buloadi
- [ ] cload  (the unsigned version of `sload`) 
- [ ] cloadi  (the unsigned version of `sloadi`) 
- [ ] iuload
- [ ] iuloadi 
- [ ] luload
- [ ] luloadi

For each of these one would have to follow the steps outlined below -

- Remove the opcode from the OpCode enum,
- Remove it from the Opcode Properties table.
- Remove from the various RAS data structures
- Remove in the Optimizer
- Remove associated entries from OMRSimplifierTableEnum and the ValuePropagationTable
- Remove the evaluator for X | P | Z | ARM (given that they exist)

**Comment by 0xdaryl** [comment]
To make this easier to digest for someone considering taking on this issue in the future, could you articulate precisely which opcodes should be removed in this issue?

**Comment by rbanerjee** [comment]
Updated the description to provide a brief overview for what needs to be done.

**Comment by andrewcraik** [comment]
I will also need to be removed from the various RAS data structures as well as some careful removals from in the optimizer - there are tables in the Simplifier and Value Propagation that are enum index based as well so they will need to be updated too.

**Comment by rbanerjee** [comment]
@andrewcraik  thanks. Updated the description accordingly.

**Comment by 0xdaryl** [comment]
I just discovered this issue.  Issue #2657 is a superset.  Closing this one.
