### ISSUE TITLE
Need more control over object alignment

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#194]
MM_Configuration sets the initial object alignment in the object model. It is hard coded to use 0x8 as the minimum object alignment at startup. The object model should define the minimum object alignment as well as current alignment.

The constant `J9_GC_OBJECT_ALIGNMENT_IN_BYTES` is not used in OMR. It should be deleted from the example glue.

The allocation APIs should have an alignment parameter for when an allocation requires a coarser alignment than the minimum. Don't make the caller adjust the allocation sizes and starts by hand.

**Comment by ktbriggs** [comment]
@rwy0717 see https://github.com/eclipse/omr/pull/289. J9_GC_OBJECT_ALIGNMENT_IN_BYTES is gone but object alignment is still determined in MM_Configuration and is fixed for all allocations. I believe that introducing variable per allocation alignment would lead to heap fragmentation so I would push back on this.
