### ISSUE TITLE
comptest (VectorTest.cpp) generates an illegal instruction on zlinux_s390x

### ISSUE THREAD

**Issue by rbanerjee** [eclipse/omr#1941]
While downgrading the required compiler version for Tril Based compiler tests (`comptest`)
(https://github.com/eclipse/omr/pull/1900), I encountered the following when trying to run comptest on `zlinux_s390x` `using GCC 4.4.6` : 

```
[==========] Running 3400 tests from 28 test cases.
[----------] 1 test from CommoningDeathTest
[----------] 1 test from CommoningDeathTest (89 ms total)

[----------] 14 tests from ILValidatorDeathTest/IllformedTrees
[----------] 14 tests from ILValidatorDeathTest/IllformedTrees (160 ms total)

[----------] 1 test from VectorTest
Illegal instruction (core dumped)
```

`comptest` seems to at least run when excluding `VectorTest`:

```
fvtest/compilertriltest/comptest --gtest_filter=-VectorTest*

...

[  FAILED  ] ShiftAndRotateTest/UInt8ShiftAndRotate.UsingConst/14, where GetParam() = (('\xFF' (255), 0), ("bushr", 0x803c043c))
[  FAILED  ] ShiftAndRotateTest/UInt8ShiftAndRotate.UsingConst/28, where GetParam() = (('\xD6' (214), 0), ("bushr", 0x803c043c))
[  FAILED  ] ShiftAndRotateTest/UInt8ShiftAndRotate.UsingConst/42, where GetParam() = (('\xFF' (255), 0), ("bushr", 0x803c043c))
[  FAILED  ] ShiftAndRotateTest/UInt8ShiftAndRotate.UsingConst/56, where GetParam() = (('\xFE' (254), 0), ("bushr", 0x803c043c))
[  FAILED  ] ShiftAndRotateTest/UInt16ShiftAndRotate.UsingConst/14, where GetParam() = ((65535, 0), ("sushr", 0x803c044c))
[  FAILED  ] ShiftAndRotateTest/UInt16ShiftAndRotate.UsingConst/28, where GetParam() = ((65494, 0), ("sushr", 0x803c044c))
[  FAILED  ] ShiftAndRotateTest/UInt16ShiftAndRotate.UsingConst/42, where GetParam() = ((65535, 0), ("sushr", 0x803c044c))
[  FAILED  ] ShiftAndRotateTest/UInt16ShiftAndRotate.UsingConst/56, where GetParam() = ((65534, 0), ("sushr", 0x803c044c))

102 FAILED TESTS

```
(I'll either fix or open up issues for the Failed Tests.)

Seems like a case of the particular machine I'm testing on, not having Vector support.
Possibly related to Issue #1843 .

**Comment by mgaudet** [comment]
Definitely #1843 -- Tril needs to figure out that the machine it's running on doesn't have Vector support, and skip the test in that case.

**Comment by dchopra001** [comment]
Quoting @mgaudet  from #2014 "for the short term the calculus was in favour of architecture guarding the test"

And in order to get comptest enabled on Z, I'm going to disable Vector Tests on all Z platforms (easy quick fix). Once we are able to determine at runtime/compile time whether the machine is vector enabled, we can revisit this.

Let me know if there are any concerns with that.

**Comment by rbanerjee** [comment]
@dchopra001  SGTM
