### ISSUE TITLE
Should deprecated unsigned opcodes be supported in tril

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#1948]
While writing some tril tests I learned that unsigned opcodes are deprecated (except perhaps the conversion ones like `iu2l`). Nodes like `iuconst` are currently not supported in tril (the node doesn't set the `isInteger()` property). This issue is opened to ask if they should be supported at all and if there is any other work required in relation to this. 
@Leonardo2718 @NigelYiboYu

**Comment by mgaudet** [comment]
If `iconst` is deprecated, can we get an issue to track its removal, perhaps modelled on https://github.com/eclipse/omr/issues/1913

**Comment by 0xdaryl** [comment]
The answer is no.  Deprecated IL opcodes will be removed via #2657.
