### ISSUE TITLE
Compilation failures in omr/tools when cross compiling

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/omr#1955]
In the context of attempting an OpenJDK/OpenJ9 cross compile for arm 32 bit, the compilation fails in the tools directory. It appears the makefiles are picking up the 32 bit size of the target platform and applying it to the tools which are being compiled for the host. Since the host is 64 bit and not configured for multi-arch this fails with missing include files (note the -m32 in the options)
```
g++  -I.  -DUT_DIRECT_TRACE_REGISTRATION  -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9X86 -c  -MMD -MP -fno-exceptions -fno-rtti -fno-threadsafe-statics -fpic -m32 -msse2 -I/usr/include/nptl -Wall -Wno-non-virtual-dtor -O3 -fno-strict-aliasing -march=pentium4 -mtune=prescott   -o FileReader.o FileReader.cpp
In file included from /usr/include/stdlib.h:24:0,
                 from FileReader.cpp:23:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
```
The makefiles need to differentiate between the target and host architectures.

**Comment by charliegracie** [comment]
The tools can/should be configured to be compiled for the host and not the target.  @youngar can you provide some guidance here?

**Comment by JamesKingdon** [comment]
The work around I used was to add OMR_ENV_DATA64=1 to toolconfigure.mk.in in the conditional section for cross compile. I have no idea if this is the 'correct' solution or not.

**Comment by youngar** [comment]
Hi, i'm seeing what you describe; `OMR_ENV_DATA64` is picked up from the target platform.  We do have separate variables `OMR_TARGET_DATASIZE... 32` and `OMR_BUILD_DATASIZE... 64` to detect the host and target platform.  We need to change how the tools are configured to set `OMR_ENV_DATA64` in toolconfigure.mk.in based on the host. Our build farm doesn't have a problem building the tools with `-m32`, so we never noticed.

**Comment by JamesKingdon** [comment]
Many thanks @youngar, I believe this problem is solved now.
