### ISSUE TITLE
Unable to include `omrgc.h` in C

### ISSUE THREAD

**Issue by pparkkin** [eclipse/omr#1957]
Trying to include `omrgc.h` in C code results in the following error.

```
.../omr/gc/include/omrgc.h:31:1: error: unknown type name ‘class’
 class MM_AllocateInitialization;
```

Compiling with `-Wall -g --std=gnu99`.

```
$ cc --version
cc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```

**Comment by charliegracie** [comment]
@ktbriggs Can you take a look at this please since the change causing this issue was part of a PR you created for ObjectModelDelegate?  Thanks

**Comment by pparkkin** [comment]
Would it be possible to get something like the example (https://github.com/eclipse/omr/blob/master/example/main.cpp) but using C?
