### ISSUE TITLE
 Enable/disable thread local resources on Concurrent Scavenger Cycle  start/end

### ISSUE THREAD

**Issue by amicic** [eclipse/omr#196]
Provide a way to enable/disable thread local resources on Concurrent Scavenger Cycle  start/end. The actual resources dealt with, will be added later.

This will rely on VM access acquire, where Scavenger will register a hook, which will do the actual work.

The hook itself will be provided by language specific code (since VM access code is language specific).

**Comment by charliegracie** [comment]
I believe this was resolved by #197
