### ISSUE TITLE
Unable to include `omrgc.h` in C

### ISSUE THREAD

**Issue by pparkkin** [eclipse/omr#1975]
Trying to include `omrgc.h` in C code results in the following error.

```
.../omr/gc/include/omrgc.h:41:159: error: expected ‘;’, ‘,’ or ‘)’ before ‘=’ token
```

Compiling with `-Wall -g --std=gnu99`.

```
$ cc --version
cc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```

I believe default values for function arguments is a C++ feature and does not exist in C.

**Comment by charliegracie** [comment]
I believe this has been resolved?

**Comment by pparkkin** [comment]
This has been resolved.

Closing.
