### ISSUE TITLE
Missing .gitignore for generated artifacts

### ISSUE THREAD

**Issue by charliegracie** [eclipse/omr#2]
After I build the standalone OMR I ran "git status" and it showed lots of new files.  We missed the .gitignore in the initial commit.

**Comment by alin00** [comment]
config.sub, config.guess, and the eclipse project . files are also missing from the root directory - not sure whether that was intentional?

**Comment by mstoodle** [comment]
config.sub and config.guess are still being reviewed by Eclipse IP team (CQ11036), so we moved forward with the other pieces and will add the config files once they are approved. Eclipse project files is another omission.

**Comment by charliegracie** [comment]
I will investigate the Eclipse project files at a later point
