### ISSUE TITLE
Proposal: A Space Odyssey

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#2001]
...with tongue-in-cheek apologies to Arthur C. Clarke and Stanley Kubrick...

**Comment by mstoodle** [comment]
Last time I treat an Eclipse OMR issue as a joke, promise!

**Comment by 0xdaryl** [comment]
Please fix the spelling of "Odyssey".

**Comment by mstoodle** [comment]
That was intentional <ahem>! But ok...

**Comment by 0xdaryl** [comment]
Alas, the dream has died...
