### ISSUE TITLE
Communicating changes to the Contribution Guidelines

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2010]
What do you think the right way of communicating changes to the project Contribution Guidelines to contributors is?

Unless someone is actively watching all PRs then they may miss the fact that the CG has changed.  In the case of PR #2007 it doesn't really have much of an effect.  But if, for example, the format of the commit message were to change substantially (say #1571), that's something that should be more directly communicated to those who believe they have already read and understood them (perhaps months ago).

Is an update on the omr-dev mailing list that the CG has changed worthwhile?

@mstoodle @charliegracie

**Comment by mstoodle** [comment]
Sounds right to me.

**Comment by 0xdaryl** [comment]
Thanks.  Will do.
