### ISSUE TITLE
Remove and fold fixedPointOverflowExceptionEnabled() from Z CodeGenerator

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2024]
The `OMR::Z::CodeGenerator` has a function `fixedPointOverflowExceptionEnabled` that only ever returns false in OMR and all known downstream projects.  Remove and fold surrounding code assuming it always returns false.

**Comment by 0xdaryl** [comment]
@fjeremic , please confirm this function can be safely removed.  I'll leave this issue marked as a Question until then.  Thanks.

**Comment by fjeremic** [comment]
On IBM Z we have the ability to update the PSW register and request for fixed point overflow signals to be raised on various floating point operations. All current downstream OMR projects do not consume such signals and this code can be safely folded as we do not envision a downstream project making use of this at this time.

**Comment by 0xdaryl** [comment]
Thanks.  Moving to the beginner backlog.
