### ISSUE TITLE
Remove OMR::Compilation::isPinningNeeded and fold code

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2030]
The function`OMR::Compilation::isPinningNeeded()` simply returns true in OMR and all known downstream projects.  Presumably, this is a legacy query.  Can this function be removed and all code guarded by it folded assuming it's true?

@vijaysun-omr @andrewcraik

**Comment by vijaysun-omr** [comment]
Yes I think it's a legacy from one of the compiler products that used to be based on OMR but if it's not used in any of the downstream projects anymore, it can be deleted.

**Comment by 0xdaryl** [comment]
Thanks.  Added to the beginner backlog.
