### ISSUE TITLE
smaller tlhMaximumSize setting can cause GC assert

### ISSUE THREAD

**Issue by zl-wang** [eclipse/omr#2089]
setting tlhMaximumSize to both 100KB and 64KB (smaller than the default 128KB) can lead to GC assertion as follows:
** ASSERTION FAILED ** j9mm.107 at LargeObjectAllocateStats.cpp:1512 Assert_MM_true_internal((false && (sizeClassIndex < _tlhAllocSizeClassStats._maxSizeClasses)))
java: LargeObjectAllocateStats.cpp:1512: MM_LargeObjectAllocateStats::incrementTlhAllocSizeClassStats: Assertion `false && (sizeClassIndex < _tlhAllocSizeClassStats._maxSizeClasses)' failed.

**Comment by LinHu2016** [comment]
both mutators and collectors could use TLH allocation, tlhMaximumSize is set for mutators to change maxumum tlh size and scavengerScanCacheMaximumSize is set for collectors (default = 128KB), currently LargeObjectAllocateStats only use tlhMaximumSize to calculate tlh sizeClass, when tlhMaximumSize is smaller than scavengerScanCacheMaximumSize(more than 20% smaller), it would cause tlh sizeClass overflow.

solution: set max(tlhMaximumSize, scavengerScanCacheMaximumSize) for calculating the tlh sizeClass

**Comment by charliegracie** [comment]
REsolved via #2092
