### ISSUE TITLE
Remove isUnsigned parameter from ParameterSymbol

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2103]
The `OMR::ParameterSymbol` constructor takes a boolean parameter `isUnsigned` that is set in the symbol but never used in OMR nor any known downstream projects.  Remove it and fix up all constructor references.

Note that constructors in downstream projects will have to change as well, so changes to this API will likely have to be staged.

@mstoodle @vijaysun-omr @andrewcraik @ymanton @fjeremic : any objections?

**Comment by ymanton** [comment]
No objections. Maintaining the signedness of parameters here was one of the things discussed in #1901 but if that turns out to be the solution we go with I don't think cleaning this up now will hurt anything.
