### ISSUE TITLE
sigTest.cpp:336: error: format '%I64d' expects type 'int', but argument 8 has type 'int64_t'

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#2139]
c++  -I. -I../util -I../../third_party/gtest-1.8.0 -I../../third_party/gtest-1.8.0/include -I../../fvtest/omrGtestGlue  -DUT_DIRECT_TRACE_REGISTRATION -I../../include_core -I../../nls -DLINUX -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DJ9HAMMER -c  -MMD -MP -fno-exceptions -fno-rtti -fno-threadsafe-statics -fPIC -ggdb -m64 -Wreturn-type -Werror -Wall -Wno-non-virtual-dtor -O3 -fno-strict-aliasing -fexceptions  -o sigTest.o sigTest.cpp
cc1plus: warnings being treated as errors
sigTest.cpp: In function 'omr_error_t test(TestAction)':
sigTest.cpp:336: error: format '%I64d' expects type 'int', but argument 8 has type 'int64_t'

Fails on zLinux RHEL 6.

**Comment by charliegracie** [comment]
I am not sure why this is causing a warning on RHEL 6 since PRId64 is the proper way to print an int64_t.  I will try to find access to a RHEL 6 zLinux machine to see if I can figure out what is wrong.

**Comment by charliegracie** [comment]
Are you sure this is failing? This was an issue months ago and was resolved.  I just successfully compiled the file mentioned above using the exact same command line you provided on a RHEL 6 machine.

What compiler version are you using?

**Comment by charliegracie** [comment]
This issue as indeed resolved in #1716.  I did find another issue on RHEL 6 on all platforms related to abortTest.cpp which I resolved in #2142.  I believe there are currently no compile issues on RHEL 6.
