### ISSUE TITLE
Do not double compute usedef use result

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#2175]
There is a lot of code that looks like this:

```
_useDefInfo->getUseDef(info, load->getUseDefIndex());
if (!info.IsZero())
   {
   ...
   }
```

The `getUseDef` function is defined as follows:
https://github.com/eclipse/omr/blob/78177d1357a00cc175191775635f147d5b76c22b/compiler/optimizer/UseDefInfo.cpp#L2637-L2641

Note the return value of `getUseDef` is identical to what we check in the subsequent `if`. This is wasteful because the `isZero` function has a loop inside which means we are double computing:
https://github.com/eclipse/omr/blob/78177d1357a00cc175191775635f147d5b76c22b/compiler/cs2/bitvectr.h#L1062-L1072

We need to simplify all such code. There are dozens of such references.

**Comment by 0xdaryl** [comment]
I believe this is fixed now.
