### ISSUE TITLE
OS/X JIT support 

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#223]
Today we do not build on OS/X, however, it is a popular platform that we should be targeting, especially since the rest of OMR already supports OS/X.

**Comment by charliegracie** [comment]
@mgaudet do you know how different the ABI is when comparing Linux x86-64 to OSX?

Do you have any gut feeling on the type of work required to bring up OSX?  If there are any easy steps it may be a good opportunity to have someone external to the project work on it.

**Comment by lmaisons** [comment]
Not Matthew, but...

For reference: https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/LowLevelABI/000-Introduction/introduction.html

x86-64 is stated as using the AMD64 System V ABI and Apple provides no information beyond a link to the standard document (version 0.90 from December 2003).  This should be directly compatible with Linux unless something significant happened across different versions (latest obvious version is 0.99.6 from December 2013) *and* Linux / GCC decided to re-target the newer version.  The main problem I would expect to encounter is assumptions in our code that Linux is the only POSIX-like platform of relevance for x86-64, and thus some of our uses of various system services will likely require re-evaluation / refactoring / re-implementation for OS X / FreeBSD.

**Comment by lmaisons** [comment]
At one point FreeBSD user space and OS X were *very* similar.  If that continues to be the case, it may be worth using a FreeBSD build environment as a proxy if Macs are scarce.

**Comment by charliegracie** [comment]
Cool thanks.  We have access to OS X machines on travis so we can always enable it here and get basic testing.  Also I have been thinking ahead and we have some OS X machines in Ottawa :)

**Comment by 0xdaryl** [comment]
@noryb009 will investigate and implement what needs to be done for OMR compiler support on OS X.

**Comment by noryb009** [comment]
#418 provides support for OS X in the JIT.

Be aware that there are likely still bugs in OS X that aren't encountered by the Test compiler and JitBuilder.

**Comment by mgaudet** [comment]
... this has worked for a while now :)
