### ISSUE TITLE
64 bit Power processor recognition on 64 bit builds

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/omr#2232]
Under certain conditions (described below) it is possible for a 64 bit build to think it is running on a 32 bit Power processor. This can cause problems in other parts of the code that assume that a 64 bit build can not run on a 32 bit processor.

The condition is triggered when a 64 bit build is run on a unrecognized Power processor. Unrecognized Power processors are given the internal value of "TR_DefaultPPCProcessor". During the runtime check to see if the processor is 64 bit or not, "TR_DefaultPPCProcessor" is considered 32 bit.

The proposed fix is for 64 bit builds to assume they are running on a 64 bit processor even if it does not recognize the processor beyond it being a Power processor. This is safe because a 64 bit build can not be run on a 32 bit processor to begin with.

Behavior on 32 bit builds will remain unchanged. It will continue to assume that an unrecognized Power processor is 32 bit.

**Comment by 0xdaryl** [comment]
PR is merged.
