### ISSUE TITLE
Consolidate generateRRInstruction and generateRegRegInstruction in z/codegen

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#2243]
I found two routines that look identical inside S390GenerateInstructions.cpp that have identical implementations and seem to serve the same purpose. We should consolidate these.

generateRegRegInstruction:
https://github.com/eclipse/omr/blob/3cda7d85e70ba406301453269cd578f76f68af1e/compiler/z/codegen/S390GenerateInstructions.cpp#L2203-L2211

generateRRInstruction:
https://github.com/eclipse/omr/blob/3cda7d85e70ba406301453269cd578f76f68af1e/compiler/z/codegen/S390GenerateInstructions.cpp#L597-L609

**Comment by shivammittal99** [comment]
Which one of the both should be kept finally?

**Comment by fjeremic** [comment]
> Which one of the both should be kept finally?

We predominantly use `generateRRInstruction`. In general on Z codegen these APIs are defined as `generate<instruction-format>Instruction` where `<instruction-format>` is the various formats defined in _z/Architecture Reference Summary_ [1] section Machine Instruction Formats, page 1.

[1] https://www-304.ibm.com/support/docview.wss?uid=isg29c69415c1e82603c852576700058075a&aid=1
