### ISSUE TITLE
Enable automatic pull request line ending checks

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2255]
In order to ensure consistent line endings across all files in the Eclipse OMR codebase, the line endings can be checked automatically as commits are pushed as part of a pull request.

The Eclipse OpenJ9 project has already done a lot of the work to enable such checks for similar reasons.  This issue is to port and enable the Eclipse OpenJ9 line end tooling to Eclipse OMR.  The Eclipse OpenJ9 pull request enabling this is https://github.com/eclipse/openj9/pull/205, and the issue motivating it is https://github.com/eclipse/openj9/pull/205.

Before this check is enabled live, it should be run against the entire code base and any problems found should be fixed.

**Comment by 0xdaryl** [comment]
@nbhuiyan

**Comment by keithc-ca** [comment]
I think we should also include the whitespace checking added in https://github.com/eclipse-openj9/openj9/pull/13252.
I'll have a look a doing both.
