### ISSUE TITLE
Dynamic allocation for MM_ScavengerHotFieldStats

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/omr#2288]
Class MM_ScavengerHotFieldStats has a size of ~4k but used only if GC_Extensions->scavengerTraceHotFields is set to true (by default it is false and might be set by -Xgc:traceHotFields). Currently class MM_ScavengerHotFieldStats is inlined inside MM_EnvironmentBase (for thread local copy) as well as in MM_GCExtensionsBase (for master copy). So we have ~4k of memory unused by default.
A dynamic allocation for this class on demand only will resolve this problem. A default footprint would be reduced and smaller size of MM_EnvironmentBase (one per each thread) is more cache friendly.
Also code can be cleaned up and simplified: currently inlined MM_ScavengerHotFieldStats exists always so pointer to it can't be NULL. So we need to check GC_Extensions->scavengerTraceHotFields instead.
In case if dynamic allocation of this class the check of boolean would be required for initialization time only and NULL check performed regularly.
There is a code refactoring, no functional change required. The only possible negative impact might be increase of dynamic memory allocations (one per thread + 1) but I think it is acceptable.

**Comment by dmitripivkine** [comment]
@jonoommen Would you please investigate this proposal?

**Comment by jonoommen** [comment]
Yes I will investigate this.
