### ISSUE TITLE
z/OS DLL open/close/query system calls are deprecated

### ISSUE THREAD

**Issue by NigelYiboYu** [eclipse/omr#2294]
It looks like the `dllqueryfn()` system call used in [port/zos390/omrsl.c](https://github.com/eclipse/omr/blob/master/port/zos390/omrsl.c) is deprecated https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.bpxbd00/dllqfn.htm

We can consider using `dlsym()`, supported since zOS V1R6. 

Similarly, `dllLoad()` and `dllfree()` can be relplaced with `dlopen()` and `dlclose()`.

**Comment by AidanHa** [comment]
Will be handling this issue. I also believe that `dlsym()`, `dlopen()`, and `dlclose()` would be the best option in this case.
