### ISSUE TITLE
unnededConv flag overlaps with the simpleDivCheck flag

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#2297]
A bug was recently discovered in openj9 that causes invalid instructions to be generated when, during treeSimplification, an `ldiv` node of two `i2l` children is transformed into an `i2l` of `idiv`. Here's an example from a tracelog showing what happens before and after the transformation is applied:

Before this transformation, the relevant trees look like the following:
```
 n201n     BBStart <block_27> (freq 1338) (extension of previous block)
 n184n     DIVCHK [#26]
 n183n       ldiv (cannotOverflow simpleDivCheck )
 n151n         ==>i2l
 n182n         i2l
 n181n           iload  java/util/stream/AbstractTask.LEAF_TARGET I[#633  final Static] [flags 0x20303 0x0 ] (cannotOverflow )
 n185n     lstore  <auto slot 2>[#634  Auto] [flags 0x4 0x0 ]
 n183n       ==>ldiv
 n190n     iflcmpgt --> block_26 BBStart at n188n ()
 n183n       ==>ldiv
 n187n       lconst 0 (highWordZero X==0 X>=0 X<=0 )
```
After the transformation, they look like below:
```
 n184n     treetop
 n232n       idiv
 n150n         ==>isub
 n181n         iload  java/util/stream/AbstractTask.LEAF_TARGET I[#633  final Static] [flags 0x20303 0x0 ] (cannotOverflow )
 n185n     lstore  <auto slot 2>[#634  Auto] [flags 0x4 0x0 ]
 n183n       i2l (unneededConv cannotOverflow )
 n232n         ==>idiv
 n190n     ificmpgt --> block_26 BBStart at n188n ()
 n232n       ==>idiv
 n187n       iconst 0 (Unsigned X==0 X>=0 X<=0 )
```

The issue is with `n183n`. During the conversion the node is recreated and the flags from the original node are copied into the new node. This is done without complete verification that the flags will be valid for the new node. For example, in the case above, the `unneededConv` and `simpleDivCheck` flag are overloaded. Since we didn't clear this flag during conversion, we end up setting it incorrectly (and unknowingly) for the new node. This leads to invalid instructions being generated during code generation.

**Comment by dchopra001** [comment]
The problem occurs because during the aforementioned transformation, the node is recreated here:
https://github.com/eclipse/omr/blob/08a7345ec6233fa31848d19a35535efc95477fe9/compiler/optimizer/OMRSimplifierHandlers.cpp#L9104-L9119
Following the path of recreation,  we arrive at `OMR::Node::copyValidProperties(TR::Node *fromNode, TR::Node *toNode)` where we copy the flags over:
https://github.com/eclipse/omr/blob/08a7345ec6233fa31848d19a35535efc95477fe9/compiler/il/OMRNode.cpp#L447

Taking a look at `setFlags`, we don't do much validation before copying over:
https://github.com/eclipse/omr/blob/08a7345ec6233fa31848d19a35535efc95477fe9/compiler/il/OMRNode.cpp#L4062-L4072

For now I have submitted a PR that changes the `unneededConv` flag value so that it doesn't overlap with `simpleDivCheck`: https://github.com/eclipse/omr/pull/2296

**Comment by dchopra001** [comment]
For the long run we probably need a broader discussion to determine if/how we should do any form of flag verification before recreating nodes. 

@fjeremic

**Comment by andrewcraik** [comment]
The trade off between compile-time and verification will come into that larger discussion question that you raised @dchopra001. We may need to be more careful about overlapping flag meanings and have some kind of better compile-time infrastructure to make sure flags are orthogonal. The recreate API probably could use some attention to try and make it easier to mirror the overlapping of flags.

**Comment by fjeremic** [comment]
> The trade off between compile-time and verification will come into that larger discussion question that you raised @dchopra001. We may need to be more careful about overlapping flag meanings and have some kind of better compile-time infrastructure to make sure flags are orthogonal. The recreate API probably could use some attention to try and make it easier to mirror the overlapping of flags.

IMO we need to deprecate unused flags to begin with as for example `isDebug` flag is completely unused. There are about ~60 flags currently. We can increase the size of the `_flags` field to be 64-bit and alleviate the problem by not overloading bits, but this solution is not future proof.

In general we cannot at the moment tell which IL type may be recreated to another IL type and which flags are valid between two arbitrary nodes. If we wish to overlap the meaning of some flags we need infrastructure to tell us which flags from IL A are valid on IL B and remove those which are not. Such a facility in my mind would be quite complicated where IL can be arbitrary. We should instead be working towards decoupling node flag values and eliminating flags where possible such that we have one bit per flag in the end.

`OMR::Node` already has so many fields which may or may not be heavily used. Another possibility is to check what can be deprecated to support a large width for the `_flags` field.

**Comment by dchopra001** [comment]
>We should instead be working towards decoupling node flag values and eliminating flags where possible such that we have one bit per flag in the end.

To add on to this, I think some extra documentation in this area would be especially helpful in saving dev time. For example, a commented list of flags that are currently free to use/available would be very helpful and informative. This would be similar to the comments we already have that explain how all the available bits have been allocated:

https://github.com/eclipse/omr/blob/6243e07bd7fd8e20d305a87288f7da1178be6ef7/compiler/il/OMRNode.hpp#L1789-L1795

**Comment by dchopra001** [comment]
Also, we found a flag (arraycopyElementSizeMask) that sets two bits:
https://github.com/eclipse/omr/blob/6243e07bd7fd8e20d305a87288f7da1178be6ef7/compiler/il/OMRNode.hpp#L1885-L1896

At first glance it doesn't seem like the best thing to do. It creates more overlap and uses two bits when we probably only need one. @andrewcraik Are you aware of any particular reason why this was done deliberately? Or should this be part of the cleanup as well?

**Comment by andrewcraik** [comment]
arraycopyElementSizeMask isn't a flag it is a mask used to select flags that tell you the size of an array element. I don't think that wants to be changed.
