### ISSUE TITLE
Linking j9hashtable with gc_base

### ISSUE THREAD

**Issue by Varun-garg** [eclipse/omr#2309]
I want to use `j9hashtable` inside gc (#1759). I tired modifying `gc/base/makefile` with my limited makefile skills

```
MODULE_INCLUDES += ../include ../stats ../structs standard segregated j9hashtable j9pool $(OMRGLUE_INCLUDES)
MODULE_STATIC_LIBS += omrutil j9avl j9hashtable j9pool
```
Everything runs fine when I compile just omr, but when I compile openj9 (for which I need docker image). I get a segmentation error (as mentioned in #2189). I am able to analyze it by locating debug symbols and moving them to the `compressedrefs` directory. So the crash is: 
```(0x000014A84915CE7E [libj9gc29.so+0x118e7e]) pool_newElement + 697 in section .text 
(0x000014A84915950A [libj9gc29.so+0x11550a]) hashTableAddNodeInList + 246 in section 
(0x000014A849159361 [libj9gc29.so+0x115361]) hashTableAdd + 320 in section .text 
(0x000014A84919D852 [libj9gc29.so+0x159852]) valgrindMempoolAlloc(MM_GCExtensionsBase*, unsigned long, unsigned long) + 170 in section 
(0x000014A84921FAD9 [libj9gc29.so+0x1dbad9]) MM_Scavenger::incrementalScanCacheBySlot(MM_EnvironmentStandard*) + 15439 
(0x000014A849222986 [libj9gc29.so+0x1de986]) MM_Scavenger::completeScan(MM_EnvironmentStandard*) 
(0x000014A849222DA2 [libj9gc29.so+0x1deda2]) MM_Scavenger::workThreadGarbageCollect(MM_EnvironmentStandard*) 
(0x000014A84929C671 [libj9gc29.so+0x258671]) MM_ParallelScavengeTask::run(MM_EnvironmentBase*) 
(0x000014A84918F811 [libj9gc29.so+0x14b811]) MM_ParallelDispatcher::slaveEntryPoint(MM_EnvironmentBase*) 
(0x000014A84918F5F8 [libj9gc29.so+0x14b5f8]) dispatcher_thread_proc2(OMRPortLibrary*, void*)
(0x000014A84B2740F9 [libj9prt29.so+0x1f0f9])
(0x000014A84918F708 [libj9gc29.so+0x14b708]) dispatcher_thread_proc
(0x000014A84BDEA269 [libj9thr29.so+0x6269])
(0x000014A850D916BA [libpthread.so.0+0x76ba])
```

Code in `pool_newElement(J9Pool *pool)` is a bit difficult. I am just wondering if it calls back gc and causes a dependency loop.

Anyway, in case using `j9hashtabe` is not possile, how can I statically link `gc/base` with `libstdc++`. If it works I will create a new module in gc/base and link that module only with `libstdc++`.

**Comment by mstoodle** [comment]
1) I do not believe J9Pool calls back into GC, but I'll confess it's not a strong area for me.
2) I believe the GC component has traditionally avoided libstdc++ so I would try to stay the course with `j9hashtable`

However, you should probably wait to hear from @charliegracie for a definitive GC answer/direction here.

**Comment by charliegracie** [comment]
Hi @Varun-garg sorry I missed this issue being opened while I was away.

You should definitely be able to use the J9HashTable (at some point this needs to be changed to OMRHashTable) structure in the GC.  Do you know if it fails on the very first hashtableAdd or if it succeeds for a while and then fails?

I am wondering if your issue right now is that the multiple threads are adding / removing from the J9Hashtable at the same time.  The J9Hashtable data structure is not thread safe so if multiple threads are adding / removing from it at the same time you will need to add an omthread_monitor and use it to ensure that thread safety.

I would suggest doing a quick run with the -Xgcthreads1 option to see if that *resolves* the issue.  If it does that will give some weight to my thread safety comments.

**Comment by Varun-garg** [comment]
@charliegracie and @mstoodle thanks a lot for clearing it out. I am having this crash in building openj9 itself so cannot try `-Xgcthreads1`  yet. But yeah this error appears on all 4 threads during build so it is most-likely what you have pointed out. I also enabled debugging in j9hashtable  to find out that they very first hashtableAdd works fine. There are a lot of hashtable queries executed before it finally crashes. Last line before one of threads crash is `hashTableFree`. I am reading [openj9 build instructions](https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/common/doc/building.md)  and trying out `jobs=1` . If it somehow works I will ensure its thread safety. I can also rename hashtable in #1759

**Comment by charliegracie** [comment]
I would not change the name in your PR as it will cause some fairly big changes throughout downstream projects.  

Ok I believe adding the appropriate locks will resolve your issue.  If the locking slows things down too much you may want to keep some thread local data and then at merge points merge the data together.

**Comment by Varun-garg** [comment]
Thanks @charliegracie, using `MUTEX` macros (f1273216b43af75d3bc3b90ad8fdd1270e12c39b) has neatly solved the problem.
