### ISSUE TITLE
Support method limiting in Test Compiler

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#231]
A fairly standard debugging technique in the JIT is to limit one's investigations down to a particular method; ie, if we can reproduce with `-Xjit:limit={Foo.bar*}` our lives are made greatly easier.

Unfortunately, the structure of the test compiler opcode tests means that we are unable to limit the test surface area effectively. While `--gtest_filter` exists, the groupings available to us lack sufficient granularity to be useful to us.

Furthermore, something like this:

```
TR_Options='traceFull,log=0log,limit={*OpCodesTest.cpp:675:lCmpneConst2_TestCase2*}' ./testjit '--gtest_filter=JITCrossPlatformsOpCodesTest.CompareTest'
```

Will fail, because of the shape of the code under test:

```
  sprintf(resolvedMethodName, "lCmpneConst2_TestCase%d", i + 1);
  lCompareConst = (signatureCharJJ_I_testMethodType *) (compileOpCodeMethod(
        _numberOfBinaryArgs, TR::lcmpne, resolvedMethodName, _argTypesBinaryLong, TR::Int32, rc, 2, 1, &(lCmpneDataArr[i][0])));
  EXPECT_EQ(compareNE(lCmpneDataArr[i][0], lCmpneDataArr[i][1]), lCompareConst(LONG_PLACEHOLDER_1, lCmpneDataArr[i][1]));
```

If we use `limit`, these tests will simply abort, because we will effectively invoke NULL (the return of the compile method if limit disallows compilation).

I'd suggest, we should really change the structure of these tests to improve debuggability to look more like this:

```
      sprintf(resolvedMethodName, "lCmpneConst2_TestCase%d", i + 1);
      rc = 0
      lCompareConst = (signatureCharJJ_I_testMethodType *) (compileOpCodeMethod(
            _numberOfBinaryArgs, TR::lcmpne, resolvedMethodName, _argTypesBinaryLong, TR::Int32, rc, 2, 1, &(lCmpneDataArr[i][0])));
      if (lCompareConst) {
            EXPECT_EQ(compareNE(lCmpneDataArr[i][0], lCmpneDataArr[i][1]), lCompareConst(LONG_PLACEHOLDER_1, lCmpneDataArr[i][1]));
      } else {
            EXPECT_EQ(rc, 0 ) 
      }
```

This would allow us to log and compile only a single opcode case. Ultimately we need  to differentiate the following two reasons for which the return address of the compile method is NULL:
1. User specifying compiler not to compile the method,
2. An error has occurred during the compile in, which case we want the test the signal the failure.

The compile method returns a return code that can hopefully be used to tell the above scenarios apart. @xliang6 looked at when options processing is done and how the return code is set during the compile. Her suggestion is that we could  set `rc = 0` before calling `compileOpCodeMethod` and if a real error happens, `rc` will be returned as non-zero; and if the method is not compiled due to options set by the user, the returned value should remain as zero.

We can check whether rc is still zero after the call, and if it is, skip the `EXPECT` statement if the returned address is `NULL`.

This works fine for the constant tests, however, it's not clear if this all works for the Variable tests, as current structure is we have separate `compile*TestMethods()` and `invoke*Tests()`.

**Comment by xliang6** [comment]
What was proposed should work even if the compile and invoke steps are separated. We can check the return code right after the compile step and flag a failure if it wasn't 0; then we can safely check for non-NULL start PC before invoking.

**Comment by xliang6** [comment]
I have a pending fix for this issue. Please ping me if you have any questions regarding this issue.

**Comment by xliang6** [comment]
Work is tracked by this PR:
https://github.com/eclipse/omr/pull/375

**Comment by mgaudet** [comment]
This is working now :)
