### ISSUE TITLE
Improving/Extending OMR Signal API

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#2332]
The objective is to improve and extend the existing OMR Signal API so that signal support can be added to OpenJ9.

**Current OMR signal API implementation**: `omrsig_set_async_signal_handler`. In OMR, a list of `J9*AsyncHandlerRecord` a.k.a `asyncHandlerList` is maintained.

```
-- omrsig_set_async_signal_handler(...,  omrsig_handler_fn handler, void *handler_arg, uint32_t flags)
---- registerMasterHandlers
------ registerSignalHandlerWithOS //call to sigaction
```

```
typedef struct J9*AsyncHandlerRecord {
	OMRPortLibrary *portLib;
	omrsig_handler_fn handler;
	void *handler_arg;
	uint32_t flags;
	struct J9*AsyncHandlerRecord *next;
} J9*AsyncHandlerRecord;
```

Whenever `omrsig_set_async_signal_handler` is invoked, we look for a record associated to the specified handler (`omrsig_handler_fn`) in `asyncHandlerList`.

If a `J9*AsyncHandlerRecord` exists in `asyncHandlerList`, we update `flags` to associate the record with a signal. If no record exists, then we add a new record for the handler in `asyncHandlerList` and set `flags` appropriately. Multiple `J9*AsyncHandlerRecord`s can be associated with a signal. On Unix, we register handlers with the OS using `sigaction`. On Windows, we don't register signals with the OS using `signal`; it is assumed signals will only be sent using `Ctrl + ...` so `SetConsoleCtrlHandler` is used to set an handler (`consoleCtrlHandler`).

When an async signal is received, `masterASynchSignalHandler` is invoked by the signal on Linux/Unix platfroms. This function increments signal counts and wakes up the `asynchSignalReporter` thread. `asynchSignalReporter` thread decrements the signal count, finds all records in `asyncHandlerList` for the raised signal and invokes the `handler` in each record.

On Windows, handlers are not registered with the OS, and there is no thread to invoke handlers. The OS invokes `consoleCtrlHandler` which was set using `SetConsoleCtrlHandler`. `consoleCtrlHandler` finds all records in asyncHandlerList for the raised signal and invokes the handler in each record.

**What needs to be done in OMR?**

1) Currently, only four signals are supported on Unix/Linux platforms: `SIGXFSZ`, `SIGQUIT`, `SIGABRT` and `SIGTERM`. We would need to extend support to all Posix signals. AIX and zOS may have some system-specific signals, which would require support.

2) On Windows, we need to support the following three signals: SIGINT, SIGTERM and SIGABRT. Currently, we don't register handlers with the OS using the `signal` system call so system calls such as `raise` and `sun.misc.Signal.raise` won't work. We would have add a new thread to process raised signals; similar to Linux. Currently, only `Ctrl + BREAK | C | CLOSE` events will be processed on Windows. Also, we would need a mechanism to keep track of signal counts.

3) Each bit in `J9*AsyncHandlerRecord->flags` represents a signal. 32 bits can only represent 32 signals. On some platforms, there are more than 32 signals. If we use `uint64_t` to represent flags, then we will be able to represent 64 signals. There will be an issue if there are more than 64 signals on a system. `NSIG` macro is available in `<signal.h>` on all platforms except zOS. `NSIG` tells us how many signals are there on a system. This can be used to create an array version of flags. Related issue: https://github.com/eclipse/omr/issues/3713.

4) New functions (API) will be required.

5) There are four implementations of `omrsig_set_async_signal_handler`: `unix`, `win32`, `win64amd` and `ztpf`. For any new API, four variants would need to be added to support each platform specification.

6) OMR signal API is part of the port library so it can't access internal macros in the thread library. For implementing the Windows thread in `omrsignal.c`, we won't have access to the synchronization macros in the thread library for using a semaphore, mutex etc. So, we would have to write those macros from scratch.

7) ... More changes will be required as we implement the above barebone specification ...

**New API details:**

1. `omrsig_set_single_async_signal_handler`: It will be similar to `omrsig_set_async_signal_handler`. Instead of associating multiple `J9*AsyncHandlerRecord`s with a signal, it will only associate one `J9*AsyncHandlerRecord` with a signal while registering the `masterASynchSignalHandler` with the OS. Previously associated `J9*AsyncHandlerRecord`s will be disassociated. `J9*AsyncHandlerRecord`s not associated to any signal will be removed from `asyncHandlerList`. In most cases, `omrsig_set_single_async_signal_handler` will only be called once to register a signal. It's very likely that `masterASynchSignalHandler` will be called multiple times. So, `asyncHandlerList` mustn't have unnecessary entries since `masterASynchSignalHandler` will loop through the entire list. `omrsig_set_async_signal_handler` returned 0 on success and non-zero on failure. `omrsig_set_single_async_signal_handler` will return the old OS handler associated with the signal on success and NULL on failure.

2. New signals would need to supported on Posix systems.

```
static struct {
	uint32_t portLibSignalNo;
	int unixSignalNo;
} signalMap[] = {
	{OMRPORT_SIG_FLAG_SIGSEGV, SIGSEGV},
	{OMRPORT_SIG_FLAG_SIGBUS, SIGBUS},
	{OMRPORT_SIG_FLAG_SIGILL, SIGILL},
	{OMRPORT_SIG_FLAG_SIGFPE, SIGFPE},
	{OMRPORT_SIG_FLAG_SIGTRAP, SIGTRAP},
	{OMRPORT_SIG_FLAG_SIGQUIT, SIGQUIT},
	{OMRPORT_SIG_FLAG_SIGABRT, SIGABRT},
	{OMRPORT_SIG_FLAG_SIGTERM, SIGTERM},
	{OMRPORT_SIG_FLAG_SIGXFSZ, SIGXFSZ},
	{OMRPORT_SIG_FLAG_SIGINT, SIGINT},
	{OMRPORT_SIG_FLAG_SIGHUP, SIGBUS},
	{OMRPORT_SIG_FLAG_SIGUSR1, SIGUSR1},
	{OMRPORT_SIG_FLAG_SIGUSR2, SIGUSR2},
	{OMRPORT_SIG_FLAG_SIGPIPE, SIGPIPE},
	{OMRPORT_SIG_FLAG_SIGALRM, SIGALRM},
	{OMRPORT_SIG_FLAG_SIGCHLD, SIGCHLD},
	{OMRPORT_SIG_FLAG_SIGCONT, SIGCONT},
	{OMRPORT_SIG_FLAG_SIGTSTP, SIGTSTP},
	{OMRPORT_SIG_FLAG_SIGTTIN, SIGTTIN},
	{OMRPORT_SIG_FLAG_SIGTTOU, SIGTTOU},
	{OMRPORT_SIG_FLAG_SIGURG, SIGURG},
	{OMRPORT_SIG_FLAG_SIGXCPU, SIGXCPU},
	{OMRPORT_SIG_FLAG_SIGVTALRM, SIGVTALRM},
	{OMRPORT_SIG_FLAG_SIGPROF, SIGPROF},
	{OMRPORT_SIG_FLAG_SIGWINCH, SIGWINCH},
	{OMRPORT_SIG_FLAG_SIGIO, SIGIO},
	{OMRPORT_SIG_FLAG_SIGSYS, SIGSYS}
#if defined(AIXPPC)
	, {OMRPORT_SIG_FLAG_SIGRECONFIG, SIGRECONFIG}
#endif
#if defined(J9ZOS390)
	, {OMRPORT_SIG_FLAG_SIGABEND, SIGABND}
#endif
};
```

3. `omr_map_unix_signal_to_portlib` and `omr_map_portlib_signal_to_unix`: the relationship in the above `signalMap` would need to be exposed. `J9*AsyncHandlerRecord->handler` has the following prototype `typedef uintptr_t (*omrsig_handler_fn)(struct OMRPortLibrary *portLib, uint32_t gpType, void *gpInfo, void *handler_arg)`. `gpType` is a `portLibSignalNo`. To merge with external projects, `unixSignalNo` is required. To use `omrsig_set_async_signal_handler`, `portLibSignalNo` is required. Functions to map `portLibSignalNo` to `unixSignalNo` and vice-versa are required.

4. `asynchSignalReporter`, `masterASynchSignalHandler`, `initializeSignalTools`, `registerMasterHandlers` and `registerSignalHandlerWithOS` would need to be updated to account for the new signals.

5. User gets to attach or detach to the `asynchSignalReporterThread` from within `J9*AsyncHandlerRecord->handler`. Everytime a `J9*AsyncHandlerRecord->handler` is run; attach and detach code will be run. Need a way to attach once at startup and detach once at shutdown.

6. `asynchSignalReporterThread` always runs. Users must have the option to `enable` or `disable` this thread.

The above details are just for `unix`. For `win32` and `win64amd`, **more changes will be required in addition to the above the changes:** 

1. Add `signalMap` definition.

2. Add macros for using semaphore or use `j9sem_t`.

3. Add a new thread similar to `asynchSignalReporterThread`. Add supporting functions: `asynchSignalReporter`, `masterASynchSignalHandler`, `initializeSignalTools`, `registerMasterHandlers` and `registerSignalHandlerWithOS`.

Ignore `ztpf` implementation. `ztpf` team will port on their own. Without `ztpf` implementation, the OpenJ9 signal implementation can't be used internally in Java 8.

**Estimated Timeline:**

1. `unix`: 2-3 weeks
2. `win32`: 3-5 weeks
3. `win64amd`: 1-2 weeks
4. `ztpf`: ignored
5. `openj9 linkage`: 1-2 weeks
6. `testing and debugging`: 1-2 weeks
7. `code reviews`: 1-2 weeks

Total: **9-16 weeks**

**Comment by babsingh** [comment]
@charliegracie @DanHeidinga @pshipton - fyi

**Comment by babsingh** [comment]
@charliegracie can you give feedback for the above proposal?

**Comment by babsingh** [comment]
Reminder: @charliegracie can you give feedback for the above proposal?

**Comment by charliegracie** [comment]
We had an offline conversation about this.  Can you capture the results in the Issue please?

**Comment by babsingh** [comment]
@charliegracie @DanHeidinga @pshipton updated the issue description above.
1. Added in-depth detail about the new API and back-end changes.
2. Added an estimated timeline.

**Comment by babsingh** [comment]
@charliegracie Please let us know if you approve the above proposal.

**Comment by pshipton** [comment]
> New signals would need to supported on Posix systems.

The list of signals contains signals which are not asynchronous. Only asynchronous signals are supported by the async_signal_handler.

Can you explain in more detail `5. User gets to attach or detach to the asynchSignalReporterThread`.

**Comment by pshipton** [comment]
> `6. asynchSignalReporterThread always runs.`

Can this be automatic? The thread isn't started unless a signal handler is registered?

> Users must have the option to enable or disable this thread.

What is the motivation for this?

**Comment by DanHeidinga** [comment]
> omr_map_unix_signal_to_portlib and omr_map_portlib_signal_to_unix: the relationship in the above signalMap would need to be exposed.

How is this handled in the existing code?  Doesn't some kind of mapping already exist, if only to handle the current set of signals?

**Comment by DanHeidinga** [comment]
> New functions (API) will be required.

Can you provide prototypes and descriptions for the new apis?

**Comment by babsingh** [comment]
@pshipton 

>> New signals would need to supported on Posix systems.

> The list of signals contains signals which are not asynchronous. Only asynchronous signals are supported by the async_signal_handler.

`signalMap` includes all the signals. Masks are available to distinguish between synchronous and asynchronous signals.

```
#define OMRPORT_SIG_FLAG_SIGALLASYNC  ...
#define OMRPORT_SIG_FLAG_SIGALLSYNC ...
```

> Can you explain in more detail 5. User gets to attach or detach to the asynchSignalReporterThread.

In OpenJ9, OMR (`asynchSignalReporterThread`) thread needs to execute `AttachCurrentThread` (attach to `J9VMThread`) in order to execute Java code. Currently, this is done from within `J9*AsyncHandlerRecord->handler`. Example - `jvminit.c::shutdownHookWrapper`.
`AttachCurrentThread` needs to be followed with `DetachCurrentThread`. Instead of executing `AttachCurrentThread`/`DetachCurrentThread` everytime within `J9*AsyncHandlerRecord->handler`, we would need a way to execute `Attach*` at JVM's startup and `Detach*` at JVM's shutdown. `asynchSignalReporterThread` (OMR thread) isn't exposed outside `omrsignal.c` (static).

>> 6. asynchSignalReporterThread always runs.

> Can this be automatic? The thread isn't started unless a signal handler is registered?

Yes. Starting the thread when the first signal is registered should work. Currently, OMR startup terminates if the thread fails to start. If thread fails to start while registering the first signal, terminating the process will be difficult.

>> Users must have the option to enable or disable this thread.

> What is the motivation for this?

If no one is using the `async_signal_handler` API, then the thread will just wait without performing any work. In this case, unnecessary startup cost is encountered, and footprint is wasted. If the thread is disabled when no one is using the API, then footprint can be reduced. Not needed for the current task - a possible optimization.

@DanHeidinga 

>> omr_map_unix_signal_to_portlib and omr_map_portlib_signal_to_unix: the relationship in the above signalMap would need to be exposed.

> How is this handled in the existing code? Doesn't some kind of mapping already exist, if only to handle the current set of signals?

There are functions to map from portlib to unix signals and vice-versa: `mapUnixSignalToPortLib` and `mapPortLibSignalToUnix`. These functions are not exposed outside OMR. Current API (`omrsig_set_async_signal_handler`) takes a `portlib` signal as input. To be consistent, the new API should take `portlib` signal as input. For this, a function to convert from `unix` signal to `portlib` signal is required in OpenJ9.

The new API can also take a `unix` signal as input, and then do the conversion to `portlib` signal from within the new OMR function. There will be inconsistency between the new and existing API but no new API to map signals will be required. 

>> New functions (API) will be required.

> Can you provide prototypes and descriptions for the new apis?

API description is provided in the `New API details` section above. Prototypes are provided below:
```
/*
 * @brief Similar to omrsig_set_single_async_signal_handler. But, only one handler is registered with a signal. 
 * @param[in] portLibrary The port library
 * @param[in] handler the function to call if an async signal arrives
 * @param[in] handler_arg the argument to handler
 * @param[in] flag portlib or unix signal value
 * @return old OS handler on success or NULL on failure
 */
void *
omrsig_set_single_async_signal_handler(struct OMRPortLibrary *portLibrary,  omrsig_handler_fn handler, void *handler_arg, uint32_t flag);
```
```
/*
 * If all async_signal_handler APIs accept a unix signal as input, then we won't need to add this API.
 * @brief Given a unix signal value, return a portlib signal value.
 * @param[in] portLibrary The port library
 * @param[in] unixSignal unix signal value
 * @return portlib signal value on success and 0 on failure
*/
uint32_t
omr_map_unix_signal_to_portlib(struct OMRPortLibrary *portLibrary, uint32_t unixSignal);
```
```
/*
 * If all async_signal_handler APIs accept a unix signal as input, then we won't need to add this API.
 * @brief Given a portlib signal value, return a unix signal value.
 * @param[in] portLibrary The port library
 * @param[in] portlibSignal portlib signal value
 * @return unix signal value on success and 0 on failure
 */
uint32_t
omr_map_portlib_signal_to_unix(struct OMRPortLibrary *portLibrary, uint32_t unixSignal);
```

**Comment by DanHeidinga** [comment]
> signalMap includes all the signals. Masks are available to distinguish between synchronous and asynchronous signals.

Implicit in Pete's question is **why** signalMap needs to include all signals when the async handler only needs to work with asynchronous signals.

> Instead of executing AttachCurrentThread/DetachCurrentThread everytime within J9*AsyncHandlerRecord->handler, we would need a way to execute Attach* at JVM's startup and Detach* at JVM's shutdown.

What's the rationale for wanting to do this once rather then in the handler?  Overhead?

>  `* @param[in] flag portlib or unix signal value`

Naming this `flag` is ambiguous.  Can you call it `signal` or `signalNumber`?  Maybe there's a better name in the existing APIs that can be reused.

OMR apis shouldn't be named for `unix` signals.  They should be written in terms of platform_signals.  I'm still surprised there's no exposed existing API to convert between platform and portlib signal numbers.

**Comment by babsingh** [comment]
> why signalMap needs to include all signals when the async handler only needs to work with asynchronous signals.

`signalMap` also gets used by `omrsignal.c::omrsig_protect`. `omrsig_protect` registers handlers for synchronous signals.

> What's the rationale for wanting to do AttachCurrentThread/DetachCurrentThread once rather then in the handler? Overhead? 

yes, because of overhead. better performance can be achieved for processing signals if `AttachCurrentThread` and `DetachCurrentThread` are performed once at startup and shutdown respectively.

> Naming this flag is ambiguous. Can you call it signal or signalNumber? Maybe there's a better name in the existing APIs that can be reused. OMR apis shouldn't be named for unix signals. 

I agree -- a more generic naming will be better suited: `osSignalValue`, `portlibSignalValue` etc. Current API, `omrsig_set_async_signal_handler` uses `flags` which will need to be changed.

**Comment by DanHeidinga** [comment]
>> What's the rationale for wanting to do AttachCurrentThread/DetachCurrentThread once rather then in the handler? Overhead?

> yes, because of overhead. better performance can be achieved for processing signals if AttachCurrentThread and DetachCurrentThread is performed once at startup and shutdown respectively.

Signals should be rare.  How much overhead does this introduce?  Does it simplify the design to do this in the handlers for the first pass and look at moving it to occur once if the overhead is too high?

**Comment by babsingh** [comment]
> How much overhead does this introduce? 

I can't quantify the overhead. But, attaching and detaching a thread look like expensive operations.

> Does it simplify the design to do this in the handlers for the first pass and look at moving it to occur once if the overhead is too high?

yes, we can attach and detach the thread in the handlers for the first pass and look at moving it to occur once if the overhead is too high.

**Comment by babsingh** [comment]
Created a pull request to add stubs for the new `omrsig` functions: https://github.com/eclipse/omr/pull/2413

**Comment by ibm-rtvs** [comment]
Just to confirm a use case that isn't working based on our testing:
-When we stop a docker x86_64 container OpenJ9 isn't running shutdown hooks. My understanding that this is because the Ctrl+C signal isn't being handled.
-A detail that you probably don't need to worry about, for legacy reasons we are launching the JVM using the eclipse launcher which in turn uses the JVM Innovation API (rather than running `java`)
-Signal's are passed to the eclipse launcher by using tini or `docker run --init`
-This all works fine in J9
-Sadly until this is fixed we'll probably go with regular OpenJDK.

**Comment by pshipton** [comment]
The change for Linux is #2494 and has been merged today. We should likely discuss in the OpenJ9 issue eclipse/openj9#54, but expect the OpenJ9 support to be merged shortly as well, today or tomorrow.

**Comment by babsingh** [comment]
@ibm-rtvs The initial changes are delivered to enable signal handling on Windows, Linux, and AIX. There will be more internal changes but the functionality should be working as of now.

Linux/AIX eclipse/omr#2494 #1603 #1642
Windows #1816 not the full functionality but enough for CTRL-C to trigger the shutdown hooks

Uber OpenJ9 issue to track OpenJ9 signal handling updates: https://github.com/eclipse/openj9/issues/54.

fyi - @pshipton
