### ISSUE TITLE
Build OMR compiler technology with port library

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2333]
Require the OMR port library to be built when the OMR compiler technology is integrated in a downstream project, the test compiler, or JitBuilder.  This is a pre-requisite to the compiler technology using more port library features.

Ensure the solution is flexible enough to not integrate the OMR port library if a consuming project chooses to provide their own port library.

**Comment by 0xdaryl** [comment]
@nbhuiyan @rwy0717

**Comment by nbhuiyan** [comment]
@0xdaryl I changed the reference to this issue in the commit message from `Closes` to just `Issue` since I wasn't sure which of the 2 PRs would go first. I think this can be closed now.

**Comment by fjeremic** [comment]
Closing due to above comment.
