### ISSUE TITLE
Agenda for March 28, 2018 OMR Compiler Architecture Meeting

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2339]
### Agenda

1.  JitBuilder status [ @mstoodle ]
2.  JitBuilder 2018 directions [ @mstoodle ]

[Meeting Replay](https://www.youtube.com/watch?v=ko_u5ACtu2Y)
[Slides are on slideshare](https://www.slideshare.net/MarkStoodley/jit-builder-status-and-directions-2018-0328)

### Details
Wednesday, March 28, 2018 @ 15:30 EST (GMT -5), 90 minutes maximum

Join WebEx (audio/screen sharing only):  https://ibm.webex.com/ibm/j.php?MTID=m30f5a28b4818d27a1800809872639b54
Meeting number: 929 294 164 
Meeting password: omrrocks!

[Call-in numbers (for audio only)](https://ibm.webex.com/cmp3200/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=650956722&tollFree=1)

**This meeting will be recorded and posted.**

**Comment by mstoodle** [comment]
I could talk for a bit about JitBuilder directions and give status on the language bindings work I've been (slowly) making progress on.

**Comment by mstoodle** [comment]
@0xdaryl you cancelled this meeting on the 14th, are you intending to push this topic forward to the 28th or do you have other plans for that meeting?
