### ISSUE TITLE
OMR's cross configuration capability (and it's downstream uses) is problematic

### ISSUE THREAD

**Issue by ymanton** [eclipse/omr#2414]
Ran into this issue while dealing with #2406. Our autoconf script has an option called `OMR_CROSS_CONFIGURE` which, when enabled, indicates that autoconf is being run on a machine that is not the build machine. In this mode we ignore the `CC` and `CXX` that have been set by the user and instead find whichever compilers are in the `PATH` and proceed to run useless tests on them, like figuring out the platform's pointer size and whether or not we have various headers, and so on. It's these pointless tests and the need for having a default compiler installed and in your path that I was trying to get rid of. Unfortunately, with the recent enabling by default of DDR I noticed that we're using autoconf's header guards (e.g. `HAVE_DWARF_H`) which means we now rely on them, even in an environment where we've been cross-configured and can't actually trust anything autoconf says.

My thinking is that cross-configuration doesn't make any sense, autoconf is intended to be run on the build machine because most of it's functionality is all around figuring out the capabilities of the build environment. Unfortunately there are some downstreams that actually run `configure` on machines that have no relation to the build system.

**Comment by rwy0717** [comment]
You're not wrong. IIRC, the xconfigure hack was written to work around the old ddr generation in j9. Thankfully, all this is going away soon. Until it does, public consumers should not be using xconfigure mode at all.

**Comment by ymanton** [comment]
Fair enough. I saw this 

https://github.com/eclipse/omr/blob/97107f4d8b0d076e8f848d11e9fae8dc521e0b94/cmake/modules/OmrPlatform.cmake#L123

and figured it was worth opening an issue so this hack would hopefully not be resurrected without some discussion. Unfortunately OpenJ9 sets this option everywhere and the IBM SDK actually needs it, which makes it harder to fix the issues I wanted to fix.

**Comment by rwy0717** [comment]
Yep, j9 always sets the cross-configure flag. It lets them disable as much of autotools' functionality as possible, even when not actually cross-configuring. J9 likes to do it's own static configuration.

When J9 begins using our new ddrgen, all three of configure, compile, and ddr-generation can run on the same machine (unless you're cross-compiling ddren). If autotools weren't on our way out, this is when we'd delete the cross-configure flag from our build system.

I think you're right about `HAVE_DWARF_H` in ddrgen, it looks like it breaks cross-configure, and we may have to fix it before cross-configure finally goes away.

I feel confident that we will not be supporting cross-configuration in cmake.

**Comment by rwy0717** [comment]
I'm just doing a bit of housekeeping and closing old build-system issues we're not going to address. @ymanton, since we're not going to be allowing this cross-configure nonsense in cmake, are you OK if we close this issue? This "feature" will go away as soon as the old build system is removed.

**Comment by ymanton** [comment]
No objection, closing.
