### ISSUE TITLE
Implement AArch64 support in port library

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2445]
Implement an AArch64 version of `omrsignal_context.c` in the port library.

**Comment by 0xdaryl** [comment]
@aarongraham9 @jeanlego

**Comment by aarongraham9** [comment]
PR #2520 has been opened for this.

**Comment by aarongraham9** [comment]
This can be closed via #2520.

**Comment by 0xdaryl** [comment]
Done
