### ISSUE TITLE
Create a Slack workspace for Eclipse OMR

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2447]
I'd like to propose that the Eclipse OMR project adopt its own Slack workspace for quick public discussions (similar to what the Eclipse OpenJ9 project has).  At the moment, Eclipse OMR is simply a channel on the public developerWorks Open workspace (dwopen.slack.com) and sees very little traffic.  I propose this dwO Slack channel be deprecated/archived.

With our own workspace we will have more control over content (e.g., creating our own subject channels) and we can better publicize and simplify the access to it to encourage more contributors to join.

I think we still want to encourage deeper discussions to occur in GitHub issues, but for quick bursts of communication relating to Eclipse OMR it can be a low-overhead tool.

**Comment by shivammittal99** [comment]
How about we switch to [gitter.im](https://gitter.im/)?

**Comment by 0xdaryl** [comment]
@shivammittal99: Can you provide a testimonial on your experience with gitter.im and how it's different/better than Slack?  I know a lot of people that work on Eclipse OMR are already Slack users, and while an alternate chat medium is not out of the question, I think the argument will have to be compelling to convince many of them to follow yet another tool.  Thanks.

**Comment by shivammittal99** [comment]
Gitter has better GitHub support.
1. It supports GitHub flavoured Markdown : 
![markdown](https://user-images.githubusercontent.com/25584932/38752744-f27a3786-3f79-11e8-8730-5b32d107a74b.gif)
2. It has support for a lot of integrations like travis, jenkins, GitHub, etc.
![integrations](https://user-images.githubusercontent.com/25584932/38752783-09f4985c-3f7a-11e8-800b-bcb2ed842a86.gif)
3. Direct referencing of issues and PRs
![issues](https://user-images.githubusercontent.com/25584932/38752927-6a91536c-3f7a-11e8-97e2-0d9032e685c1.gif)
4. Easy discoverability
![discovery](https://user-images.githubusercontent.com/25584932/38752941-75904c28-3f7a-11e8-9fa0-0e29d26233ff.gif)

It is also better in terms of joining as it has one account (GitHub/Twitter linked) for all communities/chatrooms. The join link can also be simply added as a badge to README.

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/gitterHQ/desktop?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by mgaudet** [comment]
One thing I'd suggest if slack is the decision: Set up [Shared Channels](https://get.slack.help/hc/en-us/articles/115004151203-Create-shared-channels-on-a-workspace-beta-) between the OMR and OpenJ9 slacks to minimize divergence.

**Comment by Leonardo2718** [comment]
@0xdaryl is there a timeline for this discussion? (i.e. how long before we make a decision?)

**Comment by charliegracie** [comment]
I like the integration of glitter but I also like the ability to have shared channels between OMR and OpenJ9 with slack.  Also there is IRC integration with Slack so if other communities want to "share" a channel it may be easier with Slack.

**Comment by mgaudet** [comment]
(Re: IRC Gateways: [Slack's support for IRC Gateways is ending May 15th](https://mozilla.slack.com/account/gateways), though there are API based solutions for certain clients like IRCCloud)

**Comment by youngar** [comment]
It is sad, but true, that Slack is ending its IRC support.

The Eclipse foundation has a gitter "community", and we could open both OMR and OpenJ9 "rooms" there.  Effectively, that gives us a single channel for each.  I think that to start out, having a single channel works great.  If we find the need for more channels, we can always migrate away from gitter.  Gitter also has and IRC bridge https://irc.gitter.im/.

**Comment by Leonardo2718** [comment]
@0xdaryl,

Given that the eclipse-omr.slack.com slack workspace has been created, can this issue be closed now?

**Comment by 0xdaryl** [comment]
While a resolution wasn't officially reached in this issue, at some point a Slack workspace was created and became the de facto chat medium from popular use.  I will close this issue now for this reason and also because there weren't any negative opinions expressed here to moving to Slack.  However, if anyone wishes to continue this discussion or revisit this issue please open another GitHub issue.
