### ISSUE TITLE
Add OMR artwork to repo

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#246]
Artwork related to OMR should be made part of the repository. A good place for it is a top level directory named `artwork`. Any associated license / usage policy should be put alongside the artwork itself; either as a comment in the source of the work or in a separate README/LICENSE file.

If multiple (substantially large) works are to be contributed, they should be placed in sub-directories of `artwork`. This will help deal with any specific licensing that must be applied.

**Comment by Leonardo2718** [comment]
I believe the only OMR artwork we currently have is the OMR logo. So, putting the svg files for it directly in `artwork` seems reasonable enough.

**Comment by rservant** [comment]
Commit #521 does not add a README on reasonable use of the artwork. I hadn't planned on writing this document myself.

**Comment by charliegracie** [comment]
Closing as the artwork was merged under #521
