### ISSUE TITLE
CMake: omrcore isn't linked with OMR_TRACE_LIB and OMR_CORE_GLUE_TARGET

### ISSUE THREAD

**Issue by samolisov** [eclipse/omr#2481]
If I'm trying to build `fvtests` without `omrgc` (`OMR_FVTEST=ON OMR_GC=OFF`), the following linking problems appear:

```
fvtest\rastest\CMakeFiles\omrtraceoptiontest.dir\traceOptionTest.cpp.obj: undefined symbol: omr_trc_startThreadTrace
error: omrcore.lib(omrtrcinit.c.obj): undefined symbol: omr_trc_startup
error: omrcore.lib(omrtrcinit.c.obj): undefined symbol: omrhook_lib_control
error: omrcore.lib(omrtrcinit.c.obj): undefined symbol: omr_trc_startMultiThreading
error: omrcore.lib(omrtrcinit.c.obj): undefined symbol: omr_trc_shutdown
error: omrcore.lib(omrvmstartup.cpp.obj): undefined symbol: omr_trc_startThreadTrace
error: omrcore.lib(omrvmstartup.cpp.obj): undefined symbol: omr_trc_stopThreadTrace
error: omrcore.lib(omrvmstartup.cpp.obj): undefined symbol: OMR_Glue_GetMethodDictionaryPropertyNames
error: omrcore.lib(omrvmstartup.cpp.obj): undefined symbol: OMR_Glue_GetMethodDictionaryPropertyNumr
error: omrcore.lib(OMR_TI.cpp.obj): undefined symbol: OMR_Glue_BindCurrentThread
error: omrcore.lib(OMR_TI.cpp.obj): undefined symbol: OMR_Glue_UnbindCurrentThread
```
I just removed `omrgc` from `target_link_libraries(omrtraceoptionstest` in the `fvtests/rastest/CMakeLists.txt` file and as far as I see `omrtrace` missing there. Everywhere in other targets `omrtrace` is present along with `omrcore` directly as `omrtrace` or as `OMR_TRACE_LIB` (for GC: 
in the `fvtest/gctest/CMakeLists.txt` and `gc/CMakeLists.txt` files).

If we wish to provide the ability to link `omrcore` with a client-defined `OMR_TRACE_LIB`, should we everywhere in the build system use `OMR_TRACE_LIB` and do not hardcode `omrtrace` into the `CMakeLists.txt` files? Does it depend on which library we wish to test: provided by OMR itself or a glue one? Currently some tests are linked with hardcoded libraries (`rastest`) while other are linked with specified in the `OMR_XXX_LIB` variable, for example `algotest` or `threadtest`).

The same thing is actual for the `OMR_HOOK_LIB` library.

---

The second thing is the following: `omrcore` is linked with the `OMR_CORE_GLUE_TARGET` library if only `OMR_GC` is enabled but `OMR_CORE_GLUE_TARGET` (by default - "omr_example_core_glue", defined in the `example/glue/CMakeLists.txt`) contains required symbols.

```cmake
if(OMR_GC)
	add_dependencies(omrcore
		omrgc_tracegen
		omrgc_hookgen
	)

	target_link_libraries(omrcore
		PRIVATE
			${OMR_CORE_GLUE_TARGET}
	)

	target_include_directories(omrcore
		PRIVATE
			$<TARGET_PROPERTY:omrgc,INTERFACE_INCLUDE_DIRECTORIES>
			$<TARGET_PROPERTY:${OMR_GC_GLUE_TARGET},INTERFACE_INCLUDE_DIRECTORIES>
	)
endif(OMR_GC)
```
I think `omrcore` should be linked with `${OMR_CORE_GLUE_TARGET}` regardless of the value of the `OMR_GC` flag.

P.S. `fvtests/rastest` can't be built without `omrgc` because the `example/glue/Profiling.c` compilation unit is put to the `omr_example_gc_glue` target not to the `omr_example_core_glue` one while `fvtests/rastest omrtraceoptiontest` depends on symbols from the compilation unit (`OMR_Glue_GetMethodDictionaryPropertyNames` and `OMR_Glue_GetMethodDictionaryPropertyNum`). Can we move `Profiling.c` to the `omr_example_core_glue` target? I've checked on my Windows machine and see no problem (and no GC dependencies are found in the file).

**Comment by samolisov** [comment]
Unfortunately, there is a high coupling between `omrcore` and `omrgc`. If `OMR_GC` is enabled, `omrcore` use defined in `GC` methods, see the `omr/startup/omrvmstartup.cpp` compilation unit. Unless `omrcore` and `omrgc` are decoupled, fvtests, at least the `rastest` test, must be linked with `omrgc` if the latest one is present.

**Comment by samolisov** [comment]
@rwy0717 Thank you for the comments. I've fixed CMakeLists.txt in that way you are talking about and wish to open a PR after your #2479 one will be merged.

**Comment by rwy0717** [comment]
Yeah if you want to open a PR, that would be awesome!

For `omrcore` to link against `${OMR_HOOK_LIB}` and `${OMR_THREAD_LIB}`, that sounds reasonable to me too.

**Comment by rwy0717** [comment]
I've moved my cmake changes from #2479 to a standalone PR, #2479.
