### ISSUE TITLE
Remove PseudoRealRegisters from RealRegisterEnum.hpp

### ISSUE THREAD

**Issue by dchopra001** [eclipse/omr#2491]
Inside the z/codegen's RealRegisterEnum.hpp, we have some dependencies/PseudoRealRegisters (not sure which one is the officially accepted name here) defined inside RealRegisterEnum.hpp:
https://github.com/eclipse/omr/blob/de70faf87f67ffe9cd9571d30e5a378009b85b7c/compiler/z/codegen/RealRegisterEnum.hpp#L159-L174

These dependencies are not backed by real hardware, but instead serve as hints to the register allocator. For example, `TR::RealRegister::LegalEvenOfPair` does not serve a similar purpose as `TR::RealRegister::GPR0`. 

We should separate these dependency definitions from real registers. This enum is indirectly used in certain places to size lists that represent Hardware backed registers. This results in confusion as to what the enum represents (is it a list of dependencies or hardware backed registers or both?), and potential bugs. For example, `_registerFile` is defined below to have size 81 (i.e. `TR::RealRegister::NumRegisters` maps to 81):

https://github.com/eclipse/omr/blob/de70faf87f67ffe9cd9571d30e5a378009b85b7c/compiler/z/codegen/OMRMachine.hpp#L184-L190

And when initialized, 80 real registers and a NoReg value is initialized:

https://github.com/eclipse/omr/blob/de70faf87f67ffe9cd9571d30e5a378009b85b7c/compiler/z/codegen/OMRMachine.cpp#L6122-L6132

However, as can be seen above, we also do the following: `_registerFile[TR::RealRegister::SpilledReg] = NULL;` This line is probably important to the RA, but is also undefined behaviour because `SpilledReg` maps to index 91 ( and _registerFile's size is 81). More context as to why this doesn't cause a crash here:[1]

We need to separate these dependencies from real register enumerations because they are clearly being used in different contexts. While this may not currently create bugs, it does create confusion and  can cause unwarranted bugs in the future.

For more context on this problem, please refer to the discussion in [1] when I initially tried to remove the `_registerFile[TR::RealRegister::SpilledReg] = NULL;` above:

[1] https://github.com/eclipse/omr/pull/2462#discussion_r182447301

**Comment by dchopra001** [comment]
Current proposed implementation to address this issue is here:
https://github.com/eclipse/omr/pull/2462#discussion_r182606476

I'm working on trying this out currently.

**Comment by 0xdaryl** [comment]
Good writeup @dchopra001 !
