### ISSUE TITLE
Issue with not detecting gcc when ccache is enabled in the adoptopenjdk+openj9 builds

### ISSUE THREAD

**Issue by sxa555** [eclipse/omr#2567]
Ref https://github.com/eclipse/openj9/issues/1919#issuecomment-389807665 which shows where this is set up.

It appears that if the C compiler (although in this case it's ccache) is set to have environment variables preceding it then the OMR component then configure gets confused. Haven't checked the logic but it could be that openj9 are only setting it up like that on `s390x`:

Failing job on `Linux/s390x`: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_s390x_linux/58/consoleFull
Successful job on `Linux/x86-64` where compiler is showing as `cc`: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_linux/54/consoleFull

**Comment by sxa555** [comment]
`./make/autoconf/generated-configure.sh` and `./make/autoconf/build-performance.m4` in the main openjdk repository both appear to add the extra variables to the start of the CCACHE

**Comment by smlambert** [comment]
I'd like to raise the priority of this issue, is someone working on it presently?

**Comment by DanHeidinga** [comment]
@keithc-ca Are you handling this as part of eclipse/openj9#1919?

**Comment by keithc-ca** [comment]
No, I expect this is unrelated to that, but I'd be happy to be wrong.

**Comment by DanHeidinga** [comment]
Thanks Keith for checking.

@dnakamura Can you take a look at this?

**Comment by dnakamura** [comment]
This root issue is that dash (default `/bin/sh` on ubuntu), does not properly handle setting variables  when included from an expansion inside of `eval`. 
Boiled down code:
```sh
CC="var=1 true"
ac_compiler=\$CC
eval "$ac_compiler"
```
^ works in bash but not dash. Currently working on a fix

**Comment by sxa555** [comment]
Fix doesn't appear to be resolving the problem based on the last attempt to build with the fix

**Comment by irinarada** [comment]
@dnakamura - any new updates - this is blocking the 090 binaries testing.

**Comment by dnakamura** [comment]
Opened a PR for JDK9.  working on porting to other versions now

**Comment by sxa555** [comment]
Any update @dnakamura ? It's JDK10 that's first in our priority list.

**Comment by keithc-ca** [comment]
Devin's new fix is merged for JDK10: https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/44.

**Comment by sxa555** [comment]
Thanks @pshipton - looks like you pulled this across to openj9-0.9 yesterday :-) Will kick off a build and close this off if successful.

**Comment by sxa555** [comment]
Looks happy on the latest build 100 at https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_s390x_linux :-)

**Comment by DanHeidinga** [comment]
@sxa555 The change hasn't been applied to JDK8 but the build appears to be passing at Adopt.  Are there any other JDK levels that you are aware of that need this change?

**Comment by sxa555** [comment]
@DanHeidinga Yeah 8 was never a problem. 9 is though - we haven't built that off the openj9-0.9 branch yet (assuming there is one) but the latest build off the main openj9 branch in there passed ok, so I guess the fix was applied there too.

**Comment by pshipton** [comment]
The fix is applied to jdk9 and the openj9-0.9 branch of jdk9, which does exist.

**Comment by sxa555** [comment]
Seeing something that looks very similar to this on my zlinux build with JDK11 at the moment

**Comment by keithc-ca** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/9 should fix JDK11.

**Comment by pshipton** [comment]
ibmruntimes/openj9-openjdk-jdk11#9 is merged.
