### ISSUE TITLE
Agenda for May 23, 2018 OMR Compiler Architecture Meeting

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2570]
### Agenda

1.  TR IL specification (#2569) [ @0xdaryl  ]

[Recording](https://youtu.be/Dz7eHqU8OQQ)

### Details
Wednesday, May 23, 2018 @ 3:30 EDT (GMT -4), 60 minutes maximum

Join [Webex](https://ibm.webex.com/ibm/j.php?MTID=mc19b3ba1e7334ce20b74547d304e4009)

Meeting number (access code): 928 653 413
Meeting password: omrrocks!

[Global call-in numbers (for audio only)](https://ibm.webex.com/cmp3200/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=650956722&tollFree=1)

**This meeting will be recorded and posted to the [Eclipse OMR YouTube channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).**

**Comment by dibyendumajumdar** [comment]
Hi, is there a recording of this?

**Comment by 0xdaryl** [comment]
Yes.  It will be posted in the next couple of days along with the OMR
initialization topic.  Sorry, we're a bit behind.

  Also, if you're interested in attending these calls live but can't attend
  because the time is inconvenient for your timezone, please let me know
  what timezone you're calling in from and I'll see if I can make an
  adjustment.  I can't guarantee 100% that I'll be able to make a change to
  accommodate, but I will certainly try.

  Thanks.
  ..0xdaryl

**Comment by dibyendumajumdar** [comment]
Hi @0xdaryl 

Indeed I would like to attend the meetings, but I can only do it after working hours. I think that the current timing is 7:30 am which I can't do.

The best time for me is after 9pm to midnight UK time but that is way off from your current time slot...

Regards

**Comment by 0xdaryl** [comment]
The regular current timeslot is actually 8:30pm UK (GMT +1) - 10pm UK.  Depending on the availability of the participants I've had to move it around sometimes, but 8:30pm GMT+1 is when it normally starts.

**Comment by dibyendumajumdar** [comment]
Cool - I should be able to join in that case!
