### ISSUE TITLE
AArch64: cross compile builds aren't building the compiler

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2601]
The AArch64 TravisCI cross compile builds don't build either the test compiler (with JIT) or JitBuilder.   The problem with that is that the compiler technology that we're implementing isn't being built, which was kind of the point of these cross compile builds.

We want to build either of those technologies, but not run any tests yet.  

@jeanlego @aarongraham9 : Can you look into how to make this possible?

**Comment by 0xdaryl** [comment]
@knn-k @JamesKingdon : fyi

**Comment by 0xdaryl** [comment]
We should also start filling in a CMakeLists.txt for the `arm` directories so that path is ready when needed.

**Comment by aarongraham9** [comment]
Ok. I'll take a look.

**Comment by 0xdaryl** [comment]
@aarongraham9, is there any update on this?

**Comment by aarongraham9** [comment]
I'm putting together a WIP PR this morning.

**Comment by 0xdaryl** [comment]
Cool!  Thanks.

**Comment by aarongraham9** [comment]
This can be closed via #2622.
