### ISSUE TITLE
Question: is there a mailing list for asking questions?

### ISSUE THREAD

**Issue by dibyendumajumdar** [eclipse/omr#2602]
I am hoping to use the compiler backend and expect to ask lots of questions. Where should I do this?

**Comment by fjeremic** [comment]
There is a mailing list over at [1] there is also talk of setting up Slack / gitter over in [2].

[1] https://accounts.eclipse.org/mailing-list/omr-dev
[2] https://github.com/eclipse/omr/issues/2447

**Comment by dibyendumajumdar** [comment]
Okay thank you

**Comment by dibyendumajumdar** [comment]
Hi @fjeremic 

Is the mailing list read? I posted a question but haven't heard back. 

Regards

**Comment by fjeremic** [comment]
> Is the mailing list read? I posted a question but haven't heard back.

@dibyendumajumdar I think it reaches a broader audience. There isn't too much activity on the mailing list as most people ask questions on GitHub. I personally monitor both and tag appropriate parties who are knowledgeable in the area.

**Comment by dibyendumajumdar** [comment]
Hi @fjeremic 

I would recommend adding a note about the mailing list to the front page.

Regards
