### ISSUE TITLE
Warning with gcc 4.9.3

### ISSUE THREAD

**Issue by jdekonin** [eclipse/omr#265]
Because all warnings are treated as errors omr fails to compile with gcc 4.9.3 (verified on ubuntu 16).  

../../omr/port/unix/omrfiletext.c:129:2: warning: ignoring return value of 'wctomb', declared with attribute warn_unused_result [-Wunused-result]
  wctomb(NULL, 0);

../../omr/port/unix/omrintrospect.c:337:3: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   write(barrier->descriptor_pair[1], &byte, 1);

../../omr/port/unix/omrintrospect.c:294:3: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
   write(barrier->descriptor_pair[1], &byte, 1);

../../omr/port/unix/omrintrospect.c:305:2: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
  write(barrier->descriptor_pair[1], &byte, 1);

../../omr/port/unix/omrintrospect.c:418:2: warning: ignoring return value of 'write', declared with attribute warn_unused_result [-Wunused-result]
  write(barrier->descriptor_pair[1], &byte, 1);

../../omr/include_core/omrsig.h:110:54: warning: 'struct sigvec' declared inside parameter list
 int sigvec(int sig, const struct sigvec *vec, struct sigvec *ovec) __THROW;

../../omr/port/unix/omrosdump.c:168:4: warning: ignoring return value of 'chdir', declared with attribute warn_unused_result [-Wunused-result]
    chdir(filename);

../../omr/port/unix/omrsysinfo.c:1177:3: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
   fgets((char *)lineString, MAX_LINE_LENGTH, memStatFs);

**Comment by youngar** [comment]
We have the following section in port_objects.mk; it's pretty horrible but it is our current approach to dealing with this issue.  We are just disabling warnings as errors for those files
```
# Linux standard headers have some functions marked with the attribute "warn_unused_result".
  ifeq (gcc,$(OMR_TOOLCHAIN))
omrfile.o: MODULE_CFLAGS+=-Wno-error
omrfiletext.o: MODULE_CFLAGS+=-Wno-error
omrintrospect.o: MODULE_CFLAGS+=-Wno-error
omrosdump.o: MODULE_CFLAGS+=-Wno-error
omrosdump_helpers.o: MODULE_CFLAGS+=-Wno-error
omrsysinfo.o: MODULE_CFLAGS+=-Wno-error
  endif
```

**Comment by mgaudet** [comment]
IIRC, you can be more specific with something like `-Wno-error=unused-result`.

**Comment by youngar** [comment]
Yeah, that would be the ideal flag.  Unfortunately not all our build GCC compiler versions recognize `-Wunused-result` (and so do not understand `-Wno-error=unused-result`) and fail with that option, so we opted for the `-Wno-error`.   Newer versions of GCC have an option `-Wno-unknown-warning` which we might be able to one day use.

**Comment by mgaudet** [comment]
Right -- but if you can detect 4.9 in the configure script, you could use the more specific flag (after all, this is a 4.9 failure)

**Comment by charliegracie** [comment]
Some of these should be fixed properly by checking the result but at least one the result is meaningless when the parameter is NULL as it just resets state.  The problem right now is we reconginze clang as GCC which is why we can not just turn the compiler warning off specifically.  I was thinking about adding a pragma in the files which would disable the warning for the specific cases that it should be ignored.  This should be portable as compilers should ignore unknown pragmas.

**Comment by charliegracie** [comment]
Closed this is already handled.  It is not actually causing a compiler error.  The actual issue is tracked in #266
