### ISSUE TITLE
Agenda for July 11, 2018 OMR Compiler Architecture Meeting

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#2740]
### Agenda

1.  Discuss default floating point semantics in OMR

[Recording](https://youtu.be/0qnrtCuUZOE)

### Details
Wednesday, July 11, 2018 @ 11:00 EDT (GMT -4), 60 minutes maximum

Join [Webex](https://ibm.webex.com/ibm/j.php?MTID=m9b660ecfc0277ffadbdcc59ef2aa8a6b)

Meeting number (access code): 926 359 783
Meeting password: omrrocks!

[Global call-in numbers (for audio only)](https://ibm.webex.com/cmp3200/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=650956722&tollFree=1)

**This meeting will be recorded and posted to the [Eclipse OMR YouTube channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).**

**Comment by 0xdaryl** [comment]
FYI:  @andrewcraik @0dvictor @shivammittal99 @fjeremic @gita-omr @ymanton @vijaysun-omr

**Comment by 0dvictor** [comment]
FYI, the link for "Global call-in numbers" says "The meeting has been cancelled".
