### ISSUE TITLE
Set ICF flags on labels instead of instructions in the Z codegen

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#2833]
As part of a review [1] we noticed that the Z codegen is an anomaly compared to other codegens in that we set the ICF flags on instructions rather than labels. We should not stray apart from the other codegens. The task here is to evaluate whether it is possible for us to start setting ICF flags on labels rather than instructions and completely deprecate the instruction ICF flag.

[1] https://github.com/eclipse/omr/pull/2800#discussion_r208251138

**Comment by dhong44** [comment]
While changing the ICF flags to be set only on Labels I tried to pick some consistent conventions to follow for ICF labels. 

- Unless there was a meaningful name, start ICF labels would be called cFlowRegionStart and cFlowRegionEnd, this was already found commonly in the codebase
- Dependencies are set on the end ICF label by using the overload of `generateS390LabelInstruction` that accepts a dependency
- `setStartInternalControlFlow` and `setEndInternalControlFlow` are called immediately after `generateS390LabelInstruction`

**Comment by fjeremic** [comment]
@dhong44 that all sounds reasonable. Thanks!
