### ISSUE TITLE
Configure Flags for JitBuilder and Test Compiler

### ISSUE THREAD

**Issue by noryb009** [eclipse/omr#285]
Currently, JitBuilder and the Test compiler are built and their tests run if the `OMR_JIT` and `fvtest` configure flags are enabled (specifically, JitBuilder is built if `OMR_JIT` is enabled, while everything else is built if both are enabled). They should be broken out into their own configure flags, `--enable-jitbuilder` and `--enable-test-compiler`.

**Comment by mstoodle** [comment]
@noryb009 given the commits, Is there anything left to do for this issue?

**Comment by noryb009** [comment]
This issue is not resolved. The commit referenced this to explain that the Test compiler and JitBuilder will receive their own flags at some point.

**Comment by noryb009** [comment]
Resolved in #444.
