### ISSUE TITLE
Performance regression with setOption(TR_DisableInternalPointers)

### ISSUE THREAD

**Issue by harryyu1994** [eclipse/omr#2886]
The following code snippet (from omr/compiler/compile/OMRCompilation.cpp) gives us performance regression when `TR::Options::getCmdLineOptions()->setOption(TR_DisableInternalPointers);` is changed to `self()->setOption(TR_DisableInternalPointers);`.
```
// Temporarily exclude PPC due to perf regression
      if( (self()->getMethodHotness() <= warm))
         {
         if (!TR::Compiler->target.cpu.isPower())
            TR::Options::getCmdLineOptions()->setOption(TR_DisableInternalPointers);
         }
      self()->getOptions()->setOption(TR_DisablePartialInlining);
```

In theory, `self()->setOption(TR_DisableInternalPointers)` is the correct way to do this as it only sets the TR_DisableInternalPointers bit for the current compilation. Using `TR::Options::getCmdLineOptions()->setOption(TR_DisableInternalPointers);` is a bug because changing the global TR::Options object means changing the options for all the compilations that follow. The per-compilation TR::Options object is constructed based on the global TR::Options object. 

However, performance results have shown that correcting this code leads to 4% performance regression on X. While removing this line `TR::Options::getCmdLineOptions()->setOption(TR_DisableInternalPointers);` also gives us a slight performance regression as well. Further investigation is needed.

**Comment by 0xdaryl** [comment]
@nbhuiyan , fyi for your compiler options rework.
