### ISSUE TITLE
GC: Enable snapshot at the beginning barrier for standard gc polices

### ISSUE THREAD

**Issue by ebadyano** [eclipse/omr#2987]
SATB barrier is used in metronome gc policy. We would like to enable it for gencon and optavgpause gc polices under option -Xgc:snapshotAtTheBeginningBarrier. First we need to decouple the barrier code from metronome gc and enable it for ConcurrenGC. 

Initial changes went in with https://github.com/eclipse/openj9/pull/2298 and https://github.com/eclipse/omr/pull/2717. We introduced WorkPacketsSATB, two subclasses for ConcurrnetGC (IncrementalUpdate and SATB) and RememberedSetSATB and enabled SATB barrier ability for concurrent collections. All changes are enabled only when -Xgc:snapshotAtTheBeginningBarrier option is set.

**Outstanding Tasks**

- [ ] Check that first gc cycle is completed and modify condition when isAllPacketsEmpty() to make sure all packets are processed before global gc starts
- [ ] When SATB is enabled mark objects when they are allocated
- [ ] Enable double barrier
- [ ] Check if darkMatterSampleRate sampling works with premarking
- [ ] (Re-)enabled optimization in backward and forward ReferenceArrayCopy in StandardAccessBarrier
- [ ] ~Incremental Overflow support (from @dmitripivkine Incremental Overflow uses object header bit 0x4 to mark unloaded objects. The same bit however is used as a Forwarded bit, so it would have interference with Scavenger (STW and CS))~ In the latest PR https://github.com/eclipse/omr/pull/2993 switched to using Standard overflow, needs more testing.
- [ ] Substitute OMR_GC_STACCATO and OMR_GC_REALTIME flags with  OMR_GC_SATB_BARRIER. (**cleanup**)
- [ ] Make sure it works for gencon policy (decide where to call _generationalAccessBarrierComponent in pre/postObjectStore access barrier calls).

**Comment by ebadyano** [comment]
@amicic @dmitripivkine @charliegracie FYI

**Comment by amicic** [comment]
One large outstanding task is JIT support, but probably there are few smaller ones that are yet to be discovered as we go.

For the build flags, I'm not quite sure what we want to do. One idea is to introduce OMR_GC_SATB_BARRIER, but it would not really replace OMR_GC_REALTIME/OMR_GC_STACCATO (which should collapse to one build flag).
OMR_GC_SATB_BARRIER would be used for any code that is shared between GC policy metronome, optavgpause and gencon (the later ones with enabled SATB barrier). Those would be RememberedSetSATB and WorkPacketsSATB, probably something else as well.
OMR_GC_REALTIME would be used for specifically only for Metronome (then it could be renamed to OMR_GC_METRONOME)
The analog of that in 'standard' (historically known also as Modron) GC policies would be OMR_GC_MODRON_CONCURRENT_MARK.

All 3 (REALTIME/SATB/CONCURRENT_MARK) would be enabled by default, but those could be valid combose too (should compile and link):
- REALTIME with SATB (just Metronome GC policy)
- CONCURRENT_MARK with SATB (and no REALTIME), all 3 standard GC policies (opthroughput, optavgpause, gencon), but the concurrent ones would have a choice of IncrementalUpdate (default) or SATB
- CONCURRENT_MARK without SATB or REALTIME, all 3 standard GC policies (opthroughput, optavgpause, gencon), while concurrent ones would ahve only IncrementalUpdate 'flavour'
- all three disabled, with only optthroughput GC policy
Combo of REALTIME  without SATB would not be valid.

Those build flag changes is probably better to do after Metronome migrates to OMR.

**Comment by amicic** [comment]
We will continue the work under https://github.com/eclipse/omr/issues/5494. This can be closed now.
