### ISSUE TITLE
Incorrect signedness breaks the build

### ISSUE THREAD

**Issue by shingarov** [eclipse/omr#3009]
The merge of PR 2931 (2018-09-11 10:20:18) introduced int/float bit conversion in jitbuilder.  This breaks the build for gcc>=4.9 because of the incorrect signedness in ConvertBitsTest.cpp:
`In file included from JBTestUtil.hpp:25:0,
                from ConvertBitsTest.cpp:22:
../../third_party/gtest-1.8.0/include/gtest/gtest.h: In instantiation of 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = int; T2 = unsigned int]':
ConvertBitsTest.cpp:67:4:   required from here
../../third_party/gtest-1.8.0/include/gtest/gtest.h:1522:28: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]`
Those 0 int literals should be UINT64_C(0).

**Comment by shingarov** [comment]
PR3010.

**Comment by 0xdaryl** [comment]
This is fixed.
