### ISSUE TITLE
AArch64: Floating-point instructions are unavailable

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#3016]
Wide range of floating-point instructions, such as `FMOV (register)` and `FADD`, are missing in OMRInstOpCodeEnum.hpp and OpBinary.cpp for aarch64.

**Comment by jeanlego** [comment]
view #3017

**Comment by knn-k** [comment]
PR #3280 is adding some VFP instructions.

**Comment by knn-k** [comment]
PR #3325 is also adding VFP instructions for type conversion.
Instructions for arithmetic/comparison operations are still missing.

**Comment by knn-k** [comment]
Most of the required instructions are added in #3378.  Closing.
