### ISSUE TITLE
AArch64: Branch instructions are unavailable

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#3017]
`B` (unconditional branch with PC-relative offset) and `BL` (branch and link with PC-relative offset) instructions are missing in OMRInstOpCodeEnum.hpp and OpBinary.cpp for aarch64.

**Comment by knn-k** [comment]
What was the background/reason of the decision of commenting out these opcodes from the table?

**Comment by jeanlego** [comment]
Pr #2600 
We discussed simply keeping op codes unused out of the list and add them as we go, the spreadsheet used as had a few updates so I'll put it here when I get the chance but I think that we should put back all the opcodes and simply comment out this that are unused. This way if we need them there's no need to go back and forth with the spreadsheet. Thoughts?

**Comment by knn-k** [comment]
Additional comment:
`ARM64Ops.hpp` is no longer used.  Its content was moved to `OMRInstOpCodeEnum.hpp` by PR #2778.

**Comment by knn-k** [comment]
When you add instructions, please update `opCodeToNameMap[]` in `ARM64Debug.cpp`, too.

**Comment by knn-k** [comment]
PR #3087 handles this issue.
