### ISSUE TITLE
Are interfaces just a Java concept?

### ISSUE THREAD

**Issue by mstoodle** [eclipse/omr#302]
The compiler has a definite notion of an interface defining certain kinds of call targets that can be reached from certain kinds of call sites. This concept derives from the Java world of interfaces, and pull requests like #279 adjust the semantics of how the compiler deals with interfaces based on the semantics of Java.

Is there a general notion of an "interface" that crosses languages and should we figure out how to generalize that concept? Or is interface a Java thing we should be figuring out how to sink into a Java-specific (compiler) glue layer?

@vijaysun-omr @0xdaryl @andrewcraik + anyone else who has an opinion!

**Comment by andrewcraik** [comment]
Given that interfaces are, at their root in Java, a mechanism for handling multiple inheritance the root of the issues behind interfaces in most of the optimizations is that you don't know what the implementing type is or what implementation may be called. That would seem a generally useful concept regardless of the language in which it is expressed. Trying to push interfaces down into trj9 would, for the purposes of inlining argument pre-existance, vp, and other opts be tantamount to saying that we are going to live in a world where a type is either known or unknown and a vague notion of some kind of type without enough information to know about what is being called or what the receiver is does not exist - I'm not sure that's the right direction for OMR as a whole.

The concept may need some refining at the OMR level as dynamic languages with true duck typing and/or multiple inheritance are connected, but the need to be necessarily vague seems to be the core issue the existing interface infrastructure would help to address. Evolving this support from the current interface support would seem to be the logical path from my perspective.

**Comment by vijaysun-omr** [comment]
I think that we should probably keep the notion in OMR for now until we can make a reasonable attempt at generalizing it to work for some other language. The notion of a "multiple inheritance" like thing (called "interface" for now) itself seems like it could be useful in the non Java world too.

**Comment by mstoodle** [comment]
Seems like we all agree that OMR needs a notion of "interface" and that we should be evolving some common notion of it from what's currently in OMR. I think that addresses the bulk of my question, so I'm going to close this issue, but at some point we should outline what the characteristics of an OMR interface are.
