### ISSUE TITLE
omr promotion to openj9 assertion failed at mgcalloc.cpp:116: ((false && (allocatedBytes == mixedOAM.getAllocateDescription()->getContiguousBytes())))

### ISSUE THREAD

**Issue by pshipton** [eclipse/omr#3077]
First seen in https://ci.eclipse.org/openj9/view/Pipelines/job/Pipeline-OMR-Acceptance/855/
OpenJ9: ffa84ab
OMR: 2bc0d2a
OpenJDK8: 1ba8f1a
OpenJDK11: 4f9e2ba
OpenJDK9: 364c38a

https://ci.eclipse.org/openj9/job/Test-sanity.functional-JDK11-linux_x86-64/93/console
```
20:01:56 00:01:57.553 0x7f9ce80b8e00    j9mm.107    *   ** ASSERTION FAILED ** at mgcalloc.cpp:116: ((false && (allocatedBytes == mixedOAM.getAllocateDescription()->getContiguousBytes())))
...
20:02:00 makefile:82: recipe for target 'compile' failed
```

**Comment by charliegracie** [comment]
Can you please provide some more details?  These tests are very specific to the OpenJ9 project so it is difficult to know where to even start.

Do you know when this failure started? ie. can you tell me which SHA introduced the failure and the last known working SHA? Are there steps to reproduce? How reproducible is the failure? The assertion is in OpenJ9 specific code... did that code change recently? If not it seems likely that is a new issue but rather a latent issue in either OMR or OpenJ9. Can I download a VM from somewhere to test? Do I need a special environment to run or compile the VM?

**Comment by pshipton** [comment]
This is possibly a duplicate of https://github.com/eclipse/openj9/issues/3319
All the information I have is in the description.
The last omr promotion build promoted, with the problematic openj9 change reverted.
I'd like to keep this open today while monitoring for more problems. If it doesn't occur again I will close it as a dup.

**Comment by pshipton** [comment]
The problems have not resurfaced, closing as a dup of eclipse/openj9#3319
