### ISSUE TITLE
NotEqualTo evaluates to false for NaNs

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#3206]
It seems that the `IlBuilder::NotEqualTo` service has surprising behaviour with respect to NaN when comparing floating-point types. This service ends up returning 0 when comparing a value against NaN because it uses the `fcmpne`/`dcmpne` opcodes, which evaluate to false for unordered values, instead of the more appropriate `fcmpneu`/`dcmpneu` opcodes.

This behaviour is not in line with the IEEE 754 standard, which dictates that `x != NaN` should be true for all values of x. Considering that most (if not all) languages agree on this, the behaviour of the JitBuilder service is incredibly surprising and this behaviour is probably never what the user intends.

**Comment by mstoodle** [comment]
It looks to me like no one in our consumer list is relying on compareOp() to return the "non-u" versions of dcmp/fcmp opcodes, so there shouldn't be any issue "changing" OMR's decision on this front. I believe @Leonardo2718 mentioned he had tried this in the past and there were some issues that came up in the evaluators (like, maybe they're not all implemented :) ).

@Leonardo2718 can you please outline what you found here, so we can capture what we think is needed here to move forward?

**Comment by mstoodle** [comment]
bah just noticed @aviansie-ben 's cross-link. Never mind @Leonardo2718 !

**Comment by Leonardo2718** [comment]
@mstoodle Yes, the cross-linked issue covers what I had mentioned earlier.
