### ISSUE TITLE
Reducing fvtest chattiness and duration?

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#323]
Is it possible for us to reduce the chattiness and length of the fvtest suite a bit? 

`make test` right now outputs about 17,000 lines of output on my machine... which seems a bit excessive. As well, almost half the test time occurs in one test: 

```
time ./omrthreadextendedtest
grinding time is 0 millis. (The value can be specified using -grind=<mins>)
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from ThreadExtendedTest
[ RUN      ] ThreadExtendedTest.TestSystemTimesMonotonic
[       OK ] ThreadExtendedTest.TestSystemTimesMonotonic (2162 ms)
[ RUN      ] ThreadExtendedTest.TestUserTimesMonotonic
[       OK ] ThreadExtendedTest.TestUserTimesMonotonic (0 ms)
[ RUN      ] ThreadExtendedTest.TestThreadCpuTime
[       OK ] ThreadExtendedTest.TestThreadCpuTime (513598 ms)
[ RUN      ] ThreadExtendedTest.TestJvmCpuUsageInfoMonotonic
[       OK ] ThreadExtendedTest.TestJvmCpuUsageInfoMonotonic (0 ms)
[ RUN      ] ThreadExtendedTest.TestOtherThreadCputime
[       OK ] ThreadExtendedTest.TestOtherThreadCputime (155757 ms)
[ RUN      ] ThreadExtendedTest.TestTimeBaseMonotonicity
[       OK ] ThreadExtendedTest.TestTimeBaseMonotonicity (60000 ms)
[----------] 6 tests from ThreadExtendedTest (731517 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (731517 ms total)
[  PASSED  ] 6 tests.
[  ALL TESTS PASSED  ] 

real    12m11.519s
user    45m29.180s
sys 0m6.460s
```

Is that test providing 45 minutes of CPU time worth of value?

**Comment by mgaudet** [comment]
(oh, and a [recent Travis log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/165844642/log.txt) stripped of the build step was 58,000 lines by `wc`)

**Comment by renfeiw** [comment]
We have created a logger (issue #163) to provide leveled output. It can be used it to turn down output. For now only GC test uses the logger and the eventual plan is to use it for all test output.

**Comment by charliegracie** [comment]
We need to significantly reduce the amount of output and the time it takes to complete.  My preference would be to only output error text by default.

**Comment by rwy0717** [comment]
Can we get a test writers' guide in the docs?

**Comment by mgaudet** [comment]
There's been a huge improvement in output length and chattiness since this issue was opened, so I'm going to close this for now. 

Thanks all.
