### ISSUE TITLE
Use CBZ/CBNZ instructions where applicable

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#3364]
This is a performance item.

AArch64 has compare-and-branch instructions on zero and nonzero conditions.  Use those instructions where applicable.

**Comment by mhaque5** [comment]
I am working on this issue. Any suggestion will be appreciated.

**Comment by knn-k** [comment]
Look at `ificmpHelper()` in compiler/aarch64/codegen/ControlFlowEvaluator.cpp.  It generates two instructions (compare and branch) in it.
When the condition code `cc` is `CC_EQ` or `CC_NE`, and the second child of the node is a constant zero, you can use `cbz`/`cbnz` instructions instead of the compare and branch instructions.

**Comment by knn-k** [comment]
I opened https://github.com/eclipse/omr/pull/5264.
It is needed for calling `generateCompareBranchInstruction()` with `deps` in the `if (node->getNumChildren() == 3) { ... }` path in `ificmpHelper()`.
