### ISSUE TITLE
Use FMOV (imm) instruction when applicable

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#3377]
This is a performance item.

AArch64 has an instruction for moving a floating-point immediate to a VFP register. Use the instruction in fconst/dconst when applicable.

**Comment by alvee-unb** [comment]
I am working on this performance item. If anyone has any suggestion, please share.

**Comment by knn-k** [comment]
You can use `fmovimms` (single precision) and `fmovimmd` (double precision) as the instruction opcodes for this.  They are already defined in OpBinary.cpp and OMRInstOpCodeEnum.hpp for AArch64.

Note that those instructions have fields for immediate values of only 8-bit width.  See what `ARM64Trg1ImmInstruction::insertImmediateField()` does for encoding other instructions.

**Comment by knn-k** [comment]
Related PR: #5388

**Comment by knn-k** [comment]
Loading the constant 0.0 into an FP register requires another instruction, `MOVI` (Move Immediate):

>movi v0.2s, #0 // float
>movi d0, #0 // double
