### ISSUE TITLE
Add awareness of read barriers to an arraycopy transformation

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/omr#3440]
There is a transformation that changes a reference arraycopy node into a primitive arraycopy node if neither an arraystore check nor a write barrier are required. This transformation should also not occur if a read barrier is required.

transformArrayCopyCall inside ValuePropagationCommon.cpp needs to be changed to know about read barriers and elect not to transform the reference arraycopy node if read barriers are needed.

**Comment by gita-omr** [comment]
@pshipton this is a prerequisite for https://github.com/eclipse/openj9/issues/3421

**Comment by gita-omr** [comment]
PR: https://github.com/eclipse/omr/pull/3442
