### ISSUE TITLE
Unbounded Tenure expand with disabled CM

### ISSUE THREAD

**Issue by amicic** [eclipse/omr#3492]
When running Gencon GC policy with Concurrent Mark disabled (-Xgc:noConcurrentMark
or -Xconcurrentlevel0), to maximize throughput, Scavenge GCs will continuously expand Tenure heap (with reason 'continue current collection') till is fully expanded, completely disobeying Max Free heap criteria.

With CM enabled, there is kickoff logic that will act similarly and properly balance Tenure expansion vs doing global GC, so this problem does not exist there.

**Comment by amicic** [comment]
Sample run demonstrating the problem
[jbb_noCM_orig.log](https://github.com/eclipse/omr/files/2787865/jbb_noCM_orig.log)

**Comment by amicic** [comment]
Behaviour after adding a couple of percolate reasons:
[jbb_noCM_percolate_midf_maxf.log](https://github.com/eclipse/omr/files/2787869/jbb_noCM_percolate_midf_maxf.log)

**Comment by amicic** [comment]
![percolate_nocm_tenureheap](https://user-images.githubusercontent.com/18264984/51619695-e1c7b980-1efe-11e9-8edc-988dc4161d60.jpg)

**Comment by charliegracie** [comment]
This was resolved under #3495
