### ISSUE TITLE
Support system limit on open files

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#3579]
Further to https://github.com/eclipse/omr/issues/3501  and https://github.com/eclipse/omr/pull/3511.

There is a problem with RLIMIT_NOFILE support in omrsysinfo_set_limit: if a user does:
```
omrsysinfo_get_limit(OMRPORT_RESOURCE_FILE_DESCRIPTORS | J9PORT_LIMIT_HARD, &limit);
omrsysinfo_set_limit(OMRPORT_RESOURCE_FILE_DESCRIPTORS | OMRPORT_LIMIT_SOFT, limit);
```
in the case where `omrsysinfo_get_limit()` returns -1 (unlimited) as the limit, the `omrsysinfo_set_limit()` will fail because it exceeds the system-defined limit.

Two possible resolutions:
1. have `omrsysinfo_set_limit()` check for -1 as an argument, look up the system limit and use that
2. add a separate API to get the system limit. 

 On MacOS the limit is sysctl property `kern.maxfilesperproc` from `sysctlbyname()`, or possibly a property list on earlier versions. On Linux, it is `/proc/sys/fs/file-max`.

**Comment by pdbain-ibm** [comment]
@charliegracie @youngar your thoughts?

**Comment by youngar** [comment]
If the hard limit is unlimited, I don't think there should be a problem setting the soft limit to unlimited.  The only issue I can think of is that we are not properly checking the return value of `get_limit()`.  When we return `OMRPORT_LIMIT_UNKNOWN`, limit is set to `OMRPORT_LIMIT_UNKNOWN_VALUE` which is also `-1`.  This means the code should actually look like this:
```
uint64_t limit;
int rc = omrsysinfo_get_limit(OMRPORT_RESOURCE_FILE_DESCRIPTORS | J9PORT_LIMIT_HARD, &limit);
if (rc != OMRPORT_LIMIT_UNKNOWN) {
  omrsysinfo_set_limit(OMRPORT_RESOURCE_FILE_DESCRIPTORS | OMRPORT_LIMIT_SOFT, limit);
}
```
Is it possible this is the problem?

**Comment by pdbain-ibm** [comment]
Setting the soft limit (`rlim_cur`) to -1 or anything above the system-defined maximum (kern.maxfilesperproc: 24576 on my Mac) gives an error.

```
#include <stdio.h>
#include <sys/resource.h>
int main(int argc, char *argv[]) {
	struct rlimit lim = {0, 0};
	int rc = getrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s getrlimit hard=%lld cur=%lld\n", __FILE__, __LINE__, __FUNCTION__, lim.rlim_max, lim.rlim_cur);

	lim.rlim_cur = lim.rlim_max;
	rc = setrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s setrlimit rlim_cur=rlim_max rc=%d\n", __FILE__, __LINE__, __FUNCTION__, rc);
	rc = getrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s getrlimit hard=%lld cur=%lld\n", __FILE__, __LINE__, __FUNCTION__, lim.rlim_max, lim.rlim_cur);

	lim.rlim_cur = 34577;
	rc = setrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s setrlimit rlim_cur = 34577 rc=%d\n", __FILE__, __LINE__, __FUNCTION__, rc);
	rc = getrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s getrlimit hard=%lld cur=%lld\n", __FILE__, __LINE__, __FUNCTION__, lim.rlim_max, lim.rlim_cur);

	lim.rlim_cur = 24576;
	rc = setrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s setrlimit rlim_cur = 24576 rc=%d\n", __FILE__, __LINE__, __FUNCTION__, rc);
	rc = getrlimit(RLIMIT_NOFILE, &lim);
    fprintf(stderr, "%s %d PDB_DEBUG %s getrlimit hard=%lld cur=%lld\n", __FILE__, __LINE__, __FUNCTION__, lim.rlim_max, lim.rlim_cur);
}
```

> test.c 6 PDB_DEBUG main getrlimit hard=9223372036854775807 cur=4864
> test.c 10 PDB_DEBUG main setrlimit rlim_cur=rlim_max rc=-1
> test.c 12 PDB_DEBUG main getrlimit hard=9223372036854775807 cur=4864
> test.c 16 PDB_DEBUG main setrlimit rlim_cur = 34577 rc=-1
> test.c 18 PDB_DEBUG main getrlimit hard=9223372036854775807 cur=4864
> test.c 22 PDB_DEBUG main setrlimit rlim_cur = 24576 rc=0
> test.c 24 PDB_DEBUG main getrlimit hard=9223372036854775807 cur=24576

**Comment by youngar** [comment]
Thanks for the explanation, it really helped me to understand the issue.  The issue is quite different than I thought.

From the osx page on[ setrlimit()](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/setrlimit.2.html):
```
     setrlimit() now returns with errno set to EINVAL in places that histori-
     cally succeeded.  It no longer accepts "rlim_cur = RLIM_INFINITY" for
     RLIM_NOFILE.  Use "rlim_cur = min(OPEN_MAX, rlim_max)".
```

I think that solution # 1 is okay.  Another option would be to return `min(OPEN_MAX, rlim_max)` for `omrsysinfo_get_limit(RLIM_NOFILE, &lim)`.  I think you should pursue which ever solution (or both) you think is most appropriate.

**Comment by pdbain-ibm** [comment]
I concur: further to the above, the issue with `OPEN_MAX` is that it is hard-coded in a MacOS-specific header file `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include//sys/syslimits.h:#define	OPEN_MAX		10240	/* max open files per process - todo, make a config option? */` and doesn't take into account changes the user may have made.

I will investigate option 1.
