### ISSUE TITLE
Assertions in VerboseBuffer.cpp with CS

### ISSUE THREAD

**Issue by dmitripivkine** [eclipse/omr#3619]
I noticed assertions
```
** ASSERTION FAILED ** j9vgc.1 at VerboseBuffer.cpp:169 Assert_VGC_true(('\0' == _bufferAlloc[0]))
** ASSERTION FAILED ** j9vgc.1 at VerboseBuffer.cpp:178 Assert_VGC_true(('\0' == _bufferAlloc[0]))
```
when run with `-Xgc:concurrentScavenge -Xverbosegclog:<file>`.
I use Harmony test but I believe any serious load would reproduce the problem
In Harmony failure rate is ~4/100

**Comment by fjeremic** [comment]
Which platform did this fail on? Is it software or hardware CS?

**Comment by dmitripivkine** [comment]
> Which platform did this fail on? Is it software or hardware CS?

Software CS with -Xint on zLinux

**Comment by dmitripivkine** [comment]
> > Which platform did this fail on? Is it software or hardware CS?
> 
> Software CS with -Xint on zLinux
Looks like output buffer expected to be used single threaded but it is not

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by dmitripivkine** [comment]
option -Xverbosegclog:test.log makes it happen more often

**Comment by amicic** [comment]
@RSalman please, investigate

**Comment by RSalman** [comment]
Looking into this

**Comment by fjeremic** [comment]
@dmitripivkine this sounds like an OpenJ9 issue. Shall we move it there?

**Comment by dmitripivkine** [comment]
> @dmitripivkine this sounds like an OpenJ9 issue. Shall we move it there?

Actual assertion is in VerboseBuffer.cpp in OMR. There is no prove that it is OpenJ9 usage of OMR functionality yet. I believe it should be in OMR size for now.

**Comment by RSalman** [comment]
> There is no prove that it is OpenJ9 usage of OMR functionality yet. I believe it should be in OMR size for now

Yup, it's an OMR issue... It's an intermittent issue that occurs when multiple threads write to the verbose buffer at the same time. Simple fix is to make this atomic like Balanced and Metronome have. Working on getting a PR in for the fix.
