### ISSUE TITLE
af-start/af-end stanzas missing from verbosegc logs

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/omr#362]
MM_AllocateInitialization::allocateAndInitializeObject() is not calling MM_EnvironmentBase::allocationFailureEndReportIfRequired() except in OOM scenarios. A side-effect of this is that the MM_EnvironmentBase::_allocationFailureReported flag is never reset after being set when first af-start stanza is printed. Consequently all subsequent af-start reports are supressed.

**Comment by charliegracie** [comment]
Fixed via #363
