### ISSUE TITLE
Windows Server 2019 recognized as "Windows Server 2016" and version "10.0"

### ISSUE THREAD

**Issue by pshipton** [eclipse/omr#3644]
Windows Server 2019 available from Oct 2, 2018
https://cloudblogs.microsoft.com/windowsserver/2018/10/02/windows-server-2019-now-generally-available/

See https://github.com/eclipse/omr/blob/3c6f54e31bec06c23fec77f56f45db8e25250f8d/port/win32/omrsysinfo.c#L170

and https://github.com/eclipse/omr/blob/3c6f54e31bec06c23fec77f56f45db8e25250f8d/port/win32/omrsysinfo.c#L391

**Comment by pshipton** [comment]
@pdbain-ibm is looking at this

**Comment by pdbain-ibm** [comment]
Microsoft has stopped updating the major/minor release numbers and is not adding new `IsWindows<N>OrGreater()`functions: https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/Windows-Server-2019-version-info/td-p/234472
The preferred method to get the version is to query the registry.

**Comment by pdbain-ibm** [comment]
I did a quick-and-dirty hack on `omrsysinfo.c` and it now produces this:

> java version "1.8.0_211"
> Java(TM) SE Runtime Environment (build 8.0.6.0 - pwa6480sr6-20190220_01(SR6))
> IBM J9 VM (build 2.9, JRE 1.8.0 **Windows Server 2019 Datacenter** amd64-64-Bit Compressed References 20190307_411761 (JIT enabled, AOT enabled)
> OpenJ9   - d87ca9f
> OMR      - 0727558
> IBM      - 62c4d31)
> JCL - 20190219_01 based on Oracle jdk8u211-b76

**Comment by pdbain-ibm** [comment]
Windows 10  gives: `IBM J9 VM (build 2.9, JRE 1.8.0 **Windows 10 Enterprise** amd64-64-Bit Compressed References ...` and Windows Server 2016: `IBM J9 VM (build 2.9, JRE 1.8.0 **Windows Server 2016 Standard** amd64-64-Bit Compressed References ...`

**Comment by pdbain-ibm** [comment]
Looking at `omrsysinfo.c`:
```
#if !defined(_WIN32_WINNT_WINBLUE) || !(_WIN32_WINNT_MAXVER >= _WIN32_WINNT_WINBLUE)
		OSVERSIONINFOEX versionInfo;
#endif
```
This is true if the compilation machine's OS version is less than Windows 8.1.  If this is not the case, we get the version information from the registry.

**Comment by pshipton** [comment]
@pdbain-ibm are you saying that no changes are required to support Server 2019?

**Comment by pdbain-ibm** [comment]
Not quite: it depends on where the port library was _compiled_.  If it was compiled on Windows 8 or earlier, it will give the incorrect results; two JVMs built from the same source could give different results.  My change forces the port library to use the registry regardless of the OS version.
