### ISSUE TITLE
OMR CUDA problems

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/omr#37]
* A process may hang if it uses omrcuda_* functions and terminates early by calling omrexit_shutdown_and_exit().

* Some device functions incorrectly record the presence of an initialized CUDA device context. If the first omrcuda function called by a thread is one of those below, the context will be incorrectly marked as valid, leading other functions to fail (e.g. omrcuda_linkerCreate).
  - omrcuda_deviceCanAccessPeer
  - omrcuda_deviceDisablePeerAccess
  - omrcuda_deviceEnablePeerAccess
  - omrcuda_deviceGetAttribute

**Comment by charliegracie** [comment]
Closed via #38
