### ISSUE TITLE
Missing include in omrformatconsts.h

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#3706]
While trying to use the recently added `OMR_PRId64` macro in the tril tests added in #3637, I noticed that my IDE was saying that the macro was expanding to `lld` on an x86-64 Linux, which is incorrect: on this system, `int64_t` is defined as `long int` not `long long int`, and so the correct format specifier is `ld`.

It seems that `omrformatconsts.h` checks for the presence of the `PRId64` macro before using it (with the `lld` format specifier as a fallback if it doesn't), but does not include `inttypes.h` which is where that macro would be defined.

**Comment by Leonardo2718** [comment]
FYI @rwy0717

**Comment by fjeremic** [comment]
Out of curiosity which IDE do you use?

**Comment by aviansie-ben** [comment]
@fjeremic Visual Studio Code. It takes some serious work to get the include paths set up right, but it seems to deal with extensible classes well enough to work with.

**Comment by fjeremic** [comment]
Thanks. I'm using Visual Studio proper myself, and yes IPATH's were tricky but it works. Hopefully IDE support improves once we've made the switch to CMake as some IDEs support CMake projects out of the box.

**Comment by rwy0717** [comment]
fix: https://github.com/eclipse/omr/pull/3709

**Comment by 0xdaryl** [comment]
Fixed in #3709.
