### ISSUE TITLE
ddrgen on OSX fails with some versions of dwarfdump

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse/omr#3708]
On Mac OSX, there seems to be two versions of dwarfdump. One is `llvm-dwarfdump`, which is tied to clang, and `dwarfdump-classic` which is based on dwarfutils. 

When ddrgen was first ported to Mac OSX, calling `dwarfdump` would invoke the `dwarfdump-classic` version. However, somewhat recently, it was changed so `dwarfdump` links to `llvm-dwarfdump` instead. This may have been caused by the Mojave update, or the 10.2 update to XCode, or a recent update.

Ddrgen's parser relies on the format that `dwarfdump-classic` outputs, so we need to specify we want the classic dwarfdump instead of the llvm based one. 

On systems where `dwarfdump` is not a symlink to `llvm-dwardump`, there is no `dwarfdump-classic` binary, and it is just called `dwarfdump`.

fyi @keithc-ca

**Comment by AidanHa** [comment]
>This may have been caused by the Mojave update, or the 10.2 update to XCode, or a recent update.

I believe this Issue still occurred with XCode 10.1 as well @mikezhang1234567890.
