### ISSUE TITLE
Add JitBuilder examples of ConstAddress, arrays of structs, and overlaying vm structs

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#377]
New examples/tests need to be made for the changes introduced into JitBuilder by PR #370.

These should cover:
1. using `ConstAddress()` to define a constant address value
2. defining an array of structs and accessing its elements
3. using a JitBuilder struct definition to interact with objects defined and allocated outside of a JIT (e.g. by a VM).

Points 2 and 3 must take into account that, currently, an array of structs is only guaranteed to be correctly accessed by JitBuilder if the array is itself allocated using JitBuilder. This is because JitBuilder does not add any padding to the end of structs, whereas a C/C++ compiler may (see issue #376).

**Comment by mstoodle** [comment]
In general, I would prefer the creation of tests be kept with the issue that introduces changes, but there's an additional complication in this particular case (i.e. the alignment trouble). Hopefully allowing it to be split out will not unreasonably delay the creation of the tests...

**Comment by Leonardo2718** [comment]
Fixed by PR #394.
