### ISSUE TITLE
InstructionDelegate hierarchy for project-specialization of Instructions

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#3778]
The OMR compiler Instruction hierarchy is an example of a dynamically polymorphic class hierarchy built from an extensible base class (`TR::Instruction`).  In such a hierarchy, any specialization by project lives in the base class.  The dynamic polymorphic parts live in an architecture `codegen` directory.  For example,
```
                            +--------------------------------+
                            |                                |
                            |      +------------------+      |
                            |      | OMR::Instruction |      |   omr/compiler/codegen/OMRInstruction.hpp
                            |      +------------------+      |
                            |               ^                |
                            |               |                |
                            |    +----------+------------+   |
                            |    | OMR::X86::Instruction |   |   omr/compiler/x/codegen/OMRInstruction.hpp
                            |    +-----------------------+   |
                            |               ^                |
                            |               |                |
                            |     +---------+-----------+    |
                            |     | MyProj::Instruction |    |   myproj/codegen/MyProjInstruction.hpp
                            |     +---------------------+    |
                            |               ^                |
                            |               |                |
                            |  +------------+-------------+  |
                            |  | MyProj::X86::Instruction |  |   myproj/x/codegen/MyProjInstruction.hpp
                            |  +------------+-------------+  |
                            |               ^                |
                            |               |                |
                            +---------------|----------------+
                                            |
                                   +--------+--------+
                                   | TR::Instruction |           codegen/Instruction.hpp
                                   +--------+--------+
                                            ^
                                            |
             +------------------------------+---------------------------------+
             |                              |                                 |
             |                              |                                 |
             |                              |                                 |
 +-----------+----------+       +-----------+-----------+         +-----------+----------+
 | TR_X86RegInstruction |       | TR_X86MemInstruction  |         | TR_X86ImmInstruction |    x/codegen/X86Instruction.hpp
 +----------------------+       +-----------------------+         +----------------------+
             ^
             |
+------------+------------+
| TR_X86RegRegInstruction |
+-------------------------+
```
However, there are circumstances where the dynamically polymorphic part of the hierarchy may require function specialization by project as well (for example, the `TR_X86MemInstruction` class).  To accomplish this in the current framework requires providing a means for a downstream project to subsume (or even extend) the implementation of an OMR function.

This can be done with some `#ifdef` wizardry in the OMR instruction source files to check for an "override" of a particular function by a downstream project.  "Override" is a bit of a misnomer, as the downstream project will just provide an alternative implementation in the same namespace as the OMR version.  While this can be made to work, it gets messy when there are several functions that may be overridden (each with their own `#ifdef`s).  Also, it employs a different solution to a problem for which an accepted solution (namely extensible classes) already exists throughout the OMR compiler.

The most obvious way to accomplish this with extensible classes is to make a particular instruction kind class in the dynamic hierarchy an extensible class on its own.  For example, the `TR_X86MemInstruction` class could be made extensible:
```
+-------------------------------+
|                               |
|  +------------------------+   |
|  | OMR::X86MemInstruction |   |   omr/compiler/codegen/x/OMRX86MemInstruction.hpp
|  +------------+-----------+   |   omr/compiler/codegen/x/X86MemInstruction.hpp (for concrete class in case class not extended by project)
|               ^               |
|               |               |
| +-------------+-------------+ |
| | MyProj::X86MemInstruction | |   myproj/codegen/x/MyProjX86MemInstruction.hpp
| +---------------------------+ |
|               ^               |
|               |               |
+---------------|---------------+
                |
    +-----------+-----------+
    | TR::X86MemInstruction |       myproj/codegen/x/X86MemInstruction.hpp (for concrete class)
    +-----------------------+
```
However, one of the known drawbacks of extensible classes is the number of files it requires (as seen in the diagram above, and that does not include any `.cpp` implementation files).  While this may be tolerable for a single instruction kind class, if such project specialization were to be required across many instruction kinds then this would lead to an explosion in the number of files, especially considering the fact that the Instruction hierarchy can be quite wide and deep depending on the architecture.  This is the reason we did not make the dynamic parts of the instruction hierarchy extensible in the first place.

As an alternative, consider an `InstructionDelegate` hierarchy:
```
+----------------------------------------+
|                                        |
|    +-------------------------------+   |
|    | OMR::X86::InstructionDelegate |   |   omr/compiler/x/codegen/OMRInstructionDelegate.hpp
|    +-------------------------------+   |
|                   ^                    |
|                   |                    |
|  +----------------+-----------------+  |
|  | MyProj::X86::InstructionDelegate |  |   myproj/x/codegen/MyProjInstructionDelegate.hpp
|  +----------------+-----------------+  |
|                   ^                    |
|                   |                    |
+-------------------|--------------------+
                    |
        +-------------------------+
        | TR::InstructionDelegate |          x/codegen/InstructionDelegate.hpp
        +-------------------------+
```
The purpose of this hierarchy is to provide project-specific, static delegate functions to instruction kind classes.  The first parameter of such functions should be a pointer to a particular instruction kind.  Functions within the instruction kind hierarchy can call these delegate functions if project-specialized behaviour is required.

The delegate hierarchy is constructed similarly to an extensible class hierarchy and follows most of the same rules.  The main differences are that there are only architectural-specific classes (hence connectors are not required), and only static functions are allowed (there is no instance of this hierarchy).  All instruction kinds share the same `InstructionDelegate` hierarchy and hence the number of files required is limited.

Access to private data in the instruction hierarchy can be achieved through getters/setters.  However, providing public access to this data may not be desirable.  In those instances, creative use of friending with the `InstructionDelegate` hierarchy may allow the required access to private data.

For example (some liberties taken with C++ syntax):
```
virtual void TR_X86MemInstruction::klik()
   {
   ...
   }

virtual void TR_X86MemInstruction::prem(TR::CodeGenerator *cg)
   {
   ...
   // Will call the MyProj version if it exists, otherwise will call
   // the OMR version.
   //
   TR::InstructionDelegate::spam(this, cg);
   ...
   }

static void OMR::InstructionDelegate::spam(TR_X86MemInstruction *instr, TR::CodeGenerator *cg)
   {
   instr->klik();
   ...
   }

static void MyProj::InstructionDelegate::spam(TR_X86MemInstruction *instr, TR::CodeGenerator *cg)
   {
   ...
   }
```   
This hierarchy has the danger of becoming a "kitchen sink" class of functions.  In some sense, that's what it's for.  However, in practice, the number of project-specialized functions across all the different instruction kinds is not expected to be large and hence this design is adequate.

**Comment by fjeremic** [comment]
```
static void OMR::InstructionDelegate::spam(TR_X86MemInstruction *instr, TR::CodeGenerator *cg)
```

Can we place the `cg` parameter first since it will be present on each of these APIs while the former parameter type may change?

**Comment by 0xdaryl** [comment]
The main reason I had for listing the instruction kind first was to make it easier to distinguish between multiple overloaded implementations.  For example, if 10 different instruction kinds in MyProj were specializing some function `foo()` then each would provide a different instruction kind parameter, which might be easier to distinguish (textually) if it was the first parameter.

What you're proposing isn't unreasonable though.  When I put a PR together I can provide a couple of sample implementations so that we can decide on what looks better.

**Comment by fjeremic** [comment]
> The main reason I had for listing the instruction kind first was to make it easier to distinguish between multiple overloaded implementations. For example, if 10 different instruction kinds in MyProj were specializing some function `foo()` then each would provide a different instruction kind parameter, which might be easier to distinguish (textually) if it was the first parameter.

```
void foo(TR_X86MemInstruction *instr, TR::CodeGenerator *cg)
void foo(TR_X86MemRegInstruction *instr, TR::CodeGenerator *cg)
void foo(TR_X86MemRegWithEvenLongerNameInstruction *instr, TR::CodeGenerator *cg)
void foo(TR_X86MemRegWithEvenLongerNameInstruction *instr, int32_t bar, TR::CodeGenerator *cg)
```

vs.

```

void foo(TR::CodeGenerator *cg, TR_X86MemInstruction *instr)
void foo(TR::CodeGenerator *cg, TR_X86MemRegInstruction *instr)
void foo(TR::CodeGenerator *cg, TR_X86MemRegWithEvenLongerNameInstruction *instr)
void foo(TR::CodeGenerator *cg, TR_X86MemRegWithEvenLongerNameInstruction *instr, int32_t bar)
```

**Comment by 0xdaryl** [comment]
Done!
