### ISSUE TITLE
DefineFunction() doesn't accept the string literal in C++11

### ISSUE THREAD

**Issue by ShuyuLi-ca** [eclipse/omr#378]
Some of the parameter types in DefineFunction() are char* but arguments are not to be modified. Started in C++11, DefineFunction() doesn't accept the string literal.

The parameter types should be changed in order to accommodate the string literal.

**Comment by mstoodle** [comment]
This issue was addressed by PR #373 but the issue wasn't mentioned in the commit message.

Closing manually.

Thanks for the fix, @ShuyuLi-ca !
