### ISSUE TITLE
Ternary evaluator support on Z

### ISSUE THREAD

**Issue by yanluo7** [eclipse/omr#3796]
There is newly added tril test for ternary opcode, which are are curreltly failing on Z:
https://ci.eclipse.org/omr/job/PullRequest-linux_390-64/1555/

The Z support is required to enable certain optimizer change soon that will generate more integer/address typed ternary opcode.

**Comment by yanluo7** [comment]
@fjeremic

**Comment by fjeremic** [comment]
@dchopra001 can you please take a look at the failure in #3785 and fix them? @yanluo7 if you would like you can disable the ternary Tril tests on Z referencing this issue and we'll get this fixed. See [1] as an example how to do it.

[1] https://github.com/eclipse/omr/blob/076709ec937e2e552a76b5894fe597219e2b19e2/fvtest/compilertriltest/ArithmeticTest.cpp#L150-L152

**Comment by yanluo7** [comment]
> @dchopra001 can you please take a look at the failure in #3785 and fix them? @yanluo7 if you would like you can disable the ternary Tril tests on Z referencing this issue and we'll get this fixed. See [1] as an example how to do it.
> 
> [1]
> 
> https://github.com/eclipse/omr/blob/076709ec937e2e552a76b5894fe597219e2b19e2/fvtest/compilertriltest/ArithmeticTest.cpp#L150-L152

I excluded the tests from s390 util implementation is completed in https://github.com/eclipse/omr/pull/3785

**Comment by 0xdaryl** [comment]
Is the Z work done now and can these tests be enabled?  The comment above references 3785 for the implementation (which is merged), but that PR is about adding Tril tests.

**Comment by fjeremic** [comment]
I don't believe this has been completed yet. I believe we disabled the ternary tests on Z as part of #3785 and they still need to be enabled after fixing the original issues. @dchopra001 can you confirm?

**Comment by dchopra001** [comment]
Yes. The underlying issue is here: https://github.com/eclipse/omr/issues/3525#issuecomment-489245189 and it impacts all BE platforms. 

The problem doesn't occur in openj9 because we typically don't generate `sternary` and `bternary` type trees in Java.
