### ISSUE TITLE
Compact trigger for idle tuning

### ISSUE THREAD

**Issue by amicic** [eclipse/omr#3797]
This is in regard to OpenJ9 feature when JVM can detect being inactive and aggressively release unused pages. JVM will do a GC before walking heap (Tenure specifically in Gencon configuration) and releasing OS pages within free entries of memory pool.

While GC alone should release significant amount of memory (in average 1/2 of heap between live set size and full heap size will be garbage), that memory might be relatively fragmented and not many free OS pages will fit into them. 

A  simple solution is always do a full compact (that will defragment memory), that will maximize amount of free pages being released.

However, compact operation is relatively expensive, making such GC 2-3x longer.
In a scenario with relatively frequent active->idle->active->idle scenarios (10s of transitions per hour), benefits of such compact will be low, because there will be little time to fragment memory between two idle transitions.

A compromise is to introduce a compact trigger that will estimate the amount of fragmented memory that could be potentially freed.

We have 2 types of fragmentation metrics already (specifically for Tenure in Gencon, what exactly is our target)
- macro-fragmentation - this metric is fragmented free memory the memory pool that is allocation pattern aware. It's not quite of our interest here - we care about relationship with page sizes (4K or so)
- micro-fragmentation - this metric is fragment memory that is so small that is not even in memory pool (it's also known as dark meter). We care about this. Most of this memory could/should be retrieved back.

However, we need another type of metric (that somewhat resembles macro-fragmentation) - we need to estimate out of total free memory there are free pages (that are aligned) could be freed.
Let's call it _page-aware fragmentation metric_. 
We already have a full histogram of free page sizes. However, we do not have alignment information. It would be expensive to maintain that piece of info but we can do some estimates.

One heuristic is that a free entry of size X will produce this amount of free pages:

(X - pagesize)/ pagesize

For example, for 6K free entry in 4K page size, in average (due to page alignment) there is 50% chance we will be able to squeeze out one free page. Hence, in average, we free up (6K -4K)/4K =0.5 pages. 
With this heuristic, we go through the existing histogram of free pages, apply to each of size groups and add up the pages to get the total page-aware fragmentation.

Finally, we need to add up micro-fragmentation and page-aware fragmentation and estimate if this memory is large enough to justify compaction. This needs another heuristic - as a minimum we should compare it with free memory that normally gets freed up by global GC, but some other factors could be involved (cost of compaction, frequency of GCs...).

**Comment by ShishirH** [comment]
@amicic May I know how you ended up with a default of 25% threshold? Just a little curious.

**Comment by amicic** [comment]
Many factors could influence decisions if compact is worth of doing or not, some of which we do not account at all (for example current overhead of GC when app is activle, expected duration of idleness, current load of the system, etc.,...). This is just based on ratio of current fragmented free memory over current available free memory. We can evolve the trigger even more (after some experimentation and testing with Could realistic workloads), but this is a reasonable start.

The default trigger ratio itself is fairly arbitrary, more or less comes from an observation that compact operation is at least 2x more expensive than mark operation. So doing an optional compact is worth only if there as noticeable de-fragmentation opportunity. So I just quantified 'noticeable' as 25%.
