### ISSUE TITLE
Decouple the OMR Compiler's Error Codes and Return Codes

### ISSUE THREAD

**Issue by dsouzai** [eclipse/omr#380]
The current error handling story in the compiler involves (ideally) setting an error code using the `setErrorCode` method, and then calling the `outOfMemory` which throws a `TR::CompilationException`. This happens when an error occurs deep in a compile such that, currently, there **isn't** a way to consistently propagate the error up without throwing an exception. Unfortunately, the error codes that are set using `setErrorCode` are sometimes also used as return codes that the control logic will check and then throw an exception. This happens when there we are not deep in a compile and it **is** possible to consistently propagate the error up without throwing an exception. As such, there are inconsistencies with the concepts of return and error codes. 

The plan is:
1. Replace all uses of `outOfMemory` with the throwing of appropriate C++ exceptions. 
2. Remove all uses of `setErrorCode`
3. Evaluate the #defines and remove all except those that are used as return codes

By getting rid of `outOfMemory` and `setErrorCode` calls, we remove the need to determine the type of error by checking the error code since we can simply catch the appropriate exceptions. Once this is done, step 3 is simply a cleanup step.

**Comment by dsouzai** [comment]
From what I can tell, the only valid return codes are:
COMPILATION_SUCCEEDED
COMPILATION_IL_GEN_FAILURE
COMPILATION_UNIMPL_OPCODE
and the one Xiaili is adding in #375 (COMPILATION_REQUESTED)

perhaps we also need one along the line of COMPILATION_FAILED for the cases when an exception is thrown.

**Comment by dsouzai** [comment]
These are the list of error codes that, once #412 gets merged, are replaced by TR::CompilationException or it's children:

Excessive Complexity Exception
    COMPILATION_LOOPS_OR_BASICBLOCKS_EXCEEDED
    COMPILATION_REMOVE_EDGE_NESTING_DEPTH_EXCEEDED
    COMPILATION_MAX_DEPTH_EXCEEDED
    COMPILATION_MAX_NODE_COUNT_EXCEEDED
    COMPILATION_INTERNAL_POINTER_EXCEED_LIMIT

Max caller index exceeded Exception
    COMPILATION_MAX_CALLER_INDEX_EXCEEDED

Insufficiently Aggressive Compilation Exception
    COMPILATION_NEEDED_AT_HIGHER_LEVEL
    
Recoverable Code Cache Error Exception
    COMPILATION_ALL_CODE_CACHES_RESERVED
    COMPILATION_ILLEGAL_CODE_CACHE_SWITCH

Code Cache Error Exception
    COMPILATION_NULL_SUBSTITUTE_CODE_CACHE
    COMPILATION_CODE_MEMORY_EXHAUSTED

GCR Patch Failure Exception
    COMPILATION_GCRPATCH_FAILURE

Compilation Exception
    COMPILATION_HEAP_LIMIT_EXCEEDED
    COMPILATION_METADATA_CREATION_FAILURE
    COMPILATION_OUT_OF_MEMORY_RELOCATION_DATA
    COMPILATION_LAMBDA_ENFORCE_SCORCHING
    COMPILATION_CHTABLE_COMMIT_FAILURE
    COMPILATION_CLASS_CHAIN_PERSISTANCE_FAILURE
    COMPILATION_LOW_PHYSICAL_MEMORY
    COMPILATION_INTERRUPTED


We have two options in terms of what to do with these: 1) we catch the specific exceptions and return a distinct error code per exception, resulting in some of these error codes being merged and recast as return codes, or 2) we get rid of these error codes altogether.

@lmaisons @mstoodle @0xdaryl What do you guys think?

**Comment by mpirvu** [comment]
I see no reason to keep the return codes. They only apply to a very small number of cases and because the vast majority of compilations are expected to succeed I am not concerned about the overhead of replacing a "return errCode" with "throw someException".
