### ISSUE TITLE
gencon_GC_config.xml fvtest fails when OMR is compiled with GCC 6.2

### ISSUE THREAD

**Issue by dsouzai** [eclipse/omr#385]
Compiling OMR with `gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)` results in

```
[       OK ] configFile/GCConfigTest.test/1 (53 ms)
[ RUN      ] configFile/GCConfigTest.test/2
Configuration File: fvtest/gctest/configuration/gencon_GC_config.xml
** ASSERTION FAILED ** j9mm.107 at MemorySubSpaceGeneric.cpp:757 Assert_MM_true_internal((false && ((__null == extensions->heapBaseForBarrierRange0) && (0 == extensions->heapSizeForBarrierRange0))))
omrgctest: MemorySubSpaceGeneric.cpp:757: void MM_MemorySubSpaceGeneric::addTenureRange(MM_EnvironmentBase*, uintptr_t, void*, void*): Assertion `false && ((__null == extensions->heapBaseForBarrierRange0) && (0 == extensions->heapSizeForBarrierRange0))' failed.
fvtest/omrtest.mk:45: recipe for target 'omr_gctest' failed
make[1]: *** [omr_gctest] Aborted (core dumped)
```

whereas it passes when compiling with `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4)`.

**Comment by Varun-garg** [comment]
I am having same issue with GCC 6.3 on Arch Linux. All tests run fine on a remote Ubuntu system with GCC 5.4

I thought it was because in GCC 6, they switched default c++ mode from -`std=gnu++98` to -`std=gnu++14` .

I tried to change it to gnu++98, but due to c++11 functionality (OMRDataTypes.hpp:260:4: error: identifier ‘static_assert’ is a keyword in C++11) I ended up trying c++11 option

    make -f run_configure.mk CXXFLAGS="-std=gnu++11" SPEC=linux_x86-64 OMRGLUE=./example/glue

It compiled fine, but still giving same errors. Manually editing fvtest/omrtest.mk and inserting `CXXFLAGS := -std=gnu++11` is also not solving the issue

```
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from configFile/GCConfigTest
[ RUN      ] configFile/GCConfigTest.test/0
[       OK ] configFile/GCConfigTest.test/0 (141 ms)
[ RUN      ] configFile/GCConfigTest.test/1
[       OK ] configFile/GCConfigTest.test/1 (59 ms)
[ RUN      ] configFile/GCConfigTest.test/2
** ASSERTION FAILED ** j9mm.107 at MemorySubSpaceGeneric.cpp:757 Assert_MM_true_internal((false && ((__null == extensions->heapBaseForBarrierRange0) && (0 == extensions->heapSizeForBarrierRange0))))
omrgctest: MemorySubSpaceGeneric.cpp:757: void MM_MemorySubSpaceGeneric::addTenureRange(MM_EnvironmentBase*, uintptr_t, void*, void*): Assertion `false && ((__null == extensions->heapBaseForBarrierRange0) && (0 == extensions->heapSizeForBarrierRange0))' failed.
Aborted (core dumped)
```
```

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc-multilib/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.3.1 20170306 (GCC) 
```

**Comment by ktbriggs** [comment]
Might be helpful to get a stack trace on this. To trap and assertion in gdb, put a breakpoint at trcengine.c line 1232 (in method doTriggerActionAssertDumpEvent()). To run gctest from the command line with gdb, cd to omr directory and run `gdb --args ./omrgctest -logLevel=verbose -keepVerboseLog -configListFile=fvtest/gctest/configuration/fvConfigListFile.txt &> omr-385.txt`. 

If the assertion is triggered, get a stack trace and locals from asserting thread please and save this along with redirected test output (omr-385.txt) and verbosegc log. Too bad we can't add attachments to Github issues :( (or can we)?

**Comment by Varun-garg** [comment]
Hi @ktbriggs , I couldn't find rcengine.c or doTriggerActionAssertDumpEvent()) in OMR code.
I have attached output containing verbose log and stacktrace after crash is encountered.

Attachment uploaded fine 😃. 

[omr-385.txt](https://github.com/eclipse/omr/files/1015133/omr-385.txt)

**Comment by ktbriggs** [comment]
@Varun-garg thanks the stack trace in the attachment is what I was looking for. My previous comments related to a different harness -  sorry for the confusion.

**Comment by ktbriggs** [comment]
One more question -- is this failing 100% when compiled with gcc 6.2+ and run? Or is it intermittent?

**Comment by Varun-garg** [comment]
@ktbriggs no problem, for me it always fails at that point when compiled with gcc 6.2+

**Comment by ktbriggs** [comment]
@dsouzai @Varun-garg have you recently switched to gcc 6.2+ to notice this? If you have been compiling with gcc 62+ for a while it would be helpful to know sha for most recent commit that passed gc test after compiling with gcc 6.2+.

**Comment by ktbriggs** [comment]
@amicic you might be interested in this. Assertion relates to tenure heap range.

**Comment by Varun-garg** [comment]
@ktbriggs nope, gcc 6.2 has been for a while for arch linux users (before I started working with OMR). 
BTW they have moved gcc 7 to testing repo so we can expect different results soon.

**Comment by ktbriggs** [comment]
Thanks for the update @Varun-garg. So you have been using 6.2 all along and then this pops up. Can you give me an idea of when this failure was first noticed? I'm trying to locate point in omr commit timeline when this started happening. If gcc version was constant then there must have been a code change to trigger this.

**Comment by mgaudet** [comment]
(Could be git-bisect-able)

**Comment by youngar** [comment]
This has been a problem for a long time, before Varun was involved with the OMR project.  For me, this assertion does not happen when optimizations are disabled, although that may be just a coincidence.

For me, the assertion happens on the first call to `MM_MemorySubSpaceGeneric::addTenureRange()` on the *second test*.  I think something is not getting cleaned up / reset properly between tests. The `MMSSGeneric::_extensions` field points to the same GCExtensions object between the tests, and the value of `heapBaseForBarrierRange0` does not reset between the tests.

```
Program received signal SIGABRT, Aborted.
0x00007ffff6ba1a10 in raise () from /usr/lib/libc.so.6

(gdb) p _extensions->heapBaseForBarrierRange0 
$4 = (void *) 0x7fffd6430000
(gdb) p _extensions->heapSizeForBarrierRange0 
$5 = 23003136
```

**Comment by Varun-garg** [comment]
@ktbriggs as @youngar said, I am new to the OMR project and can't help you in finding origin of this bug. Last time I was facing a [issue](https://github.com/eclipse/omr/issues/305)  compiling using run_configure.mk script but now (pulled source code few days back) it builds fine.
