### ISSUE TITLE
Flatten il subdirectory

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#3913]
The `symbol/` subdirectory under the `compiler/il` directory was originally created to minimize the clutter with all the symbol extensible classes.  However, after living with the experience for a couple of years now I'm not convinced it's providing much value from the organizational perspective.  It also makes the Symbol extensible classes unique in that they get their own directory, and you have to add an additional "symbol" path to every `#include` directive.

Move the contents of `il/symbol` into the `il` directory.  Fix up include paths and remove the `symbol` subdirectory.  Downstream projects such as OpenJ9 will need to change as well, so consider staging the implementation of this such that you keep the old versions around that simply redirect (i.e., `#include`) the new version.

Original discussion question:

~~What do people think about flattening the `il/` directory and moving the 24 files in `symbol/` up into `il/` (knowing full well that there will be a bit of a dance with downstream projects if we decide to move them)?~~

~~If no reasonable objections, I'll create an issue for someone to complete the work.~~

**Comment by fjeremic** [comment]
Seems reasonable to me. We should check if we have any other similar type work so we can batch it together given the churn it will cause for downstream projects.

**Comment by 0xdaryl** [comment]
`compiler/z/codegen/snippet` is another candidate.

**Comment by fjeremic** [comment]
> `compiler/z/codegen/snippet` is another candidate.

That one was created recently after a realization that our snippets are currently a mess and scattered randomly across various files. We have an upwards of 12 snippets. Perhaps they can live together though.

**Comment by Leonardo2718** [comment]
I'm ok with flattening the `il` directory.

**Comment by 0xdaryl** [comment]
OK, I modified the purpose of this issue to track the flattening of the `il` directory.
