### ISSUE TITLE
Remove remnants of node aliasing

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#3948]
Node aliasing is deprecated but there are still some remnants of it left in the code, namely in 
```
il/OMRSymbolReference.hpp
il/AliasSetInterface.hpp
```
grep the code for `NodeAlias` and remove the structures and template definitions.

**Comment by wbh123456** [comment]
Going to take this one

**Comment by 0xdaryl** [comment]
This isn't quite as straightforward as what I thought it was.  While it is true that "node aliasing" is deprecated and largely removed, these last remnants have their tentacles reaching into a few more places than I though and hence will be more difficult to remove.  I'm removing the Beginner label.

**Comment by wbh123456** [comment]
`OMR::Node` has 2 functions `mayUse()`  and ` mayKill(bool gcSafe)` that use objects of class `TR_NodeAliasSetInterface`. Thus, trying to just remove the `Node Alias` would cause problem.

Going to  first migrate relevant functions from the class `TR_NodeAliasSetInterface` into `TR_SymAliasSetInterface` and then comment out the `Node Alias` filed. After this, will try to refactor and simplify `TR_SymAliasSetInterface` .

**Comment by wbh123456** [comment]
**Aliasing Structure:**
The class `TR_AliasSetInterface` has two child class : `TR_SymAliasSetInterface` and `TR_NodeAliasSetInterface`. The two sub-classes are very similar: the former class treats `Symbol Alias` directly while the latter class extracts `Symbol Alias` from a `Node` object and performs operations dependent on that `Node` object. It is obvious to find out that the `TR_NodeAliasSetInterface` class is not actually `Node Aliasing`, it is really just `Symbol Aliasing` initialized from a `Node` object.

**Proposed Change:**
In the PR #3965, I migrated `TR_NodeAliasSetInterface` into `TR_SymAliasSetInterface`. Now the class `TR_AliasSetInterface` has only one child class:  `TR_SymAliasSetInterface` . This new child class has 2  constructors: one to initialize it from a `Node` object, the other to initialize it from `SymRef` directly.

`Node::mayUse()` and `Node::mayKill()` now calls  the new `TR_SymAliasSetInterface` class instead,  from the `Node` object with the new constructor.
