### ISSUE TITLE
Remove FlattenRegisterPairs from OMRRegisterPair

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#3968]
The `FlattenRegisterPairs` function is deprecated and not used anywhere in OMR or known downstream projects.  Remove it.

**Comment by agarwalrounak** [comment]
@0xdaryl There is a reference to `FlattenRegisterPairs` in [OMRRegister.hpp](https://github.com/eclipse/omr/blob/master/compiler/z/codegen/OMRRegister.hpp) too. Should I remove that too?
