### ISSUE TITLE
Rename floating-point Condition Code 

### ISSUE THREAD

**Issue by zhouyanggao** [eclipse/omr#401]
Floating-point and fixed-point have the same condition code. Instead of using name `PPCFloatingPointConditionCode`, we can use `PPCConditionRegisterConditionCode`. So we can use this enum for both floating-point and fixed-point instructions.

**Comment by zhouyanggao** [comment]
I use cr_LT instead of CR_LT because I hit an xlc bug on AIX when using capital letters..

**Comment by fjeremic** [comment]
> I use cr_LT instead of CR_LT because I hit an xlc bug on AIX when using capital letters..

Can you link the relevant code when you get a chance?

**Comment by zhouyanggao** [comment]
>> I use cr_LT instead of CR_LT because I hit an xlc bug on AIX when using capital letters..

>Can you link the relevant code when you get a chance?

In `compiler/p/codegen/OMRRealRegister.hpp`:
```cpp
typedef enum {
      cr_LT = 0x0, // less than
      cr_GT = 0x1, // greater than
      cr_EQ = 0x2, // equal
      cr_SO = 0x3  // summary overflow
   } PPCConditionRegisterConditionCode;
```
If I use CR_LT, CR_GT, CR_EQ, CR_SO, I get compilation error `The text "0x80000000" is unexpected.` on AIX. On Linux, it's fine.

**Comment by Krovatkin** [comment]
@zhouyanggao im curious, why do you guys use `typedef`. `OMRRealRegister.hpp` looks like a C++ header? :-)

**Comment by ymanton** [comment]
> If I use CR_LT, CR_GT, CR_EQ, CR_SO, I get compilation error The text "0x80000000" is unexpected. on AIX. On Linux, it's fine.

This is because on AIX `CR_LT` is defined as `0x80000000` in `/usr/include/sys/machine.h`, which is a shame. You can use a scoped enum instead and remove the `CR_` prefix, so your expressions would contain `<enum-name>::LT` and so on. (If you do that don't use a long name that nobody wants to type.)
