### ISSUE TITLE
jitbuildertest should not have public sources

### ISSUE THREAD

**Issue by rwy0717** [eclipse/omr#4069]
Jitbuildertest is an executable. Normally an executable can't be linked against, so it would only have private includes and private sources. However, On line 47 in the fvtest/jitbuildertest/CMakeLists.txt, we add public sources to jitbuildertest. Because these sources are relative (which is normal for private sources, but uncommon for interface/public sources), cmake emits a warning, we should use absolute source paths. The fix, I believe, is to use private sources only.

The warning:
```
CMake Warning (dev) at fvtest/jitbuildertest/CMakeLists.txt:47 (target_sources):
  Policy CMP0076 is not set: target_sources() command converts relative paths
  to absolute.  Run "cmake --help-policy CMP0076" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
```

Policy documentation:
```
$ cmake --help-policy CMP0076
CMP0076
-------

The ``target_sources()`` command converts relative paths to absolute.

In CMake 3.13 and above, the ``target_sources()`` command now converts
relative source file paths to absolute paths in the following cases:

* Source files are added to the target's ``INTERFACE_SOURCES``
  property.
* The target's ``SOURCE_DIR`` property differs from
  ``CMAKE_CURRENT_SOURCE_DIR``.

A path that begins with a generator expression is always left unmodified.

This policy provides compatibility with projects that have not been updated
to expect this behavior.  The ``OLD`` behavior for this policy is to leave
all relative source file paths unmodified.  The ``NEW`` behavior of this
policy is to convert relative paths to absolute according to above rules.

This policy was introduced in CMake version 3.13.  CMake version
3.14.4 warns when the policy is not set and uses ``OLD`` behavior.
Use the ``cmake_policy()`` command to set it to ``OLD`` or ``NEW``
explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.
```

fvtest/jitbuildertest/CMakeLists.txt:46:
```
if(NOT OMR_HOST_ARCH STREQUAL "ppc")
	target_sources(jitbuildertest PUBLIC UnsignedDivRemTest.cpp)
endif()
```

**Comment by oneturkmen** [comment]
@rwy0717 hmm I only get the other type of warning:

> CMake Warning (dev) in CMakeLists.txt:
>  No cmake_minimum_required command is present.  A line of code such as
> 
>    cmake_minimum_required(VERSION 3.10)
> 
>   should be added at the top of the file.  The version specified may be lower
>   if you wish to support older CMake versions for this project.  For more
>   information run "cmake --help-policy CMP0000".

Could it happen that the warning depends on the CMake version one has locally?

**Comment by rwy0717** [comment]
cmake should be run from the root of omr, it can't be run in a subdirectory.

**Comment by rwy0717** [comment]
It looks like you're using cmake 3.10, but the warning wasn't introduced until 3.13, so you'll need to upgrade to a newer version of cmake before you're able to reproduce.

**Comment by oneturkmen** [comment]
@rwy0717 I upgraded cmake to `3.15.0`. As you suggested, I tried building from the root folder, yet I don't get any warning related to `CMP0076` (i.e. with `cmake -Wdev`).

Even if I enable `--trace` mode, I only get one warning (`CMP0065`) from the `fvtest` directory:

> CMake Warning (dev) in ddr/test/CMakeLists.txt:
>  Policy CMP0065 is not set: Do not add flags to export symbols from
> executables without the ENABLE_EXPORTS target property.  Run "cmake
> --help-policy CMP0065" for policy details.  Use the cmake_policy command to
> set the policy and suppress this warning.

**Comment by oneturkmen** [comment]
@rwy0717 what version are you using? 

I also checked the changelog, I did not seem to find anything related to `CMP0076`.

**Comment by rwy0717** [comment]
What is the exact cmake command you're using?

**Comment by oneturkmen** [comment]
I tried both `cmake -Wdev ..` and `cmake -Wdev --trace ..` (the commands for building the entire project).

**Comment by rwy0717** [comment]
Try adding `-C../cmake/caches/Travis.cmake`

**Comment by oneturkmen** [comment]
Nope, still nothing :no_mouth: 

```
loading initial cache file ../cmake/caches/Travis.cmake
-- Starting with CMake version 3.15.0
-- OMR: The CPU architecture is x86
-- OMR: The OS is linux
-- OMR: The tool configuration is gnu
-- OMR: The target data size is 64
-- OMR: trace root is '~/Desktop/projects/omr/build'
-- Configuring done
-- Generating done
-- Build files have been written to: ~/Desktop/projects/omr/build
```

**Comment by oneturkmen** [comment]
Ok, now I got it. I had to delete entire `/build` folder and recompile again, both with `-Wdev` and initial cache file from `../cmake/caches/Travis.cmake`. Will push changes in a bit.
