### ISSUE TITLE
Generalize string encoding constants

### ISSUE THREAD

**Issue by pdbain-ibm** [eclipse/omr#41]
J9STR_CODE_PLATFORM indicates that the string encoding is the "platform" encoding.
There are cases where OMR converts the result of system calls, e.g. getenv, to another encoding,
e.g. EBCDIOC->Latin-1 on z/OS and Wide->UTF-8 on Windows.
This change splits J9STR_CODE_PLATFORM into two constants:
J9STR_CODE_PLATFORM_RAW: the true encoding used by the operating system in the current locale
J9STR_CODE_PLATFORM_OMR_INTERNAL: the encoding taking into account implicit conversions by OMR

**Comment by charliegracie** [comment]
Closed via #54
