### ISSUE TITLE
Double decrement of node reference count in x86 integer compare analyser

### ISSUE THREAD

**Issue by mthom** [eclipse/omr#4121]
The following assert fails when I compile a method using JITBuilder:

```
TR_ASSERT(_referenceCount > 0 || self()->getOpCode().isTreeTop(), "Assertion failure : %s (0x%p)", self()->getOpCode().getName(), this);
```

The assert is contained inside `OMR::Node::decReferenceCount()`, which is called from `TR_X86CompareAnalyser::integerCompareAnalyser`. `_referenceCount` is 0 when the assert fails.

**Comment by fjeremic** [comment]
Do you have a trace log of the method you were compiling?

**Comment by mthom** [comment]
@fjeremic yes, I've posted to a gist here:

https://gist.github.com/mthom/40d2f27bc190db7c5d61f9d7b637cb12
