### ISSUE TITLE
AArch64: length parameter needed for MemoryReference?

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#4137]
MemoryReference constructors take the length parameter, but it is used from nowhere on AArch64.
Reconsider whether the parameter is necessary or not.

**Comment by 0xdaryl** [comment]
At this point, I'd say no.  It seems to have originated from Power, and it appears to exist only to enable one particular peephole optimization.  It might be a bigger hammer than is needed.  I don't think we need this in AArch64 until we have a problem that requires it as a solution.

**Comment by knn-k** [comment]
Related PRs: #5348, eclipse/openj9#10023
