### ISSUE TITLE
IlBuilder StoreAt ignores the data type

### ISSUE THREAD

**Issue by amankumar1** [eclipse/omr#414]
The methods `IlBuilder::StoreAt` and `IlBuilder::VectorStoreAt` ignore the data type parameter passed into them. This is the data type the value is supposed to be stored as. Instead, they store the value as the data type of whatever is accessed.

This can create problems like this one:

```
StoreAt(pInt8,
   IndexAt(pInt8,
      Load("line"),
      Load("x")),
   Load("bits"));
```

`bits` here is an Int32. We want to store `bits` as an Int8 at a particular index in line. However, since the data type passed into `StoreAt` is ignored, `bits` is stored as a 32 bit int.

When `bits` is being written to the last three bytes (indices) in `buffer`, we are writing to memory outside the scope of buffer and this can cause problems.

**Comment by fjeremic** [comment]
@amankumar1 Could you please document (using a properly formatted Doxygen function definition) the `StoreAt` API as having the behavior you described. I.e. the store generated will be of the same datatype as the load.

**Comment by mstoodle** [comment]
Technically, StoreAt only takes that type parameter to make it symmetric with LoatAt. We should probably remove that parameter.

The proper fix is to ConvertTo(Int8, Load("bits")) and feed that to the store (assuming it figures out the right conversion opcode).

**Comment by mstoodle** [comment]
You have contributed the right fix. The other fix that we should do is to remove the type parameter. I put it there to keep it symmetric with LoadAt, but it's probably more confusing than it is helpful.

**Comment by amankumar1** [comment]
@mstoodle Created PR #433 to remove the data type parameter from `StoreAt`.

**Comment by mstoodle** [comment]
Given PR #433 has been merged, I'll assume this issue can be closed. If I'm mistaken, please reopen and explain my mistake.
