### ISSUE TITLE
Slack invite link in README is inactive

### ISSUE THREAD

**Issue by smlambert** [eclipse/omr#4358]
I would like to join the OMR Slack workspace and become more active in this project.  There are no invite links to the workspace from the webpage, and the one in the README appears to no longer active.  

These are unnecessary barriers to entry, which I may try to fix as I attempt to become more active in this project.

[Slack workspace link](https://join.slack.com/t/eclipse-omr/shared_invite/enQtMzg2ODIwODc4MTAyLTk4ZjJjNTZlZmMyMGRmYTczOTkzMGJiNTQ4NTA3YTA1NGU4MmJjNWI4NTBjOGNkNmNjMWQ3MmFmYjA4OGZjZjM) from line 140 of the README.md file says it is no longer active

<img width="1161" alt="Screen Shot 2019-09-24 at 10 15 13 PM" src="https://user-images.githubusercontent.com/2836948/65563976-613bdb80-df19-11e9-9304-17b5b2f03d7c.png">

**Comment by 0xdaryl** [comment]
Thanks for pointing that out @smlambert.

@mstoodle or @charliegracie, as admins and owners I believe only one of you can create a new workspace invitation link.

**Comment by charliegracie** [comment]
hmm strange someone else just joined today via the invite.  I wonder if the link is incorrect in the Readme.  Let me see if I can get the right link

**Comment by charliegracie** [comment]
I have created a new [link](https://join.slack.com/t/eclipse-omr/shared_invite/enQtMzg2ODIwODc4MTAyLWFiMzZkNmNhODc5OTM0MjgwZDdjNzg5YTg5NzM0ZmEzNTIyMGViMjk1YjYwNzczYjYwODc4YTM5MDk0NjIxMjg) but the old one should have worked as I believe I am the only who could deactivate the old one since I created it. Anyway, let me know if the new link works

**Comment by smlambert** [comment]
new one did work, thanks!

**Comment by smlambert** [comment]
PR to update link in README - https://github.com/eclipse/omr/pull/4364

Note that now that I have joined the workspace, the existing link in the README takes me to the workspace, but before I joined it showed as inactive.
