### ISSUE TITLE
Deprecate `getJitMethodEntryAlignmentThreshold`

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#4373]
As part of a https://github.com/eclipse/omr/pull/4314#pullrequestreview-293463200 comment by @0xdaryl we propose to deprecate the `getJitMethodEntryAlignmentThreshold` API. As discussed in the review:

> Ultimately, aligning the entry point of a method on a particular boundary is a performance optimization. However, the use of a threshold introduces non-determinancy (and arguably randomness run-to-run) into any performance benefit. Whether or not a particular method is aligned depends on the methods that have been compiled before it. It also doesn't take into account the "importance" of any particular method. For instance, a method invoked millions of times is better suited to be aligned than one only invoked a few times, but it could be rejected for alignment because it exceeds the threshold. Unless you align every method boundary I don't know how you would achieve consistent performance.

We need to investigate the performance impact of removing this threshold on Z, as it is currently the only codegen which makes use of it. If it is determined that not using a threshold does not impact performance we can proceed to deprecate the API.

**Comment by 0xdaryl** [comment]
My preference is to eliminate it, or enable it only with an "optimize for space" option.  But leaning more strongly toward eliminating it outright.

**Comment by fjeremic** [comment]
Totally forgot about this one. Removing stale label but not adding to the backlog since this is something I want to get done very soon.
