### ISSUE TITLE
TR::assersion

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse/omr#4422]
https://github.com/eclipse/omr/blob/0cededa77eb2bc0e54ad27520df748747819272b/compiler/infra/Assert.cpp#L151

**Comment by Leonardo2718** [comment]
@Akira1Saitoh is this supposed to be replaced by #4423? If so, can we close this issue?

**Comment by Akira1Saitoh** [comment]
Sorry, it seems I accidentally hit enter key. This issue can be closed.
