### ISSUE TITLE
ddrgen poor performance on OSX

### ISSUE THREAD

**Issue by mikezhang1234567890** [eclipse/omr#4498]
On a Macbook Pro with 8 cores, ddrgen takes ~6min to run on the OpenJ9, while on a similar Linux machine, it takes less than a minute.

From running ddrgen under the Xcode Instruments time profiler:
![Screen Shot 2019-10-22 at 2 09 12 PM](https://user-images.githubusercontent.com/32070971/67322489-13e26800-f4df-11e9-9487-5ca52f0699e6.png)
We can see that most of the time is spent in `getSourceList` and `dwarf_srcfiles`. This suggests that our implementation of the libdwarf API has some issues as ddrgen does not spend nearly as much time in this function.
If this is an issue with our libdwarf implementation, we may also want to look at the AIX implementation, since it shares code with the OSX version.

**Comment by keithc-ca** [comment]
FYI @keithc-ca
