### ISSUE TITLE
tril_compiler fails with a parse error when using stdin

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#4524]
In the past, it was possible to use the `tril_compiler` executable to compile tril trees from stdin by not specifying an input file. Recently, this appears to have stopped working. Instead, when running `tril_compiler` without an input file, it simply outputs `Parse error`. This functionality appears to have been broken by the parser rewrite in 393044a773f06033afaf1f77bbc7be0fee3f3857 (#4345).

**Comment by fjeremic** [comment]
@Yuehan-Lin @Leonardo2718 FYI. Is this something we should prioritize fixing?
