### ISSUE TITLE
All commits must be trackable to an Issue

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#46]
For us to maintain good release changelogs, and be able to identify the release where an Issue gets fixed, we must be able to easily find (1) the Issue that corresponds to a commit; (2) all the commits needed to fix an Issue.

I propose updating the contribution guidelines to include:
- Every pull request must be associated with an Issue.
- Every commit comment must clearly reference an Issue.
- Provide a template for commit comments that makes it easy for us to find the issues in the git log.

**Comment by charliegracie** [comment]
I think this is a good thing to do.  I would suggest we ask that commit comments follow a format similar to this:

Simple Description
Detailed information if required

Issue: #<issue>
Signed-off-by: First Last <email>

**Comment by DanHeidinga** [comment]
Overall, I agree with this approach but expect that trivial changes (spelling fixes, etc) can be done without an issue.

Doing a bit of reading, in particular [1], indicates:

> Unless you are making a rather minor change, it is generally a good idea to file an issue on the appropriate bug tracker, explaining your idea before writing code or submitting a PR, especially when introducing new features.

which is the kind of wording I think we should adopt.
[1] https://contribute.jquery.org/commits-and-pull-requests/

**Comment by alin00** [comment]
It sounds like we don't want to use the github feature of closing issues via commit comment, right?

It's helpful to put the Issue # in the first line of the commit comment so that you can get a quick overview using "git log --oneline".

I suggest tweaking the comment template to this:

```
Issue #nn Simple Description
Detailed information if required

Signed-off-by: First Last <email>
```

**Comment by alin00** [comment]
I don't mind not having an issue for truly trivial patches, but I think any multi-commit piece of work should be tied together by having an issue number which is referenced in the commit comments.

I don't care whether we use an issue number or pull request number, but a pull request number doesn't seem to work well since it doesn't exist until after you have made a bunch of commits and created the pull request. You would have to edit every commit on the pull request branch to add in the pull request number.

**Comment by mstoodle** [comment]
How about:

    #n Short, simple summary

    Detailed information if required

    Signed-off-by: First Last <email>


That's simple, puts the issue number (I'll make sure its described as the Issue number and should not be the pull request number) into every commit title. I suppose the recommendation would be to follow the same form in the pull request, which at least makes it easy to describe.

If no additional concerns, I'll commit this change tomorrow.

**Comment by alin00** [comment]
Looks good to me.

**Comment by charliegracie** [comment]
+1

**Comment by mstoodle** [comment]
Amusing: # starts a comment so the first line cannot start with that. D'oh!

I recommend we give up on a "rigid" positioning of the issue text and just say the title has to have #N in it somewhere.

**Comment by DanHeidinga** [comment]
+1

**Comment by alin00** [comment]
As long as we can write tooling that finds it (and doesn't get too many false hits), fine with me.

**Comment by charliegracie** [comment]
Hmmm I made some commits today that started with # and it appears in the text for the commit.

**Comment by charliegracie** [comment]
If we are not rigid then people will not do it and we will be constantly asking them to change their commit comments.  If we are saying the Issue # has to be there then we need a format for it.

**Comment by mstoodle** [comment]
The suggestion was to specify that "#n" needs to appear somewhere in the message. That's enough for github to find the link. 

I see your commits on #64, Charlie. How did you do that? When I tried it, git commit failed saying my commit message was empty (and it actually was :) ). The only difference I see is that your commits also had detailed comments whereas mine did not. No idea why it didn't treat your title line as a comment.

Weird. But your commit message still fits the template as suggested :) .

**Comment by alin00** [comment]
I agree with @charliegracie on this:
> If we are not rigid then people will not do it ...

**Comment by mstoodle** [comment]
The rigidity comment was only about the positioning...

**Comment by alin00** [comment]
http://stackoverflow.com/questions/2788092/start-a-git-commit-message-with-a-hashmark

> The rigidity comment was only about the positioning...

Understood. I prefer to have a clear template with clear positioning. I prefer going back to one of the older proposals of starting the abstract with "Issue #nn" or "Fix #nn". However, I'm willing to compromise on positioning and prefix if everyone else prefers otherwise.

My hard requirements are:
1. All commits have the same comment template, with no conditional parts that require judgment to fill in.
2. It is easy to find all commits for a particular issue number, and construct a short summary of the commits. e.g. using ```git log --grep='#25' --oneline```

**Comment by alin00** [comment]
It's quite possible for a commit comment to refer to other issue numbers, so I prefer having a keyword to identify the issue most relevant.

**Comment by alin00** [comment]
We've settled on Mark's most recent proposal.
