### ISSUE TITLE
Merge MM_Dispatcher and MM_ParallelDispatcher

### ISSUE THREAD

**Issue by amicic** [eclipse/omr#4611]
At least in OpenJ9, there is no value of keeping the base Dispatcher (all GC policies instantiate Parallel one).  On the other hand, from time-to-time, it is headache to introduce new logic into Parallel Dispatcher, due to this separation.

Perhaps, in theory, it would be useful for strictly single-threaded GCs. Any objections from general OMR point of view for this merge?

Copy of short discussion from Slack/OMR/gc:

aryoung 3:17 PM
I think they should be merged

mstoodle Today at 12:01 PM
presumably the proposed new merged MM_Dispatcher base class could still operate in a single-threaded mode (possibly with some extra overhead) ?

Aleks  1 hour ago
Correct. I don't think that any potential extra overhead of ParallelDispatcher (forced to use one thread) is even measurable.

mstoodle  1 hour ago
then sounds reasonable to me. @charliegracie any opinion?

charliegracie  1 hour ago
Thumbs up from me!

**Comment by mstoodle** [comment]
Thanks for opening the issue @amicic
