### ISSUE TITLE
Remove ununsed field lockingWord

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#463]
Unused field lockingWord exists in the following structures:
i) struct J9ThreadMonitor: omrthread_generated.h and omrthread.c 
ii) struct J9GCSpinlock: gcspinlock.h  and gcspinlock.cpp

It is also referred in comments within AtomicOperations.hpp and threadhelpers.cpp

**Comment by charliegracie** [comment]
Resolved via #464
