### ISSUE TITLE
Non UTF-8 error message needs to be converted to UTF-8 in order to be correctly displayed on AIX

### ISSUE THREAD

**Issue by hangshao0** [eclipse/omr#470]
We assume the error message is UTF-8. When the platform encoding is not UTF-8, the message becomes distorted when printed out.

**Comment by charliegracie** [comment]
Can you provide more details please?

**Comment by hangshao0** [comment]
When printing our the error message, omrnls_printf() finally calls into 
file_write_using_iconv() {
...
converter = iconv_get(portLibrary, J9FILETEXT_ICONV_DESCRIPTOR, nl_langinfo(CODESET), "UTF-8");
...
}
where we convert buf (error message) from UTF-8 to nl_langinfo(CODESET) so that is can be correctly displayed. 

The buf usually consists of NLS message (UTF-8) + platform error string returned by strerror()(see errorMessage() in port/unix/omrerrorhelpers.c). 
The encoding of platform error string returned by strerror() is determined by LC_MESSAGES in the current locale setting which might not be UTF-8. So buf passed to file_write_using_iconv() can be partially UTF-8 and partially non UTF-8, which makes the platform error string distorted when printed out. 

Non UTF-8 platform error string should be converted to UTF-8.
