### ISSUE TITLE
Simplify OMR::TreeTop::join() by removing unnecessary null check of self()

### ISSUE THREAD

**Issue by Leonardo2718** [eclipse/omr#4835]
`OMR::TreeTop::join()` checks if `self()` is `NULL` [1], which is odd because it never makes sense to call a member function on a NULL object. Such calls are undefined behaviour so the compiler likely removes the check anyways (`self()` is very likely to get inlined).

The code then, therefore, be simplified by just removing the check.

[1] https://github.com/eclipse/omr/blob/fbd89b99e4103a5e7d1a8b02b01d7e36b3c81055/compiler/il/OMRTreeTop_inlines.hpp#L80-L87

**Comment by tuckermiles70** [comment]
@Leonardo2718 I'd be glad to fix this for you!
