### ISSUE TITLE
Cleanup duplicated code created as part of the PR eclipse/omr#4578

### ISSUE THREAD

**Issue by alvee-unb** [eclipse/omr#4847]
As part of the issue eclipse/omr#681, there are some duplicated codes introduced by the PR eclipse/omr#4578 . They need to be cleaned up once the subsequent PR eclipse/openj9 #7797 lands.

Example: There are both `getSupportsSelect` and `getSupportsTernary`.

**Comment by 0xdaryl** [comment]
Done.  Closing.
