### ISSUE TITLE
AArch64: Improve code generation for loading signed byte/short

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#4856]
The AArch64 JIT generates code like this for a `bloadi-b2i` sequence:
```
ldrsbimmx w0, [w18, 0]
sxtbw w0, w0
```
The second instruction is not needed because `ldrsbimmx` (Load Register Signed Byte) does the sign-extension when loading a signed byte from memory.

The same is said for a `sloadi-s2i` sequence.  The JIT generates `ldrshimmx` (Load Register Signed Halfword) followed by redundant `sxthw`.

**Comment by knn-k** [comment]
`b2iEvaluator()` for p takes care of such cases, for example.
https://github.com/eclipse/omr/blob/d74c6364bbb14191518d369d400301b7212c879b/compiler/p/codegen/UnaryEvaluator.cpp#L240

**Comment by knn-k** [comment]
There is a similar problem in zero-extension for compressedRefs.  #5114

**Comment by sahithiponangi** [comment]
@knn-k I'm seeing a redundant `uxthx`. I'm initializing `int` to generate `ldrshimmx`. Please let me know how to generate Load Register Signed Halfword followed by redundant `sxthw`.

**Comment by knn-k** [comment]
@sahithiponangi 
An example Java program for the `sloadi-s2i` sequence:
```
public class ShortLoadTest {
        static short s[];
        static short getShort(int n) { return s[n]; }
        public static void main(String[] args) {
                s = new short[] { 100, 101, 102 };
                System.out.println(getShort(args.length));
        }
}
```

Run it as `java -Xjit:limit=getShort,count=0 ShortLoadTest`, then you will see the following `ldrshimmx-sxthw` sequence in the generated code:

```
    0xffff96dbf0a4 0000004c [    0xffff95d52d10] 79800240 4     ldrshimmx       w0, [w18, 0]            # SymRef  <array-shadow>[#187  Shadow] [flags 0x80000602 0x0 ]
    0xffff96dbf0a8 00000050 [    0xffff95d52da0] 13003c00 5     sxthw   w0, w0
```

**Comment by sahithiponangi** [comment]
@knn-k For short, on a straight build, I'm seeing `uxthx`  after `ldrshimmx`, instead of `sxthw` as mentioned in the issue. After making a build with my changes, I'm not seeing any difference in this sequence. The test program I used is as mentioned in the issue. Please let me know what I'm missing.

**Comment by knn-k** [comment]
I have no idea.
Do you have the JIT trace file from running the test program?  I am interested in looking at the trace file for seeing the IL sequence in it.

**Comment by knn-k** [comment]
I received JIT trace files from @sahithiponangi .
The instruction sequence `ldrshimmx - uxthx` is generated for the IL sequence `sloadi - su2i`.  That is a separate topic from the scope of this PR, `sloadi - s2i`.

**Comment by knn-k** [comment]
I opened a separate issue for `sloadi - su2i` as #5343.

**Comment by knn-k** [comment]
#5061 was merged.  Closing this Issue.
