### ISSUE TITLE
Semantics of monitorEnterBarrier

### ISSUE THREAD

**Issue by Akira1Saitoh** [eclipse/omr#4986]
Currently, `monitorEnterBarrier` is `readWriteBarrier` for ppc and `readBarrier` for other platforms.
I wonder if aarch64 needs to use `readWriteBarrier` because its memory model is similar to that of ppc. But I am not sure what is the requirement of `monitorEnterBarrier`. 

Can someone shed some light on this?

https://github.com/eclipse/omr/blob/0f55d83991eda0513b3200a31bceccce666fe790/include_core/AtomicSupport.hpp#L295-L303

**Comment by Akira1Saitoh** [comment]
@knn-k @0xdaryl

**Comment by 0xdaryl** [comment]
@zl-wang : do you recall what it is with the PPC memory model that requires a RW barrier for monents?

**Comment by zl-wang** [comment]
For MonEnt, you don't need readWriteBarrier on POWER.  isync or lwsync is good enough.  lwsync is preferred for performance reason on recent processors (newer than and including POWER7).  

For IRIW (Independent read and independent write) though, readWriteBarrier (aka hwsync) is needed to stop the ensuing read/load from going ahead.  For example, accessing volatile variables.

**Comment by gacholio** [comment]
IIRC, this was added specifically for Power to break any TM transaction around this monitor.

**Comment by zl-wang** [comment]
> IRC, this was added specifically for Power to break any TM transaction around this monitor.

That is not necessary.

**Comment by gacholio** [comment]
Then let's get rid of this needless complexity.

**Comment by 0xdaryl** [comment]
So, to summarize, `monitorEnterBarrier`s should simply be replaced with `readBarrier`s as they require no specialization for any architecture.  Does that match everyone's understanding?

**Comment by gacholio** [comment]
Probably the best thing to do is to change openj9 to use readBarrier and test extensively on P.

**Comment by 0xdaryl** [comment]
I opened eclipse/openj9#9273 to track the removal of `monitorEnterBarrier`.

@Akira1Saitoh : you can probably close this issue now.

**Comment by Akira1Saitoh** [comment]
@0xdaryl Thanks!
