### ISSUE TITLE
Fix spelling of containesZeroOrOneConcreteClass API

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5037]
A new API was introduced into `ClassEnv` recently (#4959).

"containes" is spelled incorrectly and should be corrected.

**Comment by 0xdaryl** [comment]
@chrisc66

**Comment by chrisc66** [comment]
Thanks for pointing it out, change is coming soon.

**Comment by chrisc66** [comment]
@0xdaryl Could you review the OMR PR, also merge it once it is approved? Thanks.

**Comment by chrisc66** [comment]
@0xdaryl @fjeremic Thanks for reviewing and merging my PRs. This issue can be closed now since related items are merged.
