### ISSUE TITLE
Hosting for presentation artifacts

### ISSUE THREAD

**Issue by youngar** [eclipse/omr#5050]
We have many articles which we wish to use as introductory materials to OMR.  These include conference workshops, blog posts, slide decks, and recorded presentations. We currently use a variety of places to host these materials.  Unfortunately, many of these hosts are unreliable, and links get broken and artifacts go missing.  The two main places where links go out of date are the [README](https://github.com/eclipse/omr/blob/master/README.md) and [Website](https://www.eclipse.org/omr/resources/presentations.html).

I would like to propose that we create a cohesive strategy for hosting these artifacts. I think we should strive to have these files easily downloadable, and post recorded presentations to the [Eclipse OMR Youtube Channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).

Some of our current hosting solutions:
- `IBM DeveloperWorks`: Appears all articles have been deleted https://developer.ibm.com/open/omr/
- `SlideShare`: Not too bad, but no account tied to the OMR project
- `Eclipse OMR Youtube Channel`: great, but cannot download videos
- `IBM Box`: Personal IBM accounts are deleted when someone leaves IBM

There are probably some limitations to what we are allowed to host, although I am not aware of what they are.

For file hosting we could probably use any hosting service, including `git-lfs`, `dropbox`, `google drive`, or `ibm box`.

This issue is related to https://github.com/eclipse/omr/issues/352

**Comment by Leonardo2718** [comment]
We could also host the content directly on either the OMR website or the OMR blog.

**Comment by fjeremic** [comment]
> * `Eclipse OMR Youtube Channel`: great, but cannot download videos

You can easily download from Youtube via `youtube-dl`:
https://github.com/ytdl-org/youtube-dl

**Comment by youngar** [comment]
@Leonardo2718 Is the OMR blog the DeveloperWorks articles? I wouldn't mind hosting blog articles directly on the website. Also, it would be nice to start generating some web pages from the docs folder. For binary files like pdf, ppt, png, I think we should store them in git-lfs.

@fjeremic I personally think that is a big hoop for people to jump through if they want to download a video, but maybe I'm wrong? In case it wasn't clear, I was thinking we would put videos both on Youtube and a file hosting service.

**Comment by Leonardo2718** [comment]
> Is the OMR blog the DeveloperWorks articles?

No. See https://eclipse-omr.org/.

**Comment by fjeremic** [comment]
We talked about this on the call linked above. We came to an agreement that we should for now just use the [eclipse/omr.website](https://github.com/eclipse/omr.website) repo to host artifacts.

**Comment by 0xdaryl** [comment]
Closing this issue based on the above disposition.
