### ISSUE TITLE
Replace MM_ConfigurationLanguageInterface* with MM_ConfigurationDelegate

### ISSUE THREAD

**Issue by ktbriggs** [eclipse/omr#508]
This is a first step toward eliminating the MM_*LanguageInterface classes that were used to catch language-dependent factors while extracting core OMR out of J9 Java. These factors represent necessary integration points but the resulting MM_*LanguageInterface classes are fragmented and difficult to maintain. Moreover they force virtual implementations of member functions which can be a performance issue for functions that are frequently called in the runtime.

Each MM_*LanguageInterface class will be replaced with a corresponding MM_*Delegate class that will implement equivalent factors as the language interface, without forcing virtual methods. In the process the delegate methods will be rationalized and simplified wherever possible so that the delegate class interface will be easier to implement, use, and document.

For this issue, MM_ConfigurationLanguageInterface will be eliminated. A MM_ConfigurationDelegate class will replace derived MM_ConfigurationLanguageInterface* subclasses in the example/glue and in glue for other existing language implementations.

**Comment by ktbriggs** [comment]
Closed via https://github.com/eclipse/omr/pull/785

**Comment by ktbriggs** [comment]
Reopening this -- some build flag issues need to be cleaned up.

**Comment by charliegracie** [comment]
Closing as #884 has been merged
