### ISSUE TITLE
Investigate mis-spelled J9_ProjectSpecific code

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5137]
There is a spot in the Power CodeGenerator where code is guarded with a mis-spelled `J9_PROJECT_SPECIFIC` macro.  Obviously this code is disabled everywhere (including OpenJ9) because nothing defines that macro.

Investigate the implications of renaming it `J9_PROJECT_SPECIFIC`.  Better still, use this as an opportunity to sink that code into OpenJ9.

https://github.com/eclipse/omr/blob/e93965e40837b28f43d71f7667bd5584e5362087/compiler/p/codegen/UnaryEvaluator.cpp#L292

**Comment by 0xdaryl** [comment]
@gita-omr @aviansie-ben FYI

**Comment by 0xdaryl** [comment]
I'm adding the `bug` label because this likely wasn't intended and there is a bug lurking somewhere (albeit in OpenJ9).

**Comment by aviansie-ben** [comment]
I've opened #5150 to fix the spelling of the `J9_PROJECT_SPECIFIC` macro here. However, after looking at this code, it's occurred to me that this code really isn't Java-specific at all and that it and that the opcodes it deals with may be good candidates to be moved into OMR. I've opened #5149 to discuss this.
