### ISSUE TITLE
Remove dead code from SwitchAnalyzer

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5182]
While investigating a `loadaddr` issue, I discovered a dead path in `SwitchAnalyzer::addTableBlock`.  It looks to be a remnant of earlier refactoring.

https://github.com/eclipse/omr/blob/b8634d51d53c1018a8abe934a50fd35fa7df514f/compiler/optimizer/SwitchAnalyzer.cpp#L1260

`branchTableSymRef` and `branchTable` are never changed from their initial values.  Remove and fold code assuming both are `0`.

**Comment by mrSeoDavid** [comment]
@0xdaryl Hey! I love to help on this. 
Just to clarify, you would like both "branchTableSymRef" and "branchTable" to be removed from the code and their values "NULL" and "0" are replaced into wherever the variables were written?
Thanks!

**Comment by 0xdaryl** [comment]
Hi... Thanks for volunteering to help.  By "fold code" I mean simplifying the code assuming the values of those variables will always be "0".  For example, the `if (branchTable)` will always evaluate to `false` since `branchTable` is always `0`, which means the code under the `if` can be deleted because it cannot ever be executed.

**Comment by mrSeoDavid** [comment]
@0xdaryl Got it! I will make changes and create the pull request!
