### ISSUE TITLE
Deprecate getBlockIndex and getCurrentBlockIndex

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#5293]
As far as I can tell the `getBlockIndex` and `getCurrentBlockIndex` codegen APIs are not currently consumed in OMR or any known downstream projects. Setting of these block indices is also inconsistent across platforms, and in case of x86 it is non-existent. We should deprecate these APIs unless anyone has a particular use for them.

**Comment by a7ehuo** [comment]
I'll work on this one.

**Comment by a7ehuo** [comment]
It looks to me all the following APIs related to `blockIndex` are not really used [1].

@fjeremic  The only places where `getNextAvailableBlockIndex ()` is called are in `z` [2]. They don't look to me necessary. Is there any concern of removing them as part of the cleanup?  

[1]
```
setBlockIndex
getBlockIndex

setCurrentBlockIndex
getCurrentBlockIndex

setNextAvailableBlockIndex
getNextAvailableBlockIndex
incNextAvailableBlockIndex
```

[2]
https://github.com/eclipse/omr/blob/8b6089f6fcc304f1c975bba9da2ef74c45113eb2/compiler/z/codegen/S390Instruction.hpp#L470
https://github.com/eclipse/omr/blob/8b6089f6fcc304f1c975bba9da2ef74c45113eb2/compiler/z/codegen/S390Instruction.hpp#L482
https://github.com/eclipse/omr/blob/8b6089f6fcc304f1c975bba9da2ef74c45113eb2/compiler/z/codegen/S390Instruction.hpp#L494
https://github.com/eclipse/omr/blob/8b6089f6fcc304f1c975bba9da2ef74c45113eb2/compiler/z/codegen/S390Instruction.hpp#L507

**Comment by fjeremic** [comment]
> @fjeremic The only places where `getNextAvailableBlockIndex ()` is called are in `z` [2]. They don't look to me necessary. Is there any concern of removing them as part of the cleanup?

Please go ahead and remove them. Thanks!
