### ISSUE TITLE
Building compiler tests emits a flood of warnings

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#5296]
Recently, after rebasing one of my changes before submitting it, I found that building the compiler tests was generating a huge flood of warnings that weren't present before. These new warnings also appear in recent Jenkins [1] and Azure Pipelines [2] builds. These warnings only seem to show up when compiling the compiler tests and not when compiling the compiler itself. After doing a `git bisect`, it looks like this was caused by 92541c812c6ed7b42cbc5f3f622905c43b03cf28 (#5180) enabling `-Wall` on these targets. The compiler has historically had issues with warnings and is not yet ready to be compiled with this many warnings enabled, as this results in an unhelpfully large number of warnings that completely drown out any actually useful build output.

[1] https://ci.eclipse.org/omr/job/Build-linux_x86-64/1949/consoleText
[2] https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=980&view=logs&j=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f&t=b6623cb2-2223-5dfe-fa7b-0ad47bab4310

**Comment by Leonardo2718** [comment]
@dnakamura Any ideas what could be done about this?
