### ISSUE TITLE
Improve how the Power register allocator tests for gr0 excludes

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#5297]
Currently, the local register allocator in the Power codegen handles instructions that require that one of their sources not be placed in `gr0` by having special-case lists of instructions with this requirement [1]. This is a problem for maintainability, as these lists are becoming quite long and will likely continue to grow over time. A better solution would be to use an instruction property flag to determine when this handling is needed.

[1] https://github.com/eclipse/omr/blob/b302c9642aea8733d4e14c75871325c7688d8c6b/compiler/p/codegen/PPCInstruction.cpp#L520-L521

**Comment by fjeremic** [comment]
We have a similar concept on Z, but only to avoid using GPR0 for base or index registers in memory references, though we don't have an instruction property to handle this, but we do keep a flag on the virtual register and mark it if it gets used as part of a memref. It then gets automatically excluded from GPR0 consideration come RA time.

The Power restriction seems not related to memory references and more so on the instruction mnemonic, so I agree with the instruction property flag approach.
