### ISSUE TITLE
Deprecate x86 BADIA32Op with either INT3 or UD2

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5374]
The x86 code generator has long used `BADIA32Op` in place of a breakpoint trap `INT3` instruction.  This is used not only for true diagnostic breakpoints but also in place of an undefined opcode instruction.  However, to make the intent clearer and to align the opcode with the proper Intel mnemonics, uses of `BADIA32Op` should be replaced with either an `INT3` (for a breakpoint trap) or a true `UD2` (for an illegal opcode).

The best way to approach this might be to introduce the `INT3` and `UD2` instructions in OMR first, replace `BADIA32Op` with the appropriate instruction (depending on the context) in downstream projects like OpenJ9, do the same in OMR, and then finally retire `BADIA32Op`.

No functional or performance differences are expected with this change.

**Comment by 0xdaryl** [comment]
Since the common mnemonic work went in on x86 (#6020) the `TR_EntryBreakPoints` feature no longer works.  This is because the `TR::InstOpCode::bad` opcode is now a pseudo opcode on x86 (and isn't emitted) and it no longer has the encoding for an `int3` breakpoint.

This could be corrected rather easily.  However, perhaps now is the time to introduce the real instructions `int3` and `ud2` into OMR and sweep through the code in OMR and OpenJ9 and replace uses of `TR::InstOpCode::bad` with the instruction appropriate for each context.

For uses where a breakpoint is required, use `int3`.  For uses encoding an undefined or unknown opcode use `ud2`.  If there are uses that never appear in an instruction encoding, use `bad`.

@BradleyWood, could you take this on please?

**Comment by BradleyWood** [comment]
Sure.
