### ISSUE TITLE
Delete empty enum in OMRBlock.hpp

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#539]
In OMRBlock.hpp it appears that [there's an empty enum](https://github.com/eclipse/omr/blob/830ebbb/compiler/il/OMRBlock.hpp#L512), an artifact of old refactoring I suspect.

```cpp
   enum //  flag bits for _moreflags
      {
      // lowest 8 bits are used for partial flags. Public declaration above.

      };

````
This is doubly confusing, since[ what _actually_ appears](https://github.com/eclipse/omr/blob/830ebbb/compiler/il/OMRBlock.hpp#L434) to be stored in `_moreflags` are 

```

   enum partialFlags // Stored in lowest 8 bits of _moreflags
      {
      _unsanitizeable         = 0x00000001,
      _containsCall           = 0x00000002,
      _restartBlock           = 0x00000004,
      _partialInlineBlock     = 0x00000008,
      _endBlock               = 0x00000010,
      _difficultBlock         = 0x00000020,
      // Available            = 0x00000040,
      // Available            = 0x00000080
      };
```

Thanks to @gurinderu for pointing this out.

**Comment by mstoodle** [comment]
believe is fixed with #584, please reopen if I'm mistaken
