### ISSUE TITLE
Remove unnecessary uses of getOptimizationPhaseIsComplete()

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5402]
There are two uses of the CodeGenerator query `getOptimizationPhaseIsComplete()` that are unnecessary.  These uses should be eliminated in preparation for deprecating this query.

1.  `getOptimizationPhaseIsComplete()` should be folded to `false` here as this function is only used during VP in the optimizer:
https://github.com/eclipse/omr/blob/b99d3036d8a20592a04fdcd77bca176e794e326d/compiler/optimizer/OMRTransformUtil.cpp#L62

2.  `getOptimizationPhaseIsComplete()` should be folded to `true` here as we are obviously already in in the CodeGenerator phase already.

https://github.com/eclipse/omr/blob/b99d3036d8a20592a04fdcd77bca176e794e326d/compiler/z/codegen/OMRCodeGenPhase.cpp#L44

**Comment by rawrex** [comment]
Hello! May I clarify. Should this call be simply omitted in the two specified places?

**Comment by 0xdaryl** [comment]
The definition of `getOptimizationPhaseIsComplete()` still remains in `compiler/codegen/OMRCodeGenerator.hpp` and should be removed before this issue is closed.

@dylanjtuttle please take care of this.
