### ISSUE TITLE
Remove unused temps from x86 CodeGenerator

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5423]
The following fields in compiler/x/codegen/OMRCodeGenerator.hpp are not used in OMR nor any downstream project and can be removed:
```
  TR::SymbolReference             *_wordConversionTemp;
  TR::SymbolReference             *_doubleWordConversionTemp;
  TR::SymbolReference             *_currentTimeMillisTemp;
```

**Comment by kev536** [comment]
I am on it.

**Comment by jamesgua** [comment]
@0xdaryl my mistake: create PR in my forked repo so link it with this issue. Pls help me with proper work flow. Thx!

**Comment by 0xdaryl** [comment]
@jamesgua : I suggest you read through this to understand the git workflow in OMR -> https://github.com/eclipse/omr/blob/master/doc/GitCrashCourse.md

**Comment by arshbeerSingh** [comment]
Can you please assign this issue to me?

**Comment by 0xdaryl** [comment]
@arshbeerSingh : thanks for your offer to help.  Please feel free to contribute a pull request.

I do recommend you first read through the [Contributors Guide](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md), and if you're not familiar with git and the workflow for OMR to read through our [git Crash Course](https://github.com/eclipse/omr/blob/master/doc/GitCrashCourse.md).
