### ISSUE TITLE
AArch64: Implement bitOpCodes

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#5438]
OMRCodeGenerator::getSupportsBitOpCodes() returns false on AArch64.

It is used in https://github.com/eclipse/openj9/blob/0d48f88b41b253f98c862176f2785ef0c663d039/runtime/compiler/ilgen/Walker.cpp#L3535.

OpCodes to be implemented:
- [x] ihbit, lhbit (#5673)
- [x] ilbit, llbit (#6112)
- [x] inolz, lnolz (#5673)
- [x] inotz, lnotz (#5673)
- [x] ipopcnt, lpopcnt (#6859)

**Comment by knn-k** [comment]
#5673 implements some of the evaluators.
Remaining evaluators: ilbit/llbit, ipopcnt/lpopcnt

**Comment by 0xdaryl** [comment]
I suppose one larger question is whether these opcodes should all live and be implemented in OMR, or should really just be present in the OpenJ9 project.  There is not testing for any of these opcodes in the OMR project.  Not a topic to resolve in this issue, but perhaps something to discuss at an Architecture Meeting.

**Comment by knn-k** [comment]
These opcodes are used in https://github.com/eclipse/openj9/blob/master/runtime/compiler/ilgen/Walker.cpp for inlining some Java methods.
But I suppose what they do (counting leading zeros, etc.) is not specific to Java.  Other architectures (x, p, z) have their implementations of these evaluators are in OMR.

**Comment by knn-k** [comment]
I opened PR #6112 for ilbit/llbit evaluators.

**Comment by knn-k** [comment]
Sample population count code in ARM64 instructions:
```
    fmov    d0, x1 // x1: 64-bit input, d0/v0: temporary register
    cnt     v0.8b, v0.8b
    addv    b0, v0.8b
    umov    w0, v0.b[0] // w0: output
```

**Comment by knn-k** [comment]
PR #6859 implements ipopcnt and lpopcnt evaluators.

**Comment by knn-k** [comment]
PR #6859 has been merged.  Closing this issue.
