### ISSUE TITLE
Stop using gcc-generated dependency files (*.d)

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#55]
Stop using the -MD compile option, and stop using the generated *.d dependency files.

They don't significantly improve compile time.

Whenever there is significant file refactoring, some *.d files are no longer removed by "make clean", and the next attempt to compile usually fails due to incorrect dependencies specified by the obsolete *.d files.

**Comment by rwy0717** [comment]
I'm not sure I understand, the *.d files are used to partially recompile OMR correctly, not quickly. The alternative that I see would be to hand maintain *.o dependencies, or always `make clean && make`.

There are probably changes to the build system we can do to make this work more smoothly, but I think the dep files are useful and we shouldn't get rid of them.

**Comment by alin00** [comment]
If *.d files are required to specify compile dependencies correctly, why are they not needed for clean compiles?

**Comment by rwy0717** [comment]
Because in a clean compile, every *.o must be built. The *.d is generated as a side effect of this operation.

**Comment by alin00** [comment]
I don't rely on *.d files for correctness of partial compiles because:
- we don't have them on all platforms
- they don't capture dependencies between libraries

**Comment by rwy0717** [comment]
The autogenerated .d files are primarily useful for tracking .o dependencies on headers. This would be useful for modifying classes in headers, for example.

If they are more of a hindrance to the developer, then lets get rid of them.

**Comment by keithc-ca** [comment]
I'm strongly opposed to removing automatic dependency tracking.

It isn't needed or helpful if you're always doing a full recompile, but otherwise it ensures that incremental compiles don't miss rebuilding object files that are affected by header file changes. I think we should work to enable this dependency tracking on platforms were it doesn't already work.

We could use '-MMD' instead of '-MD' to avoid tracking dependencies on system headers which are less likely to change frequently. We should also add '-MMP' to avoid (temporary) problems with *.d files after renaming or (re)moving header files.

If there are missing dependencies on libraries, we should simply add those explicitly.

**Comment by alin00** [comment]
Our makefiles have never correctly supported incremental builds. If you were relying on them in the past, it was a fallacy.

> We could use '-MMD' instead of '-MD' to avoid tracking dependencies on system headers which are less likely to change frequently. We should also add '-MMP' to avoid (temporary) problems with *.d files after renaming or (re)moving header files.

The system headers aren't the problem. -MP might be an improvement. However, we'll still potentially have garbage *.d files lying around after a refactoring (unless you had enough forethought to run "make clean" before merging the refactoring -- and, in which case, you're not reaping any benefits from being able to do incremental builds).

IMO, OMR compiles are short enough that I would rather do full builds than rely on unreliable incremental builds. However, if someone wants to invest in making incremental builds reliable, I won't stop them.

**Comment by DanHeidinga** [comment]
Given that this item has been dormant since April, should it just be closed?  
/cc @charliegracie

**Comment by mstoodle** [comment]
Not every change is or will be a refactoring change, which means the .d files are still useful. I don't think we should unilaterally remove them just because they don't work for every possible scenario.

**Comment by mstoodle** [comment]
I'll close this early next week if there is no further discussion on it.

**Comment by mstoodle** [comment]
Robert added the -MP option in #180 which should help with the issues raised here.
