### ISSUE TITLE
New IL Opcode Request: sbyteswap and lbyteswap

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#5517]
## IL Opcode Name

- `sbyteswap`
- `lbyteswap`

## Motivation

Currently, OMR has a single opcode for reversing the order of bytes in a 32-bit integer: `ibyteswap`. This is a relatively common operation in many cases, as it can be used to convert between big-endian and little-endian representations of integers. However, there are no such opcodes for performing the same operation on 16- and 64-bit integers. Currently, OpenJ9 does have code for performing these operations in the form of the `Short.reverseBytes` and `Long.reverseBytes` recognized methods, however these implementations are not currently available to other consumers of OMR.

Using IL opcodes to represent these instead would allow other consumers of OMR to make use of this functionality, make our IL more consistent (it doesn't make much sense to have just `ibyteswap`), and allow limited optimizations to be performed on such nodes (e.g. CSE). While it may be tempting to use a non-helper here, that would not allow any optimizations to act upon these nodes and would force them to be anchored, which is undesirable given that these nodes represent a pure function.

## Homogeneity

These opcodes act exactly the same as the existing `ibyteswap` opcode, differing only in the types they act upon.

## Structure

These opcodes each require exactly one child representing an integer (an Int16 for `sbyteswap` and an Int64 for `lbyteswap`) and return an integer of the same type. They do not require a symbol reference, do not use any node flags beyond the standard set used by all nodes, and do not introduce any control flow.

These opcodes would have the same opcode properties as the existing `ibyteswap` opcode, i.e. `ValueNumberShare`, `SupportedForPRE`, and `ByteSwap`.

## Operation

The `sbyteswap` opcode performs a byte-reversal of a 16-bit integer:

```
sbyteswap(x) = ((x & 0x00ff) << 8)
             | ((x & 0xff00) >> 8)
```

The `lbyteswap` opcode performs a byte-reversal of a 64-bit integer:

```
lbyteswap(x) = ((x & 0x00000000000000ff) << 56)
             | ((x & 0x000000000000ff00) << 40)
             | ((x & 0x0000000000ff0000) << 24)
             | ((x & 0x00000000ff000000) << 8)
             | ((x & 0x000000ff00000000) >> 8)
             | ((x & 0x0000ff0000000000) >> 24)
             | ((x & 0x00ff000000000000) >> 40)
             | ((x & 0xff00000000000000) >> 56)
```

These opcodes do not have any other side effects.

## Scope

These opcodes would be primarily intended for language use, such as implementation of the `{Short,Long}.reverseBytes` recognized methods in OpenJ9 or for implementation of languages strictly requiring little-endian such as WebAssembly on big-endian systems. Theoretically, the optimizer could recognize byte-reversing sequences and transform them into this opcode and there are certain special optimizations that could be performed with these opcodes (e.g. `lbyteswap(lbyteswap(x)) = x`).

Generally, these opcodes would map to a single instruction or a short series of optimized instructions for all architectures on which they are implemented. Currently, all of x86, Power, and Z implement the `{Short,Long}.reverseBytes` recognized methods in OpenJ9, so there is already code for doing these operations on those platforms. This existing code would be reused to implement these opcodes on those codegens.

## Implementation Dependencies

Beyond the introduction of a flag on `TR::CodeGenerator` to indicate codegen support of these opcodes, there should be no special considerations here.

## Performance

In certain scenarios, such as when working with big-endian wire formats on little-endian machines, byteswap operations can be very common. While these can be implemented by using a series of `*and`, `*shl`, `*ushr`, and `*or` operations, many architectures have special instructions or sequences of instructions that can perform this operation faster. For instance, x86 has the `bswap` instruction, P10 has the `br[hwd]` instructions, and versions of Power prior to P10 can use optimized sequences using `rlwimi` and `rldimi` to reduce the number of instructions needed.

Additionally, some architectures (such as Power) also provide instructions for performing byte-reversed loads and stores, which can be used in the codegen to further improve performance.

## Testing Considerations

These opcodes can be trivially tested using Tril, as they do not have any special behaviour that Tril currently cannot handle.

## IL Validation

These opcodes can be validated by the existing IL validator without issue.

**Comment by andrewcraik** [comment]
if we are going for completeness do we need an abyteswap as well?

**Comment by aviansie-ben** [comment]
I'm not entirely sure about `abyteswap` to be honest. I don't imagine it would be a very common operation, since pointers are not usually sent over the wire or stored on disk and even those languages that do strictly require little-endian don't typically allow users to arbitrarily mess with addresses. For instance, in WebAssembly the pointers that user code sees are simply offsets from the beginning of a sandboxed linear memory and so aren't represented by the Address type.

I don't see any reason we can't allow byte-reversing an address, but I'm not entirely sure I see a sufficiently compelling use case for that like I do for Int16 and Int64.

**Comment by 0xdaryl** [comment]
This issue will supercede #958.
