### ISSUE TITLE
TR_HOST_64BIT is defined wrongly

### ISSUE THREAD

**Issue by zl-wang** [eclipse/omr#553]
TR_HOST_64BIT was intended to mean the build rather than the underlying ISA architecture.  Currently OMR defines.h defines it according to the underlying ISA architecture.  As a result, 32bit build defines TR_HOST_64BIT too. All files can be compiled successfully but most wrongly. 

Currently:
#  if defined(__PPC64__) || defined(_ARCH_PPC64)
#    define TR_HOST_64BIT 1

Fix:
#  if defined(__PPC64__) || defined(__64BIT__)
#    define TR_HOST_64BIT 1

**Comment by mstoodle** [comment]
@zl-wang has this issue been completely fixed? can we close this issue?

**Comment by zl-wang** [comment]
yes. yes.
