### ISSUE TITLE
Contributor triage access test

### ISSUE THREAD

**Issue by dsouzai** [eclipse/omr#5576]

**Comment by dsouzai** [comment]
Can't edit labels yet.

**Comment by dsouzai** [comment]
I got the email from Eclipse stating that I've been added to `technology-omr-contributors`

**Comment by fjeremic** [comment]
I've asked on the bugzilla what the problem is:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=562071

**Comment by dsouzai** [comment]
Looks like I can add labels. I _think_ I can only assign members of Eclipse though.

**Comment by dsouzai** [comment]
Maybe the limitation still exists that a non member needs to comment on an issue before it can be assigned to them.

**Comment by fjeremic** [comment]
It seems to be a bug on their (Eclipse's) end. They mentioned in the bugzilla link above that their sync script is resetting permissions and they are looking into it.

**Comment by dsouzai** [comment]
Any luck with this? Been about a month since the last update on the bugzilla issue.

**Comment by fjeremic** [comment]
Asked for an update on the issue.

**Comment by fjeremic** [comment]
@dsouzai could you please try again?

**Comment by dsouzai** [comment]
Yeah looks like I can change labels. The only people I can assign are Eclipse members though. Do you know of anyone else who has triage access but is not a committer (on any Eclipse project)?

**Comment by fjeremic** [comment]
Do you mean assign people to issues? I forget the rules but I believe not even committers can assign arbitrary people. You had to have commented on the issue or be a committer/contributor to get assigned?

**Comment by dsouzai** [comment]
Ah ok, I thought that this might've addressed that issue. Ok well then seems like everything works as expected then with triage access level.
