### ISSUE TITLE
Make naming of CodeGenerator variable consistent

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5594]
The overwhelmingly common short form for a variable to store the `TR::CodeGenerator` object is `cg` (about 30000 instances).  The next most common form is `codeGen` (about 400).  We should use a single form for consistency and given the popularity of `cg` that should be the preferred name.  Sweep through the OMR compiler and make that change.

Here is a pipeline of greps to help find some of the places to change:
```
grep -rn codeGen * | egrep -v 'codeGen[a-zA-Z0-9(]'
```

**Comment by pkrc267** [comment]
I would like to work on this

**Comment by 0xdaryl** [comment]
Thanks for your offer to help!

**Comment by pkrc267** [comment]
Thankyou so much.

A quick question. After renaming all the instances, should I build and test the whole project?

**Comment by 0xdaryl** [comment]
Generally, it is a good practice to test your changes to the extent that you can on your own before making a pull request (for example, on x86 Linux).  The community certainly understands that you can't test them on every platform and architecture combination.

When you do make a PR (or any time that you push new commits), a Travis CI job will run automatically that will perform a build (x86 Linux only).  Once a committer has reviewed your code, they will run a much broader set of sanity tests on all architectures the OpenJ9 community cares about that you will see in the "Checks" section of the PR.

**Comment by pkrc267** [comment]
Made the names consistent and made a PR.
@0xdaryl  Please give feedback if I need to make certain things better or do anything different.

**Comment by 0xdaryl** [comment]
As there has been no indication of progress on this issue I will un-assign it. I appreciate your offer to help the project. You are welcome to pick up this issue (if it is still open) or any other issue should you wish to contribute to Eclipse OMR in the future.
