### ISSUE TITLE
Investigate flaky test detection on Azure Pipelines

### ISSUE THREAD

**Issue by dnakamura** [eclipse/omr#5629]
We should look at enabling flaky test detection on Azure. Might alleviate some of the issue with #5581

see https://docs.microsoft.com/en-us/azure/devops/pipelines/test/flaky-test-management?view=azure-devops

**Comment by fjeremic** [comment]
Thanks, the feature was enabled but the flaky tests were still counted as failures. I've enabled manual marking/unmakring and have marked the following two tests as flaky:

- omrporttest.poll_functionality_basic
- omrporttest.poll_functionality_many_sockets
