### ISSUE TITLE
Switch to using Node::isSingleRefUnevaluated() in code generators

### ISSUE THREAD

**Issue by aviansie-ben** [eclipse/omr#5648]
In many locations in the codegen, it is necessary to check that a child node is not commoned before performing any of a number of optimizations on it. Traditionally, this was done with a check like `!node->getRegister() && node->getReferenceCount() == 1`. However, this can also be checked using the more readable and shorter `node->isSingleRefUnevaluated()`, which is what's currently being done in a number of places on Z. However, no other codegens are currently taking advantage of this and even Z is not consistent about using it. We should really go through and change existing code to use this method.

**Comment by fjeremic** [comment]
As discussed on Feb. 4, 2021 OMR Architecture call we will eliminate these APIs and inline their uses which are predominantly in the Z codegen. I will do this work shortly.
