### ISSUE TITLE
Add new test configuration files to OMR GC Perf test 

### ISSUE THREAD

**Issue by mesbaha** [eclipse/omr#58]
Add three new test configuration files to the OMR GC performance test runs in order to collect more performance data.

**Comment by charliegracie** [comment]
How big are these files on disk?  I am wondering if we want to do something different for this so that the repo does not get too large.

**Comment by mesbaha** [comment]
In total, they are about 18.3 MB.

**Comment by charliegracie** [comment]
That is almost the same size as the entire OMR project and the two existing files are a lot of that size.  I think we want to spend some time thinking about this.

**Comment by charliegracie** [comment]
Closing this as I believe we do not want to increase the size of the repo for this.  We can revisit in the future if we believe it is something we require.
