### ISSUE TITLE
Access fields of TR_InlinedCallSite via getters/setters

### ISSUE THREAD

**Issue by dsouzai** [eclipse/omr#5844]
The definition of `TR_InlinedCallSite` is
```
typedef struct TR_InlinedCallSite
   {
   TR_OpaqueMethodBlock   * _methodInfo;
   #define _vmMethodInfo _methodInfo
   struct TR_ByteCodeInfo   _byteCodeInfo;
   } TR_InlinedCallSite;
```
Under relocatable compilations, `_methodInfo` does not actually hold a `TR_OpaqueMethodBlock *` but a `TR_ResolvedMethod`. This means that every part of the code that accesses `_methodInfo` needs to remember that under relocatable compilations, it has to do something like
```
reinterpret_cast<TR_AOTMethodInfo *>(methodInfo)->resolvedMethod->getPersistentIdentifier()
```
Failing to do so can lead to crashes or very subtle bugs (for example, there's a current bug in FSD in OpenJ9 where we're getting the wrong size of the emergency OSR buffer because `TR_ResolvedMethod` is passed in instead of the `TR_OpaqueMethodBlock`).

Adding getters/setters is a little tricky because `TR_InlinedCallSite` is in `jittypes.h` whereas `TR_AOTMethodInfo` is in `OMRMethod.hpp`. So, since the cleanup will be a little involved, IMO we might as well do the following:

1. Make the fields of `TR_InlinedCallSite` private (maybe just convert it to a class)
2. Declare getters/setters of the field in `jittypes.h`
3. Provide the implementation of those getters in some .cpp file that includes `compile/Method.hpp`; the getter of `_methodInfo` specifically should take in a `TR::Compilation *` param
4. Remove the...questionable... `#define _vmMethodInfo _methodInfo`
5. Replace all loads of those fields with the calls to getters

This will have to be a coordinated openj9/omr change though. We will also need a special getter/setter called get/setAOTMethodInfo that's only valid under AOT compilations; `TR_AOTMethodInfo` can be forward declared in `jittypes.h` to prevent compilation errors.

@dmitry-ten has kindly offered to do this work. @fjeremic @0xdaryl what do you think?

**Comment by dmitry-ten** [comment]
@fjeremic @0xdaryl if you guys have no objections to the implementation suggested by Irwin, I'll start working on this item.

**Comment by 0xdaryl** [comment]
My recollection for the reason this header file is a `.h` file (as opposed to a `.hpp` file) is so that it can be included in C files.  If you make `TR_InlinedCallSite` a class you break that contract.  And to make the fields private I think you have to make it a class.

If you don't make it a class, what do your getter and setters look like, and are they callable from MethodMetaData.c and the DDR code?

**Comment by dsouzai** [comment]
Ah that's unfortunate. I guess the getters & setters could be declared extern C then; at the end of the day we just need a wrapper so that if we're in an AOT compilation we know that `_methodInfo` isn't actually a `TR_OpaqueMethodBlock *`.

**Comment by fjeremic** [comment]
> Ah that's unfortunate. I guess the getters & setters could be declared extern C then; at the end of the day we just need a wrapper so that if we're in an AOT compilation we know that `_methodInfo` isn't actually a `TR_OpaqueMethodBlock *`.

An alternative is to make the field a `void*` since it seems we can store different types there. Then the user of the field has to ensure they cast to the correct type.

**Comment by 0xdaryl** [comment]
Without doing the full implementation, can you paste a sample getter/setter here that you propose?

**Comment by dsouzai** [comment]
Something like:

```
TR_OpaqueMethodBlock *
getMethodInfo(TR::Compilation *comp, TR_InlinedCallSite &callsite)
   {
   if (comp->compileRelocatableCode())
      {
      return reinterpret_cast<TR_AOTMethodInfo*>(callsite._methodInfo)->resolvedMethod->getPersistentIdentifier();
      }
   else
      {
      return callsite._methodInfo;
      }
   }

void
setMethodInfo(TR::Compilation *comp, TR_InlinedCallSite &callsite, TR_OpaqueMethodBlock *methodInfo)
   {
   callsite._methodInfo = methodInfo;
   }

TR_AOTMethodInfo *
getAotMethodInfo(TR::Compilation *comp, TR_InlinedCallSite &callsite)
   {
   TR_ASSERT_FATAL(comp->compileRelocatableCode(), "Should not be called if not a relocatable compile");
   return reinterpret_cast<TR_AOTMethodInfo *>(callsite._methodInfo);
   }
```

I looked over the code, and from what I can tell, we only store a `TR_AOTMethodInfo` during compilation in `incInlineDepth`. Most places that read out `_methodInfo` from the callsite wants the `TR_OpaqueMethodBlock`, so it would make sense to replace these with the `getMethodInfo` API. 

At present nothing in OMR needs the `TR_AOTMethodInfo` but there's one location that needs it in OpenJ9 (In `J9CodeGenerator.cpp`; it's used to generate relocation records for the inlined methods); this should use the `getAotMethodInfo` API.

Finally, In the inlining table in the metadata (also currently only in OpenJ9 though there's no reason it couldn't also be true for OMR compiled methods) which is generated at the end of a compilation, we store a `TR_InlinedCallSite` struct for each inlined method; in this context the `_methodInfo` is a `TR_OpaqueMethodBlock *` regardless of the type of compilation, hence the `setMethodInfo` API.

The point here is that `getMethodInfo` should discourage people from directly reading out `callsite._methodInfo` which is overloaded.

**Comment by dsouzai** [comment]
You know, on second thought, we might not even need `setMethodInfo`. There's this bizarre code in OpenJ9:
```
      if (vm->isAOT_DEPRECATED_DO_NOT_USE())
         {
         inlinedCallSite->_methodInfo = (TR_OpaqueMethodBlock*)-1;
         }
      memcpy(callSiteCursor, inlinedCallSite, sizeof(TR_InlinedCallSite) );
```
that overwrites the `TR_InlinedCallSite` struct in the `comp` object before mem copying it into the metadata.... I have no idea why we wouldn't just make a new copy.

Also thinking on it, we can't blindly replace uses of `inlinedCallSite->_methodInfo` in RelocationRecord.cpp because at AOT load time, the `TR_InlinedCallSite` being referenced is from the metadata, which as described in the comment above, will never hold a `TR_AOTMethodInfo` in the `_methodInfo` field.

So, the problem is: we need to only use the APIs when we get the `TR_InlinedCallSite` from the comp object, but not otherwise. We've overloaded this struct too much and it's much harder to entangle it in a consistent way than I initially thought.

**Comment by dsouzai** [comment]
>  could we just move it out of the struct altogether, and place it into a separate TR_Array inside Compilation object? 

That should be ok; you just have to take into account the fact that
```
bool OMR::Compilation::incInlineDepth(TR::ResolvedMethodSymbol * method, TR::Node *callNode, bool directCall, TR_VirtualGuardSelection *guard, TR_OpaqueClassBlock *receiverClass, TR_PrexArgInfo *argInfo)
```
is used when we inline a method, whereas
```
bool OMR::Compilation::incInlineDepth(TR::ResolvedMethodSymbol * method, TR_ByteCodeInfo & bcInfo, int32_t cpIndex, TR::SymbolReference *callSymRef, bool directCall, TR_PrexArgInfo *argInfo)
```
is used only in estimate bytecode size; even though the compiler adds a `TR_InlinedCallSite` it removes it later on. (FWIW, OpenJ9 overrides this to assert that we only use that API if we're going to remove it later).

**Comment by dsouzai** [comment]
> That should be ok; you just have to take into account the fact that

Might not even really matter actually; as long as you always add to the new TR_Array wherever we add to `_inlinedCallSites` and remove wherever we remove from `_inlinedCallSites` then everything will be consistent.

**Comment by dmitry-ten** [comment]
Yeah, I will get to it then.
