### ISSUE TITLE
Remove obsolete struct movedObjectHashCode

### ISSUE THREAD

**Issue by bragaigor** [eclipse/omr#5851]
`struct movedObjectHashCode` is code specific to external OpenJ9 project; therefore it got moved which makes the existing OMR `struct movedObjectHashCode` obsolete.

Good first time issue.

**Comment by KenCox94** [comment]
I’d like to tackle this

**Comment by bragaigor** [comment]
Awesome! There's no usages of the `struct movedObjectHashCode` in the code so all you would have to do is remove the definition and declaration of it

**Comment by bragaigor** [comment]
I don't have the power to assign people to issues. But don't worry, since you were the first to claim it, no one will be stepping here. We just ask that you refer this issue in the commit/PR that you open.

**Comment by bragaigor** [comment]
Also don't forget to sign the ECA agreement (that's the reason you an X besides the `eclipsefdn/eca` check). You can find instructions here: https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md

**Comment by bragaigor** [comment]
Once that's done you'll have to sign your commit message. Here's an example: https://github.com/eclipse/openj9/commit/d337957fcc249547472f5391b43ab803740d9687
```
Signed-off-by: Igor Braga <higorb1@gmail.com>
```

**Comment by KenCox94** [comment]
copy all! Doing that now
