### ISSUE TITLE
Remove unused IL opcodes

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#5914]
As part of the preparation work to define an API for the compiler (#5858), some cleanup of the current IL opcode set in OMR is in order.

I propose the following IL opcodes be deleted.  Those on this list were chosen for a number of reasons:
* lack of any known producers of the opcode in any known project that uses OMR
* lack of a suitable backend implementation
* no justifiable use in OMR
* lack of documentation and understanding of what the opcode is for and how it behaves
* various combinations of the above

As none of the list below has any known usage in OMR nor any known downstream projects I feel the justification to pardon any of these has to be strong enough to overcome eliminating the IL opcode now and re-introducing it later should the need arise.  The advantage of introducing it again later is that it should come with proper justification, documentation, and Tril tests which are sorely lacking for all of these opcodes.

Note that additional IL opcodes not on this list will be removed as part of #2657.

Specifically for OpenJ9, removing these is best done with a single PR in OMR and a single PR in OpenJ9 that should be merged simultaneously.  This will eliminate churn.

| IL Opcode | CodeGen Evaluators? | Known Producers | Additional Notes |
| :-------: | :--------: | :-------------: | :--------------- |
| `loadAutoOffset` | Z | None | |
| `getpm` | Z | None | |
| `setpm` | Z | None | | 
| `ibranch` | Z | None | |
| `mbranch` | Z | None | |
| `MergeNew` | None | OpenJ9 | Disabled for 20 years and has never shown a proven benefit in past attempts to enable.  Evaluators are no longer available. |
| `bitOpMemND` | None | None | |
| `trt` | Z | None | |
| `trtSimple` | Z | None | |
| `trtLookup` | None | None | |
| `getstack` | P | None | |
| `dealloca` | P | None | |
| `callIf` | None | None | |
| `dbgFence` | P | None | Historical J9 opcode.  Deprecated. |
| `Ret` | None | None | Historical J9 opcode.  Deprecated. |
| `idoz` | P | None | |
| `arraycmpWithPad` | Z | None | WCode opcode |
| `ixfrs` | P | None | WCode opcode |
| `lxfrs` | P | None | WCode opcode |
| `fxfrs` | P | None | WCode opcode |
| `dxfrs` | P | None | WCode opcode |
| `dcos` | P | None | The evaluator transforms the node to a call using the SymRef found on the node.  However, these SymRefs have no backing implementation in any known project. |
| `dsin` | P | None | As above |
| `dtan` | P | None | As above |
| `dcosh` | P | None | As above |
| `dsinh` | P | None | As above |
| `dtanh` | P | None | As above |
| `dacos` | P | None | As above |
| `dasin` | P | None | As above |
| `dlog` | P | None | As above |
| `datan` | P | None | As above |
| `datan2` | Z | None | As above |
| `dexp` | Z | None | Z always asserts with "Do not use" |
| `fexp` | Z | None | Z always asserts with "Do not use" |
| `bexp` | None | None | |
| `sexp` | None | None | |
| `cexp` | None | None | |
| `buexp` | None | None | |
| `iuexp` | None | None | |
| `luexp` | None | None | |
| `fuexp` | None | None | |
| `duexp` | None | None | |
| `iexp` | P | None | WCode opcode |
| `lexp` | P | None | WCode opcode |
| `fint` | P | None | WCode opcode |
| `dint` | P | None | WCode opcode |
| `fnint` | P,Z | None | |
| `dnint` | P,Z | None | |
| `iuRegLoad` | X,P,Z | None | |
| `luRegLoad` | X,P,Z | None | |
| `iuRegStore` | X,P,Z | None | |
| `luRegStore` | X,P,Z | None | |
| `aiuadd` | X,P,Z,A | None | |
| `aluadd` | X,P,Z,A | None | |

**Comment by aviansie-ben** [comment]
If we're looking at removing `dlog`, I'd also suggest we remove its vectorized version `vdlog` as well. Only Power has an evaluator for it which references a helper that no longer exists (so it wouldn't work anyway).
