### ISSUE TITLE
Deprecate findOrCreateLiteral codegen API

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#5937]
According to a quick search through the codebase the `findOrCreateLiteral` API seems to be unimplemented, yet there are what seems to be uses of this API in some parts of the Z codegen. Given this API is going to return an incorrect result 100% of the time, it is likely the code using it is dead and should thus be removed.

**Comment by 0xdaryl** [comment]
FYI... See #2180.  If you're going to remove it, close off 2180.
