### ISSUE TITLE
Comparation between pointer and number

### ISSUE THREAD

**Issue by gurinderu** [eclipse/omr#594]
`
../compiler/compile/OMRCompilation.cpp:809:70: error: ordered comparison between pointer and zero ('char *' and 'int')
      if (self()->getOption(TR_Randomize) || randomExercisePeriodStr > 0)
                                             ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
../compiler/compile/OMRCompilation.cpp:811:35: error: ordered comparison between pointer and zero ('char *' and 'int')
      if (randomExercisePeriodStr > 0)
          ~~~~~~~~~~~~~~~~~~~~~~~ ^ ~`


I know that it is correct code, but some modern compilers check types)

**Comment by lmaisons** [comment]
@mstoodle Is pull request 598 sufficient for resolving this?

**Comment by mstoodle** [comment]
it should have been :) . I'll close. @gurinderu please reopen if you still see a problem.
