### ISSUE TITLE
Improve assert message when generating an instruction the processor does not support

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#5963]
In eclipse/openj9#12538 we ran into an issue which triggered the following assert:

https://github.com/eclipse/omr/blob/746acf8b59ad96823c2ba98ad51bea8568dac600/compiler/z/codegen/OMRInstruction.cpp#L89

Unfortunately due to containerization and AOT we may "downgrade" the processor to for example a z10 even though we are running on a z15. In such cases it would be very useful to know what processor level we did detect.

We should improve the above assert to also print the processor, for example:

```
Processor detected (z10) does not support instruction AGHIK
```

I'm not sure if we we can extract the "z10" string or we can only get the processor ID. We should investigate what we can print here so that a developer is able to determine the processor that was detected.

**Comment by dchopra001** [comment]
I think we can use the following routine to get the name easily:
https://github.com/eclipse/omr/blob/746acf8b59ad96823c2ba98ad51bea8568dac600/compiler/z/env/OMRCPU.cpp#L246-L248

Though this routine depends on us keeping it up-to-date when future processors are released. As part of the PR I can also make the assert fatal if you think we should enforce that this routine be maintained and updated whenever a new or unrecognized processor is encountered:
https://github.com/eclipse/omr/blob/746acf8b59ad96823c2ba98ad51bea8568dac600/compiler/z/env/OMRCPU.cpp#L286-L289

**Comment by fjeremic** [comment]
Let's also change that `default` assert to fatal.

**Comment by joransiu** [comment]
If we make the assert fatal, would that impact migration of existing SDKs that have not been updated onto the new hardware?

**Comment by fjeremic** [comment]
> If we make the assert fatal, would that impact migration of existing SDKs that have not been updated onto new hardware?

If we are running on an unknown processor we should have the value `OMR_PROCESSOR_S390_UNKNOWN`. The default case should never happen IMO unless the user supplied a bogus enum value. In which case you are right, we should instead remove the assert since we don't want to fail in this case.
