### ISSUE TITLE
Test for long type is failing when getHighGlobalRegisterNumber call is not used

### ISSUE THREAD

**Issue by R-Santhir** [eclipse/omr#601]
Change !585 is causing problems on downstream Power testing, I am reverting the original change until an appropriate fix can be found.

[Commit causing the issue](https://github.com/eclipse/omr/pull/585/)

**Comment by R-Santhir** [comment]
@0xdaryl

**Comment by mstoodle** [comment]
I'm assuming this can be closed since the fix was merged. If I'm wrong, please reopen!
