### ISSUE TITLE
Deprecate callMustBeInlinedRegardlessOfSize

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#6148]
According to internal history this function:

https://github.com/eclipse/omr/blob/b173e3151fc1cdc89c0a4f3632a8b66de5a56a49/compiler/optimizer/Inliner.cpp#L4261-L4265

used to be non-empty for WCode. Since WCode was removed from OMR this function always returns false so it no longer needs to exist.

**Comment by siddharth1704** [comment]
so basically we need to remove this function

**Comment by fjeremic** [comment]
> so basically we need to remove this function

That's right, and fold away all code which depends on it both in OMR and in known downstream projects. I only know of this being used in OpenJ9 currently in these two locations:

1. https://github.com/eclipse-openj9/openj9/blob/cd8db74f1d43b37e3bdbd1c72f9e120d18047634/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3580
2. https://github.com/eclipse-openj9/openj9/blob/cd8db74f1d43b37e3bdbd1c72f9e120d18047634/runtime/compiler/optimizer/InlinerTempForJ9.cpp#L3620

**Comment by siddharth1704** [comment]
Can you assign me on this issue , this is my first open source contribution so i might need some help

**Comment by 0xdaryl** [comment]
As there has been no indication of progress on this issue I will un-assign it.  I appreciate your offer to help the project.  You are welcome to pick up this issue (if it is still open) or any other issue should you wish to contribute to Eclipse OMR in the future.

**Comment by 0xdaryl** [comment]
@jmesyou : please have a look at this
