### ISSUE TITLE
Fix s390 opcode properties

### ISSUE THREAD

**Issue by VermaSh** [eclipse/omr#6155]
Some of the opcodes are missing (or have incorrect) properties. The 3 I stumbled across are `CDS`, `CS` and `STAM`. 

COMPARE AND SWAP (32) (`CDS`) and COMPARE DOUBLE AND SWAP (32) (`CS`) set operand 1 and 2. But according to the properties they set operand 3 instead of 2 [1] [2].

STORE ACCESS MULTIPLE (`STAM`) doesn't set any of the operands. It stores the access registers, starting with R1 and ending with R3, to location specified by second operand address.

There might be other opcodes with incorrect properties. We'll need to comb through to find the rest.

[1] https://github.com/eclipse/omr/blob/6eec759cd2d446f74d2b8a7ee3348d98ce6bfa79/compiler/z/codegen/OMRInstOpCodeProperties.hpp#L1066 `CDS`
[2] https://github.com/eclipse/omr/blob/6eec759cd2d446f74d2b8a7ee3348d98ce6bfa79/compiler/z/codegen/OMRInstOpCodeProperties.hpp#L1701 `CS`
[3] https://github.com/eclipse/omr/blob/6eec759cd2d446f74d2b8a7ee3348d98ce6bfa79/compiler/z/codegen/OMRInstOpCodeProperties.hpp#L5664 `STAM`

cc: @fjeremic

**Comment by GFIGroup** [comment]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model consider this issue as likely a "good first issue". May we recommend you to label it as "good first issue" so newcomers know where to choose?

Thank you!

**Comment by Spencer-Comin** [comment]
I did a bit of combing through the opcodes and some docs, and I found some more missing and incorrect opcodes. Here's the list I've got:

### Missing properties

##### ImplicitlySetsGPR1:
- EDIT AND MARK (`EDMK`)

##### ImplicitlySetsGPR2:
- INSERT PSW KEY (`IPK`)

##### IsRegCopy:
- LOAD (short) (`LER`)
- LOAD (long) (`LDR`)
- LOAD (extended) (`LXR`)

##### ImplicitlyUsesGPR0:
- PERFORM RANDOM NUMBER OPERATION (`PRNO`)

##### SetsOperand2:
- COMPARE AND SWAP (32) (`CS`)
- COMPARE AND SWAP (32) (`CSY`)
- COMPARE AND SWAP (64) (`CSG`)
- COMPARE DOUBLE AND SWAP (32) (`CDS`)
- COMPARE DOUBLE AND SWAP (32) (`CDSY`)
- COMPARE DOUBLE AND SWAP (64) (`CDSG`)
- STORE ACCESS MULTIPLE (`STAM`)
- STORE CHARACTERS UNDER MASK (low) (`STCM`)
- STORE CONTROL (32) (`STCTL`)
- STORE MULTIPLE (32) (`STM`)
- COMPARE DOUBLE AND SWAP (64) (`CDSG`)
- COMPARE DOUBLE AND SWAP (32) (`CDSY`)
- COMPARE AND SWAP (64) (`CSG`)
- COMPARE AND SWAP (32) (`CSY`)
- STORE ACCESS MULTIPLE (`STAMY`)
- STORE CHARACTERS UNDER MASK (high) (`STCMH`)
- STORE CHARACTERS UNDER MASK (low) (`STCMY`)
- STORE CONTROL (64) (`STCTG`)
- STORE MULTIPLE (64) (`STMG`)
- STORE MULTIPLE HIGH (32) (`STMH`)
- STORE MULTIPLE (32) (`STMY`)

##### UsesM3:
- LOAD ROUNDED (long to short DFP) (`LEDTR`)
- LOAD ROUNDED (extended to long DFP) (`LDXTR`)
- VECTOR LOAD (`VL`)
- VECTOR STORE (`VST`)

##### SingleFP:
- CONVERT FROM LOGICAL (64 to short BFP) (`CELGBR`)

##### SetsOperand1:
- COMPARE DOUBLE AND SWAP (64) (`CDSG`)
- COMPARE DOUBLE AND SWAP (32) (`CDSY`)
- COMPARE AND SWAP (64) (`CSG`)
- COMPARE AND SWAP (32) (`CSY`)

### Incorrect properties

##### SetsOperand3:
- COMPARE DOUBLE AND SWAP (32) `CDS`
- COMPARE AND SWAP (32) `CS`
- STORE ACCESS MULTIPLE `STAM`
- STORE CHARACTERS UNDER MASK (low) `STCM`
- STORE CONTROL (32) `STCTL`
- STORE MULTIPLE (32) `STM`
- COMPARE DOUBLE AND SWAP (64) `CDSG`
- COMPARE DOUBLE AND SWAP (32) `CDSY`
- COMPARE AND SWAP (64) `CSG`
- COMPARE AND SWAP (32) `CSY`
- STORE ACCESS MULTIPLE `STAMY`
- STORE CHARACTERS UNDER MASK (high) `STCMH`
- STORE CHARACTERS UNDER MASK (low) `STCMY`
- STORE CONTROL (64) `STCTG`
- STORE MULTIPLE (64) `STMG`
- STORE MULTIPLE HIGH (32) `STMH`
- STORE MULTIPLE (32) `STMY`

##### SingleFP:
- STORE (long) `STD`

##### UsesRegPairForTarget:
- STORE PAIR TO QUADWORD `STPQ`

**Comment by Spencer-Comin** [comment]
I did some combing through the opcodes and compiled a list of missing and incorrect properties:

### Missing properties

##### IsRegCopy
- LOAD (short) (`LER`)
- LOAD (long) (`LDR`)
- LOAD (extended) (`LXR`)

##### ImplicitlyUsesGPR0
- PERFORM RANDOM NUMBER OPERATION (`PRNO`)

##### SetsOperand2
- COMPARE DOUBLE AND SWAP (32) (`CDS`)
- COMPARE AND SWAP (32) (`CS`)
- STORE ACCESS MULTIPLE (`STAM`)
- STORE CHARACTERS UNDER MASK (low) (`STCM`)
- STORE CONTROL (32) (`STCTL`)
- STORE MULTIPLE (32) (`STM`)
- COMPARE DOUBLE AND SWAP (64) (`CDSG`)
- COMPARE DOUBLE AND SWAP (32) (`CDSY`)
- COMPARE AND SWAP (64) (`CSG`)
- COMPARE AND SWAP (32) (`CSY`)
- STORE ACCESS MULTIPLE (`STAMY`)
- STORE CHARACTERS UNDER MASK (high) (`STCMH`)
- STORE CHARACTERS UNDER MASK (low) (`STCMY`)
- STORE CONTROL (64) (`STCTG`)
- STORE MULTIPLE (64) (`STMG`)
- STORE MULTIPLE HIGH (32) (`STMH`)
- STORE MULTIPLE (32) (`STMY`)

##### UsesM3
- LOAD ROUNDED (long to short DFP) (`LEDTR`)
- LOAD ROUNDED (extended to long DFP) (`LDXTR`)
- VECTOR LOAD (`VL`)
- VECTOR STORE (`VST`)
- CONVERT FROM LOGICAL (64 to short BFP) (`CELGBR`)
- CONVERT FROM LOGICAL (32 to short BFP) (`CELFBR`)
- CONVERT FROM LOGICAL (64 to long BFP) (`CDLGBR`)
- CONVERT FROM LOGICAL (32 to long BFP) (`CDLFBR`)

##### SingleFP
- CONVERT FROM LOGICAL (64 to short BFP) (`CELGBR`)
- STORE (short) (`STE`)
- STORE (short) (`STEY`)

##### UsesM4
- CONVERT FROM LOGICAL (64 to short BFP) (`CELGBR`)
- CONVERT FROM LOGICAL (32 to short BFP) (`CELFBR`)
- CONVERT FROM LOGICAL (64 to long BFP) (`CDLGBR`)
- CONVERT FROM LOGICAL (32 to long BFP) (`CDLFBR`)

##### UsesRegPairForSource
- STORE PAIR TO QUADWORD (`STPQ`)

##### DoubleFP
- STORE (long) (`STD`)
- STORE (long) (`STDY`)

### Incorrect properties

##### SetsOperand3
- COMPARE DOUBLE AND SWAP (32) `CDS`
- COMPARE AND SWAP (32) `CS`
- STORE ACCESS MULTIPLE `STAM`
- STORE CHARACTERS UNDER MASK (low) `STCM`
- STORE CONTROL (32) `STCTL`
- STORE MULTIPLE (32) `STM`
- COMPARE DOUBLE AND SWAP (64) `CDSG`
- COMPARE DOUBLE AND SWAP (32) `CDSY`
- COMPARE AND SWAP (64) `CSG`
- COMPARE AND SWAP (32) `CSY`
- STORE ACCESS MULTIPLE `STAMY`
- STORE CHARACTERS UNDER MASK (high) `STCMH`
- STORE CHARACTERS UNDER MASK (low) `STCMY`
- STORE CONTROL (64) `STCTG`
- STORE MULTIPLE (64) `STMG`
- STORE MULTIPLE HIGH (32) `STMH`
- STORE MULTIPLE (32) `STMY`

##### UsesRegPairForTarget
- STORE PAIR TO QUADWORD `STPQ`

##### SingleFP
- STORE (long) `STD`

##### DoubleFP
- STORE (short) `STE`
