### ISSUE TITLE
Date inconsistency in the omr repository commits

### ISSUE THREAD

**Issue by singh264** [eclipse/omr#6248]
https://support.github.com/ticket/personal/0/1400481

**Comment by 0xdaryl** [comment]
That linked ticket is not accessible (to me at least).  Can you describe the problem so contributors know what to look out for?

**Comment by singh264** [comment]
I think the Date property of the items in the output of the git log command that is run on a cloned omr repository is inconsistent with the commits on Nov 15, 2021 in the omr repository.

I think the Date property of the items in the output of the git log command that is run on a cloned omr repository are:
Date: Tue Nov 16 01:55:59 2021 +0000
Date: Mon Nov 15 19:47:01 2021 -0500
Date: Wed Oct 27 15:37:03 2021 -0400

I think the commits on Nov 15, 2021 in the omr repository are:
https://github.com/eclipse/omr/commit/f76321aa3ba1e85e71bd57c8c22b5d6cf427b4f5
https://github.com/eclipse/omr/commit/22400381ea7bc9e394282882b3af6bb0b3cb7a42
https://github.com/eclipse/omr/commit/c91ca47c9abc8315187f88d33ffcb3d53c508113

**Comment by singh264** [comment]
How could the commit date and the author date in the [patch url](https://github.com/eclipse/omr/commit/f76321aa3ba1e85e71bd57c8c22b5d6cf427b4f5.patch) of the commit be identified in the [merged pull request](https://github.com/eclipse/omr/pull/6237/commits)?

**Comment by singh264** [comment]
> How could the commit date and the author date in the [patch url](https://github.com/eclipse/omr/commit/f76321aa3ba1e85e71bd57c8c22b5d6cf427b4f5.patch) of the commit be identified in the [merged pull request](https://github.com/eclipse/omr/pull/6237/commits)?

I think the commit date appears after the commit SHA in the patch url of the commit and the author date appears after the Date property in the patch url of the commit.

**Comment by singh264** [comment]
> I think the Date property of the items in the output of the git log command that is run on a cloned omr repository is inconsistent with the commits on Nov 15, 2021 in the omr repository.
> 
> I think the Date property of the items in the output of the git log command that is run on a cloned omr repository are: Date: Tue Nov 16 01:55:59 2021 +0000 Date: Mon Nov 15 19:47:01 2021 -0500 Date: Wed Oct 27 15:37:03 2021 -0400
> 
> I think the commits on Nov 15, 2021 in the omr repository are: [f76321a](https://github.com/eclipse/omr/commit/f76321aa3ba1e85e71bd57c8c22b5d6cf427b4f5) [2240038](https://github.com/eclipse/omr/commit/22400381ea7bc9e394282882b3af6bb0b3cb7a42) [c91ca47](https://github.com/eclipse/omr/commit/c91ca47c9abc8315187f88d33ffcb3d53c508113)

@0xdaryl What are the details of the commits on Nov 15, 2021 in the output of the git log command that is run on a cloned omr repository?

I think the details of the commits on Nov 15, 2021 in the output of the git log command that is run on a cloned omr repository are:

f76321a https://ibm.box.com/s/chsymkoj07jlmcyg9lufaivgu6wsa95r

2240038 https://ibm.box.com/s/cz15hvs499d2njdk44zya6xndkpnfptl

c91ca47 https://ibm.box.com/s/v3b5740xigbyi03j82s7q6wyvn6mr649

**Comment by singh264** [comment]
@0xdaryl @ymanton

**Comment by singh264** [comment]
@ymanton

**Comment by ymanton** [comment]
I think you are being confused by two things here: time zones and commit v.s. author dates.

GitHub shows you commit dates, while `git log`, `git show`, etc show you author dates by default. That's why GitHub is showing you that c91ca47 was committed on Nov 15 while git shows you that the patch was authored on Oct 27:

```
commit c91ca47c9abc8315187f88d33ffcb3d53c508113
Author: midronij <jackie.midroni@ibm.com>
Date:   Wed Oct 27 15:37:03 2021 -0400
```

If you want to see the complete output from git try `git show --format=fuller c91ca47`:

```
commit c91ca47c9abc8315187f88d33ffcb3d53c508113
Author:     midronij <jackie.midroni@ibm.com>
AuthorDate: Wed Oct 27 15:37:03 2021 -0400
Commit:     midronij <jackie.midroni@ibm.com>
CommitDate: Mon Nov 15 09:54:24 2021 -0500
```

For f76321a the commit and author dates are the same because it is a merge commit, so that is not the issue. You have to take into consideration time zones and know how to interpret UTC +/- offset notation. GitHub shows you "Nov 15, 2021" and when you hover over that date it (I assume) expands to "Nov 15, 2021, 8:55 PM EST" (or earlier if you are in a different time zone). This is the same exact date/time as "Tue Nov 16 01:55:59 2021 +0000".

**Comment by 0xdaryl** [comment]
Is @ymanton's assessment of the problem correct?  If so, should this issue be closed?

**Comment by singh264** [comment]
> I think you are being confused by two things here: time zones and commit v.s. author dates.
> 
> GitHub shows you commit dates, while `git log`, `git show`, etc show you author dates by default. That's why GitHub is showing you that [c91ca47](https://github.com/eclipse/omr/commit/c91ca47c9abc8315187f88d33ffcb3d53c508113) was committed on Nov 15 while git shows you that the patch was authored on Oct 27:
> 
> ```
> commit c91ca47c9abc8315187f88d33ffcb3d53c508113
> Author: midronij <jackie.midroni@ibm.com>
> Date:   Wed Oct 27 15:37:03 2021 -0400
> ```
> 
> If you want to see the complete output from git try `git show --format=fuller c91ca47`:
> 
> ```
> commit c91ca47c9abc8315187f88d33ffcb3d53c508113
> Author:     midronij <jackie.midroni@ibm.com>
> AuthorDate: Wed Oct 27 15:37:03 2021 -0400
> Commit:     midronij <jackie.midroni@ibm.com>
> CommitDate: Mon Nov 15 09:54:24 2021 -0500
> ```
> 
> For [f76321a](https://github.com/eclipse/omr/commit/f76321aa3ba1e85e71bd57c8c22b5d6cf427b4f5) the commit and author dates are the same because it is a merge commit, so that is not the issue. You have to take into consideration time zones and know how to interpret UTC +/- offset notation. GitHub shows you "Nov 15, 2021" and when you hover over that date it (I assume) expands to "Nov 15, 2021, 8:55 PM EST" (or earlier if you are in a different time zone). This is the same exact date/time as "Tue Nov 16 01:55:59 2021 +0000".

I think the details of the commits on Nov 15, 2021 in the output of the git show command that is run on the cloned omr repository are:

f76321a https://drive.google.com/file/d/14ILMqZoZEGjTluMSHJPuuQl6-gm_LQre/view?usp=sharing.

2240038 https://drive.google.com/file/d/1kql4q-eylwr2ssGSM6vr1IPQwgnWKfRK/view?usp=sharing.

c91ca47 https://drive.google.com/file/d/1Hr8Sz9EyXn2IFRP59tcmSSBxfR09cVG3/view?usp=sharing.

**Comment by singh264** [comment]
> Is @ymanton's assessment of the problem correct? If so, should this issue be closed?

I think the assessment of the problem is correct and the GitHub issue could be closed.
