### ISSUE TITLE
compilation failure when I try to use our own glue instead of example/glue.

### ISSUE THREAD

**Issue by zheddie** [eclipse/omr#639]
Hi, I am trying to use OMR as the VM for smalltalk based on SOM++ project, I hit a few problem when do the compilation.  Here's the code for my project:  https://github.com/zheddie/somr

Here's the first issue I hit. 
c++ -o ../omrgcexample main.o argmain.o   -lstdc++ -liconv -lpthread  -L. -L.. -L../lib  -lomrglue -lj9omr -lomrgcbase -lomrgcstructs -lomrgcstats -lomrgcstandard -lomrgcstartup -lj9hookstatic -lj9prtstatic -lj9thrstatic -lomrgcverbose -lomrgcverbosehandlerstandard -lomrutil -lj9avl -lj9hashtable -lj9pool -lomrtrace -lomrvmstartup -ltestutil  -lm -lpthread -lc -ldl -lutil -fpic -ggdb -Wl,-rpath,\$ORIGIN
Undefined symbols for architecture x86_64:
  "Interpreter::GetFrame()", referenced from:
      MM_CollectorLanguageInterfaceImpl::markingScheme_scanRoots(MM_EnvironmentBase*) in libomrglue.a(CollectorLanguageInterfaceImpl.o)
  "Universe::GetUniverse()", referenced from:
      MM_CollectorLanguageInterfaceImpl::markingScheme_scanRoots(MM_EnvironmentBase*) in libomrglue.a(CollectorLanguageInterfaceImpl.o)
  "_globalGcCount", referenced from:
      MM_CollectorLanguageInterfaceImpl::markingScheme_scanRoots(MM_EnvironmentBase*) in libomrglue.a(CollectorLanguageInterfaceImpl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

THis issue could be fixed by modify rules.osx.mk file , to include the “-undefined dynamic_lookup” in GLOBAL_LDFLAGS. Further more, in fact, we need to modify run_configure.mk to disable the OMR_EXAMPLE if customer use their own glue instead of "example/glue".

Secondly, I hit following issue:

dyld: Symbol not found: __ZTI14MM_BaseVirtual
  Referenced from: somr.dylib
  Expected in: flat namespace
 in somr.dylib

This issue seems complain on the implementation of the virtual functions are not reside in the .hpp. Anyway, I just moved the implementation from .cpp to .hpp to fix this issue. Not sure whether there's other more effective ways to fix it or not. Following files need to be modified .
gc/base/BaseVirtual.hpp
gc/base/BaseVirtual.cpp
gc/base/StartupManager.cpp
gc/base/StartupManager.hpp
gc/verbose/VerboseManager.cpp
gc/verbose/VerboseManager.hpp

The last one is caused by the above change in second issue.  The makefile under gc/startup need to be changed to add ../verbose/handler_standard  to MODULE_INCLUDES to let OMR find the corresponding head files.

I would create a pull request on it for your review. thanks.

**Comment by mstoodle** [comment]
Hi @zheddie, thanks for taking a look and persevering through the issues you ran into. Based on a quick look, I suspect you may not be linking against all the things you should be, but I could be wrong. Most of your changes have been in the gc component, so I'll defer to @charliegracie 's opinion.

For reference and if you haven't seen it already, you can also take a look at @charliegracie 's OMR based SOM++ implementation which also has a JitBuilder based JIT compiler: https://github.com/charliegracie/SOMpp . I don't think it has his most recent updates, but if you dig through the branches a bit, you should be able to find the basic OMR hookup commits without too much trouble.

**Comment by zheddie** [comment]
Thanks @mstoodle . We use that project just for learning on omr.  Currently , our project works now, with some changes in OMR as in pull-reqeust #645 . Not sure whether @charliegracie  hit them as well during his implementation.  But as we know, OMR changed a lot since his impl. Let's see what he will comment on it. thanks.

**Comment by zheddie** [comment]
BTW, the changes in rules.osx.mk is no need now. I have figured out the ways to disable the build for OMR_EXAMPLE and fvtest from the glue's configuration file.

**Comment by zheddie** [comment]
Sorry, I had to close my pull request #645, as I finally figured out the root cause of the issue. The change in #645 is just a workaround.  I think the root cause of the issue is "-fno-rtti". Seems currently OMR do not support RTTI, while my SOM++ code is using RTTI .  Not sure how do you think is the best way to support this kind of language impl. But the shortest way for me is just remove the "-fno-rtti" from the rules.<platform>.mk.  Thoughts?

**Comment by mstoodle** [comment]
Are you actually using runtime types in your SOM++ code?

**Comment by zheddie** [comment]
yes, we used dynamic_cast over 20 places.

**Comment by charliegracie** [comment]
Hi, sorry about my slow response.  I was away on vacation.  Is it ok to close this issue now and let #646?

**Comment by charliegracie** [comment]
Closing as I believe #646 this fix for this was completed under #646.
