### ISSUE TITLE
Tolerating RTTI in OMR 

### ISSUE THREAD

**Issue by mgaudet** [eclipse/omr#646]
By default, OMR builds with `-fno-rtti` (or platform equivalent). 

Given the issues @zheddie ran into in #639, I think we need to discuss whether or not we want to tolerate RTTI for OMR.

If we decide this is something to support, a `configure` flag ought to be added, and we'll have to put support into the makefiles.

**Comment by zheddie** [comment]
Agree with you @mgaudet ,something like --enable-OMR_RTTI in configure_<platform>.mk could fix this kind of issue.

**Comment by mgaudet** [comment]
I think we can close this now given that  #648 got merged. 

Reopen if this is a mistake
