### ISSUE TITLE
Put TR_RegisterCandidate(s) and TR_GlobalRegister in TR Namespace

### ISSUE THREAD

**Issue by kevindean12** [eclipse/omr#6529]
In order to make the classes found in optimizer/RegisterCandidate.hpp/cpp available for downstream projects to customize their implementations of those classes, I'd like to be able to move them into the TR namespace where they can inherit from an OMR-namespace base class (between which projects can insert their own derived class with their modifications). This would be a similar structure to, for example, the CFGSimplifier and the LocalCSE classes.

Doing so for TR_RegisterCandidate would likely involve removing the TR_Link<TR_RegisterCandidate> from the inheritance hierarchy and putting a TR::RegisterCandidate \*_next member with getter/setter (as found in the Link/Link0 class) into the RegisterCandidate class, since the type of _next would always be a TR::RegisterCandidate*.(Although I'm open to suggestions if there are other preferences about that).

Since making this change would involve changing quite a few TR_RegisterCandidate/TR_RegisterCandidates/TR_GlobalRegister instances to TR::XXXX and, potentially, modifying the inheritance hierarchy for the TR_RegisterCandidate class as mentioned above, I wanted to check the temperature on the community's feeling toward such a change here before implementing it.

Does this sound like a reasonable approach, @0xdaryl , others?

**Comment by mstoodle** [comment]
Is there a reason you don't want to have `TR_Link<TR::RegisterCandidate>` as the base class for `OMR::RegisterCandidate` (or whatever class you decide to call the common OMR base layer of the extensible class)?

**Comment by kevindean12** [comment]
Actually, you're right that that should work just fine to use `TR_Link<TR::RegisterCandidate>` as the base class, then no need to have to add the additional members to RegisterCandidate. I can do it that way.
