### ISSUE TITLE
doDelayedTransformations processing removed nodes

### ISSUE THREAD

**Issue by JamesKingdon** [eclipse/omr#6623]
During globalVP it is possible for a node to be placed in the lists of delayed transformations in the first pass of a loop, and then those nodes (and their successors) to be removed during the second pass. `doDelayedTransformations` then performs the transformations anyway, restoring potentially broken nodes to the trees (e.g. later nodes that had their children removed) and overwriting the return instruction that was inserted during removal. In cases seen so far this results in crashes during later optimisations.

It's unclear to me how best to fix this problem. It seems that we could:

a) Check if any nodes that are about to be removed exist in the lists of delayed transformations, and if so skip the entire removal action.

b) Check the lists of delayed transformations for each removed node and if found, remove them from the lists.

c) When processing the lists of delayed transformations, check to see if the node is still valid for the transformation.

The first choice seems overly conservative and gives up the benefits of removing unreachable nodes a little too easily. b) looks like it may become computationally expensive if the number of removed nodes and delayed transformations can get large as the obvious implementation would be O(n.m). And I'm not yet sure if c) is possible/practical.

**Comment by 0xdaryl** [comment]
One thing I'm not clear on is whether the delayed transformations can be dependent on one another.  Meaning, if you remove one transformation from the list are there others that require that transformation happening that you would also have to find and remove from the list?  Or can delayed transformations be applied in any order?  @hzongaro @vijaysun-omr if you know ottoyh.

@JamesKingdon, can you describe the circumstances of this problem?  I just want to be certain that the node selected for removal (and already living on a delayed transformation list) should have been selected for removal in the first place.

**Comment by vijaysun-omr** [comment]
I'll point out https://github.com/eclipse/omr/blob/5330053254111a4e41c4afeabd53c7a5e5c16034/compiler/optimizer/OMRValuePropagation.cpp#L7492 since that checks if a block still exists in the CFG or not before transforming it. Seemed relevant to the topic but will let @JamesKingdon answer in response the prior comment.

**Comment by JamesKingdon** [comment]
Sorry for the delay, will try and get to this later today.

**Comment by JamesKingdon** [comment]
@jdmpapin crafted a testcase to reproduce the failure and can doubtless speak to the issue more accurately than I can, but using a log generated from the testcase I can describe my understanding. The following block is where the action happens:

```
n46n      BBStart <block_6> (freq 10000) (in loop 6)                                          [0x7f4acedaa5a0] bci=[-1,42,39] rc=0 vc=52 vn=57 li=- udi=- nc=0
n51n      checkcast [#86]                                                                     [0x7f4acedaa730] bci=[-1,44,39] rc=0 vc=52 vn=58 li=- udi=- nc=2
n49n        aload  <auto slot 4>[#391  Auto] [flags 0x7 0x0 ]                                 [0x7f4acedaa690] bci=[-1,42,39] rc=2 vc=52 vn=20 li=17 udi=23 nc=0
n50n        loadaddr  java/lang/Float[#394  Static] [flags 0x18307 0x0 ]                      [0x7f4acedaa6e0] bci=[-1,44,39] rc=1 vc=52 vn=19 li=- udi=- nc=0
n52n      astore  <auto slot 7>[#395  Auto] [flags 0x7 0x0 ]                                  [0x7f4acee25000] bci=[-1,47,39] rc=0 vc=52 vn=20 li=- udi=9 nc=1
n49n        ==>aload
n56n      NULLCHK on n53n [#32]                                                               [0x7f4acee25140] bci=[-1,50,47] rc=0 vc=52 vn=22 li=- udi=- nc=1
n55n        acalli  java/lang/Object.clone()Ljava/lang/Object;[#397  virtual Method -24] [flags 0x500 0x0 ]  [0x7f4acee250f0] bci=[-1,50,47] rc=4 vc=52 vn=23 li=- udi=- nc=2
n54n          aloadi  <vft-symbol>[#309  Shadow] [flags 0x18607 0x0 ]                         [0x7f4acee250a0] bci=[-1,50,47] rc=1 vc=52 vn=21 li=- udi=- nc=1
n81n            aload  <parm 1 [I>[#382  Parm] [flags 0x40000107 0x0 ] (X>=0 sharedMemory )   [0x7f4acee25910] bci=[-1,49,47] rc=1 vc=52 vn=2 li=- udi=24 nc=0 flg=0x100
n53n          aload  <parm 1 [I>[#382  Parm] [flags 0x40000107 0x0 ]                          [0x7f4acee25050] bci=[-1,49,47] rc=1 vc=52 vn=2 li=- udi=25 nc=0
n57n      astore  <pending push temp 0>[#385  Auto] [flags 0x7 0x800 ]                        [0x7f4acee25190] bci=[-1,50,47] rc=0 vc=52 vn=23 li=10 udi=10 nc=1
n55n        ==>acalli
n61n      checkcast [#86]                                                                     [0x7f4acee252d0] bci=[-1,53,47] rc=0 vc=52 vn=60 li=- udi=- nc=2
n55n        ==>acalli
n60n        loadaddr  [I[#398  Static] [flags 0x18307 0x0 ]                                   [0x7f4acee25280] bci=[-1,53,47] rc=1 vc=52 vn=24 li=- udi=- nc=0
n62n      astore  <auto slot 5>[#392  Auto] [flags 0x7 0x0 ]                                  [0x7f4acee25320] bci=[-1,56,47] rc=0 vc=52 vn=23 li=- udi=11 nc=1
n55n        ==>acalli
n64n      treetop                                                                             [0x7f4acee253c0] bci=[-1,58,49] rc=0 vc=52 vn=62 li=- udi=- nc=1
n63n        call  VpBug.opaqueFoo()V[#399  static Method] [flags 0x500 0x0 ]                  [0x7f4acee25370] bci=[-1,58,49] rc=1 vc=52 vn=61 li=- udi=- nc=0
n142n     ificmpne --> block_13 BBStart at n143n (osrGuard )                                  [0x7f4acee26c20] bci=[-1,0,21] rc=0 vc=52 vn=63 li=- udi=- nc=2 flg=0xc020
n140n       iload  unknown static[#404  Static] [flags 0x10303 0x0 ]                          [0x7f4acee26b80] bci=[-1,58,49] rc=1 vc=52 vn=25 li=- udi=- nc=0
n141n       iconst 0                                                                          [0x7f4acee26bd0] bci=[-1,58,49] rc=1 vc=52 vn=6 li=- udi=- nc=0
n130n     BBEnd </block_6> =====                                                              [0x7f4acee26860] bci=[0,0,58] rc=0 vc=52 vn=64 li=- udi=- nc=0
```

The block is within a loop and is processed in multiple passes. On the first pass n55n is placed in the deferred list for delayed transformations in order to inline a newarray/arraycopy sequence instead of the call to Object.clone(). On the second (last?) pass 
the checkcast at n51n is determined to always fail, a return is inserted and the following nodes are removed from the block. Later the delayed transformations process the acalli node n55n, the return is lost, and some (but not all) of the old nodes are pulled back into the block. In particular the ificmpne appears, but without any children:

```
n46n      BBStart <block_6> (freq 10000)                                                      [0x7f4acedaa5a0] bci=[-1,42,39] rc=0 vc=56 vn=57 li=- udi=- nc=0
n51n      checkcast [#86]                                                                     [0x7f4acedaa730] bci=[-1,44,39] rc=0 vc=56 vn=58 li=- udi=- nc=2
n49n        aload  <auto slot 4>[#391  Auto] [flags 0x7 0x0 ] (X!=0 sharedMemory )            [0x7f4acedaa690] bci=[-1,42,39] rc=1 vc=56 vn=20 li=17 udi=23 nc=0 flg=0x4
n50n        loadaddr  java/lang/Float[#394  Static] [flags 0x18307 0x0 ]                      [0x7f4acedaa6e0] bci=[-1,44,39] rc=1 vc=56 vn=19 li=- udi=- nc=0
n182n     NULLCHK on n53n [#32]                                                               [0x7f4acee278a0] bci=[-1,50,47] rc=0 vc=0 vn=90 li=- udi=- nc=1
n181n       PassThrough                                                                       [0x7f4acee27850] bci=[-1,50,47] rc=1 vc=0 vn=89 li=- udi=- nc=1
n53n          aload  <parm 1 [I>[#382  Parm] [flags 0x40000107 0x0 ]                          [0x7f4acee25050] bci=[-1,49,47] rc=3 vc=55 vn=2 li=- udi=- nc=0
n184n     treetop                                                                             [0x7f4acee27940] bci=[-1,50,47] rc=0 vc=0 vn=92 li=- udi=- nc=1
n180n       arraylength                                                                       [0x7f4acee27800] bci=[-1,50,47] rc=3 vc=0 vn=88 li=- udi=- nc=1
n53n          ==>aload
n194n     treetop                                                                             [0x7f4acee27c60] bci=[-1,50,47] rc=0 vc=0 vn=102 li=- udi=- nc=1
n55n        newarray  jitNewArrayNoZeroInit[#31  helper Method] [flags 0x400 0x0 ] (X!=0 skipZeroInit sharedMemory )  [0x7f4acee250f0] bci=[-1,50,47] rc=2 vc=55 vn=23 li=- udi=- nc=2 flg=0x8004
n180n         ==>arraylength
n185n         iconst 10   ; array type is int                                                 [0x7f4acee27990] bci=[-1,50,47] rc=1 vc=0 vn=93 li=- udi=- nc=0
n195n     treetop                                                                             [0x7f4acee27cb0] bci=[-1,50,47] rc=0 vc=0 vn=103 li=- udi=- nc=1
n193n       arraycopy  <arraycopy>[#220  helper Method] [flags 0x400 0x0 ] (Unsigned cannotOverflow forwardArrayCopy noArrayStoreCheckArrayCopy wordElementArrayCopy )  [0x7f4acee27c10] bci=[-1,50,47] rc=1 vc=0 vn=101 li=- udi=- nc=3 flg=0xd020
n190n         aladd                                                                           [0x7f4acee27b20] bci=[-1,50,47] rc=1 vc=0 vn=98 li=- udi=- nc=2
n53n            ==>aload
n189n           lconst 16                                                                     [0x7f4acee27ad0] bci=[-1,49,47] rc=1 vc=0 vn=97 li=- udi=- nc=0
n192n         aladd                                                                           [0x7f4acee27bc0] bci=[-1,50,47] rc=1 vc=0 vn=100 li=- udi=- nc=2
n55n            ==>newarray
n191n           lconst 16                                                                     [0x7f4acee27b70] bci=[-1,50,47] rc=1 vc=0 vn=99 li=- udi=- nc=0
n188n         lmul                                                                            [0x7f4acee27a80] bci=[-1,50,47] rc=1 vc=0 vn=96 li=- udi=- nc=2
n187n           i2l                                                                           [0x7f4acee27a30] bci=[-1,50,47] rc=1 vc=0 vn=95 li=- udi=- nc=1
n180n             ==>arraylength
n186n           lconst 4                                                                      [0x7f4acee279e0] bci=[-1,50,47] rc=1 vc=0 vn=94 li=- udi=- nc=0
n56n      treetop                                                                             [0x7f4acee25140] bci=[-1,50,47] rc=-2 vc=55 vn=22 li=- udi=- nc=0
n57n      astore  <pending push temp 0>[#385  Auto] [flags 0x7 0x800 ] (X!=0 sharedMemory )   [0x7f4acee25190] bci=[-1,50,47] rc=-2 vc=55 vn=23 li=10 udi=- nc=0 flg=0x4
n61n      treetop                                                                             [0x7f4acee252d0] bci=[-1,53,47] rc=-2 vc=55 vn=60 li=- udi=- nc=0
n62n      astore  <auto slot 5>[#392  Auto] [flags 0x7 0x0 ] (X!=0 sharedMemory )             [0x7f4acee25320] bci=[-1,56,47] rc=-2 vc=55 vn=23 li=- udi=- nc=0 flg=0x4
n64n      treetop                                                                             [0x7f4acee253c0] bci=[-1,58,49] rc=-2 vc=55 vn=62 li=- udi=- nc=0
n142n     ificmpne --> block_13 BBStart at n143n (osrGuard )                                  [0x7f4acee26c20] bci=[-1,0,21] rc=-2 vc=55 vn=63 li=- udi=- nc=0 flg=0xc020
n130n     BBEnd </block_6>                                                                    [0x7f4acee26860] bci=[0,0,58] rc=0 vc=53 vn=64 li=- udi=- nc=0
```

**Comment by vijaysun-omr** [comment]
I found another couple of pieces of code that seems to be trying to avoid transforming removed code : 

https://github.com/eclipse/omr/blob/5330053254111a4e41c4afeabd53c7a5e5c16034/compiler/optimizer/ValuePropagationCommon.cpp#L2936

and

https://github.com/eclipse/omr/blob/5330053254111a4e41c4afeabd53c7a5e5c16034/compiler/optimizer/ValuePropagationCommon.cpp#L2936

Maybe one of the newer transformations added `transformObjectCloneCall` for `clone` needs that sort of a test ?

**Comment by JamesKingdon** [comment]
Testcase with many thanks to @jdmpapin 

```
public class VpBug {
    public static boolean unknownCondition = true;
    public static Object unknownObject = -1;

    public static void main(String[] args) throws Exception {
        // sleep to get out of startup so that we can generate an OSR guard
        Thread.sleep(args.length == 0 ? 5000 : Integer.parseInt(args[0]));
        wrapGo();
        wrapGo();
    }

    public static void wrapGo() {
        try {
            go(42, new int[16]);
        } catch (Throwable exc) {
            exc.printStackTrace();
        }
    }

    public static int[] go(Integer x, int[] a) {
        x.getClass(); // null check

        Object y = x;
        if (unknownCondition) {
            y = unknownObject; // ensure that x, y have different value numbers below
        }

        // VP learns that y is an Integer with a non-global constraint.
        y.getClass(); // null check
        Integer intY = (Integer)y;

        Object fObj = x;
        int[] result = null;
        for (int i = 0; i < 2; i++) {
            // This cast can't succeed, but VP can't tell that the first time
            // through because it can't constrain fObj. The second time
            // through, it will have constraints for all defs of fObj, and all
            // of them will be Integer, so then
            Float f = (Float)fObj;

            // This clone() call will be put on the list the first time through
            // to be transformed in doDelayedTransformations(). Then the second
            // time through, when VP discovers that the checkcast must throw,
            // this call will be removed from the trees along with the rest of
            // the block, but doDelayedTransformations() will still try to
            // transform it.
            result = a.clone(); // avoid reassigning a, so that VP can get its type

            opaqueFoo(); // OSR guard after this call
            inlineBar(); // HCR guard eliminated
            fObj = y; // ensure that fObj above gets its own value number
        }

        return a;
    }

    public static void opaqueFoo() {}
    public static void inlineBar() {}
}
```

Invocation:

`java -Xshareclasses:none -Xjit:limit={*.go(*)*},count=1,disableAsyncCompilation,inhibitRecompilation,initialOptLevel=warm,tryToInline={*.inline*},dontInline={*.opaque*} VpBug`

**Comment by vijaysun-omr** [comment]
There is one subtle difference in what those places I pasted above are doing what we need to do in this case (from the trees pasted by James). It seems the `clone` call itself is not removed but some parent nodes have been removed. So the check that is being done in those other routines cannot simply be done on the `clone` call node itself.

**Comment by vijaysun-omr** [comment]
Ignore my prior comment, there are two checkcasts in that block and the first one is the one folded as per James' comment. In this case a test such as the one I mentioned in my prior comment that checks if the reference count is < 0 would work if done on the clone node I think. 

Whether there ought to be a more robust way to deal with this in `doDelayedTransformations` (rather than routines it calls) is a different and possibly longer term question.

**Comment by JamesKingdon** [comment]
I confirmed that adding

  ```
 if (callNode->getReferenceCount() < 1) {
      return;
   }
```

to transformArrayCloneCall prevents the crash.

**Comment by vijaysun-omr** [comment]
Maybe the same needs to be done in `transformObjectCloneCall` at least (potentially other routines called from `doDelayedTransformations`)

**Comment by JamesKingdon** [comment]
So that's exactly what I was wondering - there doesn't seem to be anything specific about the array clone transformation that makes it vulnerable to this problem, and there are many optimisations called from the the two layers of doDelayedTransformations. Should they all defend against removed nodes? At least the first one I've looked at doesn't seem to.

**Comment by vijaysun-omr** [comment]
Some of the routines called from `doDelayedTransformations` do guard against it (see my earlier comment https://github.com/eclipse/omr/issues/6623#issuecomment-1195632027) and some do not. So, either we need to guard all the routines that do transformations (called from `doDelayedTransformations` ) or we need to think of something more robust in that routine itself such that future callees don't get bitten by the same issue as I touched upon in my earlier comment https://github.com/eclipse/omr/issues/6623#issuecomment-1195651137 ). The former would be easiest to do the short term to resolve any failures that you might have, but the latter is also worth thinking about (but can be deferred until after you resolve the case at hand).

**Comment by JamesKingdon** [comment]
Adding the correctly transformed block_6 with the fix in place
```
n46n      BBStart <block_6> (freq 10000)                                                      [0x7faeb854a5a0] bci=[-1,42,39] rc=0 vc=56 vn=57 li=- udi=- nc=0
n51n      checkcast [#86]                                                                     [0x7faeb854a730] bci=[-1,44,39] rc=0 vc=56 vn=58 li=- udi=- nc=2
n49n        aload  <auto slot 4>[#391  Auto] [flags 0x7 0x0 ] (X!=0 sharedMemory )            [0x7faeb854a690] bci=[-1,42,39] rc=1 vc=56 vn=20 li=17 udi=23 nc=0 flg=0x4
n50n        loadaddr  java/lang/Float[#394  Static] [flags 0x18307 0x0 ]                      [0x7faeb854a6e0] bci=[-1,44,39] rc=1 vc=56 vn=19 li=- udi=- nc=0
n179n     return                                                                              [0x7faeb85c77b0] bci=[-1,44,39] rc=0 vc=56 vn=87 li=- udi=- nc=0
n130n     BBEnd </block_6>                                                                    [0x7faeb85c6860] bci=[0,0,58] rc=0 vc=53 vn=64 li=- udi=- nc=0
```

**Comment by JamesKingdon** [comment]
I confirmed that the crash also happens with Object.clone(), although `TR_enableDynamicObjectClone` has to be set to enable that code path.

**Comment by JamesKingdon** [comment]
Created https://github.com/eclipse/omr/pull/6630 to avoid the issue with transformObjectCloneCall and transformArrayCloneCall only. A future review will be needed to decide if other transformations called from doDelayedTransformations require similar treatment.

**Comment by JamesKingdon** [comment]
@vijaysun-omr requested a new issue for follow-on work, so I've opened https://github.com/eclipse/omr/issues/6639
