### ISSUE TITLE
Agenda for September 22, 2022 OMR Architecture Meeting

### ISSUE THREAD

**Issue by 0xdaryl** [eclipse/omr#6635]
### Agenda

* Vector masking support (#6636) [ @gita-omr ]

[**Replay**](https://youtu.be/Ai9fShrhi48)

### Details
Thursday, September 22, 2022 @ 14:00 EDT (GMT -4), 90 minutes maximum

Join [Webex](https://ibm.webex.com/ibm/j.php?MTID=m9b0be9582df417952dfbc098c57aac4d)

Meeting number (access code): 491 674 744
Meeting password: omrrocks!

North America call-in number: 1-844-531-0958

[Other global call-in numbers (for audio only)](https://ibm.webex.com/cmp3300/webcomponents/widget/globalcallin/globalcallin.do?siteurl=ibm&serviceType=MC&eventID=332731373&tollFree=1)

**This meeting will be recorded and posted to the [Eclipse OMR YouTube channel](https://www.youtube.com/channel/UCO8MkTRrFnLefi5nqReOMMA).**

**Comment by mstoodle** [comment]
My apologies, but I will be unable to present on JitBullder 2 this week. I am still keen to provide an update, though, so please keep me on the agenda for the next meeting (Sep 22?)

**Comment by vsandhya1981** [comment]
If time permits, we could discuss on the issue  decodeConversionOpcode(): https://github.com/eclipse/omr/issues/6709
