### ISSUE TITLE
Cleanup use of `vectorToScalar` IL query

### ISSUE THREAD

**Issue by r30shah** [eclipse/omr#6658]
As per discussions in https://github.com/eclipse-openj9/openj9/pull/15709, `getVectorElementType()` is more preferable query when we want to know the element type of the Vector IL. There are some places in the code that calls `vectorToScalar` query which eventually calls `getVectorElementType()` to get the type of the element that vector IL represents. We should clean up `vectorToScalar` query from the codebase.

**Comment by r30shah** [comment]
FYI @gita-omr

**Comment by gita-omr** [comment]
Agree.
