### ISSUE TITLE
Build failure on Linux and Mac - member name not found

### ISSUE THREAD

**Issue by jamesgua** [eclipse/omr#6725]
Recently my local build failed on Linux_x86_64 and Mac OS, errors are same:
omr/gc/base/MarkingScheme.hpp:292:81: error: ‘class MM_GCExtensionsBase’ has no member named ‘isScavengerBackOutFlagRaised’

And I find out that it is at [GCExtensionsBase.hpp:1129](https://github.com/eclipse/omr/blob/master/gc/base/GCExtensionsBase.hpp#L1129) but guarded by macro **OMR_GC_MODRON_SCAVENGER**

**Comment by jamesgua** [comment]
On my Mac cmake cached variables (cmake -L):
-- Starting with CMake version 3.22.2
-- Found Git: /usr/local/bin/git (found version "2.35.1")
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- OMR: The CPU architecture is x86
-- OMR: The OS is osx
-- OMR: The tool configuration is gnu
-- OMR: The target data size is 64
-- Looking for dladdr
-- Looking for dladdr - found
-- The ASM compiler identification is Clang with GNU-like command-line
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- OMR: trace root is '/Users/jamesgua/git/src/github.com/omr'
CMake Warning at CMakeLists.txt:117 (message):
  In tree builds are not recommended


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/jamesgua/git/src/github.com/omr
-- Cache values
CMAKE_BUILD_TYPE:STRING=
CMAKE_INSTALL_PREFIX:PATH=/usr/local
CMAKE_OSX_ARCHITECTURES:STRING=
CMAKE_OSX_DEPLOYMENT_TARGET:STRING=
CMAKE_OSX_SYSROOT:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk
OMRPORT_OMRSIG_SUPPORT:BOOL=OFF
OMRTHREAD_LIB_AIX:BOOL=OFF
OMRTHREAD_LIB_UNIX:BOOL=ON
OMRTHREAD_LIB_WIN32:BOOL=OFF
OMRTHREAD_LIB_ZOS:BOOL=OFF
OMR_COMPILER:BOOL=OFF
OMR_CORE_GLUE_TARGET:STRING=omr_example_core_glue
OMR_DDR:BOOL=OFF
OMR_DEBUG_INFO_OUTPUT_EXTENSION:STRING=.dSYM
OMR_ENHANCED_WARNINGS:BOOL=ON
OMR_EXAMPLE:BOOL=ON
OMR_FLATTEN_DEBUG_INFO:BOOL=OFF
OMR_FVTEST:BOOL=ON
OMR_GC:BOOL=ON
OMR_GC_ALLOCATION_TAX:BOOL=ON
OMR_GC_API:BOOL=OFF
OMR_GC_API_TEST:BOOL=OFF
OMR_GC_BATCH_CLEAR_TLH:BOOL=ON
OMR_GC_COMBINATION_SPEC:BOOL=ON
OMR_GC_CONCURRENT_SCAVENGER:BOOL=OFF
OMR_GC_CONCURRENT_SWEEP:BOOL=OFF
OMR_GC_DEBUG_ASSERTS:BOOL=ON
OMR_GC_DOUBLE_MAPPING_FOR_SPARSE_HEAP_ALLOCATION:BOOL=OFF
OMR_GC_DOUBLE_MAP_ARRAYLETS:BOOL=OFF
OMR_GC_DYNAMIC_CLASS_UNLOADING:BOOL=OFF
OMR_GC_EXPERIMENTAL_CONTEXT:BOOL=OFF
OMR_GC_EXPERIMENTAL_OBJECT_SCANNER:BOOL=OFF
OMR_GC_FULL_LIB:STRING=omrgc_full
OMR_GC_GLUE_FULL_TARGET:STRING=NOTFOUND
OMR_GC_GLUE_TARGET:STRING=omr_example_gc_glue
OMR_GC_IDLE_HEAP_MANAGER:BOOL=OFF
OMR_GC_LARGE_OBJECT_AREA:BOOL=ON
OMR_GC_LEAF_BITS:BOOL=OFF
OMR_GC_LIB:STRING=omrgc
OMR_GC_MINIMUM_OBJECT_SIZE:BOOL=ON
OMR_GC_MODRON_COMPACTION:BOOL=OFF
OMR_GC_MODRON_CONCURRENT_MARK:BOOL=OFF
OMR_GC_MODRON_SCAVENGER:BOOL=OFF
OMR_GC_MODRON_STANDARD:BOOL=ON
OMR_GC_NON_ZERO_TLH:BOOL=ON
OMR_GC_OBJECT_ALLOCATION_NOTIFY:BOOL=OFF
OMR_GC_OBJECT_MAP:BOOL=OFF
OMR_GC_POINTER_MODE:STRING=full
OMR_GC_REALTIME:BOOL=OFF
OMR_GC_SCAN_OBJECT_GLUE:BOOL=OFF
OMR_GC_SEGREGATED_HEAP:BOOL=OFF
OMR_GC_TEST:BOOL=ON
OMR_GC_THREAD_LOCAL_HEAP:BOOL=ON
OMR_GC_TLH_PREFETCH_FTA:BOOL=OFF
OMR_GC_VLHGC:BOOL=OFF
OMR_GC_VLHGC_CONCURRENT_COPY_FORWARD:BOOL=OFF
OMR_HOOK_LIB:STRING=j9hookstatic
OMR_INSTALL_ARCHIVE_DIR:PATH=lib
OMR_INSTALL_BIN_DIR:PATH=bin
OMR_INSTALL_DATA_DIR:PATH=share/omr
OMR_INSTALL_INC_DIR:PATH=include
OMR_INSTALL_LIB_DIR:PATH=lib
OMR_INTERP_HAS_SEMAPHORES:BOOL=ON
OMR_JITBUILDER:BOOL=OFF
OMR_JITBUILDER_TEST:BOOL=OFF
OMR_LLJB:BOOL=OFF
OMR_MSVC_CRT:STRING=NOTFOUND
OMR_NOTIFY_POLICY_CONTROL:BOOL=OFF
OMR_OMRSIG:BOOL=ON
OMR_OPT_CUDA:BOOL=OFF
OMR_PORT:BOOL=ON
OMR_PORT_ALLOCATE_TOP_DOWN:BOOL=OFF
OMR_PORT_ASYNC_HANDLER:BOOL=OFF
OMR_PORT_CAN_RESERVE_SPECIFIC_ADDRESS:BOOL=ON
OMR_PORT_LIB:STRING=omrport
OMR_PORT_NUMA_SUPPORT:BOOL=OFF
OMR_PORT_ZOS_CEEHDLRSUPPORT:BOOL=OFF
OMR_RAS_GLUE_TARGET:STRING=omr_example_ras_glue
OMR_RAS_TDF_TRACE:BOOL=ON
OMR_SANITIZE:STRING=OFF
OMR_SANITIZER:STRING=OFF
OMR_SEPARATE_DEBUG_INFO:BOOL=OFF
OMR_SHARED_CACHE:BOOL=OFF
OMR_TEST_COMPILER:BOOL=OFF
OMR_THREAD:BOOL=ON
OMR_THREAD_LIB:STRING=j9thrstatic
OMR_THR_ADAPTIVE_SPIN:BOOL=ON
OMR_THR_CUSTOM_SPIN_OPTIONS:BOOL=OFF
OMR_THR_FORK_SUPPORT:BOOL=OFF
OMR_THR_JLM:BOOL=ON
OMR_THR_JLM_HOLD_TIMES:BOOL=ON
OMR_THR_LOCK_NURSERY:BOOL=ON
OMR_THR_MCS_LOCKS:BOOL=OFF
OMR_THR_SPIN_WAKE_CONTROL:BOOL=OFF
OMR_THR_THREE_TIER_LOCKING:BOOL=OFF
OMR_THR_YIELD_ALG:BOOL=OFF
OMR_TOOLCONFIG:STRING=gnu
OMR_TOOLS:BOOL=ON
OMR_TOOLS_IMPORTFILE:FILEPATH=IMPORTFILE-NOTFOUND
OMR_TOOLS_USE_NATIVE_ENCODING:BOOL=ON
OMR_TRACE_LIB:STRING=omrtrace
OMR_USE_NATIVE_ENCODING:BOOL=ON
OMR_UTIL_GLUE_TARGET:STRING=omr_example_util_glue
OMR_WARNINGS_AS_ERRORS:BOOL=ON

**Comment by babsingh** [comment]
re https://github.com/eclipse/omr/issues/6725#issuecomment-1256819812:

```
 OMR_GC_MODRON_SCAVENGER:BOOL=OFF
```

- In the above build, `OMR_GC_MODRON_SCAVENGER` is disabled.
- See https://github.com/eclipse/omr/pull/6702#issuecomment-1244532852 and surrounding comments for more details about the above issue.
- https://github.com/eclipse/omr/pull/6715 aims to resolve this issue.
- The current workaround is to enable the `OMR_GC_MODRON_SCAVENGER` flag.
- Try `cmake -Wdev -C ../cmake/caches/Travis.cmake ..` for configure.
- `Travis.cmake` enables the above flag:
    https://github.com/eclipse/omr/blob/24b511df5a7d1cb6638802fb68219e9c421d3af1/cmake/caches/Travis.cmake#L28

**Comment by jamesgua** [comment]
Thx! Seems it's a duplication of #6715, I'll wait for it.

**Comment by jamesgua** [comment]
Although #6715 merged and issue should be resolved, but I still get compilation error:

> [ 13%] Building CXX object gc/CMakeFiles/omrgc.dir/base/ObjectHeapIteratorAddressOrderedList.cpp.o
omr/gc/base/ObjectHeapIteratorAddressOrderedList.cpp:109:64: error: no member named 'getConsumedSizeInBytesWithHeaderBeforeMove' in 'GC_ObjectModel'; did you mean 'getConsumedSizeInBytesWithHeader'?
                                uintptr_t sizeInBytesBeforeMove = _extensions->objectModel.getConsumedSizeInBytesWithHeaderBeforeMove(header.getForwardedObject());
                                                                                           ^~~~~~~~~
getConsumedSizeInBytesWithHeader
omr/gc/base/ObjectModelBase.hpp:227:2: note: 'getConsumedSizeInBytesWithHeader' declared here
        getConsumedSizeInBytesWithHeader(omrobjectptr_t objectPtr)
        ^
1 error generated.

I did set **OMR_GC_MODRON_SCAVENGER** but now the method is guarded by **OMR_GC_DEFERRED_HASHCODE_INSERTION**.

**Comment by babsingh** [comment]
fyi @dmitripivkine

**Comment by jamesgua** [comment]
Tried to turn off two options and now the compilation succeed
> OMR_GC_MODRON_SCAVENGER:BOOL=OFF
> OMR_GC_CONCURRENT_SCAVENGER:BOOL=OFF
