### ISSUE TITLE
Consider updating references to openjdk.java.net

### ISSUE THREAD

**Issue by keithc-ca** [eclipse/omr#6755]
OpenJDK has started updating URLs so they refer instead to openjdk.org (see https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/0fe8bef36f6034d33d362e2d09b52f19cd66f352). The old URLs currently redirect to the new domain, but it's unclear how long that will be the case. If there were only a few references in this repository, I would have just opened a pull request, but the copyright notice of most files includes a reference to http://openjdk.java.net/legal/assembly-exception.html, so it seems prudent to discuss what action, if any, we should take.

**Comment by mstoodle** [comment]
I think we should update the link to reference openjdk.org . The link is just informational anyway. If nobody expresses a concern with this update in the next week (before Oct 13, say), then I propose we just make the change.
