### ISSUE TITLE
Stop maintaining a last-modified year in copyright notices

### ISSUE THREAD

**Issue by jdmpapin** [eclipse/omr#6879]
All of our source files start with a copyright notice containing two years, like the following:

```Copyright (c) 2000, 2019 IBM Corp. and others```

The first year tells us when the file contents were first written, and the second tells us when they were last modified.

Because the copyright notices are in this form, the second year needs to be updated the first time each file is modified in a given year. These updates are a widespread paper cut that affect many contributions, as contributors generally need to manually carry them out. Furthermore, committers need to ensure that the year is updated appropriately, and remembering to do so is so error prone that we have had to develop an automated check that runs in each PR. When the check fails, before merging we have to wait for (roughly speaking) a round trip through two humans. Sometimes it can be combined with another round trip that was necessary anyway, i.e. when review has found problems that need to be addressed, but sometimes it can't be. Finally, setting aside raw efficiency, some (many?) of us find dealing with these updates to be a hassle. It's annoying to have to appease a failing copyright check.

Recently there have been [rumblings](https://hynek.me/til/copyright-years/) online about the (lack of) necessity of updating copyright years in this way for open source projects, which prompted me to look into why we do this. It turns out that maintaining the last-modified year was a requirement from IBM (my current employer) at the time of open-sourcing. However, IBM has since dropped that requirement, so it's simply no longer necessary.

As such, I propose changing our copyright notices to the following format (which is acceptable to IBM):

```Copyright IBM Corp. and others <initial-year>```

For instance, the example copyright notice from above would become:

```Copyright IBM Corp. and others 2000```

By removing the last-modified year, it no longer needs to be maintained, and we can all save a little bit of time and be a little bit less annoyed.

I would be happy to personally carry out this change. I'd like to update all of the files at once so that we aren't still left with the problem of making sure that they are updated piecemeal as other changes flow into them. The only disruption would be some (extremely easy to resolve) merge conflicts in in-flight changes that already include updates to the year in the copyright notice.

Any objections?

**Comment by keithc-ca** [comment]
> IBM has since dropped that requirement

Please share a link that supports this claim.

**Comment by mstoodle** [comment]
> >    IBM has since dropped that requirement

> Please share a link that supports this claim.

I doubt there will be a public link to this effect, so this sharing will probably have to be behind the company firewall.

**Comment by mstoodle** [comment]
I confess that this feels like a code hygiene issue to me (and we have so many of those), but if 1) it's something that doesn't need to be done and 2) the second date provides no inherent value above capturing the original copyright, then I would support removing the second copyright date from the message. But that second one is sort of up to all the contributors to assess even though IBM has provide the bulk of contributions.

This also feels like a question we could get mired in, though, so I hope it's fairly clear cut across our community, or else I will quickly switch my position to "leave it the way it is and move on".

Since the urgency is (relatively) low and I want to give as many contributors as possible a chance to see this issue and comment, I suggest we set a deadline of March 1, 2023 to make a decision on this proposal.

**Comment by janvrany** [comment]
>  Furthermore, committers need to ensure that the year is updated appropriately, and remembering to do so is so error prone that we have had to develop an automated check that runs in each PR

I have pre-commit hook that checks and automatically updates copyright years in to-be-committed files. The only problem is when commit is made in one year and submitted / reviewed / merged in next one. In that case, `git rebase -i ... --exec "$(PWD)/.git/hook/pre-commit ."` fixes them. 

In case this proposal is rejected, it might help to provide such pre-commit hook for developers to use as convenience. I'm happy to provide mine as a starting point.

**Comment by jdmpapin** [comment]
> > > IBM has since dropped that requirement
> 
> > Please share a link that supports this claim.
> 
> I doubt there will be a public link to this effect, so this sharing will probably have to be behind the company firewall.

Yes, I don't believe that IBM publishes this policy to the general public, so contributors outside of IBM have only our word on this point. FWIW, if I were misrepresenting the policy here, I would expect to see another IBMer contradict me, and I'd also expect that IBM would be none too pleased with me. (This expectation is of course just my own opinion. I am not committing IBM or other IBMers to any particular response to such hypothetical misrepresentation, nor could I do so even if I wanted to.)

That said, if an IBM employee (namely me) were to submit a change to the copyright notices in the way I've proposed, I don't know that it would really make sense for an outside contributor to object *on the grounds of IBM policy* anyway.

**Comment by jdmpapin** [comment]
> I have pre-commit hook that checks and automatically updates copyright years in to-be-committed files. [...] `git rebase -i ... --exec "$(PWD)/.git/hook/pre-commit ."` fixes them.

Nice! I've written one as well :slightly_smiling_face:. From the sound of it, mine is a bit fancier, but as a result it has limited portability... Regardless, I'd still prefer for such hooks to be made obsolete.

> In case this proposal is rejected, it might help to provide such pre-commit hook for developers to use as convenience.

:+1:

**Comment by jdmpapin** [comment]
Quoting partly from the addendum to the OpenJ9 version of Mark's comment:
> Since the urgency is (relatively) low and I want to give as many contributors as possible a chance to see this issue and comment, I suggest we set a deadline of March 1, 2023 to make a decision on this proposal.
> ...
> We don't have to use the same date I mentioned [...] if others prefer a different date.

OK, this sounds good to me. So we're soliciting feedback until March 1. If anybody wants more time, please say so.

**Comment by gacholio** [comment]
I fully support reducing meaningless paperwork.

**Comment by mstoodle** [comment]
@jdmpapin it looks like there is no objection to our making this change if IBM is willing to update the copyright message. Would you please document here what you plan to do (hoping it hasn't changed dramatically from what you described earlier).

This message is the community's last chance to voice any contrary opinion. WIthout any objections to weigh in the balance, the change to update the copyright messages will be accepted once contributed by IBM.

**Comment by jdmpapin** [comment]
There have been no changes to my plan since the initial description. To briefly restate/elaborate just a little, I'll search/replace to change the current format (`Copyright (c) <initial-year>, <last-modified-year> IBM Corp. and others`) to the new one that I've proposed (`Copyright IBM Corp. and others <initial-year>`) in all files at once so that we don't have to update them piecemeal like we've been doing with the last-modified year. I don't think that as part of this change I'll add "and others" anywhere it might currently happen to be absent, but I will still change the format accordingly. In the same PR I will also remove the automatic copyright check and the .copyrightignore file.

**Comment by keithc-ca** [comment]
Before that change occurs, you should arrange to disable the existing copyright checking job, otherwise it will fail in every pull request going forward.

**Comment by jdmpapin** [comment]
> I don't think it's sufficient to simply remove files from the repository.

Oh, I thought it was. That's good to know, thanks.

**Comment by jdmpapin** [comment]
OK, I'm getting this rolling. I've requested that the PR copyright check be turned off, and once it is, I'll open the PR

**Comment by janvrany** [comment]
@jdmpapin : I suppose you'll use some script to update copyright headers. If so, may I kindly ask you to share the script for us who might need to run it on commits merged?

**Comment by jdmpapin** [comment]
Yes, I'm using a script, and I will share it in the PR. But I don't think I understand what you mean by "might need to run it on commits merged." If you mean that commits that are merged while my PR is open can prevent it from applying cleanly, in that case I'll rebase and re-run the script myself to update the PR. If you mean that once my PR is merged, it will prevent some other open PRs from applying cleanly (in particular those that update a copyright year), then I don't think that this script is what's needed to fix those. They should be fixed either by rebasing and resolving the conflict in favour of the new copyright notice, or (without rebasing) by amending commits to leave all copyright headers unchanged.

**Comment by janvrany** [comment]
> They should be fixed either by rebasing and resolving
Yes. The idea is to use the script together with `git rebase -i --exec 'some_script.sh'` to update copyrings and then rebase atop of master. 
I use (used) similar approach when updating copyrights for commit created in previous year but to-be-merged in the year(s) after. 

Anyway, not a big deal.

**Comment by jdmpapin** [comment]
Oh, I understand. My script updates all files, which isn't what we'd want in any other PR. I think it shouldn't be too hard though for me to make a new script that will automatically (say) undo copyright changes to get rid of the conflict. Then it wouldn't even be necessary to update the base commit of a branch
