### ISSUE TITLE
[MacOS] PortSysinfoTest sysinfo_set_limit_ADDRESS_SPACE fails

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#6924]
Recently, `PortSysinfoTest.sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE` started to consistently fail on x86-64 macOS.

> https://dev.azure.com/eclipse-omr/ea4519db-b27e-4d19-a971-f01491f803e3/_apis/build/builds/7225/logs/50

```
2023-03-08T18:51:11.9911710Z 32: /Users/runner/work/1/s/fvtest/porttest/si.cpp line  691: omrsysinfo_test_sysinfo_set_limit_ADDRESS_SPACE omrsysinfo_set_limit set ADDRESS_SPACE soft max FAILED
2023-03-08T18:51:11.9912870Z 32: 
2023-03-08T18:51:11.9913940Z 32: 		LastErrorNumber: -113
2023-03-08T18:51:11.9916930Z 32: 		LastErrorMessage: Invalid argument
2023-03-08T18:51:11.9917970Z 32: 
2023-03-08T18:51:11.9919030Z 32: /Users/runner/work/1/s/fvtest/porttest/testHelpers.cpp:109: Failure
2023-03-08T18:51:11.9920150Z 32: Value of: 0 == numberFailedTestsInComponent
2023-03-08T18:51:11.9925280Z 32:   Actual: false
2023-03-08T18:51:11.9927010Z 32: Expected: true
2023-03-08T18:51:11.9928030Z 32: Test failed!
2023-03-08T18:51:11.9930170Z 32: [  FAILED  ] PortSysinfoTest.sysinfo_test_sysinfo_set_limit_ADDRESS_SPACE (0 ms)
2023-03-08T18:51:11.9931240Z 32: originalSoftLimit=65536
2023-03-08T18:51:11.9934800Z 32: originalHardLimit=65536
2023-03-08T18:51:11.9937200Z 32: soft set to hard limit=65536
```

**Comment by AdamBrousseau** [comment]
#6910

**Comment by babsingh** [comment]
https://github.com/eclipse/omr/pull/6910 introduces the failure documented in this issue. @knn-k @AdamBrousseau Shall we revert https://github.com/eclipse/omr/pull/6910 until the failure is fixed? Unless we already know how to fix it.

**Comment by knn-k** [comment]
We needed to upgrade the Azure macOS by #6910 because the macOS-10.15 environment will be removed by the end of this month.
See https://github.com/actions/runner-images/issues/5583#issuecomment-1426004850

**Comment by babsingh** [comment]
Re https://github.com/actions/runner-images/issues/5583#issuecomment-1426004850:

Can we move to macos-11 (#6930) or macos-12 (#6929)? Preferably macos-12 if both work.

**Comment by babsingh** [comment]
macos-11 (https://github.com/eclipse/omr/pull/6930) worked but the same failure was seen with macos-12 (https://github.com/eclipse/omr/pull/6929). Can we temporarily move to macos-11? Meanwhile, we can fix the failure before transitioning back to macos-latest.

**Comment by knn-k** [comment]
I agree with switching to another macOS version that is available in Azure until we find what to do with sysinfo_set_limit_ADDRESS_SPACE.

**Comment by knn-k** [comment]
@AdamBrousseau Do you have any concern for #6930?

**Comment by knn-k** [comment]
This test failed in https://ci.eclipse.org/omr/job/PullRequest-osx_aarch64/89/ on mac11-aarch64-08.

**Comment by knn-k** [comment]
The test failed again in https://ci.eclipse.org/omr/job/PullRequest-osx_aarch64/90/ on mac13-aarch64-08.

**Comment by knn-k** [comment]
This test is failing consistently on mac13-aarch64-08 these days.

**Comment by AdamBrousseau** [comment]
Do you think it's code, or something machine side?
This machine is shared with the OpenJ9 farm. We can disable the sharing again to see if that helps? Also, we have Mac 12 and Mac 11 we could borrow to try if you think it is OS version.

**Comment by knn-k** [comment]
I opened PR #7069 as a fix for AArch64 macOS.
It seems 300,000 bytes is too small as the limit value on AArch64 macOS 13.

This issue was originally reported against x86-64 macOS, but I don't know what was the problem at that time.

**Comment by knn-k** [comment]
PR https://github.com/eclipse/omr/pull/7069 has been merged.  Running the PortSysinfoTest on mac13-aarch64-08 should be OK now.

**Comment by knn-k** [comment]
The PortSysinfoTest fails on x86-64 macOS when I change the OS version in Azure build to `macOS-latest`.
See PR #7070 and its test output https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=7815&view=logs&jobId=aa2fd561-a338-5537-45ee-49ae22aea958

```
32: [----------] 38 tests from PortSysinfoTest
32: /Users/runner/work/1/s/fvtest/porttest/si.cpp line  695: omrsysinfo_test_sysinfo_set_limit_ADDRESS_SPACE omrsysinfo_set_limit set ADDRESS_SPACE soft max FAILED
32: 
32: 		LastErrorNumber: -113
32: 		LastErrorMessage: Invalid argument
```

I opened PR #7071 to change the limit value for the test also on x86-64 macOS.

**Comment by babsingh** [comment]
Fixed by
- https://github.com/eclipse/omr/pull/7069
- https://github.com/eclipse/omr/pull/7071
- https://github.com/eclipse/omr/pull/7070
