### ISSUE TITLE
z/OS omrsignal_context.c doesn't compile on V2R2 with TARGET V2R1 or earlier

### ISSUE THREAD

**Issue by pshipton** [eclipse/omr#698]
edcwccwi.h contains compile time checks for __EDC_TARGET >= __EDC_LE4202 which affects which fields are visible in struct __jumpinfo, in particular related to vector registers. Bottom line, with these checks in place, compiling on V2R2 with a TARGET of V2R1 or earlier, the fields are not exposed and omrsignal_context.c doesn't compile. 

When compiling on V2R1 or earlier the test __EDC_TARGET >= __EDC_LE4202 is true because __EDC_LE4202 is not defined. When compiling on V2R2, __EDC_LE4202 is defined and the test is only true when the TARGET is V2R2 or later. The code supports multiple versions of z/OS without recompilation, but the compile time check hides the fields unless targeting V2R2 or later.

**Comment by charliegracie** [comment]
Closing as this was resolved via #700
