### ISSUE TITLE
How appropriate is this toolset for building native (not interpreted or JITed) runtimes?

### ISSUE THREAD

**Issue by theseoafs** [eclipse/omr#7]
If I am designing a language with a runtime that compiles to native code (e.g. Go, OCaml), is OMR still an appropriate choice? Or do the pieces (GC, threading) only work in the context of a VM?

Library looks great by the way, patiently awaiting more detailed documentation :)

**Comment by charliegracie** [comment]
Hi,

Yes, I believe you will be able to consume Eclipse OMR components as part of your compiled program. Once the JIT is released you should be able to use it to generate your static code.

We are actively working on documentation and getting up to speed with working as an Eclipse project.

**Comment by mstoodle** [comment]
Circling back here... The JIT has now been released (Sep 18). While it can generate native code into a native code cache that lives as long as the process lives, the current compiler component lacks the ability to write out the native code as, say, an ELF object with all associated symbols and such.

I'm going to close this issue as an answered question but if you're interested in generating ELF objects, @theseoafs, please open another issue and we can mark that as an enhancement request.

Thanks for your interest! We're still working on improving that documentation aspect.
