### ISSUE TITLE
selectSimplifier doesn't correctly account for reference count of select node

### ISSUE THREAD

**Issue by kevindean12** [eclipse/omr#7006]
In the selectSimplifier, the following code handles the case in which a tree has the form:
```
select
    condition
    const 0
    const 1
```
https://github.com/eclipse/omr/blob/31f5d0c12612a8f5acbd2f72c26a69fae9b3a151/compiler/optimizer/OMRSimplifierHandlers.cpp#L15550-L15568

Because the condition node may be recreated, there is first a check to see if the condition node is referenced in another tree, since recreating it with its reverse operation in that case would alter the other tree incorrectly. However, there is no handling for the case in which the select node itself has a reference count > 1 while the condition node may have a reference count of only 1. A minimal example:
```
n1n    istore <symref A>
n2n        iselect (rc=2)
n3n            icmpeq (rc=1)
n4n                <int op 1>
n5n                <int op 2>
n6n            iconst 0
n7n            iconst 1

n8n    istore <symref B>
n2n        ==> iselect    
```

When this tree goes through the Simplifier, the first n2n is simplified to an icmpne, but since the iselect is replaced, the next reference to the iselect remains and is simplified again. The icmpeq condition node, which had a reference count of 1, passed the check for using "recreate", and so the second iselect now actually has a first child which has been recreated as an icmpne. It will again be simplified to the reverse of its first child, resulting in an icmpeq as the child of the n8n istore, which is incorrect:
```
O^O TREE SIMPLIFICATION: Replacing select with children of constant values 0 and 1 at [   0x9e9dbc0] with its condition reversed                                                                                                
O^O TREE SIMPLIFICATION: Replace node [   0x9e9dbc0] iselect by [   0x9e9dad0] icmpne 
...
O^O TREE SIMPLIFICATION: Replacing select with children of constant values 0 and 1 at [   0x9e9dbc0] with its condition reversed
...
O^O TREE SIMPLIFICATION: Replace node [   0x9e9dbc0] iselect by [   0x9f31a50] icmpeq
```

The resulting tree:
```
istore <symref A>
    icmpne (rc=1)
        <int op 1>
        <int op 2>
...
istore <symref B>
    icmpeq (rc=1)
        ==> <int op 1>
        ==> <int op 2>
```

I see two kinds of solutions that preserve the simplification step being done here:

1. Add a check for the select node's reference count, such as by adding (&& node->getReferenceCount() == 1) to [line 15550](https://github.com/eclipse/omr/blob/master/compiler/optimizer/OMRSimplifierHandlers.cpp#L15550)
2. In the existing case in which the first child of the select has a reference count of 1, perform a recreate (a recreateWithoutProperties, more likely, given the discussion [about Node transmutation here](https://github.com/eclipse/omr/blob/master/doc/compiler/il/Node.md?plain=1#L98-L103)) on the select node itself so that other references to it are also transformed in place.

Are there ideas in the community as to which approach (or another) is preferred?

**Comment by kevindean12** [comment]
@0xdaryl FYI

**Comment by vsandhya** [comment]
With the current OMR code, simplification is done twice on the iselect node (n2n) , which could be avoided if the original iselect node itself was replaced such that all references to it would automatically point to the transformed node. 
However, in the comments section of the https://github.com/eclipse/omr/blob/31f5d0c12612a8f5acbd2f72c26a69fae9b3a151/compiler/optimizer/OMROptimization.cpp#L512, the visit count is reset to zero to ensure it is visited again on next reference.
