### ISSUE TITLE
Potential issue with omrtime_current_time_millis() in GC

### ISSUE THREAD

**Issue by knn-k** [eclipse/omr#7051]
`omrtime_current_time_millis()` is implemented by `gettimeofday()` on UNIX, and the API is not guaranteed to be monotonic. The time returned by the API could jump forward or backward.

I found some uses of `omrtime_current_time_millis()` in the GC code that seem to be expecting monotonic time as shown below.

MM_Scavenger::getFreeCache()
https://github.com/eclipse/omr/blob/d38498870404fd9cff734f11559d946d2df289bc/gc/base/standard/Scavenger.cpp#L3308
`duration` is declared as `uint64_t`, and it can be a huge value when `gettimeofday()` value is smaller than its previous value.

**Comment by kangyining** [comment]
Please assign, thanks!

**Comment by knn-k** [comment]
Fix has been merged.  Closing.
