### ISSUE TITLE
LoopVersioner creates certain guard tests unsafely

### ISSUE THREAD

**Issue by ymanton** [eclipse/omr#717]
When creating `asynccheck` guard tests for loops `LoopVersioner` duplicates trees from inside the loop to create these tests without doing anything to clear any flags that may be set in the duplicated nodes. These flags need to be cleared because they may no longer be valid at the location where the duplicated trees are inserted.

**Comment by mstoodle** [comment]
PR looks merged so I'll aggressively close this issue. If there's more to do here @ymanton please say so and I'll reopen it.
