### ISSUE TITLE
Add omrtime API for process time

### ISSUE THREAD

**Issue by tajila** [eclipse/omr#7201]
See https://github.com/eclipse-openj9/openj9/issues/18598 for motivation

On linux process start time can be found in /proc/[pid]/stat.

On windows one can use GetProcessTimes

More research needs to be done for mac, aix and z/os.

**Comment by singh264** [comment]
@tajila I would like to address this GitHub issue.

**Comment by babsingh** [comment]
- Closing as per https://github.com/eclipse/omr/issues/7201#issuecomment-1904073760.
- z/TPF port is tracked through https://github.com/eclipse/omr/issues/7226.
