### ISSUE TITLE
Add a NOTICE file in the top directory 

### ISSUE THREAD

**Issue by dorrab** [eclipse/omr#74]
Apache does not mandate the presence of a NOTICE file but recommend adding one: http://www.apache.org/legal/src-headers.html#notice

Example of a NOTICE file: https://www.apache.org/licenses/example-NOTICE.txt

**Comment by mstoodle** [comment]
We are not an Apache project; we are simply allowing others to use the Eclipse OMR Project resources under an Apache 2.0 license. I don't think we need to include such a file.

In particular, this code was not developed at the Apache organization and should not be copyrighted by them.

**Comment by dorrab** [comment]
Thanks. Canceling this issue
