### ISSUE TITLE
retrieveLinuxMemoryStats() does not report the memory limits set by containers/cgroup

### ISSUE THREAD

**Issue by mpirvu** [eclipse/omr#7453]
`retrieveLinuxMemoryStats(struct OMRPortLibrary *portLibrary, struct J9MemoryInfo *memInfo)` calls `retrieveLinuxCgroupMemoryStats(portLibrary, &cgroupMemInfo);` to determine the memory limits set by containers.
I have observed that `retrieveLinuxCgroupMemoryStats()` returns an error code and therefore `retrieveLinuxMemoryStats()` will only report the memory available on the host.
Additional tracing showed that `retrieveLinuxCgroupMemoryStats()` is actually able to determine the cgroup memory limits, but it fails when trying to determine the swapiness:
```
	rc = readCgroupSubsystemFile(portLibrary, OMR_CGROUP_SUBSYSTEM_MEMORY, CGROUP_MEMORY_SWAPPINESS, numItemsToRead, "%" SCNu64, &cgroupMemInfo->swappiness);
	if (0 != rc) {
		goto _exit;
	}
```
Maybe the code should not abort immediately and provide whatever partial information was able to gather correctly.

**Comment by mpirvu** [comment]
@babsingh Could you please comment on this issue? Thanks

**Comment by mpirvu** [comment]
@babsingh Gentle reminder to comment in this issue. Thanks

**Comment by babsingh** [comment]
Sorry, I missed the earlier ping. But, the above suggestion does make better sense. How urgent is the need for this to be addressed?
