### ISSUE TITLE
Deprecate isJITEntry and isJITExit

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#755]
The z Systems specific `OMRInstruction::isJITEntry` and `OMRInstruction::isJITExit` APIs do not appear to be used anywhere and there are many references to setting such flags. I'm not quite sure of the history or what such an API would be used for. These look like candidates for removal:

https://github.com/eclipse/omr/blob/master/compiler/z/codegen/OMRInstruction.hpp#L119-L123

@joransiu Perhaps you may have some history with these APIs?

**Comment by joransiu** [comment]
Hmm, I do not recall why we introduced these APIs, and what they were used for.   If they are not used anymore, I agree that they should be removed.
