### ISSUE TITLE
Vector Evaluator fixes and improvements on p and z

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/omr#767]
Vector Evaluator fixes and improvements on p and z

Some vector evaluators on p currently transfer data between vector registers and GPRs by going through memory. The proposed changes will change them to use instructions that directly move data between the two register types.

This change will also fix some bugs such as:
-vneg Evaluator on Power is incorrect when an input value is the minimum signed 32 bit int (-2147483648). vsubuwm should be used instead of vsumsws.
-vand, vor and vxor on Power may attempt to use a VMX instruction on a VSX register. VSX instruction should be used instead.
-getvelem and vsetelem returned incorrect values on z when working with 64 bit data on a 31 bit system. The cause was incorrect handling of pair registers.
-generateMvFprGprInstructions on Power does not work under Little Endian. Support needs to be added.

Other various improvements:
-extra entries in convertScalarToVector to handle cases like frem and lxor.
-updated getSupportsOpCodeForAutoSIMD on p and z to reflect the current state of vector evaluator support.

**Comment by mstoodle** [comment]
In future, I would prefer more focused issues rather than this kind of "grab bag" approach. Its harder to see what's actually being addressed by an issue with multiple seemingly unrelated "fixes" inside. It's not that hard to open another issue :) .

**Comment by IBMJimmyk** [comment]
Okay. Even when I was writing this I could tell it was a bit all over the place. I'll definitely split something like this up into multiple Issues in the future.
