### ISSUE TITLE
Remove build flag OMR_THR_SPIN_CODE_REFACTOR

### ISSUE THREAD

**Issue by babsingh** [eclipse/omr#773]
Remove build flag, OMR_THR_SPIN_CODE_REFACTOR, and old changes once new changes in https://github.com/eclipse/omr/pull/722 have been thoroughly tested across all platforms.

**Comment by mstoodle** [comment]
Assuming this issue can be closed since the associated PR has been merged. Please re-open if I'm mistaken.

**Comment by babsingh** [comment]
@mstoodle we haven't removed the flag yet. it will be removed after a month. so, we need to let it stay open.

**Comment by mstoodle** [comment]
Thanks @babsingh and sorry for the over-eager trigger finger (I should have looked at the referenced merge first, I suppose).
