### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [eclipse/omr#8]
Would you like to add more error handling for return values from functions like the following?
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [iconv_init](https://github.com/eclipse/omr/blob/64edf053d9d1cfe1594f9cf5bc2925f8b1beedba/util/a2e/atoe.c#L2397)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [ArgParser::parseOptions](https://github.com/eclipse/omr/blob/64edf053d9d1cfe1594f9cf5bc2925f8b1beedba/tools/tracegen/ArgParser.cpp#L55)

**Comment by charliegracie** [comment]
Yes it would be great to have others contributing fixes to the project.  Please read the [CONTRIBUTING.md](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md) to make sure you following the Eclipse OMR guidelines for contributing code.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by igouss** [comment]
elfring are you a bot?

**Comment by mstoodle** [comment]
Let's keep the discussion civil, please.

May a small simple sample patch might help us to understand what you're proposing, elfring, to be able to express interest or not?

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20090808093257/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by igouss** [comment]
@mstoodle, Hi! I'm am civil:
https://github.com/munificent/wren/issues/335 
https://github.com/emojicode/emojicode/issues/24
https://github.com/Microsoft/CNTK/issues/34

**Comment by mstoodle** [comment]
Thanks for your interest and for participating @igouss ! We're really happy see people getting involved!

Bottom line: let's try to keep our discussion focused on the issue that was opened. Thanks!

**Comment by elfring** [comment]
@igouss: You have noticed that I dare to repeat some bug reports for various software. Would you like to look a bit more at the spectrum of feedback?

@mstoodle: Are you familiar with [the software "AspectJ"](https://eclipse.org/aspectj/ "aspect-oriented extension to the Java programming language")?
How do you think about to achieve similar benefits from [the approach "AspectC++"](http://aspectc.org/ "Software development with AspectC++?") for further software developments?

**Comment by charliegracie** [comment]
@elfring are you proposing using AspectC++ to resolve the error handling concerns you mentioned above?

**Comment by elfring** [comment]
Yes. - How do you think about to delegate the source code transformation for more complete exception handling to such a development tool?

**Comment by charliegracie** [comment]
Could you provide an example for one error checking callsite so I could see how it would work?

**Comment by elfring** [comment]
1. Specification of appropriate pointcuts
  Which source code filters will be needed?

2. Selection of advices for aspects around better exception handling
   Olaf Spinczyk gave me the following example for a small AspectC++ script a while ago.
  ```
…
aspect CheckAllReturnedPointersForNull {
 advice execution("% * ...::%(...)": after() {
   if (*tjp->result() == NULL)
      printf ("Oops: Function %s returned NULL\n", JoinPoint::signature());
 }
};
…
```

**Comment by mstoodle** [comment]
My feeling is that aspects would be pretty hard to use in a language runtime for this purpose because:

1. sometimes NULL is a perfectly valid return value
2. recovery from a "NULL" return value tends to be pretty site specific

Given those two observations, I think I would prefer to have a single (even if harder to manage) approach to dealing with such error conditions, rather than using aspects in some places and "hard" coding error condition handling in others.

I know I asked you for a simple example and then complained that your simple example isn't powerful enough, so let's say I'm pretty strongly in the "opposed" camp, but I could still be convinced otherwise. Any other opinions on the use of aspects for this kind of thing?

On the original topic this issue was raised for, I'll just confirm Charlie's first response: that we would welcome commits that help to address missing return code checks and error handling.

**Comment by elfring** [comment]
>My feeling is that aspects would be pretty hard to use in a language runtime for this purpose

Do you see just some software development challenges which might look a bit bigger at the moment because we can not be familiar enough with various design details around aspect-oriented programming so far?


>I know I asked you for a simple example and then complained that your simple example isn't powerful enough,

* How much do you like the shown functionality that a source code search pattern and a corresponding advice can be automatically applied at various places?
* Is a short formula like "Specify conditions once and let the code run almost everywhere" useful?


>…, but I could still be convinced otherwise.

* Do you find the shown search pattern (pointcut) too generic?
* How do you think about to extend such a AspectC++ script?
* Would you like to specify a special function name list there?


>… we would welcome commits that help to address missing return code checks and error handling.

* Do you use any other source code checking tools which will point open issues out from this programming area?
* Do you prefer to stick to fixing software to some degree manually?

**Comment by mstoodle** [comment]
Has anyone ever used aspects to handle error conditions in a code base with hundreds of thousands of line of code?

Aspects seem like a great idea for some forms of diagnostic analysis (i.e. as a mechanism to be used "on the spot" to gather data when something is going wrong). I don't find them attractive as the implementation of the code base or even specifically as a mechanism for handling error conditions as you've suggested in this issue. The reaction needed for error conditions isn't always consistent across a large code base and that makes expressing an aspect based solution complicated and, sadly, error prone.

So I guess my answer to your last question "Do you prefer to stick to fixing software to some degree manually?" is yes. We would welcome such fixes.

Would you like to submit a pull request to add more error handling for return values for functions?

**Comment by elfring** [comment]
>I don't find them attractive as the implementation of the code base or even specifically as a mechanism for handling error conditions as you've suggested in this issue.

How are the circumstances under which the reuse of libraries for pointcuts, advices and aspects will become acceptable in your software?


>We would welcome such fixes.

Would you like to increase the usage of class libraries which will take care of the mentioned software design concern already?

**Comment by mstoodle** [comment]
For myself, I prefer the source code to be the source code. C and C++ are complicated enough without having to wonder if something else is going to be woven into my code due to an aspect.

This discussion has been extremely abstract in nature despite the seemingly concrete reason the issue was raised. If you want to submit a fix for the problem you identified, I would be happy to consider it.

**Comment by elfring** [comment]
Another example:
Do you care for a probability around [locking failures](https://github.com/eclipse/omr/blob/64edf053d9d1cfe1594f9cf5bc2925f8b1beedba/port/unix/omrsignal.c#L595 "Checking pthread_mutex_lock() calls?")?

**Comment by mstoodle** [comment]
Yes, but there's a comment right above that pthread_mutex_lock call:
                /*
		 * I won't attempt to generate diagnostics if the following pthread
		 * functions return errors because it may interfere with diagnostics
		 * we are attempting to generate for earlier events.
		 */

**Comment by elfring** [comment]
Does this comment point another open issue out?

How do you think about to replace any calls of a function like "pthread_mutex_lock" by the use of [a class like "std::lock_guard"](http://en.cppreference.com/w/cpp/thread/lock_guard "Using mutex wrappers?")?
