### ISSUE TITLE
ddrgen tool initial contribution

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#87]
DDR is a tool for analyzing core dumps. DDRGen is a utility that generates metadata for the DDR tool. In particular, it extracts information about data structures and macros from the runtime build. It outputs two artifacts that are consumed by the DDR tool chain (not included in this contribution):
1. superset - Metadata for generating language-specific accessor stubs for coredump data, which allow implementation of advanced debug functions in DDR.
2. blob - Metadata about structures, field offsets, and #defined values, used to generate the accessors.

The initial contribution of DDRGen covers:
* Extraction of debug data from DWARF debug data in output from GCC.
* Build and test on Linux/GCC x86-64 and -32.
  * Linux/GCC on p- and z- should "just work" after #88 is resolved.

DDRGen is **disabled** by default. Steps to build and run it:

<pre>
make -f run_configure.mk SPEC=linux_x86-64 OMRGLUE=example/glue EXTRA_CONFIGURE_ARGS='--enable-DDR'

# Compiles ddrgen tools, but does no ddrgen processing
make

# Build ddr artifacts for sample test program
# vars can be customized to process full omr or runtime source tree
make -f ddr_artifacts.mk TOP_SRCDIR=tools/ddrgen/test DBG_FILE_LIST=tools/ddrgen/test/file_list

# Read the contents of the binary blob
./blob_reader blob.dat > blob.dat.strings
</pre>

**Comment by charliegracie** [comment]
Initial contribution happened awhile ago.  Closing
