### ISSUE TITLE
--enable-fvtest flag no longer exists but is referenced in the help documentation of configure

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#872]
Steps to reproduce:

```
make -f run_configure.mk SPEC=s390-linux64-gcc OMRGLUE=./example/glue
make -f run_configure.mk OMRGLUE=./example/glue --enable-fvtest
```

Output:

```
> make -f run_configure.mk OMRGLUE=./example/glue --enable-fvtest
make: unrecognized option '--enable-fvtest'
```

`./configure --help` output (trimmed for relevant bit):

```
> ./configure --help
`configure' configures OMR 1.0 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.
...
Optional Features:
  --disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
...
  --enable-fvtest         Build fvtests. (Default: no)
```

Is the documentation incorrect? How do I build fvtests?

**Comment by charliegracie** [comment]
Does `make -f run_configure.mk SPEC=s390-linux64-gcc OMRGLUE=./example/glue` work?  If so can you paste the `./configure` line generated by that?  The option `--enable-fvtest` is enabled by default and is an option to `./configure`.

When I run the following command:
`make -f run_configure.mk SPEC=linux_x86-64 OMRGLUE=./example/glue`

I get the following output which definitely includes `--enable-fvtest`
`sh configure --disable-auto-build-flag 'OMRGLUE=./example/glue' 'SPEC=linux_x86-64'  --enable-OMR_EXAMPLE --enable-OMR_GC --enable-OMR_PORT --enable-OMR_THREAD --enable-OMR_OMRSIG --enable-fvtest --enable-OMR_GC_SEGREGATED_HEAP --enable-OMR_GC_MODRON_SCAVENGER --enable-OMR_GC_MODRON_CONCURRENT_MARK --enable-OMR_THR_CUSTOM_SPIN_OPTIONS --enable-OMR_NOTIFY_POLICY_CONTROL --enable-OMR_THR_SPIN_WAKE_CONTROL --enable-OMR_THR_SPIN_CODE_REFACTOR --enable-OMR_EXAMPLE --enable-OMR_GC --enable-OMR_PORT --enable-OMR_TEST_COMPILER --enable-OMR_THREAD --enable-OMR_OMRSIG --enable-OMR_THR_THREE_TIER_LOCKING --enable-OMR_THR_YIELD_ALG --enable-OMR_JITBUILDER  --enable-OMRTHREAD_LIB_UNIX --enable-OMR_ARCH_X86 --enable-OMR_ENV_DATA64 --enable-OMR_ENV_LITTLE_ENDIAN --enable-OMR_GC_TLH_PREFETCH_FTA --enable-OMR_PORT_CAN_RESERVE_SPECIFIC_ADDRESS --enable-OMR_PORT_NUMA_SUPPORT --enable-OMR_THR_FORK_SUPPORT --enable-OMR_GC_ARRAYLETS libprefix=lib exeext= solibext=.so arlibext=.a objext=.o 'AS=as' 'CC=cc' 'CXX=c++' 'CCLINK=$(CC)' 'CXXLINKSHARED=$(CC)' 'CXXLINKEXE=$(CXX)' 'AR=ar' 'OMR_HOST_OS=linux' 'OMR_HOST_ARCH=x86' 'OMR_TARGET_DATASIZE=64' 'OMR_TOOLCHAIN=gcc'`

**Comment by fjeremic** [comment]
@charliegracie I opened #874 to address another issue here. The `SPEC` value for Linux on z I was specifying was incorrect as I wanted to build the test compiler. The `SPEC` options are not clearly listed anywhere. This was part of the problem.

My other issue was that I was passing `--enable-fvtest` to the `run_configure.mk` rather than to the `./configure` output. Running `./configure --enable-fvtest` does work correctly.

> The option `--enable-fvtest` is enabled by default and is an option to `./configure`.

The help documentation (pasted in the first comment of this issue) seems to imply that tests are not enabled by default. i.e. "Build fvtests. (Default: no)".

**Comment by charliegracie** [comment]
It is `default: off` for `./configure`.  It is enabled by the convenience configure_includes for most (if not all specs) that get used when you are using `run_configure.mk`

**Comment by fjeremic** [comment]
@charliegracie thanks, that makes sense and clears things up.
