### ISSUE TITLE
Configure help should list the available SPEC options

### ISSUE THREAD

**Issue by fjeremic** [eclipse/omr#874]
The compilertest sub-project seems to imply that to build the test compiler for Linux on z 64-bit you have to specify `SPEC=s390-linux64-gcc`, however this is not actually a valid `SPEC` option as it does not get recognized during configuration of OMR. To configure OMR to build on Linux on z the correct `SPEC` value should be `SPEC=linux_390-64`.

This list of available options for the `SPEC` parameter is not listed anywhere. A user has to dig inside the actual makefile to find how these `SPEC` values are parsed. The help documentation provided via `./configure --help` should define the list of available `SPEC` values.

**Comment by charliegracie** [comment]
There should actually be a bunch of clean up work around the current configure / build system.  As the different components of OMR settle on a single build / configure mechanism I believe a lot of these issues will be resolved.

If the current autoconf process stays I believe we should actually remove the `run_configure.mk` and all of the `example\configure_includes`.  The next step would be to revisit the set of options that are `default: on` for configure and select an appropriate set.  

I think we should also make a change in how we handle the SPEC environment variable. I think we should completely remove it as it is not needed and a left over artifact from J9.  SPEC was used to override options for a given platform / architecture / feature.  Most of the platform / architecture options are auto detected by `./configure` and the rest can easily be added to the `./configure` command line when you want to compile specific differences.

**Comment by rwy0717** [comment]
Filip, with the move to cmake, which doesn't have a notion of specs, I don't think we're going to address this issue. Do you mind if we close it?

**Comment by fjeremic** [comment]
> Filip, with the move to cmake, which doesn't have a notion of specs, I don't think we're going to address this issue. Do you mind if we close it?

I totally agree. CMake has made this a non-issue.
