### ISSUE TITLE
Allow ddrgen to be built with custom libdwarf

### ISSUE THREAD

**Issue by alin00** [eclipse/omr#88]
libdwarf lib and header install location varies by distro. For p & z-linux, binary packages aren't provided, and the consumer may need to build & install libdwarf in a custom location.

Add configure variables to enable ddrgen to be built with libdwarf from a custom location.

**Comment by alin00** [comment]
Also need to update the library path in the ddrgen makefile, after the initial contribution is accepted.

**Comment by charliegracie** [comment]
@jason-hall is this something we are likely still going to need to do?

**Comment by jason-hall** [comment]
Yes

**Comment by charliegracie** [comment]
I believe the work for this has been completed under other items.  @jason-hall please re-open if I have incorrectly closed this Issue.  Thanks
