### ISSUE TITLE
Complete build options for Pthread API

### ISSUE THREAD

**Issue by elfring** [eclipse/omr#9]
Would you like to add the configuration script "[AX_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html "How to build C programs using POSIX threads?")" to [your build specification](https://github.com/eclipse/omr/blob/b3c44edf20ca4ea9362b9325754d1eed85a34394/configure.ac#L232 "Configuration checks")?

**Comment by alin00** [comment]
AX_PTHREAD() is not supported by autoconf 2.63.

Additionally, OMR is not designed to work without pthread support (on Unix-like platforms), so it doesn't make sense to define compile options to only conditionally support pthreads.

**Comment by elfring** [comment]
Which implementation detail of the macro "AX_PTHREAD" will not work together with the software "autoconf 2.63"?

**Comment by alin00** [comment]
Sorry, I misunderstood how AX_PTHREAD() was defined.

However, OMR does not currently require the specific pthread features tested for, and pthread compile & link options are already included in the makefiles.

**Comment by elfring** [comment]
Do you care for the configuration checks that are provided by the macro "AX_PTHREAD" already?

**Comment by alin00** [comment]
We don't currently need the configuration checks that are provided by AX_PTHREAD. And given that the AX_PTHREAD macro has different license terms than the rest of OMR, I don't think that it is currently worthwhile to pursue incorporating it into our code base.

**Comment by elfring** [comment]
Do you care for any system variations around parameters for the proper usage of the POSIX thread application programming interface?

**Comment by alin00** [comment]
We already handle variations in pthread usage for a variety of operating systems and compilers.

If you provide patches and a concrete example of how this improves the capabilities of the OMR project, I am happy to reconsider.
