### ISSUE TITLE
Expanding AutoSIMD support to Float datatype on z

### ISSUE THREAD

**Issue by IBMJimmyk** [eclipse/omr#950]
Modified the evaluators for the following opcodes to handle float data type on z:
vadd, vsub, vmul, vdiv, vneg
vsplats, getvelem, vsetelem

The following opcode evaluators already supported float data type (since they don't care about data type) but are now marked as supported in getSupportsOpCodeForAutoSIMD.
vload, vloadi, vstore, vstorei

inlineVectorUnaryOp and inlineVectorBinaryOp are used inside many of the previously mentioned evaluators. They were changed to set the right bits in an instruction to indicate that a floating point version should be used.

As an example, prior to any changes, the mask4 bits in a VFA instruction were always set to 0x3 to indicate double type data since it was only used for doubles at the time. This was changed so that for float type data, the mask4 bit are now set to 0x2 to indicate the vector contains floats that need to be added together.

generateFusedMultiplyAddIfPossible was modified to try and generate VFMA or VFMS for float data as well as the previously supported double data.

In most of the modified functions, a check for zNext is performed since it is necessary for the floating point version of the vector instructions.

After these changes, AutoSIMD support for floats on z now matches the support for doubles.

**Comment by 0xdaryl** [comment]
@IBMJimmyk : can this issue be closed now, or is there more work that needs to be done?

**Comment by IBMJimmyk** [comment]
This can be closed. All outstanding work on this item has been completed. Any future work would go under a new Issue.
