### ISSUE TITLE
Add IL opcode TR::lbyteswap

### ISSUE THREAD

**Issue by liqunl** [eclipse/omr#958]
Bytecode ibyteswap is added, we need to add its 64 bit version lbyteswap as well. Unit test is needed when lbyteswap is added to the code base.

**Comment by liqunl** [comment]
This will be implemented by me in a different PR that's coming soon (don't know how to assign a git issue, so put this comment).

FYI @vijaysun-omr @0xdaryl

**Comment by 0xdaryl** [comment]
This issue proposes creating a `TR::lbyteswap` opcode that is the 64-bit analog of the `TR::ibyteswap` opcode.  The opcode itself needs to be created, various tables indexed by opcode need to be updated, and codegen evaluators on each platform need to be created.  Consider sharing evaluator code between `TR::ibyteswap` and `TR::lbyteswap` if appropriate.

Studying how `TR::ibyteswap` is implemented is a good place to start as most of the same code will need to be touched.

Test cases should be written as well to exercise the new opcode (I suggest Tril-based tests).

**Comment by 0xdaryl** [comment]
@fjeremic @knn-k :  the `ibyteswap` opcode is unimplemented on Z and AArch32 codegens.  Can you recommend the instruction(s) to implement this support and I'll create an issue to track the work.  Ditto for `lbyteswap` (this issue).

@R-Santhir @gita-omr : can you confirm the Power sequence for `lbyteswap` please?

**Comment by fjeremic** [comment]
> @fjeremic @knn-k : the ibyteswap opcode is unimplemented on Z and AArch32 codegens. Can you recommend the instruction(s) to implement this support and I'll create an issue to track the work. Ditto for lbyteswap (this issue).

For Z we can use the Load Reversed (`LRVH`, `LRV`, `LGRV`) for register to memory operations for 16-bit, 32-bit, and 64-bit respectively and `LRVR` and `LRVGR` for register to register operations for 32-bit and 64-bit respectively.

**Comment by knn-k** [comment]
In ARM32, you can use the `REV` instruction for the ibyteswap operation.
`REV Rd, Rn`
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489bj/Cihjgdid.html
For lbyteswap, you need a temporary register and use `REV` twice.
`REV` is not available in ARMOps.hpp now.

**Comment by gita-omr** [comment]
Consulted with @zl-wang : on Power, we have instruction to read from memory and swap 8 bytes. If data is in register, more work is needed and perhaps we can just fall back to original code. Power 10 will support long swap in register.

**Comment by 0xdaryl** [comment]
This issue is superceded by #5517, which was approved at the Sept 10, 2020 OMR Architecture meeting (#5515).  Closing this.
